// @generated by HoloScript NextJSCompiler — DO NOT EDIT
'use client';

import React from 'react';
import { BrittneyFullScreen } from '@/components/ai/BrittneyFullScreen';

// @generated by HoloScript Native2DCompiler — DO NOT EDIT
function implicitComponent() {



  return (
    <div className="holoscript-2d-root w-full h-full">
      <div data-holo-slot="BrittneyFullScreen">
        <BrittneyFullScreen />
      </div>
    </div>
  );
}

export default implicitComponent;
