import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { compilerTools, handleCompilerTool } from '../compiler-tools';

const testDir = dirname(fileURLToPath(import.meta.url));

const robotComposition = `composition "Robot" {
  object "base_link" {
    geometry: "cube"
    position: [0, 0, 0]
  }
}`;

type TextContent = {
  type: 'text';
  text: string;
};

function firstTextContent(result: unknown): TextContent {
  const content = (result as { content?: unknown }).content;
  expect(Array.isArray(content)).toBe(true);
  const first = content[0] as Partial<TextContent> | undefined;
  expect(first?.type).toBe('text');
  expect(typeof first?.text).toBe('string');
  return first as TextContent;
}

function sha256Text(value: string): string {
  return `sha256:${createHash('sha256').update(value, 'utf8').digest('hex')}`;
}

describe('compiler tools', () => {
  it('publishes convenience tools for every listed export target', async () => {
    const result = (await handleCompilerTool('list_export_targets', {})) as {
      targets?: string[];
    };
    const toolNames = new Set(compilerTools.map((tool) => tool.name));
    // Convenience tools normalise hyphenated target ids to underscores
    // (android-xr → compile_to_android_xr, a2a-agent-card → compile_to_a2a_agent_card, …).
    // Non-hyphenated ids (quest, 3dgs, webgpu) pass through unchanged.
    const targetToolName = (target: string): string =>
      `compile_to_${target.replace(/-/g, '_')}`;

    expect(Array.isArray(result.targets)).toBe(true);
    const missing = result.targets
      ?.map((target) => targetToolName(target))
      .filter((toolName) => !toolNames.has(toolName));

    expect(missing).toEqual([]);

    for (const target of result.targets ?? []) {
      const toolName = targetToolName(target);
      try {
        const dispatchResult = await handleCompilerTool(toolName, {});
        expect(dispatchResult).not.toBeNull();
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        expect(message).not.toMatch(/^Unknown tool:/);
      }
    }
  });

  it('compiles USD through its convenience tool', async () => {
    const result = (await handleCompilerTool('compile_to_usd', {
      code: robotComposition,
    })) as {
      success?: boolean;
      output?: string;
    };

    expect(result.success).toBe(true);
    expect(result.output).toContain('#usda');
    expect(result.output).toContain('base_link');
  });

  it('compiles an agent brain through its convenience tool', async () => {
    const result = (await handleCompilerTool('compile_to_agent_inference', {
      code: `composition "PlannerBrain" {
        object "planner_agent" {
          @agent(role: "planner")
          @model(provider: "openai", name: "gpt-4o")
          @system_prompt(text: "Plan safely.")
        }
      }`,
    })) as {
      success?: boolean;
      output?: string;
      target?: string;
    };

    expect(result.success).toBe(true);
    expect(result.target).toBe('agent-inference');
    expect(typeof result.output).toBe('string');
    const files = JSON.parse(result.output ?? '{}') as Record<string, string>;
    expect(files['agent.ts']).toContain('Generated by HoloScript AgentInferenceCompiler');
    expect(files['config.json']).toContain('gpt-4o');
  });

  it('compiles a typed TypeScript SDK from a service contract through its convenience tool', async () => {
    const code = readFileSync(
      resolve(testDir, '../../../partner-sdk/src/api/registry-client.contract.holo'),
      'utf8'
    );

    const result = (await handleCompilerTool('compile_to_sdk', {
      code,
      options: { clientClassName: 'RegistryClient', packageName: '@holoscript/generated-registry-client' },
    })) as {
      success?: boolean;
      output?: string;
      target?: string;
    };

    expect(result.success).toBe(true);
    expect(result.target).toBe('sdk');
    const files = JSON.parse(result.output ?? '{}') as Record<string, string>;
    // Same generated files as the direct SDKCompiler unit test
    // (packages/core/src/compiler/__tests__/SDKCompiler.test.ts) — proves the
    // MCP dispatch path (compile_to_sdk -> handleCompileToTarget -> ExportManager
    // -> SDKCompiler) is wired end-to-end, not just the compiler in isolation.
    expect(files['src/RegistryClient.ts']).toBeDefined();
    expect(files['src/sdk-runtime.ts']).toBeDefined();
    expect(files['sdk-compiler-receipt.json']).toBeDefined();
    expect(files['src/RegistryClient.ts']).toContain('@generated by HoloScript SDKCompiler');
    expect(files['src/RegistryClient.ts']).toContain('export interface PackageInfo');

    const receipt = JSON.parse(files['sdk-compiler-receipt.json']) as {
      type?: string;
      target?: string;
    };
    expect(receipt.type).toBe('SDKCompilerReceipt');
    expect(receipt.target).toBe('sdk:typescript');
  });

  it('exports an Omnigent agent YAML bridge through its convenience tool', async () => {
    const result = (await handleCompilerTool('compile_to_omnigent_agent_yaml', {
      code: `composition "PlannerBrain" {
        object "planner_agent" {
          @agent(role: "planner")
          @model(provider: "openai", name: "gpt-4o")
          @system_prompt(text: "Plan safely.")
          @tool(name: "lookup_order", description: "Look up an order")
        }
      }`,
      options: { source: 'planner.hsplus' },
    })) as {
      success?: boolean;
      output?: string;
      target?: string;
    };

    expect(result.success).toBe(true);
    expect(result.target).toBe('omnigent-agent-yaml');
    const bridge = JSON.parse(result.output ?? '{}') as {
      agentYaml?: string;
      receipt?: { source?: string; target?: string; warnings?: Array<{ code?: string }> };
    };
    expect(bridge.agentYaml).toContain('harness: codex');
    expect(bridge.agentYaml).toContain('name: lookup_order');
    expect(bridge.receipt?.source).toBe('planner.hsplus');
    expect(bridge.receipt?.target).toBe('omnigent-agent-yaml');
    expect(bridge.receipt?.warnings?.map((warning) => warning.code)).toContain(
      'function_tool_unowned_schema'
    );
  });

  it('compiles DaimonSeed IR through its convenience tool', async () => {
    const result = (await handleCompilerTool('compile_to_daimon_seed', {
      code: `composition "SeedBrain" {
        object "mentor_agent" {
          @agent(role: "mentor")
          @emergence(heldout: true)
        }
      }`,
      options: {
        provenanceChainRef: 'prov:v2:test',
        emergenceContractRef: 'emergence:t4:test',
      },
    })) as {
      success?: boolean;
      output?: string;
      target?: string;
    };

    expect(result.success).toBe(true);
    expect(result.target).toBe('daimon-seed');
    const seed = JSON.parse(result.output ?? '{}') as {
      kind?: string;
      thresholdRuntime?: { id?: string };
      fidelityContract?: { metric?: string };
      hysteresisExp2?: { coefficient?: string };
      custody?: { runtimeOnly?: string[] };
      provenanceChainRef?: string;
    };
    expect(seed.kind).toBe('DaimonSeed');
    expect(seed.thresholdRuntime?.id).toBe('ContentPolicyGate.jsonLogic');
    expect(seed.fidelityContract?.metric).toBe('exportFidelity');
    expect(seed.hysteresisExp2?.coefficient).toBe('div(A,B)/div(A,A_prime)');
    expect(seed.custody?.runtimeOnly).toEqual(['realizedComposition', 'observationPath', 'soul']);
    expect(seed.provenanceChainRef).toBe('prov:v2:test');
  });

  it('compiles MCP server modules with stable source and output hashes', async () => {
    const code = `composition "ParityAgent" {
      object "agent" {
        @llm_agent { model: "local-sovereign" }
      }
    }`;

    const result = (await handleCompilerTool('compile_to_mcp_server', {
      code,
      options: { serverName: 'parity-server', serverVersion: '1.2.3' },
    })) as {
      success?: boolean;
      output?: string;
      target?: string;
      sourceSha256?: string;
      outputSha256?: string;
      metadata?: {
        sourceSha256?: string;
        outputSha256?: string;
        hashAlgorithm?: string;
      };
    };

    expect(result.success).toBe(true);
    expect(result.target).toBe('mcp-server');
    expect(result.output).toContain('Generated by HoloMCPCompiler');
    expect(result.output).toContain('parity-server');
    expect(result.sourceSha256).toBe(sha256Text(code));
    expect(result.outputSha256).toBe(sha256Text(result.output ?? ''));
    expect(result.metadata?.sourceSha256).toBe(result.sourceSha256);
    expect(result.metadata?.outputSha256).toBe(result.outputSha256);
    expect(result.metadata?.hashAlgorithm).toBe('sha256');

    const second = (await handleCompilerTool('compile_to_mcp_server', {
      code,
      options: { serverName: 'parity-server', serverVersion: '1.2.3' },
    })) as { outputSha256?: string };
    expect(second.outputSha256).toBe(result.outputSha256);
  });

  it('returns a 3D Tiles stream manifest through stream_world_tiles', async () => {
    const result = (await handleCompilerTool('stream_world_tiles', {
      code: 'composition "TileWorld" {}',
      options: { streamBaseUrl: 'https://tiles.example/holo', streamId: 'tile-run' },
    })) as {
      success?: boolean;
      target?: string;
      manifestUrl?: string;
      files?: Record<string, string>;
    };

    expect(result.success).toBe(true);
    expect(result.target).toBe('3dtiles');
    expect(result.manifestUrl).toBe('https://tiles.example/holo/tile-run/tileset.json');
    expect(result.files?.['tileset.json']).toContain('"version": "1.1"');
    expect(result.files?.['cael-tile-provenance.json']).toContain('cael-3dtiles-provenance-chain');
  });

  it('returns a non-empty ROS 2 deployment bundle', async () => {
    const result = await handleCompilerTool('compile_to_ros2_deploy', {
      code: robotComposition,
      packageName: 'test_robot_pkg',
      options: {
        rviz: true,
        gazebo: true,
        controllers: ['base_joint'],
      },
    });

    const bundle = JSON.parse(firstTextContent(result).text) as {
      urdf?: string;
      launchFile?: string;
      controllersYaml?: string;
      packageName?: string;
      urdfFilename?: string;
    };

    expect(bundle.packageName).toBe('test_robot_pkg');
    expect(bundle.urdfFilename).toBe('test_robot_pkg.urdf');
    expect(bundle.urdf).toContain('<robot');
    expect(bundle.urdf).toContain('base_link');
    expect(bundle.launchFile).toContain('robot_state_publisher');
    expect(bundle.launchFile).toContain('test_robot_pkg.urdf');
    expect(bundle.controllersYaml).toContain('joint_state_broadcaster');
    expect(bundle.controllersYaml).toContain('base_joint');
  });
});
