import { PBRMaterialConfig, PresetCategory } from './types';

export const DEFAULT_CONFIG: PBRMaterialConfig = {
  name: 'Default',
  color: '#ffffff',
  roughness: 0.5,
  metalness: 0,
  emissive: '#000000',
  emissiveIntensity: 0,
  opacity: 1,
  transparent: false,
  transmission: 0,
  thickness: 0.5,
  ior: 1.5,
  attenuationColor: '#ffffff',
  attenuationDistance: 1,
  clearcoat: 0,
  clearcoatRoughness: 0.1,
  sheenColor: '#000000',
  sheenRoughness: 0.5,
  sheen: 0,
  iridescence: 0,
  iridescenceIOR: 1.3,
  anisotropy: 0,
  anisotropyRotation: 0,
  wireframe: false,
  flatShading: false,
  side: 'front',
};

export const PRESET_CATEGORIES: PresetCategory[] = [
  {
    label: 'Metals',
    icon: '🔩',
    presets: [
      {
        key: 'polishedSteel',
        label: 'Polished Steel',
        config: { color: '#b0b0b0', roughness: 0.08, metalness: 1.0, clearcoat: 0.6 },
      },
      {
        key: 'brushedAluminum',
        label: 'Brushed Aluminum',
        config: { color: '#c0c0c0', roughness: 0.35, metalness: 0.95, anisotropy: 0.8 },
      },
      { key: 'gold', label: 'Gold', config: { color: '#ffd700', roughness: 0.12, metalness: 1.0 } },
      {
        key: 'copper',
        label: 'Copper',
        config: { color: '#b87333', roughness: 0.25, metalness: 1.0 },
      },
      {
        key: 'bronze',
        label: 'Bronze',
        config: { color: '#cd7f32', roughness: 0.4, metalness: 0.9 },
      },
      {
        key: 'chrome',
        label: 'Chrome',
        config: {
          color: '#ddd',
          roughness: 0.02,
          metalness: 1.0,
          clearcoat: 1.0,
          clearcoatRoughness: 0.02,
        },
      },
      {
        key: 'titanium',
        label: 'Titanium',
        config: { color: '#8a8a8a', roughness: 0.3, metalness: 0.85 },
      },
      { key: 'iron', label: 'Iron', config: { color: '#434343', roughness: 0.6, metalness: 0.75 } },
    ],
  },
  {
    label: 'Glass & Crystal',
    icon: '💎',
    presets: [
      {
        key: 'clearGlass',
        label: 'Clear Glass',
        config: {
          color: '#ffffff',
          roughness: 0.0,
          metalness: 0,
          transmission: 1.0,
          thickness: 0.5,
          ior: 1.5,
          transparent: true,
          opacity: 0.1,
        },
      },
      {
        key: 'frostedGlass',
        label: 'Frosted Glass',
        config: {
          color: '#eeeeff',
          roughness: 0.4,
          metalness: 0,
          transmission: 0.9,
          ior: 1.5,
          transparent: true,
          opacity: 0.2,
        },
      },
      {
        key: 'crystal',
        label: 'Crystal',
        config: {
          color: '#e0e8ff',
          roughness: 0.0,
          metalness: 0,
          transmission: 0.95,
          ior: 2.0,
          iridescence: 0.5,
          transparent: true,
          opacity: 0.05,
        },
      },
      {
        key: 'diamond',
        label: 'Diamond',
        config: {
          color: '#ffffff',
          roughness: 0.0,
          metalness: 0,
          transmission: 1.0,
          ior: 2.42,
          iridescence: 0.8,
          transparent: true,
          opacity: 0.0,
        },
      },
      {
        key: 'stainedGlass',
        label: 'Stained Glass',
        config: {
          color: '#cc2244',
          roughness: 0.1,
          metalness: 0,
          transmission: 0.7,
          transparent: true,
          opacity: 0.3,
        },
      },
    ],
  },
  {
    label: 'Natural',
    icon: '🌿',
    presets: [
      { key: 'wood', label: 'Wood', config: { color: '#8B4513', roughness: 0.75, metalness: 0 } },
      { key: 'stone', label: 'Stone', config: { color: '#808080', roughness: 0.85, metalness: 0 } },
      {
        key: 'marble',
        label: 'Marble',
        config: { color: '#f0ece0', roughness: 0.2, metalness: 0, clearcoat: 0.3 },
      },
      {
        key: 'clay',
        label: 'Clay',
        config: { color: '#cc8855', roughness: 0.95, metalness: 0, flatShading: true },
      },
      { key: 'sand', label: 'Sand', config: { color: '#c2b280', roughness: 1.0, metalness: 0 } },
      {
        key: 'water',
        label: 'Water',
        config: {
          color: '#004488',
          roughness: 0.02,
          metalness: 0,
          transmission: 0.6,
          ior: 1.33,
          transparent: true,
          opacity: 0.4,
        },
      },
    ],
  },
  {
    label: 'Fabric',
    icon: '🧵',
    presets: [
      {
        key: 'silk',
        label: 'Silk',
        config: {
          color: '#dd3366',
          roughness: 0.4,
          metalness: 0,
          sheen: 1.0,
          sheenColor: '#ff88aa',
          sheenRoughness: 0.2,
        },
      },
      {
        key: 'velvet',
        label: 'Velvet',
        config: {
          color: '#440022',
          roughness: 0.9,
          metalness: 0,
          sheen: 0.8,
          sheenColor: '#880044',
          sheenRoughness: 0.6,
        },
      },
      {
        key: 'denim',
        label: 'Denim',
        config: {
          color: '#1a3a5c',
          roughness: 0.85,
          metalness: 0,
          sheen: 0.3,
          sheenColor: '#3366aa',
          sheenRoughness: 0.7,
        },
      },
      {
        key: 'leather',
        label: 'Leather',
        config: { color: '#6b3a2a', roughness: 0.65, metalness: 0, clearcoat: 0.15 },
      },
      {
        key: 'cotton',
        label: 'Cotton',
        config: {
          color: '#f5f0e8',
          roughness: 0.95,
          metalness: 0,
          sheen: 0.2,
          sheenRoughness: 0.8,
        },
      },
    ],
  },
  {
    label: 'Synthetic',
    icon: '🧴',
    presets: [
      {
        key: 'plastic',
        label: 'Plastic',
        config: { color: '#ff4488', roughness: 0.4, metalness: 0, clearcoat: 0.3 },
      },
      {
        key: 'rubber',
        label: 'Rubber',
        config: { color: '#222222', roughness: 0.95, metalness: 0 },
      },
      {
        key: 'ceramic',
        label: 'Ceramic',
        config: {
          color: '#f0f0f0',
          roughness: 0.1,
          metalness: 0,
          clearcoat: 0.8,
          clearcoatRoughness: 0.05,
        },
      },
      {
        key: 'carPaint',
        label: 'Car Paint',
        config: {
          color: '#cc0000',
          roughness: 0.1,
          metalness: 0.3,
          clearcoat: 1.0,
          clearcoatRoughness: 0.03,
        },
      },
      {
        key: 'holographic',
        label: 'Holographic',
        config: {
          color: '#aaddff',
          roughness: 0.1,
          metalness: 0.5,
          iridescence: 1.0,
          iridescenceIOR: 1.8,
          clearcoat: 0.5,
        },
      },
    ],
  },
  {
    label: 'Emissive',
    icon: '💡',
    presets: [
      {
        key: 'neonPink',
        label: 'Neon Pink',
        config: {
          color: '#111',
          roughness: 0.5,
          metalness: 0,
          emissive: '#ff00ff',
          emissiveIntensity: 3.0,
        },
      },
      {
        key: 'neonCyan',
        label: 'Neon Cyan',
        config: {
          color: '#111',
          roughness: 0.5,
          metalness: 0,
          emissive: '#00ffff',
          emissiveIntensity: 3.0,
        },
      },
      {
        key: 'lava',
        label: 'Lava',
        config: {
          color: '#330000',
          roughness: 0.8,
          metalness: 0,
          emissive: '#ff3300',
          emissiveIntensity: 2.0,
        },
      },
      {
        key: 'plasma',
        label: 'Plasma',
        config: {
          color: '#000022',
          roughness: 0.3,
          metalness: 0,
          emissive: '#8800ff',
          emissiveIntensity: 4.0,
        },
      },
    ],
  },
];
