import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import fs from 'node:fs/promises';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import type { createApp as createAppType } from '../app';

const apiKey = `hsk_${'a'.repeat(64)}`;
const otherApiKey = `hsk_${'b'.repeat(64)}`;

const validSource = `
composition "ExportSmoke" {
  object "Cube" {
    geometry: "box"
  }
}
`;

const invalidSource = `
composition "Broken" {
  object "Cube" {
`;

let server: http.Server | undefined;
let baseUrl = '';
let tmpDir = '';

function apiKeySub(rawKey: string): string {
  return `apikey:${createHash('sha256').update(rawKey).digest('hex').slice(0, 12)}`;
}

function listen(instance: http.Server): Promise<number> {
  return new Promise((resolve, reject) => {
    instance.once('error', reject);
    instance.listen(0, '127.0.0.1', () => {
      instance.off('error', reject);
      const address = instance.address();
      if (!address || typeof address === 'string') {
        reject(new Error('failed to bind test server'));
        return;
      }
      resolve(address.port);
    });
  });
}

function close(instance: http.Server): Promise<void> {
  return new Promise((resolve, reject) => {
    instance.close((error) => {
      if (error) {
        reject(error);
        return;
      }
      resolve();
    });
  });
}

async function request(
  route: string,
  init: RequestInit & { apiKey?: string | null } = {},
): Promise<Response> {
  const headers = new Headers(init.headers);
  if (init.body && !headers.has('content-type')) {
    headers.set('content-type', 'application/json');
  }
  if (init.apiKey !== null) {
    headers.set('x-api-key', init.apiKey ?? apiKey);
  }
  return fetch(`${baseUrl}${route}`, { ...init, headers });
}

async function submitCompile(source: string): Promise<string> {
  const res = await request('/api/v1/compile', {
    method: 'POST',
    body: JSON.stringify({ source, target: 'webgpu' }),
  });
  expect(res.status).toBe(202);
  const body = (await res.json()) as { jobId: string };
  expect(body.jobId).toBeTruthy();
  return body.jobId;
}

async function pollJob(jobId: string): Promise<Record<string, unknown>> {
  for (let i = 0; i < 100; i++) {
    const res = await request(`/api/v1/compile/${jobId}`);
    expect(res.status).toBe(200);
    const body = (await res.json()) as Record<string, unknown>;
    if (body.status === 'completed' || body.status === 'failed') {
      return body;
    }
    await new Promise((resolve) => setTimeout(resolve, 25));
  }
  throw new Error(`Timed out waiting for ${jobId}`);
}

describe('compile routes', () => {
  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'export-api-compile-'));
    process.env.NODE_ENV = 'test';
    process.env.LOG_LEVEL = 'silent';
    process.env.JWT_SECRET = 'compile-route-test-secret';
    process.env.EXPORT_API_DATA_DIR = tmpDir;
    vi.resetModules();

    const mod = (await import('../app')) as { createApp: typeof createAppType };
    server = http.createServer(mod.createApp());
    const port = await listen(server);
    baseUrl = `http://127.0.0.1:${port}`;
  });

  afterEach(async () => {
    if (server) {
      await close(server);
      server = undefined;
    }
    if (tmpDir) {
      await fs.rm(tmpDir, { recursive: true, force: true });
      tmpDir = '';
    }
    vi.resetModules();
  });

  it('compiles with the real core compiler and streams owner and signed outputs', async () => {
    const jobId = await submitCompile(validSource);
    const status = await pollJob(jobId);

    expect(status.status).toBe('completed');
    expect(status.outputSizeBytes).toBeGreaterThan(0);
    expect(typeof status.outputUrl).toBe('string');

    const ownerOutput = await request(`/api/v1/compile/${jobId}/output`);
    expect(ownerOutput.status).toBe(200);
    expect(ownerOutput.headers.get('content-type')).toContain('text/typescript');
    expect(ownerOutput.headers.get('x-holoscript-compile-job')).toBe(jobId);
    const ownerText = await ownerOutput.text();
    expect(ownerText).toContain('Auto-generated by HoloScript WebGPUCompiler');

    const signedOutput = await request(status.outputUrl as string, { apiKey: null });
    expect(signedOutput.status).toBe(200);
    expect(await signedOutput.text()).toBe(ownerText);
  });

  it('hides completed output from a different authenticated principal', async () => {
    const jobId = await submitCompile(validSource);
    const status = await pollJob(jobId);
    expect(status.status).toBe('completed');

    const other = await request(`/api/v1/compile/${jobId}/output`, { apiKey: otherApiKey });
    expect(other.status).toBe(404);
  });

  it('returns conflict for failed job output', async () => {
    const jobId = await submitCompile(invalidSource);
    const status = await pollJob(jobId);

    expect(status.status).toBe('failed');
    expect(String(status.error)).toContain('Parse failed');

    const output = await request(`/api/v1/compile/${jobId}/output`);
    expect(output.status).toBe(409);
    const body = (await output.json()) as { message: string };
    expect(body.message).toContain('failed');
  });

  it('requires auth or a valid signed token for output', async () => {
    const jobId = await submitCompile(validSource);
    const status = await pollJob(jobId);
    expect(status.status).toBe('completed');

    const anonymous = await request(`/api/v1/compile/${jobId}/output`, { apiKey: null });
    expect(anonymous.status).toBe(404);

    const signed = await request(status.outputUrl as string, { apiKey: null });
    expect(signed.status).toBe(200);
  });

  it('records jobs under the authenticated creator in durable job storage', async () => {
    const jobId = await submitCompile(validSource);
    await pollJob(jobId);

    const raw = await fs.readFile(path.join(tmpDir, 'compile-jobs.json'), 'utf8');
    const jobs = JSON.parse(raw) as Array<{ id: string; createdBy: string; sourceHash: string }>;
    expect(jobs).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          id: jobId,
          createdBy: apiKeySub(apiKey),
          sourceHash: createHash('sha256').update(validSource).digest('hex'),
        }),
      ]),
    );
  });
});
