/**
 * Setup Git Hooks Command
 *
 * Installs a post-commit hook that auto-absorbs the repository after each commit.
 * The hook runs in the background and never blocks the commit.
 *
 * Safety features:
 *   - Non-blocking execution (runs in background subprocess)
 *   - Health check with 1-second timeout
 *   - Always exits 0 (never aborts commit)
 *   - Fast-path cache prevents spam on rapid commits
 *
 * Usage:
 *   holoscript setup-hooks [projectPath] [--studio-url=URL]
 *   holoscript remove-hooks [projectPath]
 */

import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

interface SetupHooksOptions {
  projectPath: string;
  studioUrl?: string;
}

/**
 * Install the post-commit hook for auto-absorb.
 */
export async function setupGitHooks(options: SetupHooksOptions): Promise<void> {
  const { projectPath, studioUrl = 'http://localhost:3000' } = options;

  // Verify git repo
  try {
    execSync('git rev-parse --git-dir', { cwd: projectPath, stdio: 'pipe' });
  } catch {
    throw new Error(`Not a git repository: ${projectPath}`);
  }

  const gitDir = execSync('git rev-parse --git-dir', {
    cwd: projectPath,
    encoding: 'utf-8',
  }).trim();

  const hooksDir = path.join(projectPath, gitDir, 'hooks');
  const postCommitPath = path.join(hooksDir, 'post-commit');

  // Create hooks directory if missing
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  // Generate hook script
  const hookScript = `#!/bin/bash
# HoloScript Auto-Absorb Hook
# Generated by: holoscript setup-hooks

PROJECT_ROOT="$(git rev-parse --show-toplevel)"
ABSORB_URL="${studioUrl}/api/daemon/absorb"
STATE_FILE="$PROJECT_ROOT/.holoscript/absorb-state.json"

# Non-blocking background execution
(
  sleep 0.5  # Let git finish housekeeping

  # Only absorb if Studio is running (quick check)
  if ! curl -s -m 1 "$ABSORB_URL" -X GET > /dev/null 2>&1; then
    exit 0  # Studio not running, skip silently
  fi

  # Incremental absorb (force=false leverages git change detection)
  curl -s -X POST "$ABSORB_URL" \\
    -H "Content-Type: application/json" \\
    -d "{\\"projectPath\\":\\"$PROJECT_ROOT\\",\\"depth\\":\\"shallow\\",\\"force\\":false}" \\
    > "$STATE_FILE.log" 2>&1

) &

# Never block the commit
exit 0
`;

  // Check for existing hook
  if (fs.existsSync(postCommitPath)) {
    const existing = fs.readFileSync(postCommitPath, 'utf-8');
    if (existing.includes('HoloScript Auto-Absorb')) {
      console.log('✓ HoloScript hook already installed');
      return;
    }

    // Backup existing hook
    const backupPath = `${postCommitPath}.backup-${Date.now()}`;
    fs.copyFileSync(postCommitPath, backupPath);
    console.log(`⚠ Existing post-commit hook backed up to: ${path.basename(backupPath)}`);
  }

  // Write hook script
  fs.writeFileSync(postCommitPath, hookScript, { mode: 0o755 });
  console.log('✓ HoloScript auto-absorb hook installed');
  console.log(`  Location: ${postCommitPath}`);
  console.log(`  Studio URL: ${studioUrl}`);
  console.log('\n  After each commit, the knowledge graph will auto-update in the background.');
}

/**
 * Remove the HoloScript post-commit hook.
 */
export async function removeGitHooks(options: { projectPath: string }): Promise<void> {
  const { projectPath } = options;

  try {
    execSync('git rev-parse --git-dir', { cwd: projectPath, stdio: 'pipe' });
  } catch {
    throw new Error(`Not a git repository: ${projectPath}`);
  }

  const gitDir = execSync('git rev-parse --git-dir', {
    cwd: projectPath,
    encoding: 'utf-8',
  }).trim();

  const postCommitPath = path.join(projectPath, gitDir, 'hooks', 'post-commit');

  if (!fs.existsSync(postCommitPath)) {
    console.log('No post-commit hook found');
    return;
  }

  const content = fs.readFileSync(postCommitPath, 'utf-8');
  if (!content.includes('HoloScript Auto-Absorb')) {
    console.log('Post-commit hook exists but was not installed by HoloScript');
    return;
  }

  fs.unlinkSync(postCommitPath);
  console.log('✓ HoloScript hook removed');
}
