import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    coverage: {
      provider: 'v8',
      all: true,
      include: [
        'packages/core/src/**/*.ts',
        'packages/lsp/src/**/*.ts',
        'packages/vscode-extension/src/**/*.ts',
        'packages/graphql-api/src/**/*.ts',
        'packages/mcp-server/src/**/*.ts',
        'packages/marketplace-web/src/**/*.ts',
        'packages/marketplace-api/src/**/*.ts',
        'packages/auth/src/**/*.ts',
        'packages/llm-provider/src/**/*.ts',
        'packages/studio/src/**/*.ts',
        'packages/cli/src/**/*.ts',
        'packages/formatter/src/**/*.ts',
        'packages/linter/src/**/*.ts',
        'packages/partner-sdk/src/**/*.ts',
        'packages/adapter-postgres/src/**/*.ts',
        'packages/collab-server/src/**/*.ts',
        'packages/registry/src/**/*.ts',
        'packages/runtime/src/**/*.ts',
        'packages/fs/src/**/*.ts',
        'packages/security-sandbox/src/**/*.ts',
        'packages/ai-validator/src/**/*.ts',
        'packages/holoscript-cdn/src/**/*.ts',
        'packages/std/src/**/*.ts',
        'packages/animation-presets/src/**/*.ts',
      ],
      exclude: [
        '**/*.test.ts',
        '**/*.prod.test.ts',
        '**/*.d.ts',
        '**/*.js',
        '**/node_modules/**',
        '**/dist/**',
        '**/build/**',
        '**/__snapshots__/**',
        '**/__mocks__/**',
        '**/examples/**',
      ],
      reporter: ['text-summary', 'html', 'lcov', 'json-summary'],
      reportsDirectory: './coverage',
      thresholds: {
        // Baseline — ratchet upward after initial measurement
        lines: 0,
        functions: 0,
        branches: 0,
        statements: 0,
      },
    },
    projects: [
      // ── Packages with their own vitest.config.ts ──────────────────────
      'packages/core/vitest.config.ts',
      'packages/cli/vitest.config.ts',
      'packages/formatter/vitest.config.ts',
      'packages/linter/vitest.config.ts',
      'packages/lsp/vitest.config.ts',
      'packages/vscode-extension/vitest.config.ts',
      'packages/adapter-postgres/vitest.config.ts',
      'packages/mcp-server/vitest.config.ts',
      'packages/partner-sdk/vitest.config.ts',
      'packages/security-sandbox/vitest.config.ts',
      'packages/ai-validator/vitest.config.ts',
      'packages/comparative-benchmarks/vitest.config.ts',
      'packages/llm-provider/vitest.config.ts',
      'packages/registry/vitest.config.ts',
      'packages/holoscript-cdn/vitest.config.ts',
      'packages/runtime/vitest.config.ts',
      'packages/fs/vitest.config.ts',
      'packages/playground/vitest.config.ts',
      'packages/collab-server/vitest.config.ts',
      'packages/studio/vitest.config.ts',
      'packages/studio-plugin-sdk/vitest.config.ts',
      'packages/react-agent-sdk/vitest.config.ts',
      'packages/preview-component/vitest.config.ts',
      'packages/marketplace-web/vitest.config.ts',
      'packages/marketplace-api/vitest.config.ts',
      'packages/auth/vitest.config.ts',
      'packages/animation-presets/vitest.config.ts',
      'packages/connector-upstash/vitest.config.ts',

      // ── Packages without a vitest.config.ts (inline) ─────────────────
      'packages/test/vitest.config.ts',
      {
        test: {
          name: '@holoscript/benchmark',
          root: './packages/benchmark',
          include: ['src/**/*.test.ts'],
          exclude: ['**/dist/**', '**/node_modules/**'],
          environment: 'node',
        },
      },
      {
        test: {
          name: '@holoscript/sdk',
          root: './packages/holoscript',
          include: ['src/**/*.test.ts'],
          exclude: ['**/dist/**', '**/node_modules/**'],
          environment: 'node',
        },
      },
      {
        test: {
          name: 'std',
          root: './packages/std',
          include: ['src/**/*.test.ts'],
          exclude: ['**/dist/**', '**/node_modules/**'],
          environment: 'node',
        },
      },
      {
        test: {
          name: 'graphql-api',
          root: './packages/graphql-api',
          include: ['src/**/*.test.ts'],
          exclude: ['**/dist/**', '**/node_modules/**'],
        },
      },
      {
        test: {
          name: '@holoscript/visual',
          root: './packages/visual',
          include: ['src/**/*.test.ts', 'src/**/*.test.tsx'],
          exclude: ['**/dist/**', '**/node_modules/**'],
          environment: 'node',
        },
      },
    ],
  },
});
