"""
HoloScript Robotics Module

Provides utilities for the robotics community to work with HoloScript
in ROS 2, Gazebo, and robotic simulation contexts.

Supports:
- URDF/SDF export from HoloScript scenes
- ROS 2 launch file generation
- Gazebo world file creation
- Robot trait templates
"""

from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field


@dataclass
class URDFExportResult:
    """Result of exporting a HoloScript scene to URDF format."""
    success: bool
    urdf_content: str = ""
    robot_name: str = "holoscript_robot"
    link_count: int = 0
    joint_count: int = 0
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)


@dataclass
class SDFExportResult:
    """Result of exporting a HoloScript scene to SDF format."""
    success: bool
    sdf_content: str = ""
    world_name: str = "holoscript_world"
    model_count: int = 0
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)


@dataclass
class ROSLaunchResult:
    """Result of generating a ROS 2 launch file."""
    success: bool
    launch_content: str = ""
    package_name: str = "holoscript_scene"
    nodes: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)


# ============================================================================
# Trait-to-URDF mapping utilities
# ============================================================================

# Known robotics-relevant traits and their URDF/SDF equivalents
ROBOTICS_TRAIT_MAPPINGS: Dict[str, Dict[str, Any]] = {
    "@physics": {
        "urdf": "inertial",
        "sdf": "inertial",
        "description": "Adds inertial properties to URDF/SDF link",
        "default_mass": 1.0,
    },
    "@collidable": {
        "urdf": "collision",
        "sdf": "collision",
        "description": "Adds collision geometry to URDF/SDF link",
    },
    "@static": {
        "urdf": "fixed_joint",
        "sdf": "static=true",
        "description": "Creates fixed joint in URDF; static model in SDF",
    },
    "@sensor": {
        "urdf": "gazebo_sensor_plugin",
        "sdf": "sensor",
        "description": "Adds sensor plugin hints",
    },
    "@grabbable": {
        "urdf": "<!-- holoscript:grabbable -->",
        "sdf": "<!-- holoscript:grabbable -->",
        "description": "Interaction hint (comment-based in URDF/SDF)",
    },
}

# Standard robot geometry shapes
GEOMETRY_TYPES = {
    "cube": {"urdf": "box", "sdf": "box"},
    "sphere": {"urdf": "sphere", "sdf": "sphere"},
    "cylinder": {"urdf": "cylinder", "sdf": "cylinder"},
    "plane": {"urdf": "box", "sdf": "plane"},
    "mesh": {"urdf": "mesh", "sdf": "mesh"},
}


def export_urdf(
    holo_code: str,
    robot_name: str = "holoscript_robot",
    include_visual: bool = True,
    include_collision: bool = True,
    include_inertial: bool = True,
    default_mass: float = 1.0,
    mesh_path_prefix: str = "package://robot_description/meshes",
) -> URDFExportResult:
    """
    Export HoloScript code to URDF (Unified Robot Description Format).

    Parses HoloScript scene description and generates a ROS-compatible
    URDF XML file suitable for use with Gazebo or other ROS simulators.

    Args:
        holo_code: HoloScript source code to export
        robot_name: Name for the URDF robot element
        include_visual: Include visual geometry elements
        include_collision: Include collision geometry elements
        include_inertial: Include inertial (mass/inertia) properties
        default_mass: Default mass in kg for objects without @physics
        mesh_path_prefix: ROS package path prefix for mesh files

    Returns:
        URDFExportResult with URDF content and metadata

    Example:
        >>> result = export_urdf('''
        ...     sphere {
        ...         @physics
        ...         @collidable
        ...         @position(0, 1, 0)
        ...     }
        ... ''', robot_name="my_robot")
        >>> if result.success:
        ...     print(result.urdf_content)
    """
    from holoscript.parser import parse

    parse_result = parse(holo_code)
    if not parse_result.success:
        return URDFExportResult(
            success=False,
            errors=[f"Parse error: {e.message}" for e in parse_result.errors],
        )

    lines: List[str] = []
    lines.append('<?xml version="1.0"?>')
    lines.append(f'<!-- Auto-generated by HoloScript Python Bindings -->')
    lines.append(f'<!-- holoscript export: urdf -->')
    lines.append(f'<robot name="{_sanitize_xml_attr(robot_name)}">')
    lines.append('')

    # Default material
    lines.append('  <material name="default">')
    lines.append('    <color rgba="0.8 0.8 0.8 1.0"/>')
    lines.append('  </material>')
    lines.append('')

    # Base link (required for valid URDF)
    lines.append('  <link name="base_link">')
    lines.append('  </link>')
    lines.append('')

    link_count = 1
    joint_count = 0
    warnings: List[str] = []

    # Process each object from the parsed AST
    objects = parse_result.objects or []
    for i, obj_name in enumerate(objects):
        link_name = _sanitize_link_name(obj_name)
        link_count += 1

        lines.append(f'  <link name="{link_name}">')

        if include_visual:
            lines.append('    <visual>')
            lines.append('      <geometry>')
            geom = _get_geometry_for_object(obj_name)
            lines.append(f'        <{geom["urdf"]} size="1 1 1"/>')
            lines.append('      </geometry>')
            lines.append('      <material name="default"/>')
            lines.append('    </visual>')

        if include_collision:
            lines.append('    <collision>')
            lines.append('      <geometry>')
            lines.append(f'        <{geom["urdf"]} size="1 1 1"/>')
            lines.append('      </geometry>')
            lines.append('    </collision>')

        if include_inertial:
            mass = default_mass
            lines.append('    <inertial>')
            lines.append(f'      <mass value="{mass}"/>')
            lines.append('      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>')
            lines.append('    </inertial>')

        lines.append('  </link>')
        lines.append('')

        # Add joint connecting to base_link
        joint_name = f"base_to_{link_name}_joint"
        joint_count += 1
        lines.append(f'  <joint name="{joint_name}" type="fixed">')
        lines.append('    <parent link="base_link"/>')
        lines.append(f'    <child link="{link_name}"/>')
        lines.append('    <origin xyz="0 0 0" rpy="0 0 0"/>')
        lines.append('  </joint>')
        lines.append('')

    lines.append('</robot>')

    return URDFExportResult(
        success=True,
        urdf_content='\n'.join(lines),
        robot_name=robot_name,
        link_count=link_count,
        joint_count=joint_count,
        warnings=warnings,
    )


def export_sdf(
    holo_code: str,
    world_name: str = "holoscript_world",
    sdf_version: str = "1.9",
    include_physics: bool = True,
    include_gravity: bool = True,
) -> SDFExportResult:
    """
    Export HoloScript code to SDF (Simulation Description Format) for Gazebo.

    Args:
        holo_code: HoloScript source code to export
        world_name: Name for the SDF world element
        sdf_version: SDF format version (default: 1.9 for Gazebo Harmonic)
        include_physics: Include physics engine configuration
        include_gravity: Include gravity vector

    Returns:
        SDFExportResult with SDF content and metadata

    Example:
        >>> result = export_sdf('''
        ...     plane { @collidable @static }
        ...     sphere { @physics @gravity @collidable @position(0, 5, 0) }
        ... ''')
        >>> print(result.sdf_content)
    """
    from holoscript.parser import parse

    parse_result = parse(holo_code)
    if not parse_result.success:
        return SDFExportResult(
            success=False,
            errors=[f"Parse error: {e.message}" for e in parse_result.errors],
        )

    lines: List[str] = []
    lines.append('<?xml version="1.0"?>')
    lines.append(f'<!-- Auto-generated by HoloScript Python Bindings -->')
    lines.append(f'<!-- holoscript export: sdf -->')
    lines.append(f'<sdf version="{sdf_version}">')
    lines.append(f'  <world name="{_sanitize_xml_attr(world_name)}">')
    lines.append('')

    if include_gravity:
        lines.append('    <gravity>0 0 -9.8</gravity>')
        lines.append('')

    if include_physics:
        lines.append('    <physics name="default_physics" type="ode">')
        lines.append('      <max_step_size>0.001</max_step_size>')
        lines.append('      <real_time_factor>1</real_time_factor>')
        lines.append('      <real_time_update_rate>1000</real_time_update_rate>')
        lines.append('    </physics>')
        lines.append('')

    # Ground plane model
    lines.append('    <include>')
    lines.append('      <uri>model://ground_plane</uri>')
    lines.append('    </include>')
    lines.append('')

    # Ambient lighting
    lines.append('    <include>')
    lines.append('      <uri>model://sun</uri>')
    lines.append('    </include>')
    lines.append('')

    model_count = 0
    objects = parse_result.objects or []

    for obj_name in objects:
        model_name = _sanitize_link_name(obj_name)
        model_count += 1
        geom = _get_geometry_for_object(obj_name)

        lines.append(f'    <model name="{model_name}">')
        lines.append('      <static>false</static>')
        lines.append('      <pose>0 0 0 0 0 0</pose>')
        lines.append('      <link name="link">')
        lines.append('        <inertial>')
        lines.append('          <mass>1.0</mass>')
        lines.append('          <inertia>')
        lines.append('            <ixx>0.1</ixx><ixy>0.0</ixy><ixz>0.0</ixz>')
        lines.append('            <iyy>0.1</iyy><iyz>0.0</iyz><izz>0.1</izz>')
        lines.append('          </inertia>')
        lines.append('        </inertial>')
        lines.append('        <visual name="visual">')
        lines.append('          <geometry>')
        lines.append(f'            <{geom["sdf"]}><size>1 1 1</size></{geom["sdf"]}>')
        lines.append('          </geometry>')
        lines.append('        </visual>')
        lines.append('        <collision name="collision">')
        lines.append('          <geometry>')
        lines.append(f'            <{geom["sdf"]}><size>1 1 1</size></{geom["sdf"]}>')
        lines.append('          </geometry>')
        lines.append('        </collision>')
        lines.append('      </link>')
        lines.append('    </model>')
        lines.append('')

    lines.append('  </world>')
    lines.append('</sdf>')

    return SDFExportResult(
        success=True,
        sdf_content='\n'.join(lines),
        world_name=world_name,
        model_count=model_count,
    )


def generate_ros2_launch(
    holo_code: str,
    package_name: str = "holoscript_scene",
    urdf_file: str = "robot.urdf",
    use_rviz: bool = True,
    use_gazebo: bool = True,
) -> ROSLaunchResult:
    """
    Generate a ROS 2 Python launch file for a HoloScript scene.

    Creates a launch file that starts robot_state_publisher with the
    generated URDF and optionally launches Gazebo and RViz2.

    Args:
        holo_code: HoloScript source code (used for metadata extraction)
        package_name: ROS 2 package name containing the generated files
        urdf_file: Filename of the generated URDF (relative to config/)
        use_rviz: Include RViz2 visualization node
        use_gazebo: Include Gazebo Classic simulator

    Returns:
        ROSLaunchResult with launch file content

    Example:
        >>> result = generate_ros2_launch(my_holo_code, package_name="my_robot")
        >>> with open("launch/holoscript.launch.py", "w") as f:
        ...     f.write(result.launch_content)
    """
    nodes: List[str] = ["robot_state_publisher"]
    if use_gazebo:
        nodes.append("gazebo")
        nodes.append("spawn_entity")
    if use_rviz:
        nodes.append("rviz2")

    lines: List[str] = [
        '"""',
        f'ROS 2 Launch File - Generated by HoloScript Python Bindings',
        f'Package: {package_name}',
        '"""',
        '',
        'from launch import LaunchDescription',
        'from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription',
        'from launch.substitutions import LaunchConfiguration, PathJoinSubstitution',
        'from launch_ros.actions import Node',
        'from launch_ros.substitutions import FindPackageShare',
        'import os',
        '',
        '',
        'def generate_launch_description():',
        f'    pkg_share = FindPackageShare(package="{package_name}").find("{package_name}")',
        f'    urdf_path = os.path.join(pkg_share, "config", "{urdf_file}")',
        '',
        '    with open(urdf_path, "r") as f:',
        '        robot_description = f.read()',
        '',
        '    nodes = []',
        '',
        '    # Robot State Publisher',
        '    nodes.append(Node(',
        '        package="robot_state_publisher",',
        '        executable="robot_state_publisher",',
        '        name="robot_state_publisher",',
        '        output="screen",',
        '        parameters=[{"robot_description": robot_description}],',
        '    ))',
        '',
        '    # Joint State Publisher GUI',
        '    nodes.append(Node(',
        '        package="joint_state_publisher_gui",',
        '        executable="joint_state_publisher_gui",',
        '        name="joint_state_publisher_gui",',
        '    ))',
        '',
    ]

    if use_rviz:
        lines.extend([
            '    # RViz2 Visualization',
            '    nodes.append(Node(',
            '        package="rviz2",',
            '        executable="rviz2",',
            '        name="rviz2",',
            '        output="screen",',
            '    ))',
            '',
        ])

    if use_gazebo:
        lines.extend([
            '    # Gazebo Classic',
            '    nodes.append(Node(',
            '        package="gazebo_ros",',
            '        executable="spawn_entity.py",',
            '        arguments=["-topic", "robot_description", "-entity", "holoscript_robot"],',
            '        output="screen",',
            '    ))',
            '',
        ])

    lines.extend([
        '    return LaunchDescription(nodes)',
    ])

    return ROSLaunchResult(
        success=True,
        launch_content='\n'.join(lines),
        package_name=package_name,
        nodes=nodes,
    )


def list_robotics_traits() -> List[Dict[str, str]]:
    """
    List HoloScript traits relevant to robotics simulation.

    Returns a list of trait descriptions with URDF/SDF mapping info.

    Returns:
        List of dicts with trait name, description, and platform mappings

    Example:
        >>> traits = list_robotics_traits()
        >>> for t in traits:
        ...     print(f"{t['trait']}: {t['description']}")
    """
    result = []
    for trait_name, mapping in ROBOTICS_TRAIT_MAPPINGS.items():
        result.append({
            "trait": trait_name,
            "description": mapping["description"],
            "urdf_element": mapping["urdf"],
            "sdf_element": mapping["sdf"],
        })
    return result


# ============================================================================
# Internal helpers
# ============================================================================

def _sanitize_xml_attr(value: str) -> str:
    """Sanitize a string for use as an XML attribute value."""
    return value.replace('"', '&quot;').replace('<', '&lt;').replace('>', '&gt;')


def _sanitize_link_name(name: str) -> str:
    """Convert object name to a valid URDF link name (lowercase, underscores)."""
    import re
    sanitized = re.sub(r'[^a-zA-Z0-9_]', '_', name.lower())
    if sanitized and sanitized[0].isdigit():
        sanitized = 'link_' + sanitized
    return sanitized or 'unnamed_link'


def _get_geometry_for_object(obj_name: str) -> Dict[str, str]:
    """Map HoloScript object type to URDF/SDF geometry type."""
    name_lower = obj_name.lower()
    for holo_type, mapping in GEOMETRY_TYPES.items():
        if holo_type in name_lower:
            return mapping
    # Default to box for unknown object types
    return {"urdf": "box", "sdf": "box"}
