/**
 * Regression tests for HoloScriptPlusParser.parse() never returning. Each case
 * below once sent a parse loop spinning forever without consuming a token.
 * Parsing is synchronous, so that is a real process hang, not a slow parse: it
 * blocks any tool that reads .hsplus source (LSP, watch mode, repo sweeps).
 * Board task_1790634481269_amrk.
 *
 * The four hang classes found so far:
 *
 * 1. parseMatchExpression()'s case loop, on `match true { <expr> => ... }`
 *    (Hololand Button.hsplus:149). A case "pattern" that is an arbitrary
 *    expression such as `!self.enabled` gets a positioned error from
 *    parseMatchPattern(), which returned without consuming anything.
 * 2. parseStructBlock()'s field loop, on a field that starts with a token no
 *    field name can be, after another field (Hololand Parser.hsplus, struct
 *    ASTNode, `[key: string]: any`). recoverStructField() scanned for a
 *    separator from the token before it, re-found the newline that ended the
 *    previous field, and returned with nothing consumed.
 * 3. The named-import list of `@import { ... } from "..."`, on anything but a
 *    name or a comma: a list written over several lines, a quoted name,
 *    `* as ns`, a keyword such as `state`. All are now refused with a
 *    positioned error; none of them is read as an import list.
 * 4. An orb or object body's `transition "x"` without `-> "target"` (now
 *    refused with a positioned error, not read). Its backtrack went
 *    to before the name, and no branch after it consumes a name.
 *
 * The struct-recovery tests also pin which fields survive recovery. They expect
 * exactly what origin/main's parser keeps for the same source (generated by
 * running main's parser, not written by hand). An earlier version of this fix
 * consumed one token too many and dropped the next valid field.
 *
 * The Hololand files are external, read-only inputs and are not copied here;
 * these are minimal reproductions of the same constructs.
 */
import { assert, describe, expect, it } from 'vitest';
import vm from 'node:vm';
import {
  HoloScriptPlusParser,
  type HSPlusParseResult,
  type HSPlusParserOptions,
} from '../HoloScriptPlusParser';

/** On the fixed parser every case returns in milliseconds. */
const BOUND_MS = 2000;
/** Vitest's own timeout cannot fire during a synchronous loop; this is a backstop. */
const TEST_TIMEOUT_MS = 10000;

type BoundedParse = { hung: true } | { hung: false; result: HSPlusParseResult };

/**
 * The error node:vm throws when its timeout interrupts a script. Under vitest
 * it can come from another realm, so `instanceof Error` is false for it; match
 * on its code and message instead.
 */
function isScriptTimeout(error: unknown): boolean {
  if (typeof error !== 'object' || error === null) return false;
  const { code, message } = error as { code?: unknown; message?: unknown };
  return (
    code === 'ERR_SCRIPT_EXECUTION_TIMEOUT' ||
    (typeof message === 'string' && /Script execution timed out/.test(message))
  );
}

/**
 * Run `parser.parse(source)` under a hard wall-clock bound.
 *
 * A Promise or setTimeout race cannot see this failure: the hang is a
 * synchronous loop that starves the event loop, so no timer ever runs. V8's
 * vm.Script timeout interrupts synchronous code mid-loop, which turns "the
 * process hangs forever" into a fast, observable result.
 */
function parseWithBoundedTime(source: string, options: HSPlusParserOptions = {}): BoundedParse {
  const parser = new HoloScriptPlusParser({ enableVRTraits: true, ...options });
  const sandbox: { parser: HoloScriptPlusParser; source: string; result?: HSPlusParseResult } = {
    parser,
    source,
  };
  vm.createContext(sandbox);
  try {
    vm.runInContext('result = parser.parse(source);', sandbox, { timeout: BOUND_MS });
  } catch (error) {
    if (isScriptTimeout(error)) return { hung: true };
    throw error;
  }
  return { hung: false, result: sandbox.result as HSPlusParseResult };
}

/** Parse, failing with a plain "the reader hung" message if parse() never returns. */
function parseOrReportHang(source: string, options?: HSPlusParserOptions): HSPlusParseResult {
  const outcome = parseWithBoundedTime(source, options);
  if (outcome.hung) {
    assert.fail(`the reader hung: parse() did not return within ${BOUND_MS} ms`);
  }
  return outcome.result;
}

function errorPositions(result: HSPlusParseResult): string[] {
  return result.errors.map((e) => `${e.code}@${e.line}:${e.column}`);
}

type StructFieldPin = {
  name: string;
  projection: string;
  type?: string;
  optional?: boolean;
  annotations?: string[];
};

function structFieldsOf(result: HSPlusParseResult): StructFieldPin[] {
  const children = (result.ast as unknown as { children?: Array<Record<string, unknown>> })
    .children;
  const struct = children?.find((node) => node.type === 'struct');
  expect(struct, 'parse result has no struct node').toBeDefined();
  return (struct!.fields as Array<Record<string, unknown>>).map((field) => {
    const pin: StructFieldPin = {
      name: field.name as string,
      projection: field.projection as string,
    };
    if (field.type !== undefined) pin.type = field.type as string;
    if (field.optional) pin.optional = true;
    if (field.annotations) pin.annotations = field.annotations as string[];
    return pin;
  });
}

describe('HoloScriptPlusParser - reader hang regression', () => {
  describe('match expression case loop', () => {
    it(
      'finishes on `match true { <expr> => ... }` and reports the pattern error (Button.hsplus repro)',
      () => {
        // Minimal reduction of Button.hsplus line 149. The loop is reachable
        // from any value position, so an object property exercises it without
        // depending on @method body handling.
        const result = parseOrReportHang(
          [
            'orb Button {',
            '  color: match true {',
            '    !self.enabled => self.disabledColor,',
            '    self.state == ButtonState.pressed => self.pressedColor,',
            '    _ => self.backgroundColor',
            '  }',
            '}',
          ].join('\n')
        );

        // `!self.enabled` is a boolean-guard idiom, not the literal/identifier/_
        // pattern grammar. This fix is about the hang, not that grammar, so
        // the primary error is the positioned pattern error at the `!`.
        expect(result.success).toBe(false);
        const primary = result.errors[0];
        expect(primary.code).toBe('HSP300');
        expect(primary.message).toMatch(
          /Expected match pattern \(literal, identifier, or _\), got EXCLAMATION/
        );
        expect([primary.line, primary.column]).toEqual([3, 5]);
      },
      TEST_TIMEOUT_MS
    );
  });

  describe('struct field recovery', () => {
    it(
      'finishes on an index-signature field after a normal field (Parser.hsplus repro)',
      () => {
        const result = parseOrReportHang(
          ['struct ASTNode {', '  type: NodeType', '  [key: string]: any', '}'].join('\n')
        );

        expect(result.success).toBe(false);
        expect(
          result.errors.some(
            (e) =>
              e.code === 'HSP100' && /Expected struct field name, got LBRACKET/.test(e.message)
          )
        ).toBe(true);
        expect(structFieldsOf(result)).toEqual([
          { name: 'type', projection: 'typed', type: 'NodeType' },
        ]);
      },
      TEST_TIMEOUT_MS
    );

    it(
      'finishes on a struct whose only field is an index signature',
      () => {
        // The pre-fix code happened not to hang here (the token before `[` is a
        // zero-width INDENT, not a newline). Kept so a refactor cannot quietly
        // re-break it.
        const result = parseOrReportHang(['struct Foo {', '  [key: string]: any', '}'].join('\n'));
        expect(result.success).toBe(false);
        expect(structFieldsOf(result)).toEqual([]);
      },
      TEST_TIMEOUT_MS
    );

    // Each row: source, then what origin/main's parser keeps for it (fields)
    // and where main reports errors. These sources finish on main; recovery
    // must not swallow the field after a bad one. Generated from main's parser.
    const keptByMain: Array<[string, StructFieldPin[], string[]]> = [
      ['struct S { x, y: number }', [{ name: 'y', projection: 'typed', type: 'number' }], ['HSP009@1:12']],
      [
        'struct S { a: number, x, c: string }',
        [
          { name: 'a', projection: 'typed', type: 'number' },
          { name: 'c', projection: 'typed', type: 'string' },
        ],
        ['HSP009@1:23'],
      ],
      ['struct S { @unknown, b }', [], ['HSP100@1:20', 'HSP009@1:22']],
      [
        'struct S { @unknown, b: number }',
        [{ name: 'b', projection: 'typed', type: 'number' }],
        ['HSP100@1:20'],
      ],
      ['struct S {\n  @\n  b\n}', [], ['HSP100@2:3', 'HSP100@2:4', 'HSP009@3:3']],
      [
        'struct S {\n  @\n  b: number\n}',
        [{ name: 'b', projection: 'typed', type: 'number' }],
        ['HSP100@2:3', 'HSP100@2:4'],
      ],
      [
        'struct S { x?, y: number }',
        [{ name: 'y', projection: 'typed', type: 'number' }],
        ['HSP009@1:12'],
      ],
      [
        'struct S { a; x; c }',
        [],
        ['HSP100@1:12', 'HSP009@1:12', 'HSP100@1:15', 'HSP009@1:15', 'HSP009@1:18'],
      ],
      [
        'struct S { a: number; x; c: string }',
        [
          { name: 'a', projection: 'typed', type: 'number' },
          { name: 'c', projection: 'typed', type: 'string' },
        ],
        ['HSP100@1:23', 'HSP009@1:23'],
      ],
      [
        'struct S { @ ; @unknown b: number }',
        [{ name: 'b', projection: 'typed', type: 'number', annotations: ['unknown'] }],
        ['HSP100@1:12', 'HSP100@1:12', 'HSP100@1:16'],
      ],
    ];

    it.each(keptByMain)(
      'keeps the fields main keeps: %j',
      (source, fields, errorsAt) => {
        const result = parseOrReportHang(source + '\n');
        expect(result.success).toBe(false);
        expect(structFieldsOf(result)).toEqual(fields);
        expect(errorPositions(result)).toEqual(errorsAt);
      },
      TEST_TIMEOUT_MS
    );
  });

  describe('named import list', () => {
    it(
      'finishes on a list written over several lines, and refuses it',
      () => {
        const result = parseOrReportHang(
          ['@import {', '  A,', '  B', '} from "./x.hs"', 'orb O { }', ''].join('\n'),
          { enableTypeScriptImports: true }
        );
        // This reader never accepted a list across lines (the loop hung on
        // one). Reading it now would change the language, which needs its own
        // proposal (docs/spec/holoscript-spec-v0.1.md, No-break policy), so it
        // is refused: one positioned error, at the first line break.
        expect(result.success).toBe(false);
        expect(result.errors).toHaveLength(1);
        expect(result.errors[0].code).toBe('HSP002');
        expect(result.errors[0].message).toContain(
          'An @import list must be written on one line in .hsplus; a list across lines is not part of the language yet'
        );
        expect([result.errors[0].line, result.errors[0].column]).toEqual([1, 10]);
      },
      TEST_TIMEOUT_MS
    );

    it.each([
      ['@import { "Foo" } from "./x.hs"', 'STRING "Foo"'],
      ['@import { * as ns } from "./x.hs"', 'ASTERISK "*"'],
      ['@import { state } from "./x.hs"', 'STATE "state"'],
    ])(
      'finishes on %j and reports the token it cannot read',
      (source, got) => {
        const result = parseOrReportHang(source + '\n', { enableTypeScriptImports: true });
        expect(result.success).toBe(false);
        expect(result.errors[0].code).toBe('HSP002');
        expect(result.errors[0].message).toContain(
          `Expected a name in the import list, got ${got}`
        );
        expect([result.errors[0].line, result.errors[0].column]).toEqual([1, 11]);
      },
      TEST_TIMEOUT_MS
    );
  });

  describe('transition without an arrow', () => {
    const firstChild = (result: HSPlusParseResult) => {
      const root = result.ast as unknown as { children?: Array<Record<string, unknown>> };
      const node = root.children?.[0] as { children?: Array<Record<string, unknown>> } | undefined;
      return node?.children?.[0];
    };

    // In an orb or object body, main reads only the arrow form and hung on every
    // other quoted transition, so those are refused, never read. (Main reads the
    // block form inside a template or state_machine body; that is unchanged.)
    const refusal = (event: string) =>
      `Expected -> after transition "${event}": in this body a transition is written transition "${event}" -> "target"`;

    it.each(['orb', 'object'])(
      'finishes on `%s O { transition "fade" }` and refuses it',
      (keyword) => {
        const result = parseOrReportHang(`${keyword} O { transition "fade" }\n`);
        expect(result.success).toBe(false);
        const primary = result.errors[0];
        expect(primary.code).toBe('HSP001');
        expect(primary.message).toContain(refusal('fade'));
        // At the token where -> should be: the closing brace.
        expect([primary.line, primary.column]).toEqual([1, keyword.length + 24]);
      },
      TEST_TIMEOUT_MS
    );

    it(
      'refuses `transition "name" { ... }` in an orb body, and still reads what follows',
      () => {
        const result = parseOrReportHang(
          ['orb O {', '  transition "fade" { guard: "x" }', '  color: "red"', '}', ''].join('\n')
        );
        expect(result.success).toBe(false);
        expect(result.errors).toHaveLength(1);
        expect(result.errors[0].code).toBe('HSP001');
        expect(result.errors[0].message).toContain(refusal('fade'));
        expect([result.errors[0].line, result.errors[0].column]).toEqual([2, 21]);
        // Recovery moves past the refused block without swallowing the next line.
        const orb = (result.ast as unknown as { children: Array<{ properties: Record<string, unknown> }> })
          .children[0];
        expect(orb.properties.color).toBe('red');
      },
      TEST_TIMEOUT_MS
    );

    it(
      'still reads the arrow form `transition "event" -> "target"`',
      () => {
        const result = parseOrReportHang('orb O { transition "go" -> "done" }\n');
        expect(result.errors).toEqual([]);
        expect(firstChild(result)).toMatchObject({
          type: 'transition',
          event: 'go',
          target: 'done',
        });
      },
      TEST_TIMEOUT_MS
    );
  });
});
