/**
 * OPLoRAMonitor.ts
 *
 * Monitors OPLoRA training for catastrophic forgetting indicators during
 * GRPO training of the Brittney 7B model.
 *
 * Tracks:
 *   - Benchmark scores over training steps (HumanEval, MBPP)
 *   - Orthogonal projection constraint satisfaction percentage
 *   - Per-module weight magnitude ratios (LoRA delta vs base weights)
 *   - Alerts when general ability drops beyond configurable thresholds
 *   - Recommendations for corrective action
 *
 * The monitor stores full history for dashboard visualisation and provides
 * a rich API for querying training health at any point.
 *
 * @module self-improvement
 */

// =============================================================================
// TYPES
// =============================================================================

/** Supported benchmark identifiers */
export type BenchmarkName = 'humaneval' | 'mbpp' | 'holoscript_eval' | string;

/** A single benchmark score measurement at a training step */
export interface BenchmarkScore {
  /** Training step when this measurement was taken */
  step: number;
  /** Benchmark identifier */
  benchmark: BenchmarkName;
  /** Score value (typically 0-100 or 0-1 depending on benchmark) */
  score: number;
  /** Timestamp of measurement */
  timestamp: number;
}

/** Per-module weight magnitude data */
export interface ModuleWeightRatio {
  /** Module name (e.g., "q_proj", "v_proj") */
  moduleName: string;
  /** Training step */
  step: number;
  /** Frobenius norm of the LoRA delta weights */
  loraDeltaNorm: number;
  /** Frobenius norm of the base (pre-trained) weights */
  baseWeightNorm: number;
  /** Ratio: loraDeltaNorm / baseWeightNorm */
  ratio: number;
}

/** Orthogonal constraint satisfaction measurement */
export interface ConstraintSatisfaction {
  /** Training step */
  step: number;
  /** Percentage of constraint satisfied (0-100) */
  satisfactionPct: number;
  /** Per-module breakdown */
  perModule: Record<string, number>;
}

/** Alert severity levels */
export type AlertSeverity = 'info' | 'warning' | 'critical';

/** An alert generated by the monitor */
export interface MonitorAlert {
  /** Alert severity */
  severity: AlertSeverity;
  /** Short description */
  message: string;
  /** Detailed recommendation for corrective action */
  recommendation: string;
  /** Training step when the alert was raised */
  step: number;
  /** Timestamp when the alert was raised */
  timestamp: number;
  /** Which benchmark or module triggered the alert (if applicable) */
  source?: string;
}

/** Configuration for the OPLoRA monitor */
export interface OPLoRAMonitorConfig {
  /**
   * Absolute score drop threshold (in the same units as the benchmark).
   * Alert when: baseline_score - current_score > absoluteDropThreshold.
   * Default: 2 (for percentage-based benchmarks like HumanEval).
   */
  absoluteDropThreshold: number;

  /**
   * Relative score drop threshold (as a fraction of baseline).
   * Alert when: (baseline - current) / baseline > relativeDropThreshold.
   * Default: 0.05 (5% relative drop).
   */
  relativeDropThreshold: number;

  /**
   * Minimum constraint satisfaction percentage before alerting.
   * Default: 80 (alert if satisfaction drops below 80%).
   */
  minConstraintSatisfaction: number;

  /**
   * Maximum acceptable weight magnitude ratio (LoRA delta / base).
   * If any module exceeds this, it suggests the adapter is overriding
   * too much of the base model's knowledge.
   * Default: 0.1 (LoRA delta should be < 10% of base weight norm).
   */
  maxWeightRatio: number;

  /**
   * Number of steps to look back for trend analysis.
   * Default: 10.
   */
  trendWindowSize: number;
}

/** Aggregate statistics for the monitor */
export interface MonitorStats {
  /** Total benchmark measurements recorded */
  totalBenchmarkMeasurements: number;
  /** Total weight ratio measurements recorded */
  totalWeightMeasurements: number;
  /** Total constraint measurements recorded */
  totalConstraintMeasurements: number;
  /** Total alerts raised */
  totalAlerts: number;
  /** Alerts by severity */
  alertsBySeverity: Record<AlertSeverity, number>;
  /** Current step (most recent measurement) */
  currentStep: number;
  /** Latest scores per benchmark */
  latestScores: Record<string, number>;
  /** Baseline scores per benchmark */
  baselineScores: Record<string, number>;
}

/** Full snapshot of monitor state for dashboard serialisation */
export interface MonitorSnapshot {
  config: OPLoRAMonitorConfig;
  stats: MonitorStats;
  benchmarkHistory: BenchmarkScore[];
  weightHistory: ModuleWeightRatio[];
  constraintHistory: ConstraintSatisfaction[];
  alerts: MonitorAlert[];
}

// =============================================================================
// DEFAULTS
// =============================================================================

const DEFAULT_MONITOR_CONFIG: OPLoRAMonitorConfig = {
  absoluteDropThreshold: 2,
  relativeDropThreshold: 0.05,
  minConstraintSatisfaction: 80,
  maxWeightRatio: 0.1,
  trendWindowSize: 10,
};

// =============================================================================
// MONITOR
// =============================================================================

/**
 * OPLoRA training monitor that tracks forgetting indicators and provides
 * alerts with corrective recommendations.
 *
 * @example
 * ```ts
 * const monitor = new OPLoRAMonitor();
 *
 * // Set baselines before training
 * monitor.setBaseline('humaneval', 65.0);
 * monitor.setBaseline('mbpp', 72.0);
 *
 * // During training, record measurements
 * monitor.recordBenchmark({ step: 100, benchmark: 'humaneval', score: 64.5 });
 * monitor.recordConstraint({ step: 100, satisfactionPct: 95, perModule: {} });
 *
 * // Check for alerts
 * const alerts = monitor.getAlerts();
 * const snapshot = monitor.getSnapshot();
 * ```
 */
export class OPLoRAMonitor {
  private config: OPLoRAMonitorConfig;
  private baselines: Map<string, number> = new Map();
  private benchmarkHistory: BenchmarkScore[] = [];
  private weightHistory: ModuleWeightRatio[] = [];
  private constraintHistory: ConstraintSatisfaction[] = [];
  private alerts: MonitorAlert[] = [];
  private currentStep: number = 0;

  constructor(config: Partial<OPLoRAMonitorConfig> = {}) {
    this.config = { ...DEFAULT_MONITOR_CONFIG, ...config };
  }

  // ---------------------------------------------------------------------------
  // Baseline management
  // ---------------------------------------------------------------------------

  /**
   * Set the baseline score for a benchmark (measured before training starts).
   * All forgetting detection is measured relative to these baselines.
   */
  setBaseline(benchmark: BenchmarkName, score: number): void {
    this.baselines.set(benchmark, score);
  }

  /**
   * Get the baseline score for a benchmark.
   * Returns undefined if no baseline has been set.
   */
  getBaseline(benchmark: BenchmarkName): number | undefined {
    return this.baselines.get(benchmark);
  }

  // ---------------------------------------------------------------------------
  // Recording measurements
  // ---------------------------------------------------------------------------

  /**
   * Record a benchmark score and check for forgetting.
   * Returns any new alerts generated by this measurement.
   */
  recordBenchmark(measurement: Omit<BenchmarkScore, 'timestamp'>): MonitorAlert[] {
    const entry: BenchmarkScore = {
      ...measurement,
      timestamp: Date.now(),
    };
    this.benchmarkHistory.push(entry);
    this.currentStep = Math.max(this.currentStep, measurement.step);

    return this.checkBenchmarkAlerts(entry);
  }

  /**
   * Record per-module weight magnitude ratios.
   * Returns any new alerts generated by this measurement.
   */
  recordWeightRatio(ratio: ModuleWeightRatio): MonitorAlert[] {
    this.weightHistory.push(ratio);
    this.currentStep = Math.max(this.currentStep, ratio.step);

    return this.checkWeightAlerts(ratio);
  }

  /**
   * Record orthogonal constraint satisfaction.
   * Returns any new alerts generated by this measurement.
   */
  recordConstraint(
    measurement: Omit<ConstraintSatisfaction, never>,
  ): MonitorAlert[] {
    this.constraintHistory.push(measurement);
    this.currentStep = Math.max(this.currentStep, measurement.step);

    return this.checkConstraintAlerts(measurement);
  }

  // ---------------------------------------------------------------------------
  // Alert checking (internal)
  // ---------------------------------------------------------------------------

  private checkBenchmarkAlerts(entry: BenchmarkScore): MonitorAlert[] {
    const newAlerts: MonitorAlert[] = [];
    const baseline = this.baselines.get(entry.benchmark);

    if (baseline === undefined) return newAlerts;

    const absoluteDrop = baseline - entry.score;
    const relativeDrop = baseline > 0 ? absoluteDrop / baseline : 0;

    // Critical: exceeds absolute drop threshold
    if (absoluteDrop > this.config.absoluteDropThreshold) {
      const alert: MonitorAlert = {
        severity: 'critical',
        message: `${entry.benchmark} score dropped ${round4(absoluteDrop)} points from baseline ${baseline} to ${entry.score}`,
        recommendation:
          'Increase orthogonalWeight by 0.5, reduce learning rate by 50%, or increase projectionRank. ' +
          'Consider early stopping if the drop persists for 50+ steps.',
        step: entry.step,
        timestamp: entry.timestamp,
        source: entry.benchmark,
      };
      newAlerts.push(alert);
      this.alerts.push(alert);
    }
    // Warning: exceeds relative drop threshold
    else if (relativeDrop > this.config.relativeDropThreshold) {
      const alert: MonitorAlert = {
        severity: 'warning',
        message: `${entry.benchmark} score dropped ${round4(relativeDrop * 100)}% relative to baseline`,
        recommendation:
          'Consider increasing orthogonalWeight by 0.25 or reducing learning rate by 25%. ' +
          'Monitor closely for the next 100 steps.',
        step: entry.step,
        timestamp: entry.timestamp,
        source: entry.benchmark,
      };
      newAlerts.push(alert);
      this.alerts.push(alert);
    }

    // Trend analysis: check if scores are declining even if within thresholds
    const benchmarkScores = this.benchmarkHistory
      .filter((s) => s.benchmark === entry.benchmark)
      .slice(-this.config.trendWindowSize);

    if (benchmarkScores.length >= 3) {
      const slope = computeSlope(benchmarkScores.map((s) => s.score));
      if (slope < -0.01 && absoluteDrop <= this.config.absoluteDropThreshold) {
        const alert: MonitorAlert = {
          severity: 'info',
          message: `${entry.benchmark} shows negative trend (slope: ${round4(slope)} per step)`,
          recommendation:
            'Negative trend detected. No action required yet, but continue monitoring. ' +
            'If the trend persists for 200+ steps, preemptively increase orthogonalWeight.',
          step: entry.step,
          timestamp: entry.timestamp,
          source: entry.benchmark,
        };
        newAlerts.push(alert);
        this.alerts.push(alert);
      }
    }

    return newAlerts;
  }

  private checkWeightAlerts(ratio: ModuleWeightRatio): MonitorAlert[] {
    const newAlerts: MonitorAlert[] = [];

    if (ratio.ratio > this.config.maxWeightRatio) {
      const alert: MonitorAlert = {
        severity: 'warning',
        message: `Module "${ratio.moduleName}" LoRA delta is ${round4(ratio.ratio * 100)}% of base weight norm (threshold: ${this.config.maxWeightRatio * 100}%)`,
        recommendation:
          `Reduce learning rate for module "${ratio.moduleName}" or increase loraDropout. ` +
          'Large LoRA deltas relative to base weights indicate the adapter is overriding ' +
          'base knowledge rather than extending it.',
        step: ratio.step,
        timestamp: Date.now(),
        source: ratio.moduleName,
      };
      newAlerts.push(alert);
      this.alerts.push(alert);
    }

    return newAlerts;
  }

  private checkConstraintAlerts(
    measurement: ConstraintSatisfaction,
  ): MonitorAlert[] {
    const newAlerts: MonitorAlert[] = [];

    if (measurement.satisfactionPct < this.config.minConstraintSatisfaction) {
      const severity: AlertSeverity =
        measurement.satisfactionPct < this.config.minConstraintSatisfaction * 0.75
          ? 'critical'
          : 'warning';

      const alert: MonitorAlert = {
        severity,
        message: `Orthogonal constraint satisfaction dropped to ${round4(measurement.satisfactionPct)}% (minimum: ${this.config.minConstraintSatisfaction}%)`,
        recommendation:
          'Increase orthogonalWeight by 0.5 or recompute SVD basis (reduce svdRecomputeInterval). ' +
          'Low constraint satisfaction means LoRA updates are intruding into the protected knowledge subspace.',
        step: measurement.step,
        timestamp: Date.now(),
      };
      newAlerts.push(alert);
      this.alerts.push(alert);
    }

    // Check per-module constraint satisfaction
    for (const [moduleName, satisfaction] of Object.entries(measurement.perModule)) {
      if (satisfaction < this.config.minConstraintSatisfaction * 0.5) {
        const alert: MonitorAlert = {
          severity: 'critical',
          message: `Module "${moduleName}" constraint satisfaction is critically low at ${round4(satisfaction)}%`,
          recommendation:
            `Module "${moduleName}" needs attention. Consider excluding it from LoRA targets ` +
            'or significantly increasing orthogonalWeight.',
          step: measurement.step,
          timestamp: Date.now(),
          source: moduleName,
        };
        newAlerts.push(alert);
        this.alerts.push(alert);
      }
    }

    return newAlerts;
  }

  // ---------------------------------------------------------------------------
  // Query API
  // ---------------------------------------------------------------------------

  /** Get all alerts, optionally filtered by severity */
  getAlerts(severity?: AlertSeverity): MonitorAlert[] {
    if (severity) {
      return this.alerts.filter((a) => a.severity === severity);
    }
    return [...this.alerts];
  }

  /** Get alerts raised after a specific step */
  getAlertsSinceStep(step: number): MonitorAlert[] {
    return this.alerts.filter((a) => a.step >= step);
  }

  /** Get the most recent benchmark scores for all tracked benchmarks */
  getLatestScores(): Record<string, number> {
    const latest: Record<string, number> = {};
    for (const entry of this.benchmarkHistory) {
      latest[entry.benchmark] = entry.score;
    }
    return latest;
  }

  /** Get benchmark score history for a specific benchmark */
  getBenchmarkHistory(benchmark: BenchmarkName): BenchmarkScore[] {
    return this.benchmarkHistory.filter((s) => s.benchmark === benchmark);
  }

  /** Get the latest constraint satisfaction measurement */
  getLatestConstraint(): ConstraintSatisfaction | undefined {
    return this.constraintHistory.length > 0
      ? this.constraintHistory[this.constraintHistory.length - 1]
      : undefined;
  }

  /** Get aggregate statistics */
  getStats(): MonitorStats {
    const alertsBySeverity: Record<AlertSeverity, number> = {
      info: 0,
      warning: 0,
      critical: 0,
    };
    for (const alert of this.alerts) {
      alertsBySeverity[alert.severity]++;
    }

    return {
      totalBenchmarkMeasurements: this.benchmarkHistory.length,
      totalWeightMeasurements: this.weightHistory.length,
      totalConstraintMeasurements: this.constraintHistory.length,
      totalAlerts: this.alerts.length,
      alertsBySeverity,
      currentStep: this.currentStep,
      latestScores: this.getLatestScores(),
      baselineScores: Object.fromEntries(this.baselines),
    };
  }

  /** Get a full snapshot of the monitor state for dashboard serialisation */
  getSnapshot(): MonitorSnapshot {
    return {
      config: { ...this.config },
      stats: this.getStats(),
      benchmarkHistory: [...this.benchmarkHistory],
      weightHistory: [...this.weightHistory],
      constraintHistory: [...this.constraintHistory],
      alerts: [...this.alerts],
    };
  }

  /** Reset the monitor to initial state */
  reset(): void {
    this.baselines.clear();
    this.benchmarkHistory = [];
    this.weightHistory = [];
    this.constraintHistory = [];
    this.alerts = [];
    this.currentStep = 0;
  }
}

// =============================================================================
// HELPERS
// =============================================================================

/**
 * Compute OLS slope over an array of values.
 * x = 0, 1, 2, ..., n-1
 */
function computeSlope(values: number[]): number {
  const n = values.length;
  if (n < 2) return 0;

  let sumX = 0;
  let sumY = 0;
  let sumXY = 0;
  let sumX2 = 0;

  for (let i = 0; i < n; i++) {
    sumX += i;
    sumY += values[i];
    sumXY += i * values[i];
    sumX2 += i * i;
  }

  const denominator = n * sumX2 - sumX * sumX;
  if (denominator === 0) return 0;

  return (n * sumXY - sumX * sumY) / denominator;
}

function round4(v: number): number {
  return Math.round(v * 10000) / 10000;
}
