'use client';

/**
 * AvatarExportPanel — Export options for composed avatars
 *
 * POC: JSON config export + stub for GLB/VRM export.
 * Full implementation requires a server-side mesh compositor
 * that can merge GLB parts and bake textures.
 */

import { useState } from 'react';
import { Download, FileJson, Package, FileCode, Copy, Check } from 'lucide-react';
import {
  useAvatarStore,
  exportAvatarConfig,
  getActiveTraits,
  AVATAR_PARTS,
} from '@/lib/stores/avatarStore';
import { logger } from '@/lib/logger';

export function AvatarExportPanel() {
  const config = useAvatarStore((s) => s.config);
  const [copied, setCopied] = useState(false);
  const [exporting, setExporting] = useState(false);

  const traits = getActiveTraits(config);
  const exportData = exportAvatarConfig(config);
  const exportJson = JSON.stringify(exportData, null, 2);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(exportJson);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJSON = () => {
    const blob = new Blob([exportJson], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `avatar-config-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
    logger.debug('[AvatarExport] Downloaded JSON config');
  };

  const handleExportGLB = async () => {
    setExporting(true);
    logger.debug('[AvatarExport] GLB export requested');

    // POC: Simulate async export
    await new Promise((resolve) => setTimeout(resolve, 1500));

    alert(
      'GLB export is a POC stub.\n\n' +
        'Full implementation requires:\n' +
        '• Server-side mesh compositor\n' +
        '• GLB part merging\n' +
        '• Texture atlas baking\n' +
        '• Skeleton re-targeting'
    );
    setExporting(false);
  };

  const handleExportVRM = async () => {
    setExporting(true);
    logger.debug('[AvatarExport] VRM export requested');

    await new Promise((resolve) => setTimeout(resolve, 1500));

    alert(
      'VRM export is a POC stub.\n\n' +
        'Full implementation requires:\n' +
        '• VRM 1.0/0.x spec compliance\n' +
        '• Blend shape mapping\n' +
        '• Spring bone setup\n' +
        '• License metadata injection'
    );
    setExporting(false);
  };

  const handleExportHoloScript = () => {
    const parts = [
      config.head && `  head = "${config.head}"`,
      config.body && `  body = "${config.body}"`,
      config.hair && `  hair = "${config.hair}"`,
      config.eyes && `  eyes = "${config.eyes}"`,
      config.mouth && `  mouth = "${config.mouth}"`,
      config.clothing.length > 0 && `  clothing = [${config.clothing.map((c) => `"${c}"`).join(', ')}]`,
      config.accessories.length > 0 &&
        `  accessories = [${config.accessories.map((a) => `"${a}"`).join(', ')}]`,
      `  scale = ${config.scale}`,
      `  colors = ${JSON.stringify(config.colors, null, 4).replace(/\n/g, '\n  ')}`,
    ]
      .filter(Boolean)
      .join('\n');

    const hsCode = `// Auto-generated by HoloScript Avatar Authoring\n// ${new Date().toISOString()}\n\navatar "MyAvatar" {\n${parts}\n}\n`;

    const blob = new Blob([hsCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `avatar-${Date.now()}.holo`;
    a.click();
    URL.revokeObjectURL(url);
    logger.debug('[AvatarExport] Exported .holo');
  };

  const resolvedParts = [
    config.head,
    config.body,
    config.hair,
    config.eyes,
    config.mouth,
    ...config.clothing,
    ...config.accessories,
  ]
    .filter(Boolean)
    .map((id) => AVATAR_PARTS.find((p) => p.id === id))
    .filter(Boolean);

  return (
    <div className="flex h-full">
      {/* Left: Export actions */}
      <div className="flex w-96 flex-col border-r border-studio-border bg-studio-panel p-6">
        <h2 className="text-lg font-bold text-white">Export Avatar</h2>
        <p className="mt-1 text-sm text-studio-muted">Choose your export format</p>

        <div className="mt-6 space-y-3">
          <button
            onClick={handleDownloadJSON}
            className="flex w-full items-center gap-3 rounded-xl border border-studio-border bg-black/20 p-4 text-left transition hover:border-purple-500/40"
          >
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-500/10">
              <FileJson className="h-5 w-5 text-blue-400" />
            </div>
            <div>
              <p className="text-sm font-semibold text-white">JSON Config</p>
              <p className="text-xs text-studio-muted">Machine-readable part configuration</p>
            </div>
          </button>

          <button
            onClick={handleExportHoloScript}
            className="flex w-full items-center gap-3 rounded-xl border border-studio-border bg-black/20 p-4 text-left transition hover:border-purple-500/40"
          >
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-purple-500/10">
              <FileCode className="h-5 w-5 text-purple-400" />
            </div>
            <div>
              <p className="text-sm font-semibold text-white">HoloScript (.holo)</p>
              <p className="text-xs text-studio-muted">Native HoloScript avatar definition</p>
            </div>
          </button>

          <button
            onClick={handleExportGLB}
            disabled={exporting}
            className="flex w-full items-center gap-3 rounded-xl border border-studio-border bg-black/20 p-4 text-left transition hover:border-purple-500/40 disabled:opacity-50"
          >
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-green-500/10">
              <Package className="h-5 w-5 text-green-400" />
            </div>
            <div>
              <p className="text-sm font-semibold text-white">GLB (3D Model)</p>
              <p className="text-xs text-studio-muted">Requires server-side compositor (POC)</p>
            </div>
          </button>

          <button
            onClick={handleExportVRM}
            disabled={exporting}
            className="flex w-full items-center gap-3 rounded-xl border border-studio-border bg-black/20 p-4 text-left transition hover:border-purple-500/40 disabled:opacity-50"
          >
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-pink-500/10">
              <Package className="h-5 w-5 text-pink-400" />
            </div>
            <div>
              <p className="text-sm font-semibold text-white">VRM (VR Avatar)</p>
              <p className="text-xs text-studio-muted">VR-ready with blend shapes (POC)</p>
            </div>
          </button>
        </div>

        <div className="mt-6 rounded-lg border border-yellow-500/30 bg-yellow-500/5 p-4">
          <p className="text-xs font-semibold text-yellow-300">⚠️ POC Limitations</p>
          <ul className="mt-2 list-inside list-disc space-y-1 text-xs text-yellow-200/60">
            <li>GLB/VRM exports are stubs — no mesh merging yet</li>
            <li>Preview uses emoji placeholders, not 3D models</li>
            <li>JSON and .holo exports are fully functional</li>
          </ul>
        </div>
      </div>

      {/* Right: Raw config preview */}
      <div className="flex flex-1 flex-col bg-studio-bg">
        <div className="flex items-center justify-between border-b border-studio-border px-6 py-3">
          <h3 className="text-sm font-semibold text-white">Raw Configuration</h3>
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 rounded-lg border border-studio-border px-3 py-1.5 text-xs text-studio-muted transition hover:text-studio-text"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-green-400" /> : <Copy className="h-3.5 w-3.5" />}
            {copied ? 'Copied!' : 'Copy'}
          </button>
        </div>

        <div className="flex-1 overflow-auto p-6">
          <pre className="rounded-xl border border-studio-border bg-black/40 p-4 text-xs text-studio-muted">
            <code>{exportJson}</code>
          </pre>
        </div>
      </div>
    </div>
  );
}
