import { World } from '@holoscript/engine/ecs/World';
import { EditorPersistence } from './EditorPersistence';
import { HoloScriptRuntime } from '../HoloScriptRuntime';
import { HoloScriptCodeParser } from '../HoloScriptCodeParser';
import { logger } from '../logger';

export type PlayModeState = 'stopped' | 'playing' | 'paused';

export interface PlayModeOptions {
  world: World;
  persistence: EditorPersistence;
  onStateChange?: (state: PlayModeState) => void;
}

/**
 * PlayModeController
 *
 * Manages the play/pause/stop execution loop for the HoloScript Studio similar to Unity's Play mode.
 * Automatically handles state snapshots and AST compilation.
 */
export class PlayModeController {
  private state: PlayModeState = 'stopped';
  private world: World;
  private persistence: EditorPersistence;
  private onStateChange?: (state: PlayModeState) => void;
  private runtime: HoloScriptRuntime | null = null;
  
  // Snapshot identifier to recover state when stopped
  private readonly PLAY_SNAPSHOT_KEY = '__editor_play_snapshot__';

  constructor(options: PlayModeOptions) {
    this.world = options.world;
    this.persistence = options.persistence;
    this.onStateChange = options.onStateChange;
  }

  public getState(): PlayModeState {
    return this.state;
  }

  public async play(): Promise<void> {
    if (this.state === 'playing') return;

    logger.info('[PlayModeController] Entering Play Mode');
    
    // 1. Snapshot editor state before playing
    if (this.state === 'stopped') {
      this.persistence.save(this.PLAY_SNAPSHOT_KEY);
    }

    this.state = 'playing';
    this.notifyStateChange();

    // 2. Fetch the current composition logic
    // Usually the logic would be generated by AST compiler or derived from UI system. 
    // Here we can initialize our runtime instance and hook into the engine.
    try {
      // In a real implementation this would fetch true AST from VisualEditor / EditorPersistence.
      const dummyAst = { type: 'Composition', name: 'Preview', declarations: [] }; 
      this.runtime = new HoloScriptRuntime(dummyAst);
      // Wait for initialization
      await this.runtime.executeNode(dummyAst as any); 
    } catch (e) {
      logger.error('[PlayModeController] Failed to enter play mode:', e);
      this.stop();
    }
  }

  public pause(): void {
    if (this.state !== 'playing') return;
    logger.info('[PlayModeController] Pausing Play Mode');
    this.state = 'paused';
    this.notifyStateChange();
    // Logic to freeze the HoloScript engine tick would go here
  }

  public stop(): void {
    if (this.state === 'stopped') return;
    logger.info('[PlayModeController] Stopping Play Mode and restoring state');
    this.state = 'stopped';
    this.notifyStateChange();

    // Clear runtime
    this.runtime = null;

    // Restore to edit-time state
    try {
      this.persistence.load(this.PLAY_SNAPSHOT_KEY);
    } catch (e) {
      logger.error('[PlayModeController] Failed to restore editor snapshot', e);
    }
  }

  /**
   * Used for Phase 3 Copilot Generate-and-Run.
   * Can accept newly generated HoloScript directly from Copilot.
   */
  public async executeGeneratedScript(holoScriptCode: string): Promise<void> {
    logger.info('[PlayModeController] Executing AI generated script directly.', holoScriptCode.length);
    try {
      const parser = new HoloScriptCodeParser();
      const ast = parser.parse(holoScriptCode);
      
      this.runtime = new HoloScriptRuntime(ast);
      
      // Stop current play mode if already running
      if (this.state !== 'stopped') {
        this.stop();
      }

      await this.play();
      this.runtime.executeProgram(ast, 0);

    } catch (e) {
      logger.error('[PlayModeController] Error executing generated script:', e);
    }
  }

  private notifyStateChange(): void {
    if (this.onStateChange) {
      this.onStateChange(this.state);
    }
  }
}
