#!/usr/bin/env tsx
/**
 * holoscript.net — Lotus Scene Compiler (native-surface dogfood)
 *
 * Compiles the papers-program "proof flower" from its HoloScript composition
 * (examples/lotus-flower/garden.seedable.holo) into a deterministic render
 * scene. The lotus is AUTHORED in HoloScript and COMPILED to R3F — it is not
 * hand-authored in the renderer (F.099; the flower is the I.007 genesis proof,
 * so it must itself be compiled HoloScript). This mirrors the Studio view
 * registry's generated-as-source doctrine (compile-view-registry.ts).
 *
 *   .holo  ──parseHolo──▶ objects ──buildLotusSceneFromComposition──▶ LotusScene
 *                                          (+ botanical_lotus render profile)
 *
 * The renderer (LotusProgram.tsx) imports LOTUS_SCENE from the generated module;
 * it owns NONE of the flower's structure, placement, palette, or bloom state.
 *
 * Usage: pnpm lotus:build   |   pnpm lotus:check  (--strict, CI drift gate)
 *
 * @cites I.007, F.014 (no regex HS parsing — uses @holoscript/core parseHolo), F.099
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { parseHolo } from '../../../packages/core/src/parser/HoloCompositionParser';
import {
  buildLotusSceneFromComposition,
  createBotanicalLotusRenderProfile,
} from '../../../packages/core/src/traits/BotanicalLotusTrait';

const SCRIPT_DIR = import.meta.dirname || __dirname;
const SERVICE_ROOT = join(SCRIPT_DIR, '..');
const HOLO_SRC = join(SERVICE_ROOT, '..', '..', 'examples', 'lotus-flower', 'garden.seedable.holo');
const OUT_PATH = join(SERVICE_ROOT, 'src', 'components', 'lotus.scene.generated.ts');
const STRICT = process.argv.includes('--strict') || process.env.HOLO_STRICT === '1';

const EXPECTED_PETALS = 42; // 8 + 13 + 21 Fibonacci rings

function render(): { out: string; petalCount: number } {
  const src = readFileSync(HOLO_SRC, 'utf-8');
  const parsed = parseHolo(src);
  if (!parsed.success || !parsed.ast) {
    throw new Error(
      `garden.seedable.holo did not parse: ${JSON.stringify(parsed.errors?.[0] ?? 'unknown')}`
    );
  }
  const objects = (parsed.ast as { objects?: unknown[] }).objects ?? [];
  const scene = buildLotusSceneFromComposition(
    objects as Parameters<typeof buildLotusSceneFromComposition>[0],
    createBotanicalLotusRenderProfile()
  );
  if (scene.petals.length !== EXPECTED_PETALS) {
    throw new Error(
      `expected ${EXPECTED_PETALS} petals from the composition, compiled ${scene.petals.length}`
    );
  }
  const out =
    '// @generated by scripts/compile-lotus-scene.mts from ' +
    'examples/lotus-flower/garden.seedable.holo — DO NOT EDIT.\n' +
    '// Edit the .holo composition (or the botanical_lotus trait) and run `pnpm lotus:build`.\n' +
    "// The lotus is compiled HoloScript: structure + per-paper bloom from the .holo,\n" +
    "// geometry + pink palette + PBR from the @holoscript/core botanical_lotus trait.\n" +
    "import type { LotusScene } from '@holoscript/core/traits/botanical-lotus';\n\n" +
    `export const LOTUS_SCENE: LotusScene = ${JSON.stringify(scene, null, 2)};\n`;
  return { out, petalCount: scene.petals.length };
}

function main(): void {
  const { out, petalCount } = render();

  if (STRICT) {
    // Drift gate: the committed generated scene must match a fresh compile.
    if (!existsSync(OUT_PATH)) {
      throw new Error(`lotus:check (strict): ${OUT_PATH} missing — run pnpm lotus:build`);
    }
    const current = readFileSync(OUT_PATH, 'utf-8');
    if (current.trim() !== out.trim()) {
      throw new Error(
        'lotus:check (strict): generated lotus scene is STALE.\n' +
          'The .holo composition or botanical_lotus trait changed without regenerating.\n' +
          'Run `pnpm lotus:build` and commit src/components/lotus.scene.generated.ts.'
      );
    }
    console.log(`✓ lotus scene up to date (${EXPECTED_PETALS} petals) — no drift`);
    return;
  }

  writeFileSync(OUT_PATH, out);
  console.log(`✓ compiled garden.seedable.holo → ${OUT_PATH} (${petalCount} petals)`);
}

main();
