package com.meta.spatial.samples.startersample

import com.meta.spatial.core.Entity

/*
 * @generated by the quest compiler from the worlds/ folder (compile_to_quest, world registry).
 * DO NOT EDIT — add a world by dropping a worlds/<id>.holo and recompiling.
 * Maps a scanned world id (WorldPortal.worldId) to its compiled HoloScript world.
 */
object Worlds {
  val ids: Set<String> = setOf("aurora", "hololand")

  /** Build the compiled world for [worldId], or null if no such HoloScript world is bundled. */
  fun build(worldId: String): MutableList<Entity>? =
      when (worldId.lowercase()) {
      "aurora" -> World_aurora.build()
      "hololand" -> World_hololand.build()
        else -> null
      }

  /** The world's own display name (from its composition), or null if unknown. */
  fun displayName(worldId: String): String? =
      when (worldId.lowercase()) {
      "aurora" -> World_aurora.displayName
      "hololand" -> World_hololand.displayName
        else -> null
      }
}
