import React from 'react';
import {
  AbsoluteFill,
  Sequence,
  useVideoConfig,
  interpolate,
  useCurrentFrame,
  Easing,
} from 'remotion';
import { TitleCard } from '../components/TitleCard';
import { CodeStep } from '../components/CodeStep';
import { theme } from '../utils/theme';

// ─── Input .holo scene ───────────────────────────────────────────────────────

const HOLO_STEPS = [
  {
    title: 'Write the .holo scene',
    description: 'We start with a simple scene: a spinning cube that casts shadows.',
    lines: [
      { content: 'scene SpinningDemo {', highlight: true, annotation: 'scene root' },
      { content: '  object Cube {' },
      { content: '    mesh: Cube { size: 1 }' },
      { content: '    material: StandardMaterial { color: #4488ff }' },
      { content: '    position: [0, 0, 0]' },
      { content: '    traits: [CastShadow, ReceiveShadow]', annotation: 'behavior' },
      { content: '  }' },
      { content: '  light: DirectionalLight { intensity: 1.2, castShadows: true }' },
      { content: '  camera: PerspectiveCamera { fov: 60, position: [3, 3, 5] }' },
      { content: '}' },
    ],
  },
  {
    title: 'Invoke the Unity compiler',
    description: 'Import the UnityCompiler from @holoscript/core and call compile().',
    lines: [
      { content: 'import { parse } from "@holoscript/core"', highlight: true },
      { content: 'import { UnityCompiler } from "@holoscript/core/compilers"', highlight: true },
      { content: '' },
      { content: 'const source = await readFile("SpinningDemo.holo", "utf8")', dim: true },
      { content: 'const parseResult = parse(source)' },
      { content: 'const composition = parseResult.composition' },
      { content: '' },
      { content: 'const compiler = new UnityCompiler({', highlight: true },
      { content: "  namespace: 'HoloScene'," },
      { content: "  className: 'SpinningDemo'," },
      { content: '  useURP: true,' },
      { content: '})' },
      { content: '' },
      {
        content: 'const csharpCode = compiler.compile(composition)',
        annotation: '→ string',
        highlight: true,
      },
    ],
  },
];

// ─── Output C# ───────────────────────────────────────────────────────────────

const OUTPUT_STEPS = [
  {
    title: 'Generated C# — namespace & class',
    description: 'HoloScript emits a clean MonoBehaviour with your scene name as the class.',
    lines: [
      { content: '// Auto-generated by HoloScript v3.4.0', dim: true },
      { content: '// Do not edit — regenerate from SpinningDemo.holo', dim: true },
      { content: '' },
      { content: 'using UnityEngine;', highlight: true },
      { content: 'using UnityEngine.Rendering.Universal;' },
      { content: '' },
      { content: 'namespace HoloScene', highlight: true },
      { content: '{' },
      {
        content: '  public class SpinningDemo : MonoBehaviour',
        highlight: true,
        annotation: '← generated class',
      },
      { content: '  {' },
      { content: '    private GameObject _cube;', type: 'added' as const },
      { content: '    private Light _directionalLight;', type: 'added' as const },
      { content: '    private Camera _mainCamera;', type: 'added' as const },
    ],
  },
  {
    title: 'Generated C# — Awake() method',
    description: 'All scene construction happens in Awake() — ready before the first frame.',
    lines: [
      { content: '    private void Awake()' },
      { content: '    {' },
      { content: '      // Cube' },
      { content: "      _cube = new GameObject('Cube');", highlight: true },
      {
        content: '      var meshFilter = _cube.AddComponent<MeshFilter>();',
        type: 'added' as const,
      },
      { content: '      meshFilter.mesh = CreateCubeMesh(1f);', type: 'added' as const },
      {
        content: '      var meshRenderer = _cube.AddComponent<MeshRenderer>();',
        type: 'added' as const,
      },
      {
        content: '      meshRenderer.material.color = new Color(0.27f, 0.53f, 1f);',
        type: 'added' as const,
        annotation: '#4488ff',
      },
      { content: '      var rb = _cube.AddComponent<Rigidbody>();', dim: true },
      { content: '' },
      { content: '      // Directional light' },
      { content: "      var lightGo = new GameObject('DirectionalLight');" },
      { content: '      _directionalLight = lightGo.AddComponent<Light>();', highlight: true },
      { content: '      _directionalLight.type = LightType.Directional;', type: 'added' as const },
      { content: '      _directionalLight.intensity = 1.2f;', type: 'added' as const },
      { content: '      _directionalLight.shadows = LightShadows.Soft;', type: 'added' as const },
    ],
  },
];

// ─── Summary slide ────────────────────────────────────────────────────────────

const SummaryCard: React.FC = () => {
  const frame = useCurrentFrame();
  const opacity = interpolate(frame, [0, 20], [0, 1], {
    extrapolateRight: 'clamp',
    easing: Easing.out(Easing.ease),
  });

  const items = [
    { icon: '1', text: 'Write a .holo scene — any complexity' },
    { icon: '2', text: 'Call UnityCompiler.compile(composition)' },
    { icon: '3', text: 'Get production-ready C# MonoBehaviour' },
    { icon: '→', text: 'Works with all 17 other targets too', accent: true },
  ];

  return (
    <AbsoluteFill
      style={{
        background: theme.bg,
        padding: theme.padding,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        gap: 48,
        fontFamily: theme.titleFont,
        opacity,
      }}
    >
      <h2 style={{ color: theme.text, fontSize: 48, fontWeight: 700, margin: 0 }}>
        That's the full pipeline
      </h2>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
        {items.map((item, i) => (
          <div
            key={i}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 24,
              opacity: interpolate(frame, [i * 8, i * 8 + 15], [0, 1], {
                extrapolateRight: 'clamp',
              }),
            }}
          >
            <div
              style={{
                width: 48,
                height: 48,
                borderRadius: '50%',
                background: item.accent ? theme.accent : theme.accentDim,
                border: `2px solid ${theme.accentGlow}`,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: theme.text,
                fontFamily: theme.font,
                fontWeight: 700,
                fontSize: 18,
                flexShrink: 0,
              }}
            >
              {item.icon}
            </div>
            <span
              style={{
                color: item.accent ? theme.accent : theme.text,
                fontSize: 28,
                fontWeight: item.accent ? 600 : 400,
              }}
            >
              {item.text}
            </span>
          </div>
        ))}
      </div>

      <div
        style={{
          marginTop: 16,
          padding: '20px 28px',
          background: theme.surface,
          borderRadius: theme.borderRadius,
          border: `1px solid ${theme.accentGlow}44`,
          display: 'flex',
          gap: 12,
          alignItems: 'center',
          fontFamily: theme.font,
          fontSize: 20,
          color: theme.textMuted,
        }}
      >
        <span style={{ color: theme.success }}>▶</span>
        <span>npx holoscript compile SpinningDemo.holo --target unity</span>
      </div>
    </AbsoluteFill>
  );
};

// ─── Composition registration ─────────────────────────────────────────────────

export const UnityCompilerWalkthrough: React.FC = () => {
  const { fps } = useVideoConfig();

  const TITLE_FRAMES = fps * 3;
  const STEP_FRAMES = fps * 6;
  const SUMMARY_FRAMES = fps * 5;

  const allSteps = [...HOLO_STEPS, ...OUTPUT_STEPS];

  return (
    <AbsoluteFill>
      <Sequence from={0} durationInFrames={TITLE_FRAMES}>
        <TitleCard
          title="HoloScript →"
          compilerTarget="Unity C#"
          subtitle="From .holo scene to MonoBehaviour in seconds"
          tag="Compiler Demo"
        />
      </Sequence>

      {allSteps.map((step, i) => (
        <Sequence key={i} from={TITLE_FRAMES + i * STEP_FRAMES} durationInFrames={STEP_FRAMES}>
          <CodeStep
            title={step.title}
            description={step.description}
            language={i < HOLO_STEPS.length ? 'holo' : 'csharp'}
            lines={step.lines}
            stepNumber={i + 1}
            totalSteps={allSteps.length}
          />
        </Sequence>
      ))}

      <Sequence
        from={TITLE_FRAMES + allSteps.length * STEP_FRAMES}
        durationInFrames={SUMMARY_FRAMES}
      >
        <SummaryCard />
      </Sequence>
    </AbsoluteFill>
  );
};
