/**
 * E2 — Native panel render-wiring: determinism + LOC measurement
 *
 * Evidence for paper "Compile the Surface" (research/2026-06-14_paper-native-frontend-aaa-compile.md):
 *   C4: native .holo LOC < hand-written React equivalent for equivalent rendered structure
 *   C5: one .holo source → two compiled targets with byte-stable output per target
 *
 * Test panel: agentMonitor (packages/studio/src/lib/studio/panels/agentMonitor.holo)
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';
import { createHash } from 'crypto';
import { parseHolo } from '@holoscript/core';
import { Native2DCompiler } from '../../../core/src/compiler/Native2DCompiler';
import type { HoloComposition } from '../../../core/src/parser/HoloCompositionTypes';

const PANEL_PATH = join(__dirname, '../lib/studio/panels/agentMonitor.holo');

function sha256(s: string): string {
  return createHash('sha256').update(s, 'utf8').digest('hex');
}

function getAst(): HoloComposition {
  const src = readFileSync(PANEL_PATH, 'utf-8');
  const result = parseHolo(src);
  if (!result.success || !result.ast) throw new Error('parse failed');
  return result.ast as unknown as HoloComposition;
}

describe('E2 native panel — agentMonitor', () => {
  it('parses without errors', () => {
    const src = readFileSync(PANEL_PATH, 'utf-8');
    const result = parseHolo(src);
    expect(result.success).toBe(true);
    expect(result.errors).toHaveLength(0);
  });

  it('C4 — native .holo non-blank LOC < 65 (vs ~70 for hand-written React equivalent)', () => {
    const src = readFileSync(PANEL_PATH, 'utf-8');
    const loc = src.split('\n').filter((l) => l.trim().length > 0).length;
    expect(loc).toBeLessThan(65);
  });

  it('C5a — react target is byte-stable across two compilations', () => {
    const ast = getAst();
    const compiler = new Native2DCompiler();
    const compile = () =>
      compiler.generateReactComponent('agentMonitor', ast.objects ?? [], ast, { format: 'react' });
    expect(sha256(compile())).toBe(sha256(compile()));
  });

  it('C5b — html target is byte-stable across two compilations', () => {
    const ast = getAst();
    const compiler = new Native2DCompiler();
    const compile = () => compiler.generateHTMLPage('agentMonitor', ast.objects ?? [], ast);
    expect(sha256(compile())).toBe(sha256(compile()));
  });

  it('C5c — react and html are distinct targets from one source', () => {
    const ast = getAst();
    const compiler = new Native2DCompiler();
    const reactOut = compiler.generateReactComponent('agentMonitor', ast.objects ?? [], ast, {
      format: 'react',
    });
    const htmlOut = compiler.generateHTMLPage('agentMonitor', ast.objects ?? [], ast);
    expect(reactOut).not.toBe(htmlOut);
    expect(reactOut).toContain('@generated by HoloScript');
    expect(htmlOut).toContain('<!DOCTYPE html>');
  });

  it('@bind resolves to reactive JSX expression — agents?.active in react output', () => {
    const ast = getAst();
    const compiler = new Native2DCompiler();
    const out = compiler.generateReactComponent('agentMonitor', ast.objects ?? [], ast, {
      format: 'react',
    });
    expect(out).toContain('agents?.active');
  });
});
