// ═══════════════════════════════════════════════════════════════════════════
// THE GOLD GAME — Gate 30 canonical packaging assets (single source of truth).
//
// The portable Drive build at D:/GOLD-GAME/ was originally hand-assembled across
// many sessions, so its launcher/docs/server/setup files drifted out of sync with
// examples/gold-game/ (Gate 30's whole point: there was no single command that
// regenerates everything and copies it with proof). These string constants are the
// CANONICAL definition of every non-build artifact in the deployed package. Both
// the packager (gate-30-package.mjs) and the verifier (gate-30-package-verify.mjs)
// import them, so the deployed bytes are deterministically reproducible from source.
//
// The two web builds (3d/, 2d/) are NOT here — they are regenerated by the real
// drive-build.mjs / gold-2d-build.mjs from the parsed gold-vault-game.holo.
// The 92MB Node-SEA GOLD-GAME-Server.exe is a PRE-BUILT binary: it is verified
// present + digested, never regenerated here (Node SEA is slow + platform-specific
// and would be a build-spend; rebuilding it is a separate, optional step).
// ═══════════════════════════════════════════════════════════════════════════

// The launcher menu shown by index.html / GOLD-GAME-Server.exe at the drive root.
export const LAUNCHER_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>THE GOLD GAME — The Vault</title>
<style>
  :root{--gold:#d4af37;--ink:#06070a}
  html,body{margin:0;height:100%;background:radial-gradient(120% 90% at 50% 0%,#1a1626 0%,#06070a 60%);
    color:#f0d79a;font-family:system-ui,sans-serif;display:flex;align-items:center;justify-content:center}
  .wrap{text-align:center;max-width:760px;padding:24px}
  h1{font-size:42px;letter-spacing:6px;margin:0 0 6px;color:#ffe9a0;text-shadow:0 2px 18px #000}
  .sub{color:#b09a5a;font-size:14px;letter-spacing:2px;margin-bottom:34px}
  .cards{display:flex;gap:22px;justify-content:center;flex-wrap:wrap}
  a.card{display:block;width:300px;text-decoration:none;color:#f0d79a;background:#0d0e16cc;
    border:2px solid var(--gold);border-radius:14px;padding:26px 22px;transition:transform .15s,box-shadow .15s}
  a.card:hover{transform:translateY(-4px);box-shadow:0 10px 40px #d4af3733}
  a.card h2{margin:0 0 8px;font-size:24px;color:#ffe9a0;letter-spacing:1px}
  a.card p{margin:0;font-size:13px;color:#c9b888;line-height:1.5}
  .tag{display:inline-block;margin-top:12px;font-size:11px;color:var(--gold);border:1px solid var(--gold);
    border-radius:20px;padding:3px 12px;letter-spacing:1px}
  .foot{margin-top:32px;font-size:11px;color:#7a6c4a;line-height:1.6}
</style></head>
<body><div class="wrap">
  <h1>THE GOLD GAME</h1>
  <div class="sub">THE VAULT &middot; the real GOLD curation system, turned into a world</div>
  <div class="cards">
    <a class="card" href="3d/index.html">
      <h2>&#9650; 3D / VR</h2>
      <p>Walk the vault from Bronze Valley to the Diamond Peak. On a Quest, tap <b>Enter VR</b>, then pull the trigger on a glowing gem to graduate it &mdash; every grab is validated by HoloGate.</p>
      <span class="tag">WebGL &middot; WebXR &middot; HoloGate</span>
    </a>
    <a class="card" href="2d/index.html">
      <h2>&#9650; Retro 2D</h2>
      <p>The same world as a pixel-art side view &mdash; tier platforms, gem entries, curator sprites. Opens instantly on any screen.</p>
      <span class="tag">HTML5 canvas &middot; offline</span>
    </a>
  </div>
  <div class="foot">
    Self-contained &middot; opens offline by double-click &middot; one <code>.holo</code> source, two modalities.<br>
    For the LIVE vault count in 3D, launch <code>GOLD-GAME-Server.exe</code> instead.
  </div>
</div></body></html>
`;

export const START_HERE_TXT = `===============================================================
  THE GOLD GAME — The Vault   (portable Drive build)
===============================================================

TO PLAY (one double-click):

  >  "PLAY THE GOLD GAME.bat"      — opens the game in your browser (offline; keyboard + VR)
  >  index.html                    — same launcher menu, double-click directly
  >  GOLD-GAME-Server.exe          — LIVE-VAULT mode: serves the game + the real GOLD vault count
  >  "PLAY LIVE GOLD GAME (Node).bat" — source live server with full GOLD entry bodies

  When you plug the drive in, Windows shows it as "THE GOLD GAME".
  Open the drive and double-click "PLAY THE GOLD GAME.bat" (or click the
  "Play THE GOLD GAME" option in the Windows AutoPlay pop-up, if it appears).

WHY IT ISN'T FULLY AUTOMATIC:
  Windows disabled auto-launch-on-insert for USB/removable drives in 2011
  (a security lock, after the Conficker worm). NO removable drive can open a
  program by itself anymore. The autorun.inf here gets you as close as Windows
  allows: the drive name, icon, and a one-click "Play" action. For true
  open-on-insert, run setup/setup-gold-game-autolaunch.ps1 once per PC.

CONTROLS:
  3D desktop: click the scene for first-person . WASD/arrows move . mouse looks .
              E/Space graduate . F opens the full GOLD entry body.
  3D VR:      on a Quest, tap Enter VR and pull the trigger on a glowing gem
              (graduation is HoloGate-validated).
  Retro 2D:   W/S move tier . A/D move . E graduate.

WHAT IT IS:
  The real GOLD knowledge-curation system, turned into a game. Climb Bronze
  Valley -> Gold Terrace -> Diamond Peak; graduate knowledge entries; the
  Archivist ratifies your standing. One .holo source -> 3D + retro-2D.
  Source of truth: examples/gold-game/ in the HoloScript repo. This package is
  regenerated + copied here in one verified command (Gate 30): the source builds,
  this launcher, the docs, the server, and the setup scripts all derive from a
  single packager so the drive never drifts from the repo again.
`;

export const PLAY_BAT = `@echo off
rem THE GOLD GAME — one-double-click launcher. Opens the game in your default browser.
rem (Offline scene + keyboard/VR controls. For the LIVE vault backend, run GOLD-GAME-Server.exe instead.)
start "" "%~dp0index.html"
`;

export const PLAY_NODE_BAT = `@echo off
rem THE GOLD GAME — live source-server launcher for machines with Node.js.
rem Uses server.cjs so /api/vault-entry can return full GOLD markdown bodies.
cd /d "%~dp0"
node server.cjs
pause
`;

export const AUTORUN_INF = `[autorun]
label=THE GOLD GAME
icon=GOLD-GAME-Server.exe,0
open=GOLD-GAME-Server.exe
action=Play THE GOLD GAME
shell\\play=Play THE GOLD GAME
shell\\play\\command=GOLD-GAME-Server.exe
shell=play
`;

export const SETUP_WATCHER_PS1 = `# THE GOLD GAME — auto-launch watcher (per-machine, host-resident).
# Listens for removable-volume arrival; when the GOLD-game drive mounts (identified by
# GOLD-GAME-Server.exe at its root), opens the launcher in the default browser.
# Started at logon by the Scheduled Task that setup-gold-game-autolaunch.ps1 registers.
$ErrorActionPreference = 'SilentlyContinue'

Register-CimIndicationEvent -ClassName Win32_VolumeChangeEvent -SourceIdentifier GoldGameVolWatch -Action {
  $ev = $Event.SourceEventArgs.NewEvent
  if ($ev.EventType -eq 2) {                 # 2 = device/volume arrival
    Start-Sleep -Seconds 2                    # let the volume finish mounting
    $root = [string]$ev.DriveName + '\\'       # e.g. "E:\\"
    $marker  = Join-Path $root 'GOLD-GAME-Server.exe'   # identifies OUR drive (travels with it)
    $launcher = Join-Path $root 'index.html'
    if ((Test-Path $marker) -and (Test-Path $launcher)) {
      Start-Process $launcher                 # opens the game launcher in the default browser
    }
  }
} | Out-Null

# Keep this host process alive so it keeps receiving volume-arrival events.
while ($true) { Start-Sleep -Seconds 600 }
`;

export const SETUP_INSTALL_PS1 = `# THE GOLD GAME — install per-machine auto-launch. Run ONCE per PC (no admin needed).
#
#   Install:    powershell -ExecutionPolicy Bypass -File "setup-gold-game-autolaunch.ps1"
#   Uninstall:  powershell -ExecutionPolicy Bypass -File "setup-gold-game-autolaunch.ps1" -Uninstall
#
# It copies the watcher to %LOCALAPPDATA%\\GoldGame (so it survives the drive being unplugged)
# and registers a logon Scheduled Task to keep it running. The watcher then opens the game
# whenever ITS drive (the one with GOLD-GAME-Server.exe) is plugged into THIS machine.
# PER-MACHINE by design: this lives on the host, not the drive — run it once on each PC you want it on.
param([switch]$Uninstall)

$taskName    = 'GoldGameAutoLaunch'
$dest        = Join-Path $env:LOCALAPPDATA 'GoldGame'
$watcherDest = Join-Path $dest 'gold-game-autolaunch-watcher.ps1'

if ($Uninstall) {
  Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
  Get-CimInstance Win32_Process -Filter "Name='powershell.exe'" -ErrorAction SilentlyContinue |
    Where-Object { $_.CommandLine -like '*gold-game-autolaunch-watcher*' } |
    ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
  Remove-Item -Recurse -Force $dest -ErrorAction SilentlyContinue
  Write-Host 'THE GOLD GAME auto-launch UNINSTALLED from this machine.'
  return
}

New-Item -ItemType Directory -Force -Path $dest | Out-Null
Copy-Item (Join-Path $PSScriptRoot 'gold-game-autolaunch-watcher.ps1') $watcherDest -Force

$action   = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File \`"$watcherDest\`""
$trigger  = New-ScheduledTaskTrigger -AtLogOn
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
try {
  Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Force \`
    -Description 'Opens THE GOLD GAME when its drive is plugged into this PC.' -ErrorAction Stop | Out-Null
} catch {
  Write-Host "INSTALL FAILED registering the Scheduled Task: $($_.Exception.Message)"
  Write-Host "If this is 'Access Denied' (0x80070005): open a NORMAL PowerShell window on this PC (your own user — a per-user logon task needs no admin) and re-run this script. Some locked-down/sandboxed shells block task registration."
  return
}
# Verify it actually registered (don't claim success blindly).
if (-not (Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue)) {
  Write-Host "INSTALL FAILED: the task did not register. Re-run in a normal PowerShell window on this PC."
  return
}

# Start it now so it works without a re-logon.
Start-Process powershell.exe -ArgumentList "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File \`"$watcherDest\`""

Write-Host 'INSTALLED + VERIFIED. THE GOLD GAME will now open whenever its drive is plugged into THIS PC.'
Write-Host 'Per-machine (host-resident). Uninstall: re-run this script with  -Uninstall'
`;

// The full manifest of what a complete deployed package contains, and how each
// artifact is produced. `kind`:
//   'build'   — regenerated by running a real builder (drive-build / 2d-build)
//   'copy'    — copied byte-for-byte from a source file in examples/gold-game/
//   'static'  — materialized from a canonical string constant above
//   'prebuilt'— a pre-built binary verified present + digested, NOT regenerated
export const PACKAGE_MANIFEST = [
  { rel: '3d/index.html',                       kind: 'build',    builder: 'drive-build.mjs',  from: 'drive-build/index.html' },
  { rel: '3d/START-HERE.txt',                   kind: 'build',    builder: 'drive-build.mjs',  from: 'drive-build/START-HERE.txt' },
  { rel: '2d/index.html',                       kind: 'build',    builder: 'gold-2d-build.mjs', from: '2d-build/index.html' },
  { rel: '2d/START-HERE.txt',                   kind: 'build',    builder: 'gold-2d-build.mjs', from: '2d-build/START-HERE.txt' },
  { rel: 'index.html',                          kind: 'static',   content: 'LAUNCHER_HTML' },
  { rel: 'START-HERE.txt',                      kind: 'static',   content: 'START_HERE_TXT' },
  { rel: 'PLAY THE GOLD GAME.bat',              kind: 'static',   content: 'PLAY_BAT' },
  { rel: 'PLAY LIVE GOLD GAME (Node).bat',      kind: 'static',   content: 'PLAY_NODE_BAT' },
  { rel: 'autorun.inf',                         kind: 'static',   content: 'AUTORUN_INF' },
  { rel: 'server.cjs',                          kind: 'copy',     from: 'server.cjs' },
  { rel: 'vault-ops.cjs',                       kind: 'copy',     from: 'vault-ops.cjs' },
  { rel: 'sea-config.json',                     kind: 'copy',     from: 'sea-config.json' },
  { rel: 'setup/gold-game-autolaunch-watcher.ps1', kind: 'static', content: 'SETUP_WATCHER_PS1' },
  { rel: 'setup/setup-gold-game-autolaunch.ps1',   kind: 'static', content: 'SETUP_INSTALL_PS1' },
  { rel: 'GOLD-GAME-Server.exe',                kind: 'prebuilt', note: 'Node-SEA binary; verified present + digested, never regenerated here' },
];

export const STATIC_CONTENT = {
  LAUNCHER_HTML, START_HERE_TXT, PLAY_BAT, PLAY_NODE_BAT, AUTORUN_INF,
  SETUP_WATCHER_PS1, SETUP_INSTALL_PS1,
};
