import type { PageEntry } from './routes.js';
import type { ComponentNode } from './tree.js';

export interface PageGraph {
  page: PageEntry;
  tree: ComponentNode;
}

export interface EmitMeta {
  generatedAt: string;
  studioRoot: string;
  pageCount: number;
  uniqueComponentCount: number;
  source: 'studio-ui-graph v0.1';
}

/**
 * Emit a HoloScript scene representation of a set of page graphs. v0.1 keeps
 * the schema minimal — pages with @route + @file traits, components with
 * @file + @reused_in. State and API detection land in v0.2.
 */
export function emitHolo(graphs: PageGraph[], meta: EmitMeta): string {
  const reuseMap = collectReuseMap(graphs);
  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by @holoscript/studio-ui-graph — do not edit by hand');
  lines.push(`// generated: ${meta.generatedAt}`);
  lines.push(`// source:    ${meta.source}`);
  lines.push(`// studio:    ${meta.studioRoot}`);
  lines.push(`// pages:     ${meta.pageCount}`);
  lines.push(`// unique components: ${meta.uniqueComponentCount}`);
  lines.push('');
  lines.push('scene Studio {');
  for (const g of graphs) {
    emitPage(g, reuseMap, 1, lines);
    lines.push('');
  }
  // Shared-component summary block
  const shared = [...reuseMap.entries()]
    .filter(([, pages]) => pages.size >= 2)
    .sort(([a], [b]) => a.localeCompare(b));
  if (shared.length > 0) {
    lines.push('  // Components used by ≥2 pages — candidates for the panels/ tier');
    for (const [name, pageIds] of shared) {
      const sortedPages = [...pageIds].sort().join(', ');
      lines.push(`  shared_component ${sanitize(name)} { @reused_in([${sortedPages}]) }`);
    }
    lines.push('');
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function emitPage(g: PageGraph, reuse: Map<string, Set<string>>, indent: number, out: string[]): void {
  const pad = '  '.repeat(indent);
  out.push(`${pad}page ${g.page.id} { @route("${g.page.route}") @file("${g.page.file}")`);
  for (const child of g.tree.children) {
    emitNode(child, g.page.id, reuse, indent + 1, out);
  }
  out.push(`${pad}}`);
}

function emitNode(node: ComponentNode, pageId: string, reuse: Map<string, Set<string>>, indent: number, out: string[]): void {
  const pad = '  '.repeat(indent);
  const traits: string[] = [`@file("${node.file}")`];
  const reusedIn = reuse.get(node.name);
  if (reusedIn && reusedIn.size >= 2) {
    const others = [...reusedIn].filter((id) => id !== pageId).sort();
    if (others.length > 0) traits.push(`@reused_in([${others.join(', ')}])`);
  }
  if (node.children.length === 0) {
    out.push(`${pad}${sanitize(node.name)} { ${traits.join(' ')} }`);
    return;
  }
  out.push(`${pad}${sanitize(node.name)} { ${traits.join(' ')}`);
  for (const child of node.children) {
    emitNode(child, pageId, reuse, indent + 1, out);
  }
  out.push(`${pad}}`);
}

function collectReuseMap(graphs: PageGraph[]): Map<string, Set<string>> {
  const map = new Map<string, Set<string>>();
  // Skip the per-page root node (always named "Page") — including it produces a
  // bogus "Page reused in all 60 pages" entry. Only descendants belong here.
  for (const g of graphs) {
    for (const child of g.tree.children) visit(child, g.page.id, map);
  }
  return map;
}

function visit(node: ComponentNode, pageId: string, map: Map<string, Set<string>>): void {
  const set = map.get(node.name) ?? new Set<string>();
  set.add(pageId);
  map.set(node.name, set);
  for (const child of node.children) visit(child, pageId, map);
}

function sanitize(name: string): string {
  // .holo identifiers: alphanumeric + underscore. Strip anything else.
  return name.replace(/[^A-Za-z0-9_]/g, '_');
}
