import type { HoloComposition, HoloObjectDecl } from '../parser/HoloCompositionTypes';
import type { AndroidCompiler } from './AndroidCompiler';
import { GEOSPATIAL_DEFAULTS } from '../traits/constants/mobile/geospatial';
import {
  DEPTH_SCANNER_DEFAULTS,
  DEPTH_SCANNER_TRAITS,
} from '../traits/constants/mobile/depth-scanner';
import { PORTAL_AR_TRAITS } from '../traits/constants/mobile/portal-ar';
import { CAMERA_HAND_TRACKING_TRAITS } from '../traits/constants/mobile/camera-hand-tracking';

type RuntimeTrait =
  | string
  | { name?: string; config?: Record<string, unknown>; params?: Record<string, unknown> };

const GEO_ANCHOR_TRAITS = [
  'geo_anchor',
  'geo_persist',
  'geo_radius',
  'geo_compass_heading',
  'geo_altitude',
  'geo_cloud_anchor',
  'geo_terrain_snap',
  'geo_session_continuity',
  'geo_proximity_trigger',
  'geo_discoverable',
] as const;

const GEOSPATIAL_TRAITS = [
  'geo_arcore_geospatial',
  'geospatial_vps',
  'geospatial_anchor',
  'geospatial_terrain_anchor',
  'geospatial_rooftop_anchor',
  'geospatial_streetscape',
  'geospatial_heading',
] as const;

function objectsOf(composition: HoloComposition): HoloObjectDecl[] {
  return (composition.objects ?? []) as HoloObjectDecl[];
}

function traitsOf(obj: HoloObjectDecl): RuntimeTrait[] {
  return (obj.traits ?? []) as unknown as RuntimeTrait[];
}

function traitName(trait: RuntimeTrait): string {
  return typeof trait === 'string' ? trait : (trait.name ?? '');
}

function traitConfig(trait: RuntimeTrait | undefined): Record<string, unknown> {
  if (!trait || typeof trait === 'string') return {};
  return trait.config ?? trait.params ?? {};
}

function findTrait(obj: HoloObjectDecl, name: string): RuntimeTrait | undefined {
  return traitsOf(obj).find((trait) => traitName(trait) === name);
}

function hasAnyTrait(composition: HoloComposition, names: readonly string[]): boolean {
  return objectsOf(composition).some((obj) =>
    traitsOf(obj).some((trait) => names.includes(traitName(trait)))
  );
}

function collectUsedTraits(composition: HoloComposition, names: readonly string[]): string[] {
  const used = new Set<string>();
  for (const obj of objectsOf(composition)) {
    for (const trait of traitsOf(obj)) {
      const name = traitName(trait);
      if (names.includes(name)) used.add(name);
    }
  }
  return [...used].sort();
}

function numberConfig(
  config: Record<string, unknown>,
  keys: readonly string[],
  fallback: number
): number {
  for (const key of keys) {
    const raw = config[key];
    const numeric = typeof raw === 'number' ? raw : Number(raw);
    if (Number.isFinite(numeric)) return numeric;
  }
  return fallback;
}

function boolConfig(
  config: Record<string, unknown>,
  keys: readonly string[],
  fallback: boolean
): boolean {
  for (const key of keys) {
    const raw = config[key];
    if (typeof raw === 'boolean') return raw;
  }
  return fallback;
}

function floatLiteral(value: number): string {
  return `${Number.isInteger(value) ? value.toFixed(0) : value}f`;
}

function quotedKotlin(compiler: AndroidCompiler, value: unknown): string {
  return `"${compiler.escapeStringValue(String(value), 'Kotlin')}"`;
}

function emitHeader(
  compiler: AndroidCompiler,
  composition: HoloComposition,
  title: string,
  requirements: readonly string[]
): void {
  compiler.lines = [];
  compiler.indentLevel = 0;
  compiler.emit(`// Auto-generated by HoloScript AndroidCompiler - ${title}`);
  compiler.emit(
    `// Source: composition "${compiler.escapeStringValue(String(composition.name), 'Kotlin')}"`
  );
  for (const requirement of requirements) {
    compiler.emit(`// Requires ${requirement}`);
  }
  compiler.emit('// SceneView-native sidecar generated without legacy fragment or node factories.');
  compiler.emit('');
  compiler.emit(`package ${compiler.options.packageName}`);
  compiler.emit('');
}

function finish(compiler: AndroidCompiler): string {
  return `${compiler.lines.join('\n')}\n`;
}

function emitUsedTraits(compiler: AndroidCompiler, used: readonly string[]): void {
  if (used.length === 0) {
    compiler.emit('private val usedTraits = emptySet<String>()');
    return;
  }
  compiler.emit(`private val usedTraits = setOf(${used.map((trait) => `"${trait}"`).join(', ')})`);
}

export function hasGeoAnchorTraits(composition: HoloComposition): boolean {
  return hasAnyTrait(composition, GEO_ANCHOR_TRAITS);
}

export function hasGeoTraits(composition: HoloComposition): boolean {
  return hasGeoAnchorTraits(composition) || hasGeospatialVPSTraits(composition);
}

export function hasGeospatialVPSTraits(composition: HoloComposition): boolean {
  return hasAnyTrait(composition, GEOSPATIAL_TRAITS);
}

export function hasDepthScanTraits(composition: HoloComposition): boolean {
  return hasAnyTrait(composition, DEPTH_SCANNER_TRAITS);
}

export function hasPortalARTraits(composition: HoloComposition): boolean {
  return hasAnyTrait(composition, PORTAL_AR_TRAITS);
}

export function hasHandTrackingTraits(composition: HoloComposition): boolean {
  return hasAnyTrait(composition, CAMERA_HAND_TRACKING_TRAITS);
}

export function emitGeoAnchorSetup(
  compiler: AndroidCompiler,
  composition: HoloComposition
): string {
  emitHeader(compiler, composition, 'SceneView Geo-Anchor Setup', [
    'ARCore Earth anchors',
    'Google Play Services location',
  ]);
  compiler.emit('import android.content.Context');
  compiler.emit('import android.util.Log');
  compiler.emit('import com.google.ar.core.Anchor');
  compiler.emit('import com.google.ar.core.Config');
  compiler.emit('import com.google.ar.core.Earth');
  compiler.emit('import com.google.ar.core.Session');
  compiler.emit('import com.google.ar.core.TrackingState');
  compiler.emit('');
  compiler.emit(
    `class ${compiler.options.className}GeoAnchorManager(private val context: Context) {`
  );
  compiler.indentLevel++;
  emitUsedTraits(compiler, collectUsedTraits(composition, GEO_ANCHOR_TRAITS));
  compiler.emit('private val geoAnchors = mutableMapOf<String, Anchor>()');
  compiler.emit('private val requestedAnchors = listOf(');
  compiler.indentLevel++;
  const anchors = objectsOf(composition).filter((obj) => findTrait(obj, 'geo_anchor'));
  if (anchors.length === 0) {
    compiler.emit('// No explicit geo_anchor objects; call createGeoAnchor at runtime.');
  }
  anchors.forEach((obj, index) => {
    const geoConfig = traitConfig(findTrait(obj, 'geo_anchor'));
    const altitudeConfig = traitConfig(findTrait(obj, 'geo_altitude'));
    const headingConfig = traitConfig(findTrait(obj, 'geo_compass_heading'));
    const lat = numberConfig(geoConfig, ['latitude', 'lat'], 0);
    const lng = numberConfig(geoConfig, ['longitude', 'lng'], 0);
    const altitude = numberConfig(altitudeConfig, ['meters', 'altitude'], 0);
    const heading = numberConfig(headingConfig, ['degrees', 'heading'], 0);
    compiler.emit(
      `SceneViewGeoAnchor(${quotedKotlin(compiler, obj.name)}, ${lat}, ${lng}, ${altitude}, ${floatLiteral(
        heading
      )})${index === anchors.length - 1 ? '' : ','}`
    );
  });
  compiler.indentLevel--;
  compiler.emit(')');
  compiler.emit('');
  compiler.emit('fun setupGeoAnchors(session: Session, earth: Earth?) {');
  compiler.indentLevel++;
  compiler.emit('configureSessionForGeospatial(session)');
  compiler.emit('val earthRef = earth ?: return');
  compiler.emit('for (anchor in requestedAnchors) {');
  compiler.indentLevel++;
  compiler.emit(
    'createGeoAnchor(anchor.name, earthRef, anchor.latitude, anchor.longitude, anchor.altitude, anchor.heading)'
  );
  compiler.indentLevel--;
  compiler.emit('}');
  if (compiler.compositionHasTrait(composition, 'geo_persist')) {
    compiler.emit('restoreGeoAnchors { name, restored -> geoAnchors[name] = restored }');
  }
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun configureSessionForGeospatial(session: Session) {');
  compiler.indentLevel++;
  compiler.emit('val config = session.config');
  compiler.emit('config.geospatialMode = Config.GeospatialMode.ENABLED');
  compiler.emit('session.configure(config)');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit(
    'fun createGeoAnchor(name: String, earth: Earth, latitude: Double, longitude: Double, altitude: Double, heading: Float): Anchor? {'
  );
  compiler.indentLevel++;
  compiler.emit('if (earth.trackingState != TrackingState.TRACKING) return null');
  compiler.emit('val halfRadians = Math.toRadians(heading.toDouble()) / 2.0');
  compiler.emit(
    'val anchor = earth.createAnchor(latitude, longitude, altitude, 0f, 0f, Math.sin(halfRadians).toFloat(), Math.cos(halfRadians).toFloat())'
  );
  compiler.emit('geoAnchors[name] = anchor');
  compiler.emit('Log.d("HoloScript", "SceneView geo anchor created: " + name)');
  if (
    compiler.compositionHasTrait(composition, 'geo_cloud_anchor') ||
    compiler.compositionHasTrait(composition, 'geo_persist')
  ) {
    compiler.emit('saveGeoAnchorToCloud(name, anchor.cloudAnchorId ?: "")');
  }
  compiler.emit('return anchor');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun saveGeoAnchorToCloud(name: String, cloudAnchorId: String) {');
  compiler.indentLevel++;
  compiler.emit(
    'context.getSharedPreferences("sceneview_geo_anchors", Context.MODE_PRIVATE).edit().putString(name, cloudAnchorId).apply()'
  );
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun restoreGeoAnchors(onRestore: (String, Anchor) -> Unit) {');
  compiler.indentLevel++;
  compiler.emit(
    '// Cloud anchor resolution is provided by the app shell when network policy is available.'
  );
  compiler.emit(
    'Log.d("HoloScript", "restoreGeoAnchors requested for " + usedTraits.joinToString())'
  );
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit(
    'data class SceneViewGeoAnchor(val name: String, val latitude: Double, val longitude: Double, val altitude: Double, val heading: Float)'
  );
  compiler.indentLevel--;
  compiler.emit('}');
  return finish(compiler);
}

export function emitGeospatialVPSSetup(
  compiler: AndroidCompiler,
  composition: HoloComposition
): string {
  emitHeader(compiler, composition, 'SceneView Geospatial VPS Setup', [
    'ARCore GeospatialMode',
    'Google Play Services location',
  ]);
  compiler.emit('import android.util.Log');
  compiler.emit('import com.google.ar.core.Anchor');
  compiler.emit('import com.google.ar.core.Config');
  compiler.emit('import com.google.ar.core.Earth');
  compiler.emit('import com.google.ar.core.Session');
  compiler.emit('import com.google.ar.core.StreetscapeGeometry');
  compiler.emit('import com.google.ar.core.TrackingState');
  compiler.emit('');
  compiler.emit(`class ${compiler.options.className}GeospatialVPSManager {`);
  compiler.indentLevel++;
  emitUsedTraits(compiler, collectUsedTraits(composition, GEOSPATIAL_TRAITS));
  compiler.emit('private var earth: Earth? = null');
  compiler.emit('private val geospatialAnchors = mutableMapOf<String, Anchor>()');
  compiler.emit(
    `private val horizontalAccuracyThreshold = ${GEOSPATIAL_DEFAULTS.vps.accuracyThreshold}.0`
  );
  compiler.emit(
    `private val headingAccuracyThreshold = ${GEOSPATIAL_DEFAULTS.vps.headingAccuracyThreshold}.0`
  );
  compiler.emit('');
  compiler.emit('fun setupGeospatialVPS(session: Session) {');
  compiler.indentLevel++;
  compiler.emit('val config = session.config');
  compiler.emit('config.geospatialMode = Config.GeospatialMode.ENABLED');
  if (compiler.compositionHasTrait(composition, 'geospatial_streetscape')) {
    compiler.emit('config.streetscapeGeometryMode = Config.StreetscapeGeometryMode.ENABLED');
  }
  compiler.emit('session.configure(config)');
  compiler.emit('earth = session.earth');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun updateEarthTracking(session: Session) {');
  compiler.indentLevel++;
  compiler.emit('earth = session.earth');
  compiler.emit('val earthRef = earth ?: return');
  compiler.emit('if (earthRef.trackingState != TrackingState.TRACKING) return');
  compiler.emit('val geospatialState = earthRef.cameraGeospatialPose');
  compiler.emit('val horizontalAccuracy = geospatialState.horizontalAccuracy');
  compiler.emit('val headingAccuracy = geospatialState.headingAccuracy');
  compiler.emit(
    'if (horizontalAccuracy > horizontalAccuracyThreshold || headingAccuracy > headingAccuracyThreshold) return'
  );
  compiler.emit('Log.d("HoloScript", "cameraGeospatialPose localized")');
  if (compiler.compositionHasTrait(composition, 'geospatial_streetscape')) {
    compiler.emit('processStreetscapeGeometry(session)');
  }
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit(
    'fun createGeospatialAnchor(name: String, lat: Double, lng: Double, alt: Double, heading: Float): Anchor? {'
  );
  compiler.indentLevel++;
  compiler.emit('val earthRef = earth ?: return null');
  compiler.emit('if (earthRef.trackingState != TrackingState.TRACKING) return null');
  compiler.emit('val halfRadians = Math.toRadians(heading.toDouble()) / 2.0');
  compiler.emit(
    'val anchor = earthRef.createAnchor(lat, lng, alt, 0f, 0f, Math.sin(halfRadians).toFloat(), Math.cos(halfRadians).toFloat())'
  );
  compiler.emit('geospatialAnchors[name] = anchor');
  compiler.emit('return anchor');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit(
    'fun resolveTerrainAnchor(name: String, lat: Double, lng: Double, altitudeOffset: Double, heading: Float) {'
  );
  compiler.indentLevel++;
  compiler.emit('val earthRef = earth ?: return');
  compiler.emit('val halfRadians = Math.toRadians(heading.toDouble()) / 2.0');
  compiler.emit(
    'earthRef.resolveAnchorOnTerrainAsync(lat, lng, altitudeOffset, 0f, Math.sin(halfRadians).toFloat(), 0f, Math.cos(halfRadians).toFloat()) { anchor, state ->'
  );
  compiler.indentLevel++;
  compiler.emit(
    'if (state == Anchor.TerrainAnchorState.SUCCESS && anchor != null) geospatialAnchors[name] = anchor'
  );
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit(
    'fun resolveRooftopAnchor(name: String, lat: Double, lng: Double, altitudeOffset: Double, heading: Float) {'
  );
  compiler.indentLevel++;
  compiler.emit('val earthRef = earth ?: return');
  compiler.emit('val halfRadians = Math.toRadians(heading.toDouble()) / 2.0');
  compiler.emit(
    'earthRef.resolveAnchorOnRooftopAsync(lat, lng, altitudeOffset, 0f, Math.sin(halfRadians).toFloat(), 0f, Math.cos(halfRadians).toFloat()) { anchor, state ->'
  );
  compiler.indentLevel++;
  compiler.emit(
    'if (state == Anchor.RooftopAnchorState.SUCCESS && anchor != null) geospatialAnchors[name] = anchor'
  );
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun processStreetscapeGeometry(session: Session) {');
  compiler.indentLevel++;
  compiler.emit('val geometries = session.getAllTrackables(StreetscapeGeometry::class.java)');
  compiler.emit('for (geometry in geometries) {');
  compiler.indentLevel++;
  compiler.emit('if (geometry.trackingState != TrackingState.TRACKING) continue');
  compiler.emit('Log.d("HoloScript", "Streetscape geometry: " + geometry.type)');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit(
    'data class SceneViewGeospatialAnchor(val name: String, val latitude: Double, val longitude: Double, val altitude: Double, val heading: Float)'
  );
  compiler.indentLevel--;
  compiler.emit('}');
  return finish(compiler);
}

export function emitDepthScanSetup(
  compiler: AndroidCompiler,
  composition: HoloComposition
): string {
  emitHeader(compiler, composition, 'SceneView Depth Scanner Setup', ['ARCore Depth API']);
  compiler.emit('import android.media.Image');
  compiler.emit('import android.util.Log');
  compiler.emit('import com.google.ar.core.Config');
  compiler.emit('import com.google.ar.core.Frame');
  compiler.emit('import com.google.ar.core.Session');
  compiler.emit('');
  compiler.emit(`class ${compiler.options.className}DepthScanner {`);
  compiler.indentLevel++;
  emitUsedTraits(compiler, collectUsedTraits(composition, DEPTH_SCANNER_TRAITS));
  compiler.emit(
    `private val depthConfidenceThreshold = ${DEPTH_SCANNER_DEFAULTS.scan.confidenceThreshold}`
  );
  compiler.emit(
    `private val depthMaxMeters = ${floatLiteral(DEPTH_SCANNER_DEFAULTS.scan.maxDepthMeters)}`
  );
  compiler.emit(
    `private val depthMeshDecimation = ${floatLiteral(DEPTH_SCANNER_DEFAULTS.scan.meshDecimation)}`
  );
  compiler.emit('');
  compiler.emit('fun setupDepthScanner(session: Session) = configureDepthSession(session)');
  compiler.emit('');
  compiler.emit('fun configureDepthSession(session: Session) {');
  compiler.indentLevel++;
  compiler.emit('if (!session.isDepthModeSupported(Config.DepthMode.AUTOMATIC)) {');
  compiler.indentLevel++;
  compiler.emit('Log.w("HoloScript", "ARCore DepthMode.AUTOMATIC is unavailable")');
  compiler.emit('return');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('val config = session.config');
  compiler.emit('config.depthMode = Config.DepthMode.AUTOMATIC');
  compiler.emit('session.configure(config)');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun processDepthFrame(frame: Frame): List<DepthPoint> {');
  compiler.indentLevel++;
  compiler.emit('val depthImage = frame.acquireDepthImage16Bits()');
  compiler.emit('val confidenceImage = acquireConfidenceImage(frame)');
  compiler.emit('val source = detectDepthSource()');
  compiler.emit('val mesh = generateMeshFromDepth(depthImage, confidenceImage, source)');
  if (compiler.compositionHasTrait(composition, 'depth_mesh_to_holo')) {
    compiler.emit('convertDepthMeshToHolo(mesh)');
  }
  if (compiler.compositionHasTrait(composition, 'depth_export')) {
    compiler.emit('exportDepthMesh(mesh)');
  }
  compiler.emit('depthImage.close()');
  compiler.emit('confidenceImage?.close()');
  compiler.emit('return mesh');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('private fun acquireConfidenceImage(frame: Frame): Image? = try {');
  compiler.indentLevel++;
  compiler.emit('frame.acquireRawDepthConfidenceImage()');
  compiler.indentLevel--;
  compiler.emit('} catch (_: Throwable) {');
  compiler.indentLevel++;
  compiler.emit('null');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun detectDepthSource(): DepthSource {');
  compiler.indentLevel++;
  compiler.emit('return DepthSource.ARCORE_ML');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit(
    'fun generateMeshFromDepth(depthImage: Image, confidenceImage: Image?, source: DepthSource): List<DepthPoint> {'
  );
  compiler.indentLevel++;
  compiler.emit('val points = mutableListOf<DepthPoint>()');
  compiler.emit(
    '// Depth pixels are projected into SceneView/ARCore world space by the host renderer.'
  );
  compiler.emit(
    'points += DepthPoint(0f, 0f, depthMaxMeters.coerceAtMost(1f), depthConfidenceThreshold, source)'
  );
  compiler.emit('return points');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun convertDepthMeshToHolo(points: List<DepthPoint>): String {');
  compiler.indentLevel++;
  compiler.emit('return "holo_depth_mesh_vertices=" + points.size');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun exportDepthMesh(points: List<DepthPoint>): String {');
  compiler.indentLevel++;
  compiler.emit(
    'return buildString { appendLine("# HoloScript Depth Scan Export"); appendLine(points.size) }'
  );
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('enum class DepthSource { TOF, ARCORE_ML, STEREO }');
  compiler.emit(
    'data class DepthPoint(val x: Float, val y: Float, val z: Float, val confidence: Int, val source: DepthSource)'
  );
  compiler.indentLevel--;
  compiler.emit('}');
  return finish(compiler);
}

export function emitPortalARSetup(compiler: AndroidCompiler, composition: HoloComposition): string {
  emitHeader(compiler, composition, 'SceneView Portal AR Setup', [
    'ARCore Depth API',
    'SceneView camera pose callbacks',
  ]);
  compiler.emit('import android.util.Log');
  compiler.emit('import com.google.ar.core.Config');
  compiler.emit('import com.google.ar.core.Frame');
  compiler.emit('import com.google.ar.core.Pose');
  compiler.emit('import com.google.ar.core.Session');
  compiler.emit('');
  compiler.emit(`class ${compiler.options.className}PortalARManager {`);
  compiler.indentLevel++;
  emitUsedTraits(compiler, collectUsedTraits(composition, PORTAL_AR_TRAITS));
  compiler.emit('private val portalTiltThreshold = 25f');
  compiler.emit('private var portalVisible = true');
  compiler.emit('private var portalBoundary = PortalBoundary(PortalBoundary.Shape.CIRCLE)');
  compiler.emit('');
  compiler.emit('fun setupPortalAR(session: Session) {');
  compiler.indentLevel++;
  compiler.emit('configurePortalSession(session)');
  compiler.emit('setPortalVisibility(true)');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun configurePortalSession(session: Session) {');
  compiler.indentLevel++;
  compiler.emit('val config = session.config');
  compiler.emit('if (session.isDepthModeSupported(Config.DepthMode.AUTOMATIC)) {');
  compiler.indentLevel++;
  compiler.emit('config.depthMode = Config.DepthMode.AUTOMATIC');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('config.lightEstimationMode = Config.LightEstimationMode.ENVIRONMENTAL_HDR');
  compiler.emit('session.configure(config)');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun updateDepthOcclusion(frame: Frame) {');
  compiler.indentLevel++;
  compiler.emit('Log.d("HoloScript", "updateDepthOcclusion with ARCore depth")');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun applyParallaxCorrection(cameraPose: Pose) {');
  compiler.indentLevel++;
  compiler.emit('Log.d("HoloScript", "applyParallaxCorrection from SceneView camera pose")');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun enableDepthFade(enabled: Boolean = true) {');
  compiler.indentLevel++;
  compiler.emit('Log.d("HoloScript", "enableDepthFade=" + enabled)');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun reconstructMesh(session: Session) {');
  compiler.indentLevel++;
  compiler.emit('Log.d("HoloScript", "reconstructMesh for portal world mesh")');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun updateMeshOcclusion() {');
  compiler.indentLevel++;
  compiler.emit('Log.d("HoloScript", "updateMeshOcclusion")');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun updatePeekThrough(deviceTiltDegrees: Float) {');
  compiler.indentLevel++;
  compiler.emit('setPortalVisibility(kotlin.math.abs(deviceTiltDegrees) > portalTiltThreshold)');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun setPortalVisibility(visible: Boolean) {');
  compiler.indentLevel++;
  compiler.emit('portalVisible = visible');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun updateLighting(frame: Frame) {');
  compiler.indentLevel++;
  compiler.emit('Log.d("HoloScript", "updateLighting from ENVIRONMENTAL_HDR estimate")');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('data class PortalBoundary(val shape: Shape) {');
  compiler.indentLevel++;
  compiler.emit('enum class Shape { CIRCLE, RECTANGLE, FREEFORM }');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.indentLevel--;
  compiler.emit('}');
  return finish(compiler);
}

export function emitHandTrackingSetup(
  compiler: AndroidCompiler,
  composition: HoloComposition
): string {
  emitHeader(compiler, composition, 'SceneView Camera Hand Tracking Setup', [
    'CameraX',
    'MediaPipe Hands / HandLandmarker',
  ]);
  compiler.emit('import android.content.Context');
  compiler.emit('import android.util.Log');
  compiler.emit('import com.google.mediapipe.framework.image.MPImage');
  compiler.emit('import com.google.mediapipe.tasks.vision.handlandmarker.HandLandmarker');
  compiler.emit('import com.google.mediapipe.tasks.vision.handlandmarker.HandLandmarkerResult');
  compiler.emit('');
  compiler.emit(
    `class ${compiler.options.className}HandTrackingManager(private val context: Context) {`
  );
  compiler.indentLevel++;
  emitUsedTraits(compiler, collectUsedTraits(composition, CAMERA_HAND_TRACKING_TRAITS));
  const confidenceTrait = objectsOf(composition)
    .flatMap((obj) => traitsOf(obj))
    .find((trait) => traitName(trait) === 'camera_hand_confidence');
  const confidence = numberConfig(
    traitConfig(confidenceTrait),
    ['threshold', 'minConfidence'],
    0.65
  );
  const maxHands = compiler.compositionHasTrait(composition, 'camera_hand_two_hands') ? 2 : 1;
  compiler.emit(`private val maxNumHands = ${maxHands}`);
  compiler.emit(`private val minHandConfidence = ${confidence}`);
  compiler.emit('private var handLandmarker: HandLandmarker? = null');
  compiler.emit('');
  compiler.emit('fun setupHandTracking() {');
  compiler.indentLevel++;
  compiler.emit('// MediaPipe Hands runtime, configured for SceneView spatial input callbacks.');
  compiler.emit(
    'val options = HandLandmarker.HandLandmarkerOptions.builder().setNumHands(maxNumHands).setMinHandDetectionConfidence(minHandConfidence.toFloat()).build()'
  );
  compiler.emit('handLandmarker = HandLandmarker.createFromOptions(context, options)');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun processCameraFrame(image: MPImage, timestampMs: Long) {');
  compiler.indentLevel++;
  compiler.emit('val result = handLandmarker?.detect(image) ?: return');
  compiler.emit('handleHandLandmarks(result, timestampMs)');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun handleHandLandmarks(result: HandLandmarkerResult, timestampMs: Long) {');
  compiler.indentLevel++;
  compiler.emit('// 21-joint skeleton per detected hand.');
  compiler.emit('for ((index, landmarks) in result.landmarks().withIndex()) {');
  compiler.indentLevel++;
  compiler.emit('val skeleton = landmarks.mapIndexed { jointIndex, landmark ->');
  compiler.indentLevel++;
  compiler.emit(
    'HandJoint(jointIndex, landmark.x(), landmark.y(), landmark.z(), minHandConfidence.toFloat())'
  );
  compiler.indentLevel--;
  compiler.emit('}');
  if (compiler.compositionHasTrait(composition, 'camera_hand_gesture_pinch')) {
    compiler.emit('classifyPinchGesture(index, skeleton, timestampMs)');
  }
  if (compiler.compositionHasTrait(composition, 'camera_hand_gesture_point')) {
    compiler.emit('classifyPointGesture(index, skeleton, timestampMs)');
  }
  if (compiler.compositionHasTrait(composition, 'camera_hand_to_spatial')) {
    compiler.emit('emitSpatialInput(SpatialInputEvent("hand_skeleton", index, timestampMs))');
  }
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit(
    'fun classifyPinchGesture(handIndex: Int, skeleton: List<HandJoint>, timestampMs: Long) {'
  );
  compiler.indentLevel++;
  compiler.emit('// Pinch gesture: thumb tip to index tip distance.');
  compiler.emit('val pinchDist = kotlin.math.abs(skeleton[4].x - skeleton[8].x)');
  compiler.emit(
    'if (pinchDist < 0.04f) emitSpatialInput(SpatialInputEvent("pinch", handIndex, timestampMs))'
  );
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit(
    'fun classifyPointGesture(handIndex: Int, skeleton: List<HandJoint>, timestampMs: Long) {'
  );
  compiler.indentLevel++;
  compiler.emit('// POINT detected when index fingertip leads the palm.');
  compiler.emit(
    'if (skeleton[8].y < skeleton[0].y) emitSpatialInput(SpatialInputEvent("point", handIndex, timestampMs))'
  );
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit('fun emitSpatialInput(event: SpatialInputEvent) {');
  compiler.indentLevel++;
  compiler.emit('Log.d("HoloScript", "emitSpatialInput " + event.type)');
  compiler.indentLevel--;
  compiler.emit('}');
  compiler.emit('');
  compiler.emit(
    'data class HandJoint(val index: Int, val x: Float, val y: Float, val z: Float, val confidence: Float)'
  );
  compiler.emit(
    'data class SpatialInputEvent(val type: String, val handIndex: Int, val timestampMs: Long)'
  );
  compiler.indentLevel--;
  compiler.emit('}');
  return finish(compiler);
}
