import { describe, it, expect, beforeEach } from 'vitest';
import { BabylonCompiler } from './BabylonCompiler';
import { registerAllPresets } from '../traits/visual';
import { createTestCompilerToken } from './CompilerBase';
import type { HoloComposition, HoloObjectDecl, HoloLight, HoloCamera, HoloSpatialGroup, HoloTimeline, HoloAudio, HoloZone, HoloUI, HoloEffects, HoloTransition, HoloEnvironment } from '../parser/HoloCompositionTypes';

// Ensure TraitVisualRegistry is populated for TraitCompositor integration tests
registerAllPresets();

// ============================================================================
// Test Agent Token
// ============================================================================
let testToken: string;

beforeEach(() => {
  // Create a valid CODE_GENERATOR token for all tests
  testToken = createTestCompilerToken();
});

// ============================================================================
// Helpers
// ============================================================================

function createComposition(overrides: Partial<HoloComposition> = {}): HoloComposition {
  return {
    type: 'HoloComposition',
    name: 'TestScene',
    objects: [],
    spatialGroups: [],
    lights: [],
    timelines: [],
    audio: [],
    zones: [],
    transitions: [],
    ...overrides,
  } as HoloComposition;
}

function createObject(name: string, overrides: Partial<HoloObjectDecl> = {}): HoloObjectDecl {
  return {
    type: 'ObjectDecl',
    name,
    properties: [],
    traits: [],
    children: [],
    ...overrides,
  } as HoloObjectDecl;
}

function prop(key: string, value: any): { key: string; value: any } {
  return { key, value };
}

function trait(name: string, config?: Record<string, any>): { name: string; config: Record<string, any> } {
  return { name, config: config || {} };
}

function createLight(overrides: Partial<HoloLight> & { lightType?: string } = {}): HoloLight {
  return {
    name: 'TestLight',
    lightType: overrides.lightType || 'point',
    properties: overrides.properties || [
      prop('position', [0, 5, 0]),
      prop('intensity', 1.0),
    ],
    ...overrides,
  } as HoloLight;
}

// ============================================================================
// Tests
// ============================================================================

describe('BabylonCompiler', () => {
  let compiler: BabylonCompiler;

  beforeEach(() => {
    compiler = new BabylonCompiler();
  });

  // --------------------------------------------------------------------------
  // Constructor
  // --------------------------------------------------------------------------

  describe('constructor', () => {
    it('should create with default options', () => {
      expect(compiler).toBeDefined();
      expect(compiler).toBeInstanceOf(BabylonCompiler);
    });

    it('should accept custom class name', () => {
      const c = new BabylonCompiler({ className: 'MyScene' });
      const output = c.compile(createComposition(), testToken);
      expect(output).toContain('export class MyScene');
    });

    it('should accept custom indent', () => {
      const c = new BabylonCompiler({ indent: '    ' });
      const output = c.compile(createComposition(), testToken);
      expect(output).toContain('    ');
    });

    it('should default className to GeneratedScene', () => {
      const output = compiler.compile(createComposition(), testToken);
      expect(output).toContain('export class GeneratedScene');
    });
  });

  // --------------------------------------------------------------------------
  // Basic Compilation
  // --------------------------------------------------------------------------

  describe('compile()', () => {
    it('should produce a string', () => {
      const result = compiler.compile(createComposition(), testToken);
      expect(typeof result).toBe('string');
    });

    it('should include auto-generated comment', () => {
      const output = compiler.compile(createComposition(), testToken);
      expect(output).toContain('// Auto-generated by HoloScript BabylonCompiler');
    });

    it('should include source composition name', () => {
      const output = compiler.compile(createComposition({ name: 'MyWorld' }), testToken);
      expect(output).toContain('Source: composition "MyWorld"');
    });

    it('should emit imports', () => {
      const output = compiler.compile(createComposition(), testToken);
      expect(output).toContain('import * as BABYLON from "@babylonjs/core"');
    });

    it('should emit the class structure', () => {
      const output = compiler.compile(createComposition(), testToken);
      expect(output).toContain('export class GeneratedScene');
      expect(output).toContain('private engine: BABYLON.Engine');
      expect(output).toContain('private scene: BABYLON.Scene');
      expect(output).toContain('constructor(canvas: HTMLCanvasElement)');
    });

    it('should emit build method', () => {
      const output = compiler.compile(createComposition(), testToken);
      expect(output).toContain('async build(): Promise<void>');
    });

    it('should emit dispose method', () => {
      const output = compiler.compile(createComposition(), testToken);
      expect(output).toContain('dispose(): void');
      expect(output).toContain('this.scene.dispose()');
      expect(output).toContain('this.engine.dispose()');
    });

    it('should emit render loop', () => {
      const output = compiler.compile(createComposition(), testToken);
      expect(output).toContain('engine.runRenderLoop');
    });

    it('should emit default light when no lights specified', () => {
      const output = compiler.compile(createComposition({ lights: [] }), testToken);
      expect(output).toContain('HemisphericLight');
      expect(output).toContain('defaultLight');
    });

    it('should emit default camera when no camera specified', () => {
      const output = compiler.compile(createComposition(), testToken);
      expect(output).toContain('ArcRotateCamera');
      expect(output).toContain('defaultCamera');
    });
  });

  // --------------------------------------------------------------------------
  // Imports
  // --------------------------------------------------------------------------

  describe('imports', () => {
    it('should include Babylon core import', () => {
      const output = compiler.compile(createComposition(), testToken);
      expect(output).toContain('import * as BABYLON from "@babylonjs/core"');
    });

    it('should include GUI import when UI is present', () => {
      const output = compiler.compile(createComposition({
        ui: { elements: [{ name: 'Btn1', properties: [prop('type', 'button'), prop('text', 'Click')] }] } as any,
      }), testToken);
      expect(output).toContain('import * as GUI from "@babylonjs/gui"');
    });

    it('should include Havok import when useHavok is true', () => {
      const c = new BabylonCompiler({ useHavok: true });
      const output = c.compile(createComposition(), testToken);
      expect(output).toContain('import HavokPhysics from "@babylonjs/havok"');
    });

    it('should not include Havok import when useHavok is false', () => {
      const c = new BabylonCompiler({ useHavok: false });
      const output = c.compile(createComposition(), testToken);
      expect(output).not.toContain('HavokPhysics');
    });

    it('should include loaders import when XR enabled', () => {
      const c = new BabylonCompiler({ enableXR: true });
      const output = c.compile(createComposition(), testToken);
      expect(output).toContain('import "@babylonjs/loaders"');
    });
  });

  // --------------------------------------------------------------------------
  // Objects
  // --------------------------------------------------------------------------

  describe('objects', () => {
    it('should emit sphere mesh', () => {
      const obj = createObject('MySphere', {
        properties: [
          { key: 'geometry', value: 'sphere' },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('CreateSphere');
      expect(output).toContain('MySphere');
    });

    it('should emit cube mesh', () => {
      const obj = createObject('MyCube', {
        properties: [
          { key: 'geometry', value: 'cube' },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('CreateBox');
    });

    it('should emit cylinder mesh', () => {
      const obj = createObject('MyCylinder', {
        properties: [
          { key: 'geometry', value: 'cylinder' },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('CreateCylinder');
    });

    it('should emit torus mesh', () => {
      const obj = createObject('MyTorus', {
        properties: [
          { key: 'geometry', value: 'torus' },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('CreateTorus');
    });

    it('should emit capsule mesh', () => {
      const obj = createObject('MyCapsule', {
        properties: [
          { key: 'geometry', value: 'capsule' },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('CreateCapsule');
    });

    it('should emit plane/ground mesh', () => {
      const obj = createObject('MyGround', {
        properties: [
          { key: 'geometry', value: 'plane' },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('CreateGround');
    });

    it('should emit disc mesh', () => {
      const obj = createObject('MyDisc', {
        properties: [
          { key: 'geometry', value: 'disc' },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('CreateDisc');
    });

    it('should handle position property', () => {
      const obj = createObject('Positioned', {
        properties: [
          { key: 'geometry', value: 'sphere' },
          { key: 'position', value: [1, 2, 3] },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('new BABYLON.Vector3(1, 2, 3)');
    });

    it('should handle scale property', () => {
      const obj = createObject('Scaled', {
        properties: [
          { key: 'geometry', value: 'cube' },
          { key: 'scale', value: [2, 2, 2] },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('scaling');
    });

    it('should handle rotation property', () => {
      const obj = createObject('Rotated', {
        properties: [
          { key: 'geometry', value: 'cube' },
          { key: 'rotation', value: [0, 45, 0] },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('rotation');
    });

    it('should handle color property as PBR material', () => {
      const obj = createObject('Colored', {
        properties: [
          { key: 'geometry', value: 'sphere' },
          { key: 'color', value: '#ff0000' },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('PBRMaterial');
      expect(output).toContain('albedoColor');
    });

    it('should handle opacity property', () => {
      const obj = createObject('Transparent', {
        properties: [
          { key: 'geometry', value: 'sphere' },
          { key: 'opacity', value: 0.5 },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('alpha');
    });

    it('should handle model geometry type', () => {
      const obj = createObject('Model', {
        properties: [
          { key: 'model', value: 'character.glb' },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('SceneLoader');
    });

    it('should handle text geometry type', () => {
      const obj = createObject('TextObj', {
        properties: [
          { key: 'geometry', value: 'text' },
          { key: 'text', value: 'Hello World' },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('Hello World');
    });

    it('should handle emissive properties', () => {
      const obj = createObject('Glowing', {
        properties: [
          { key: 'geometry', value: 'sphere' },
          { key: 'emissive', value: '#00ff00' },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('emissiveColor');
    });

    it('should handle metallic property', () => {
      const obj = createObject('Metal', {
        properties: [
          { key: 'geometry', value: 'sphere' },
          { key: 'metallic', value: 0.8 },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('metallic');
    });

    it('should handle roughness property', () => {
      const obj = createObject('Rough', {
        properties: [
          { key: 'geometry', value: 'sphere' },
          { key: 'roughness', value: 0.3 },
        ],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('roughness');
    });
  });

  // --------------------------------------------------------------------------
  // Traits
  // --------------------------------------------------------------------------

  describe('traits', () => {
    it('should handle @grabbable trait', () => {
      const obj = createObject('Grabbable', {
        properties: [{ key: 'geometry', value: 'cube' }],
        traits: [trait('grabbable')],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('ActionManager');
    });

    it('should handle @physics trait', () => {
      const obj = createObject('Physical', {
        properties: [{ key: 'geometry', value: 'sphere' }],
        traits: [trait('physics')],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('PhysicsBody');
    });

    it('should handle @collidable trait', () => {
      const obj = createObject('Collidable', {
        properties: [{ key: 'geometry', value: 'cube' }],
        traits: [trait('collidable')],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('PhysicsBody');
    });

    it('should handle @hoverable trait', () => {
      const obj = createObject('Hoverable', {
        properties: [{ key: 'geometry', value: 'sphere' }],
        traits: [trait('hoverable')],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('Pointer');
    });

    it('should handle @shadow trait', () => {
      const obj = createObject('Shadowed', {
        properties: [{ key: 'geometry', value: 'cube' }],
        traits: [trait('shadow')],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('receiveShadows');
    });

    it('should handle @accessible trait', () => {
      const obj = createObject('Accessible', {
        properties: [{ key: 'geometry', value: 'cube' }],
        traits: [trait('accessible')],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('accessibilityTag');
    });

    it('should handle @gaussian_splat trait', () => {
      const obj = createObject('Splat', {
        properties: [{ key: 'geometry', value: 'sphere' }],
        traits: [trait('gaussian_splat')],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('PointsCloudSystem');
    });

    it('should handle multiple traits', () => {
      const obj = createObject('Multi', {
        properties: [{ key: 'geometry', value: 'cube' }],
        traits: [trait('grabbable'), trait('physics'), trait('shadow')],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      expect(output).toContain('ActionManager');
      expect(output).toContain('PhysicsBody');
      expect(output).toContain('receiveShadows');
    });
  });

  // --------------------------------------------------------------------------
  // Lights
  // --------------------------------------------------------------------------

  describe('lights', () => {
    it('should emit hemispheric light', () => {
      const light = createLight({ lightType: 'hemisphere', name: 'AmbientLight' });
      const output = compiler.compile(createComposition({ lights: [light] }), testToken);
      expect(output).toContain('HemisphericLight');
    });

    it('should emit directional light', () => {
      const light = createLight({ lightType: 'directional', name: 'SunLight' });
      const output = compiler.compile(createComposition({ lights: [light] }), testToken);
      expect(output).toContain('DirectionalLight');
    });

    it('should emit point light', () => {
      const light = createLight({ lightType: 'point', name: 'Lamp' });
      const output = compiler.compile(createComposition({ lights: [light] }), testToken);
      expect(output).toContain('PointLight');
    });

    it('should emit spot light', () => {
      const light = createLight({ lightType: 'spot', name: 'Spotlight' });
      const output = compiler.compile(createComposition({ lights: [light] }), testToken);
      expect(output).toContain('SpotLight');
    });

    it('should set light intensity', () => {
      const light = createLight({ properties: [prop('position', [0, 5, 0]), prop('intensity', 2.5)] });
      const output = compiler.compile(createComposition({ lights: [light] }), testToken);
      expect(output).toContain('intensity = 2.5');
    });

    it('should set light color', () => {
      const light = createLight({ properties: [prop('position', [0, 5, 0]), prop('intensity', 1.0), prop('color', '#ffcc00')] });
      const output = compiler.compile(createComposition({ lights: [light] }), testToken);
      expect(output).toContain('diffuse');
    });

    it('should not emit default light when lights are provided', () => {
      const light = createLight({ lightType: 'point' });
      const output = compiler.compile(createComposition({ lights: [light] }), testToken);
      expect(output).not.toContain('defaultLight');
    });

    it('should handle multiple lights', () => {
      const lights = [
        createLight({ lightType: 'point', name: 'Light1' }),
        createLight({ lightType: 'directional', name: 'Light2' }),
      ];
      const output = compiler.compile(createComposition({ lights }), testToken);
      expect(output).toContain('PointLight');
      expect(output).toContain('DirectionalLight');
    });
  });

  // --------------------------------------------------------------------------
  // Camera
  // --------------------------------------------------------------------------

  describe('camera', () => {
    it('should emit perspective camera as ArcRotateCamera', () => {
      const camera = { cameraType: 'perspective', properties: [prop('position', [0, 5, -10])] } as any;
      const output = compiler.compile(createComposition({ camera }), testToken);
      expect(output).toContain('ArcRotateCamera');
    });

    it('should emit orthographic camera', () => {
      const camera = { cameraType: 'orthographic', properties: [prop('position', [0, 10, 0])] } as any;
      const output = compiler.compile(createComposition({ camera }), testToken);
      expect(output).toContain('ORTHOGRAPHIC');
    });

    it('should attach camera control to canvas', () => {
      const camera = { cameraType: 'perspective', properties: [] } as any;
      const output = compiler.compile(createComposition({ camera }), testToken);
      expect(output).toContain('attachControl');
    });

    it('should not emit default camera when camera is specified', () => {
      const camera = { cameraType: 'perspective', properties: [] } as any;
      const output = compiler.compile(createComposition({ camera }), testToken);
      expect(output).not.toContain('defaultCamera');
    });
  });

  // --------------------------------------------------------------------------
  // Environment
  // --------------------------------------------------------------------------

  describe('environment', () => {
    it('should emit skybox configuration', () => {
      const env = { properties: [prop('skybox', 'nebula')] } as any;
      const output = compiler.compile(createComposition({ environment: env as any }), testToken);
      expect(output).toContain('skybox');
    });

    it('should emit ambient light from environment', () => {
      const env = { properties: [prop('ambient_light', 0.5)] } as any;
      const output = compiler.compile(createComposition({ environment: env as any }), testToken);
      expect(output).toContain('0.5');
    });

    it('should emit fog configuration', () => {
      const env = { properties: [prop('fog', { type: 'exponential', density: 0.02 })] } as any;
      const output = compiler.compile(createComposition({ environment: env as any }), testToken);
      expect(output).toContain('fog');
    });

    it('should emit ground configuration', () => {
      const env = { properties: [prop('ground', { color: '#885533' })] } as any;
      const output = compiler.compile(createComposition({ environment: env as any }), testToken);
      expect(output).toContain('CreateGround');
    });
  });

  // --------------------------------------------------------------------------
  // Spatial Groups
  // --------------------------------------------------------------------------

  describe('spatialGroups', () => {
    it('should emit group container', () => {
      const group: HoloSpatialGroup = {
        name: 'TestGroup',
        properties: [],
        objects: [createObject('Child1', { properties: [{ key: 'geometry', value: 'cube' }] } as any)],
      } as any;
      const output = compiler.compile(createComposition({ spatialGroups: [group] }), testToken);
      expect(output).toContain('TestGroup');
    });

    it('should parent children to group node', () => {
      const group: HoloSpatialGroup = {
        name: 'GroupNode',
        properties: [],
        objects: [
          createObject('A', { properties: [{ key: 'geometry', value: 'sphere' }] } as any),
          createObject('B', { properties: [{ key: 'geometry', value: 'cube' }] } as any),
        ],
      } as any;
      const output = compiler.compile(createComposition({ spatialGroups: [group] }), testToken);
      expect(output).toContain('parent');
    });
  });

  // --------------------------------------------------------------------------
  // Timelines / Animation
  // --------------------------------------------------------------------------

  describe('timelines', () => {
    it('should emit animation code', () => {
      const timeline: HoloTimeline = {
        name: 'BounceAnim',
        entries: [
          { time: 0.5, action: { kind: 'animate', target: 'Ball', properties: { 'position.y': 2 } } },
        ],
      } as any;
      const output = compiler.compile(createComposition({ timelines: [timeline] }), testToken);
      expect(output).toContain('Animation');
    });
  });

  // --------------------------------------------------------------------------
  // Audio
  // --------------------------------------------------------------------------

  describe('audio', () => {
    it('should emit audio/sound code', () => {
      const audio: HoloAudio = {
        name: 'BGMusic',
        properties: [
          prop('src', 'music.mp3'),
          prop('loop', true),
        ],
      } as any;
      const output = compiler.compile(createComposition({ audio: [audio] }), testToken);
      expect(output).toContain('Sound');
    });
  });

  // --------------------------------------------------------------------------
  // Zones
  // --------------------------------------------------------------------------

  describe('zones', () => {
    it('should emit zone trigger', () => {
      const zone: HoloZone = {
        name: 'DangerZone',
        properties: [
          prop('shape', 'box'),
          prop('position', [0, 0, 0]),
          prop('size', [10, 5, 10]),
        ],
      } as any;
      const output = compiler.compile(createComposition({ zones: [zone] }), testToken);
      expect(output).toContain('DangerZone');
    });
  });

  // --------------------------------------------------------------------------
  // UI
  // --------------------------------------------------------------------------

  describe('ui', () => {
    it('should emit GUI AdvancedDynamicTexture for UI', () => {
      const ui: HoloUI = {
        elements: [{ name: 'PlayBtn', properties: [prop('type', 'button'), prop('text', 'Play')] }],
      } as any;
      const output = compiler.compile(createComposition({ ui }), testToken);
      expect(output).toContain('AdvancedDynamicTexture');
    });

    it('should emit button element', () => {
      const ui: HoloUI = {
        elements: [{ name: 'StartBtn', properties: [prop('type', 'button'), prop('text', 'Start')] }],
      } as any;
      const output = compiler.compile(createComposition({ ui }), testToken);
      expect(output).toContain('Button');
    });

    it('should emit text element', () => {
      const ui: HoloUI = {
        elements: [{ name: 'ScoreText', properties: [prop('type', 'text'), prop('text', 'Score: 0')] }],
      } as any;
      const output = compiler.compile(createComposition({ ui }), testToken);
      expect(output).toContain('TextBlock');
    });

    it('should emit progress bar', () => {
      const ui: HoloUI = {
        elements: [{ name: 'HealthBar', properties: [prop('type', 'progress'), prop('value', 75)] }],
      } as any;
      const output = compiler.compile(createComposition({ ui }), testToken);
      expect(output).toContain('StackPanel');
    });
  });

  // --------------------------------------------------------------------------
  // Effects (Post-Processing)
  // --------------------------------------------------------------------------

  describe('effects', () => {
    it('should emit bloom effect', () => {
      const effects: HoloEffects = {
        effects: [{ effectType: 'bloom', properties: { intensity: 0.5, threshold: 0.8 } }],
      } as any;
      const output = compiler.compile(createComposition({ effects }), testToken);
      expect(output).toContain('bloom');
    });

    it('should emit depth of field effect', () => {
      const effects: HoloEffects = {
        effects: [{ effectType: 'dof', properties: { focalLength: 50 } }],
      } as any;
      const output = compiler.compile(createComposition({ effects }), testToken);
      expect(output).toContain('depthOfField');
    });

    it('should emit SSAO effect', () => {
      const effects: HoloEffects = {
        effects: [{ effectType: 'ssao', properties: { radius: 2.0 } }],
      } as any;
      const output = compiler.compile(createComposition({ effects }), testToken);
      expect(output).toContain('ssao');
    });

    it('should emit vignette effect', () => {
      const effects: HoloEffects = {
        effects: [{ effectType: 'vignette', properties: { weight: 1.5 } }],
      } as any;
      const output = compiler.compile(createComposition({ effects }), testToken);
      expect(output).toContain('vignette');
    });

    it('should emit chromatic aberration effect', () => {
      const effects: HoloEffects = {
        effects: [{ effectType: 'chromatic_aberration', properties: { amount: 0.3 } }],
      } as any;
      const output = compiler.compile(createComposition({ effects }), testToken);
      expect(output).toContain('chromatic');
    });

    it('should emit tone mapping effect', () => {
      const effects: HoloEffects = {
        effects: [{ effectType: 'tone_mapping', properties: { type: 'ACES' } }],
      } as any;
      const output = compiler.compile(createComposition({ effects }), testToken);
      expect(output).toContain('toneMapping');
    });
  });

  // --------------------------------------------------------------------------
  // Transitions
  // --------------------------------------------------------------------------

  describe('transitions', () => {
    it('should emit transition code', () => {
      const transition: HoloTransition = {
        name: 'FadeOut',
        properties: [
          prop('effect', 'fade'),
          prop('duration', 1000),
        ],
      } as any;
      const output = compiler.compile(createComposition({ transitions: [transition] }), testToken);
      expect(output).toContain('FadeOut');
    });
  });

  // --------------------------------------------------------------------------
  // XR
  // --------------------------------------------------------------------------

  describe('XR support', () => {
    it('should emit XR setup when enabled', () => {
      const c = new BabylonCompiler({ enableXR: true });
      const output = c.compile(createComposition(), testToken);
      expect(output).toContain('createDefaultXRExperienceAsync');
    });

    it('should not emit XR setup when disabled', () => {
      const c = new BabylonCompiler({ enableXR: false });
      const output = c.compile(createComposition(), testToken);
      expect(output).not.toContain('XRExperience');
    });
  });

  // --------------------------------------------------------------------------
  // TraitCompositor Integration
  // --------------------------------------------------------------------------

  describe('TraitCompositor integration', () => {
    it('should invoke TraitCompositor for objects with traits', () => {
      const obj = createObject('Composited', {
        properties: [{ key: 'geometry', value: 'cube' }],
        traits: [trait('glowing'), trait('transparent')],
      } as any);
      const output = compiler.compile(createComposition({ objects: [obj] }), testToken);
      // TraitCompositor produces composed material properties
      expect(output).toContain('PBRMaterial');
    });
  });

  // --------------------------------------------------------------------------
  // Multiple Objects
  // --------------------------------------------------------------------------

  describe('complex compositions', () => {
    it('should compile a composition with multiple objects', () => {
      const objects = [
        createObject('Floor', {
          properties: [
            { key: 'geometry', value: 'plane' },
            { key: 'position', value: [0, 0, 0] },
          ],
        } as any),
        createObject('Player', {
          properties: [
            { key: 'geometry', value: 'capsule' },
            { key: 'position', value: [0, 1, 0] },
            { key: 'color', value: '#00ff00' },
          ],
          traits: [trait('physics'), trait('collidable')],
        } as any),
        createObject('Enemy', {
          properties: [
            { key: 'geometry', value: 'sphere' },
            { key: 'position', value: [5, 1, 5] },
            { key: 'color', value: '#ff0000' },
          ],
        } as any),
      ];
      const output = compiler.compile(createComposition({ objects }), testToken);
      expect(output).toContain('Floor');
      expect(output).toContain('Player');
      expect(output).toContain('Enemy');
      expect(output).toContain('CreateGround');
      expect(output).toContain('CreateCapsule');
      expect(output).toContain('CreateSphere');
    });

    it('should compile a full scene with lights, camera, objects, and effects', () => {
      const output = compiler.compile(createComposition({
        name: 'FullScene',
        environment: { properties: [prop('skybox', 'sunset'), prop('ambient_light', 0.3)] } as any,
        lights: [createLight({ lightType: 'directional', name: 'Sun' })],
        camera: { cameraType: 'perspective', properties: [] } as any,
        objects: [
          createObject('Ground', {
            properties: [{ key: 'geometry', value: 'ground' }],
          } as any),
        ],
        effects: { effects: [{ effectType: 'bloom', properties: { intensity: 0.5 } }] } as any,
      }), testToken);

      expect(output).toContain('FullScene');
      expect(output).toContain('DirectionalLight');
      expect(output).toContain('ArcRotateCamera');
      expect(output).toContain('CreateGround');
      expect(output).toContain('bloom');
    });

    it('should handle empty composition', () => {
      const output = compiler.compile(createComposition({
        name: 'Empty',
        objects: [],
        lights: [],
      }), testToken);
      expect(output).toContain('Empty');
      expect(output).toContain('HemisphericLight'); // default light
      expect(output).toContain('ArcRotateCamera'); // default camera
    });
  });

  // --------------------------------------------------------------------------
  // Re-compilation (idempotency)
  // --------------------------------------------------------------------------

  describe('re-compilation', () => {
    it('should produce consistent output for same input', () => {
      const composition = createComposition({
        objects: [createObject('Obj', { properties: [{ key: 'geometry', value: 'sphere' }] } as any)],
      });
      const output1 = compiler.compile(composition);
      const output2 = compiler.compile(composition);
      expect(output1).toBe(output2);
    });

    it('should reset state between compilations', () => {
      const comp1 = createComposition({ name: 'Scene1', objects: [] });
      const comp2 = createComposition({ name: 'Scene2', objects: [] });
      const out1 = compiler.compile(comp1);
      const out2 = compiler.compile(comp2);
      expect(out1).toContain('Scene1');
      expect(out1).not.toContain('Scene2');
      expect(out2).toContain('Scene2');
      expect(out2).not.toContain('Scene1');
    });
  });
});
