/**
 * HoloScript -> GBNF grammar generator (M4 "constrained subset").
 *
 * Emits a llama.cpp GBNF grammar that constrains a local model's DECODING so it
 * can only produce syntactically-valid HoloScript. This is validity-by-
 * construction pushed down to the token level: paired with `@llama_serve { grammar:
 * "holoscript" }` the compiler writes this grammar into the server bundle and the
 * launch command gains `--grammar-file`, so a 4B local model on the sovereign
 * fleet emits parseable `.holo` every time instead of "usually parseable" prose.
 *
 * The terminals here follow the PRODUCTION lexer (packages/core/src/parser/
 * composition/lexer.ts + tokens.ts), NOT the more permissive tree-sitter grammar:
 *   - number = `-?[0-9]+(\.[0-9]+)?`  (NO exponent, NO leading dot)
 *   - string = "..." / '...' with the exact escape set the lexer accepts (\" \\ \' \n \t \r)
 *   - identifiers = `[A-Za-z_][A-Za-z0-9_]*`  (cannot start with a digit)
 *   - hex colors are authored as QUOTED strings (`base_color: "#5d4037"`) — the
 *     conformance-accepted form — so `value` covers them without a bare-# rule.
 *
 * Scope (first subset, deliberately): keyword objects (`object "Name" @trait { ... }`),
 * primitive objects (`cube { ... }`), and material blocks (`material "Stone" @advanced_pbr
 * { ... }`), each with `@trait(args)` applications and `key: value` properties over
 * number / string / boolean / null / array values. `.hs` control-flow logic (Rust/WASM)
 * is out of scope. Widen the keyword/shape/trait sets via options as the language grows.
 */

/** Options for {@link generateHoloScriptGbnf} — defaults are a useful, parser-valid subset. */
export interface HoloScriptGbnfOptions {
  /** Keyword-object head keywords (each requires a name), e.g. `object "Name" { }`. */
  objectKeywords?: readonly string[];
  /** Primitive shape keywords (optional id), e.g. `cube { }`. */
  primitiveShapes?: readonly string[];
  /** Material-family block keywords, e.g. `material "Stone" @advanced_pbr { }`. */
  materialKeywords?: readonly string[];
  /**
   * Require at least one top-level definition (`root ::= ws (def ws)+`). Default true —
   * an empty document is not a useful constrained generation.
   */
  requireDefinition?: boolean;
}

/**
 * The default subset. Object keywords + primitive shapes are drawn from the parser
 * token SSOT (tokens.ts KEYWORDS 'OBJECT' entries + PRIMITIVE_SHAPES); kept as a
 * curated list here so the generator has no runtime dependency on the lexer and
 * stays a pure, testable string builder. Widen via options when the subset grows.
 */
export const DEFAULT_OBJECT_KEYWORDS = ['object', 'entity', 'instanced_object', 'orb'] as const;
export const DEFAULT_PRIMITIVE_SHAPES = [
  'cube',
  'box',
  'sphere',
  'cylinder',
  'cone',
  'torus',
  'plane',
  'capsule',
  'circle',
  'text',
] as const;
export const DEFAULT_MATERIAL_KEYWORDS = ['material'] as const;

/** GBNF alternation of quoted literals: ["a","b"] -> `"a" | "b"`. Empty -> a never-matching rule. */
function literalAlternation(values: readonly string[]): string {
  const unique = [...new Set(values.filter((v) => v.length > 0))];
  if (unique.length === 0) return '"\\u0000"'; // unreachable literal — keeps the grammar well-formed
  return unique.map((v) => `"${v}"`).join(' | ');
}

/**
 * Generate a llama.cpp GBNF grammar constraining output to the HoloScript subset.
 * The result is deterministic (stable rule order) so it hashes and diffs cleanly.
 */
export function generateHoloScriptGbnf(options: HoloScriptGbnfOptions = {}): string {
  const objectKeywords = options.objectKeywords ?? DEFAULT_OBJECT_KEYWORDS;
  const primitiveShapes = options.primitiveShapes ?? DEFAULT_PRIMITIVE_SHAPES;
  const materialKeywords = options.materialKeywords ?? DEFAULT_MATERIAL_KEYWORDS;
  const requireDefinition = options.requireDefinition ?? true;

  const rootRepeat = requireDefinition ? '(def ws)+' : '(def ws)*';

  // Rule bodies. Terminals mirror the production lexer exactly (see file header).
  return [
    '# HoloScript constrained subset — generated by generateHoloScriptGbnf().',
    '# Constrains a llama.cpp model to emit syntactically-valid HoloScript',
    '# (keyword objects, primitive objects, material blocks; @traits + key:value',
    '# properties over number/string/boolean/null/array values). Terminals follow',
    '# the production lexer (composition/lexer.ts), not the looser tree-sitter grammar.',
    '',
    `root ::= ws ${rootRepeat}`,
    'def ::= object | material | primitive',
    '',
    'object ::= object-kw sp string ws traits block',
    'material ::= material-kw sp string ws traits block',
    'primitive ::= prim-shape (sp obj-id)? ws block',
    '',
    `object-kw ::= ${literalAlternation(objectKeywords)}`,
    `material-kw ::= ${literalAlternation(materialKeywords)}`,
    `prim-shape ::= ${literalAlternation(primitiveShapes)}`,
    'obj-id ::= string | ("#" ident) | ident',
    '',
    'block ::= "{" ws (member ws)* "}"',
    'member ::= trait | property',
    'traits ::= (trait ws)*',
    '',
    'trait ::= "@" ident trait-args?',
    'trait-args ::= "(" ws (arg (ws "," ws arg)*)? ws ")"',
    'arg ::= (ident ws ":" ws)? value',
    '',
    'property ::= ident ws ":" ws value (ws ",")?',
    '',
    'value ::= number | string | boolean | null | array',
    'array ::= "[" ws (value (ws "," ws value)*)? ws "]"',
    '',
    'number ::= "-"? [0-9]+ ("." [0-9]+)?',
    'boolean ::= "true" | "false"',
    'null ::= "null"',
    'string ::= "\\"" str-char* "\\""',
    'str-char ::= [^"\\\\] | escape',
    'escape ::= "\\\\" ( "\\"" | "\\\\" | "\'" | "n" | "t" | "r" )',
    'ident ::= [a-zA-Z_] [a-zA-Z0-9_]*',
    '',
    'sp ::= [ \\t]+',
    'ws ::= [ \\t\\n\\r]*',
    '',
  ].join('\n');
}

/** The canonical preset names accepted by `@llama_serve { grammar: "<preset>" }`. */
export const HOLOSCRIPT_GRAMMAR_PRESETS = ['holoscript', 'holoscript-subset'] as const;
export type HoloScriptGrammarPreset = (typeof HOLOSCRIPT_GRAMMAR_PRESETS)[number];

/** True when a `grammar:` value names a built-in HoloScript GBNF preset (vs an inline grammar). */
export function isHoloScriptGrammarPreset(value: string): value is HoloScriptGrammarPreset {
  return (HOLOSCRIPT_GRAMMAR_PRESETS as readonly string[]).includes(value);
}
