/**
 * IOSCompiler TrueDepth Face Tracking Tests (M.010.14)
 *
 * Verifies that the IOSCompiler emits correct Swift code for
 * face tracking traits (ARFaceAnchor, blendshapes, emotion detection, gaze, etc.).
 */

import { describe, it, expect, beforeEach } from 'vitest';
import { IOSCompiler } from './IOSCompiler';
import type { HoloComposition, HoloObjectDecl } from '../parser/HoloCompositionTypes';

describe('IOSCompiler — TrueDepth Face Tracking', () => {
  let compiler: IOSCompiler;

  beforeEach(() => {
    compiler = new IOSCompiler();
  });

  function createComposition(overrides: Partial<HoloComposition> = {}): HoloComposition {
    return {
      type: 'Composition',
      name: 'TestFaceScene',
      objects: [],
      templates: [],
      spatialGroups: [],
      lights: [],
      imports: [],
      timelines: [],
      audio: [],
      zones: [],
      transitions: [],
      conditionals: [],
      iterators: [],
      npcs: [],
      quests: [],
      abilities: [],
      dialogues: [],
      stateMachines: [],
      achievements: [],
      talentTrees: [],
      shapes: [],
      ...overrides,
    };
  }

  function createObject(name: string, traitNames: string[]): HoloObjectDecl {
    return {
      name,
      properties: [],
      traits: traitNames.map((t) => ({ name: t, args: [] })),
    } as unknown as HoloObjectDecl;
  }

  describe('faceTrackingFile presence', () => {
    it('should NOT emit faceTrackingFile when no face traits present', () => {
      const composition = createComposition({
        objects: [createObject('Cube', ['interactive'])],
      });
      const result = compiler.compile(composition);
      expect(result.faceTrackingFile).toBeUndefined();
    });

    it('should emit faceTrackingFile when face_track_truedepth trait is present', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_track_truedepth'])],
      });
      const result = compiler.compile(composition);
      expect(result.faceTrackingFile).toBeDefined();
      expect(typeof result.faceTrackingFile).toBe('string');
      expect(result.faceTrackingFile!.length).toBeGreaterThan(100);
    });

    it('should emit faceTrackingFile for any face_* trait', () => {
      const faceTraits = [
        'face_track_truedepth',
        'face_blendshapes',
        'face_mesh',
        'face_transform',
        'face_avatar_drive',
        'face_blendshape_mirror',
        'face_puppet',
        'face_retarget',
        'face_emotion_detect',
        'face_gaze_direction',
        'face_tongue_detect',
      ];

      for (const trait of faceTraits) {
        const composition = createComposition({
          objects: [createObject('Avatar', [trait])],
        });
        const result = compiler.compile(composition);
        expect(result.faceTrackingFile).toBeDefined();
      }
    });
  });

  describe('header and imports', () => {
    it('should emit ARKit import and header comment', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_track_truedepth'])],
      });
      const result = compiler.compile(composition);
      const file = result.faceTrackingFile!;
      expect(file).toContain('Auto-generated by HoloScript IOSCompiler');
      expect(file).toContain('TrueDepth Face Tracking');
      expect(file).toContain('import ARKit');
      expect(file).toContain('import SwiftUI');
      expect(file).toContain('import Foundation');
    });
  });

  describe('face_track_truedepth — ARSession setup', () => {
    it('should emit ARFaceTrackingConfiguration and isSupported check', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_track_truedepth'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('ARFaceTrackingConfiguration.isSupported');
      expect(file).toContain('ARFaceTrackingConfiguration()');
      expect(file).toContain('session.run(configuration)');
    });

    it('should emit FaceTrackingManager class with delegate', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_track_truedepth'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('FaceTrackingManager: NSObject, ObservableObject, ARSessionDelegate');
      expect(file).toContain('func startTracking()');
      expect(file).toContain('func stopTracking()');
    });
  });

  describe('face_blendshapes — 52 coefficients', () => {
    it('should emit blendShapes property and extraction', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_blendshapes'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('blendShapes: [ARFaceAnchor.BlendShapeLocation: NSNumber]');
      expect(file).toContain('faceAnchor.blendShapes');
    });
  });

  describe('face_mesh — 1220 vertices topology', () => {
    it('should access ARFaceAnchor.geometry', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_mesh'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('faceAnchor.geometry');
      expect(file).toContain('geometry.vertices.count');
      expect(file).toContain('faceVertexCount');
      expect(file).toContain('1220 vertices');
    });

    it('should set maximumNumberOfTrackedFaces when face_mesh present', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_mesh'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('configuration.maximumNumberOfTrackedFaces = 1');
    });
  });

  describe('face_transform — head position/orientation', () => {
    it('should extract faceAnchor.transform', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_transform'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('headTransform: simd_float4x4');
      expect(file).toContain('faceAnchor.transform');
    });
  });

  describe('face_avatar_drive — morph target mapping', () => {
    it('should emit driveAvatar method', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_avatar_drive'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('func driveAvatar(morphTargets: inout [String: Float])');
      expect(file).toContain('key.rawValue');
    });
  });

  describe('face_blendshape_mirror — 1:1 coefficient mapping', () => {
    it('should emit getBlendShapeCoefficients method', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_blendshape_mirror'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('func getBlendShapeCoefficients() -> [String: Float]');
      expect(file).toContain('Blendshape Mirror');
    });
  });

  describe('face_puppet — dedicated puppet mode', () => {
    it('should emit getPuppetMorphTargets method', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_puppet'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('Puppet Mode');
      expect(file).toContain('func getPuppetMorphTargets() -> [String: Float]');
    });
  });

  describe('face_retarget — non-human avatar topologies', () => {
    it('should emit retarget map and applyRetargeting', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_retarget'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('retargetMap');
      expect(file).toContain('applyRetargeting');
      expect(file).toContain('retargetedBlendShapes');
      expect(file).toContain('mapping.scale');
    });
  });

  describe('face_emotion_detect — emotion from blendshape combos', () => {
    it('should emit DetectedEmotion enum and detectEmotion method', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_emotion_detect'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('enum DetectedEmotion: String, CaseIterable');
      expect(file).toContain('case happy');
      expect(file).toContain('case sad');
      expect(file).toContain('case surprised');
      expect(file).toContain('case angry');
      expect(file).toContain('case neutral');
    });

    it('should derive happy from mouthSmile > 0.5', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_emotion_detect'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('.mouthSmileLeft');
      expect(file).toContain('.mouthSmileRight');
      expect(file).toContain('emotion = .happy');
    });

    it('should derive surprised from eyeWide + jawOpen', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_emotion_detect'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('.eyeWideLeft');
      expect(file).toContain('.jawOpen');
      expect(file).toContain('emotion = .surprised');
    });

    it('should derive angry from browDown + mouthPress', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_emotion_detect'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('.browDownLeft');
      expect(file).toContain('.mouthPressLeft');
      expect(file).toContain('emotion = .angry');
    });
  });

  describe('face_gaze_direction — lookAtPoint', () => {
    it('should extract lookAtPoint from ARFaceAnchor', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_gaze_direction'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('gazeDirection: simd_float3');
      expect(file).toContain('faceAnchor.lookAtPoint');
    });
  });

  describe('face_tongue_detect — tongueOut blendshape', () => {
    it('should check tongueOut blendshape', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_tongue_detect'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('.tongueOut');
      expect(file).toContain('isTongueOut');
    });
  });

  describe('SwiftUI Preview', () => {
    it('should emit SwiftUI preview with blendshape list', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_blendshapes'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('FaceTrackingPreview: View');
      expect(file).toContain('@StateObject');
      expect(file).toContain('onAppear { manager.startTracking() }');
      expect(file).toContain('onDisappear { manager.stopTracking() }');
      expect(file).toContain('ScrollView');
      expect(file).toContain('ProgressView');
    });

    it('should include emotion display when face_emotion_detect is present', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_emotion_detect'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('currentEmotion.rawValue');
    });

    it('should include gaze display when face_gaze_direction is present', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_gaze_direction'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('gazeDirection.x');
    });

    it('should include tongue display when face_tongue_detect is present', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_tongue_detect'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('Tongue Out');
    });

    it('should include vertex count display when face_mesh is present', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_mesh'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('Face Vertices');
    });

    it('should emit #Preview macro', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_track_truedepth'])],
      });
      const file = compiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('#Preview');
      expect(file).toContain('FaceTrackingPreview()');
    });
  });

  describe('combined traits', () => {
    it('should emit all sections when all face traits are present', () => {
      const composition = createComposition({
        objects: [
          createObject('Avatar', [
            'face_track_truedepth',
            'face_blendshapes',
            'face_mesh',
            'face_transform',
            'face_avatar_drive',
            'face_blendshape_mirror',
            'face_puppet',
            'face_retarget',
            'face_emotion_detect',
            'face_gaze_direction',
            'face_tongue_detect',
          ]),
        ],
      });
      const file = compiler.compile(composition).faceTrackingFile!;

      // All sections present
      expect(file).toContain('ARFaceTrackingConfiguration');
      expect(file).toContain('blendShapes');
      expect(file).toContain('faceVertexCount');
      expect(file).toContain('headTransform');
      expect(file).toContain('driveAvatar');
      expect(file).toContain('getBlendShapeCoefficients');
      expect(file).toContain('getPuppetMorphTargets');
      expect(file).toContain('applyRetargeting');
      expect(file).toContain('detectEmotion');
      expect(file).toContain('gazeDirection');
      expect(file).toContain('isTongueOut');
      expect(file).toContain('DetectedEmotion');
    });

    it('should use custom className from options', () => {
      const customCompiler = new IOSCompiler({ className: 'MyAvatar' });
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_track_truedepth'])],
      });
      const file = customCompiler.compile(composition).faceTrackingFile!;
      expect(file).toContain('MyAvatarFaceTrackingManager');
      expect(file).toContain('MyAvatarFaceTrackingPreview');
    });
  });

  describe('does not affect other output files', () => {
    it('should still emit viewFile, sceneFile, stateFile, infoPlist', () => {
      const composition = createComposition({
        objects: [createObject('Avatar', ['face_track_truedepth'])],
      });
      const result = compiler.compile(composition);
      expect(result.viewFile).toBeDefined();
      expect(result.sceneFile).toBeDefined();
      expect(result.stateFile).toBeDefined();
      expect(result.infoPlist).toBeDefined();
    });
  });
});
