/**
 * @holoscript/core/compiler — Native 2D Compiler Target
 *
 * Compiles HoloScript objects with Native 2D traits (@panel, @layout, @button, etc.)
 * into flat, performant HTML/Tailwind strings or React (.tsx) components.
 *
 * Supports '--format react' vs default HTML string generation.
 */

import { CompilerBase, type BaseCompilerOptions } from './CompilerBase';
import { readJson } from '../errors/safeJsonParse';
import type {
  HoloComposition,
  HoloObjectDecl,
  HoloUIElement,
} from '../parser/HoloCompositionTypes';

export interface Native2DCompilerOptions extends BaseCompilerOptions {
  /** Output format: raw html/css string or full React .tsx component */
  format?: 'html' | 'react';
  /** Map @holoscript/ui components instead of raw HTML tags */
  useUIComponents?: boolean;
  /** Slot imports: map of slot name → { component, importPath } */
  slots?: Record<string, { component: string; importPath: string }>;
}

export class Native2DCompiler extends CompilerBase {
  protected readonly compilerName = 'Native2DCompiler';

  // @ts-expect-error During migration
  compile(
    composition: HoloComposition,
    agentToken: string,
    outputPath?: string,
    options?: Native2DCompilerOptions
  ): string | any {
    // 1. Validate permissions
    this.validateCompilerAccess(agentToken, outputPath);

    const isReact = options?.format === 'react';

    // 2. Discover UI elements (either in composition.ui, or standard objects)
    const elements = composition.ui?.elements || composition.objects || [];

    // 3. Generate markup
    if (isReact) {
      const code = this.generateReactComponent(composition.name, elements, composition, options);
      return this.withTripleOutputIfRequested(composition, code, options);
    }
    const code = this.generateHTMLPage(composition.name, elements, composition);
    return this.withTripleOutputIfRequested(composition, code, options);
  }

  // ============================================================================
  // REACT GENERATION
  // ============================================================================

  /** Collected during node traversal — used to generate imports and hooks */
  private _slotImports: Map<string, { component: string; importPath: string }> = new Map();
  private _uiImports: Set<string> = new Set();
  private _stateFields: Map<string, unknown> = new Map();
  private _fetchCalls: Array<{ name: string; endpoint: string; method: string }> = [];
  private _options: Native2DCompilerOptions = {};

  generateReactComponent(
    name: string,
    objects: HoloObjectDecl[] | HoloUIElement[] | Record<string, unknown>[],
    composition?: HoloComposition,
    options?: Native2DCompilerOptions
  ): string {
    // Reset per-compilation state
    this._slotImports.clear();
    this._uiImports.clear();
    this._stateFields.clear();
    this._fetchCalls = [];
    this._options = options || {};

    const safeName = name.replace(/[^a-zA-Z0-9]/g, '');

    // Extract state from composition
    if (composition?.state?.properties) {
      for (const prop of composition.state.properties) {
        this._stateFields.set(prop.key, prop.value ?? null);
      }
    }

    // Generate JSX from objects
    const jsx = objects
      .map((obj) => this.generateReactNode(obj as unknown as Record<string, unknown>))
      .join('\n        ');

    // Build imports
    const imports: string[] = [];
    const reactImports = new Set<string>();
    if (this._stateFields.size > 0) reactImports.add('useState');
    if (this._fetchCalls.length > 0) reactImports.add('useEffect');
    imports.push(
      reactImports.size > 0
        ? `import React, { ${[...reactImports].join(', ')} } from 'react';`
        : `import React from 'react';`
    );

    if (this._uiImports.size > 0) {
      imports.push(`import { ${[...this._uiImports].join(', ')} } from '@holoscript/ui';`);
    }

    for (const [, slot] of this._slotImports) {
      imports.push(`import { ${slot.component} } from '${slot.importPath}';`);
    }

    // Build state hooks
    const stateHooks: string[] = [];
    for (const [key, value] of this._stateFields) {
      const capitalKey = key.charAt(0).toUpperCase() + key.slice(1);
      const initValue = JSON.stringify(value);
      stateHooks.push(
        `  const [${key}, set${capitalKey}] = useState(${initValue === undefined ? 'null' : initValue});`
      );
    }

    // Build fetch effects
    const fetchEffects: string[] = [];
    for (const f of this._fetchCalls) {
      fetchEffects.push(`  useEffect(() => {
    fetch(\`${f.endpoint}\`${f.method !== 'GET' ? `, { method: '${f.method}' }` : ''})
      .then(r => r.json())
      .then(set${f.name.charAt(0).toUpperCase() + f.name.slice(1)})
      .catch(console.error);
  }, []);`);
    }

    return `${imports.join('\n')}

// @generated by HoloScript Native2DCompiler — DO NOT EDIT
export function ${safeName}Component() {
${stateHooks.join('\n')}
${fetchEffects.join('\n')}

  return (
    <div className="holoscript-2d-root w-full h-full">
      ${jsx}
    </div>
  );
}

export default ${safeName}Component;
`;
  }

  private generateReactNode(obj: Record<string, unknown>): string {
    const traits = this.extractTraits(obj);

    // @slot trait: mount a hand-written React component
    if (traits.slot) {
      const slotName = traits.slot.name || (obj as Record<string, unknown>).name || 'Slot';
      const configuredSlot = this._options.slots?.[String(slotName)];
      const component = traits.slot.component || configuredSlot?.component || slotName;
      const importPath =
        traits.slot.import || configuredSlot?.importPath || `@/components/${component}`;
      this._slotImports.set(slotName, { component, importPath });
      const propsStr = traits.slot.props ? ` {...${JSON.stringify(traits.slot.props)}}` : '';
      return `<div data-holo-slot="${slotName}">
        <${component}${propsStr} />
      </div>`;
    }

    // @fetch trait: register a fetch call and bind to state
    if (traits.fetch) {
      const name = traits.fetch.into || 'data';
      const endpoint = traits.fetch.endpoint || '/api/data';
      const method = traits.fetch.method || 'GET';
      this._fetchCalls.push({ name, endpoint, method });
      if (!this._stateFields.has(name)) {
        this._stateFields.set(name, null);
      }
    }

    let tag =
      traits.theme?.tag ||
      traits.panel?.tag ||
      (typeof obj.type === 'string' ? obj.type.toLowerCase() : undefined) ||
      'div';

    // Default mapping for custom semantic keywords used in HoloScript (nav, section, container)
    if (
      [
        'nav',
        'section',
        'main',
        'footer',
        'form',
        'style',
        'a',
        'header',
        'h1',
        'h2',
        'h3',
      ].includes(tag)
    ) {
      // Keep structural and explicit tags
    } else if (tag === 'container') {
      tag = 'div';
    } else if (traits.link || tag === 'link') {
      tag = 'a';
    } else if (traits.button || tag === 'button') {
      tag = 'button';
    } else if (traits.image || tag === 'image') {
      tag = 'img';
    } else if (traits.input || tag === 'input') {
      tag = 'input';
    } else if (traits.text || tag === 'text') {
      tag = this.mapTextVariantToTag(traits.text?.variant || 'body');
    } else {
      tag = 'div';
    }

    const styles = this.buildStyles(traits);
    const classes = this.buildClasses(traits);
    let props = ``;

    if (traits.theme?.className) {
      classes.push(traits.theme.className);
    }
    if (traits.theme?.id) {
      props += ` id="${traits.theme.id}"`;
    }

    const combinedStyles: Record<string, string> = { ...styles };
    if (traits.theme?.style) {
      traits.theme.style.split(';').forEach((rule: string) => {
        const [key, ...valueParts] = rule.split(':');
        const value = valueParts.join(':');
        if (key && value) {
          const camelKey = key.trim().replace(/-([a-z])/g, (g: string) => g[1].toUpperCase());
          combinedStyles[camelKey] = value.trim();
        }
      });
    }

    if (Object.keys(combinedStyles).length > 0) {
      props += ` style={${JSON.stringify(combinedStyles)}}`;
    }
    if (classes.length > 0) {
      props += ` className="${classes.join(' ')}"`;
    }
    if (traits.theme?.attributes) {
      try {
        const parsedAttrs = readJson(traits.theme.attributes) as Record<string, string>;
        for (const [key, value] of Object.entries(parsedAttrs)) {
          props += ` ${key}="${value}"`;
        }
      } catch (e) {
        // Intentionally swallowed: invalid theme attributes JSON should not break rendering
      }
    }

    // Interactive props
    if (traits.button?.onClick || traits.form?.onSubmit) {
      const action = traits.button?.onClick || traits.form?.onSubmit;
      if (action) {
        const cleanAction = action.replace(/["']/g, "'");
        // Simple mapping for demo prototypes
        if (cleanAction.includes('navigate')) {
          props += ` onClick={() => ${cleanAction}}`;
        } else if (cleanAction.includes('submit')) {
          // Wrap in an arrow so the handler is PASSED, not invoked during render.
          // `onSubmit={submitFn(e)}` calls submitFn at render time (e undefined);
          // `onSubmit={(e) => submitFn(e)}` is the correct event-handler form.
          props += ` onSubmit={(e) => ${cleanAction}}`;
        } else if (cleanAction.includes('window.open')) {
          props += ` onClick={() => ${cleanAction}}`;
        } else {
          props += ` onClick={() => console.log('${cleanAction}')}`;
        }
      }
    }

    // Media & Input props
    if (traits.image?.src) props += ` src="${traits.image.src}"`;
    if (traits.image?.alt) props += ` alt="${traits.image.alt}"`;
    if (traits.link?.href) props += ` href="${traits.link.href}"`;
    if (traits.input?.placeholder) props += ` placeholder="${traits.input.placeholder}"`;
    if (traits.input?.type) props += ` type="${traits.input.type}"`;
    if (traits.input?.required) props += ` required`;
    if (traits.button?.type) props += ` type="${traits.button.type}"`;

    const childrenMarkup = ((obj.children || obj.objects || []) as Record<string, unknown>[])
      .map((child: Record<string, unknown>) => this.generateReactNode(child))
      .join('\n');

    const content =
      traits.text?.content || traits.button?.content || traits.link?.content || traits.icon?.name;
    let safeContent = '';
    if (content) {
      safeContent = `{\`${content.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`}`;
    }

    if (tag === 'style') {
      const escapedStyle = (content || '').replace(/`/g, '\\`').replace(/\$/g, '\\$');
      return `<style dangerouslySetInnerHTML={{ __html: \`${escapedStyle}\` }} />`;
    }

    if (tag === 'img' || tag === 'input') {
      return `<${tag}${props} />`;
    }

    return `<${tag}${props}>
      ${safeContent}
      ${childrenMarkup}
    </${tag}>`;
  }

  // ============================================================================
  // HTML GENERATION
  // ============================================================================

  private generateHTMLPage(name: string, objects: unknown[], composition: HoloComposition): string {
    const content = objects.map((obj) => this.generateHTMLNode(obj)).join('\n      ');

    let bgColor = '#ffffff';
    let color = '#000000';

    // Extract background environment theme
    if (composition.environment?.properties) {
      const themeProp = composition.environment.properties.find((p) => p.key === 'theme');
      const bgProp = composition.environment.properties.find((p) => p.key === 'backgroundColor');
      if (
        themeProp?.value === 'dark' ||
        (
          composition as unknown as {
            traits?: Array<{ name: string; config?: { dark?: boolean } }>;
          }
        ).traits?.some((t) => t.name === 'theme' && t.config?.dark)
      ) {
        bgColor = (bgProp?.value as string) || '#050510';
        color = '#ffffff';
      }
    }

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${name}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
      body { margin: 0; padding: 0; background-color: ${bgColor}; color: ${color}; font-family: system-ui, -apple-system, sans-serif; }
      /* Basic resets and custom trait animations to mirror React Framer variants */
      .glow-btn:hover { box-shadow: 0 0 15px rgba(255,255,255,0.5); }
      .lift-card { transition: transform 0.2s ease, box-shadow 0.2s ease; }
      .lift-card:hover { transform: translateY(-4px); box-shadow: 0 10px 20px rgba(0,0,0,0.2); }
      [data-holo-template] { display: none; }
    </style>
</head>
<body>
    <div id="holoscript-native-root">
      ${content}
    </div>
    <script>
      function navigate(path) { window.location.href = path; }
      function submitNewsletter(e) { e.preventDefault(); alert('Subscribed!'); }
    </script>
    <script>
      /* HoloScript Native2D — hydration-free live list-binding runtime (@fetch).
         For each [data-holo-fetch] container: fetch the endpoint, then clone the
         [data-holo-template] child per item and interpolate {{field}} (dotted paths
         supported) into text + attributes. Plain DOM — no framework, no hydration. */
      (function () {
        function getPath(o, p) { return p.split('.').reduce(function (a, k) { return a == null ? a : a[k]; }, o); }
        function interp(s, item) { return s.replace(/\{\{([^}]+)\}\}/g, function (_, k) { var v = getPath(item, k.trim()); return v == null ? '' : String(v); }); }
        function fill(node, item) {
          if (node.attributes) { for (var i = 0; i < node.attributes.length; i++) { var a = node.attributes[i]; if (a.value.indexOf('{{') >= 0) a.value = interp(a.value, item); } }
          (node.childNodes || []).forEach(function (c) {
            if (c.nodeType === 3) { if (c.nodeValue.indexOf('{{') >= 0) c.nodeValue = interp(c.nodeValue, item); }
            else if (c.nodeType === 1) fill(c, item);
          });
        }
        function render(el) {
          var url = el.getAttribute('data-holo-fetch'); var method = el.getAttribute('data-holo-method') || 'GET';
          var tpl = el.querySelector('[data-holo-template]'); if (!tpl) return;
          fetch(url, { method: method }).then(function (r) { return r.json(); }).then(function (d) {
            var items = (d && (d.items || d.actions)) || (Array.isArray(d) ? d : []);
            items.forEach(function (item) {
              var n = tpl.cloneNode(true); n.removeAttribute('data-holo-template'); n.style.display = '';
              fill(n, item); el.appendChild(n);
            });
            var into = el.getAttribute('data-holo-into');
            if (into) { document.querySelectorAll('[data-holo-count-for="' + into + '"]').forEach(function (c) { c.textContent = String(items.length); }); }
          }).catch(function (e) { console.error('[holo-fetch]', url, e); });
        }
        function boot() { document.querySelectorAll('[data-holo-fetch]').forEach(render); }
        if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot); else boot();
      })();
    </script>
</body>
</html>`;
  }

  /** Build a semantic HTML block for @semantic_entity / @semantic_layout traits.
   *
   * HoloScript's `generate_semantic_ui` tool emits 3D-world-style objects
   * (`mesh`, `text`, `plane`) annotated with semantic traits:
   *   @semantic_entity(stock_table)                     → config._arg0 = entity name
   *   @semantic_layout(table, columns:["a","b","c"])    → config._arg0 = layout type
   *   @content("Inventory Dashboard")                   → config._arg0 = text
   *   @color("#16213e")                                 → config._arg0 = bg colour
   *
   * Without this handler every semantic object falls through to `tag = 'div'` with
   * no content.  This method maps the semantic vocabulary to real HTML elements so
   * the compiled page is actually perceivable.
   */
  private generateSemanticHTMLBlock(traits: Record<string, any>): string | null {
    // semantic_layout supports both positional arg (_arg0) and named key (flow/type/layout).
    // semantic_entity supports both positional arg (_arg0) and named key (type/name/entity).
    // Both config shapes are emitted depending on how traits are authored in .holo source.
    const layoutType = (
      traits.semantic_layout?._arg0 ||
      traits.semantic_layout?.flow ||
      traits.semantic_layout?.layout ||
      traits.semantic_layout?.type
    ) as string | undefined;
    const entityName = (
      traits.semantic_entity?._arg0 ||
      traits.semantic_entity?.type ||
      traits.semantic_entity?.name ||
      traits.semantic_entity?.entity
    ) as string | undefined;
    const bgColor = traits.color?._arg0 as string | undefined;
    const textContent = traits.content?._arg0 as string | undefined;

    if (!layoutType && !entityName) return null;

    const styleAttr = bgColor
      ? ` style="background-color:${bgColor};padding:1rem;border-radius:0.5rem;margin-bottom:1rem;"`
      : ` style="padding:1rem;margin-bottom:1rem;"`;

    // ── TABLE layout ─────────────────────────────────────────────────────────────
    // Match explicit 'table' layout or entity names that imply tabular data (stock_table, etc.)
    const isTableEntity =
      !!entityName &&
      (entityName.includes('table') || entityName.includes('grid') || entityName.includes('list'));
    if (layoutType === 'table' || (isTableEntity && !layoutType)) {
      const columns = (traits.semantic_layout?.columns as string[] | undefined) || [];
      const headerCells = columns
        .map((col) => `<th style="padding:0.5rem 1rem;text-align:left;border-bottom:2px solid #334;">${col}</th>`)
        .join('');
      // Render two sample rows so the table body is non-empty and selectors match.
      const sampleRow = columns
        .map((col) => `<td style="padding:0.5rem 1rem;">${col}</td>`)
        .join('');
      return `<div${styleAttr} data-holo-semantic="table" data-holo-entity="${entityName || ''}">
  <table style="width:100%;border-collapse:collapse;">
    <thead><tr>${headerCells}</tr></thead>
    <tbody>
      <tr>${sampleRow}</tr>
    </tbody>
  </table>
</div>`;
    }

    // ── FORM layout ─────────────────────────────────────────────────────────────
    if (layoutType === 'form' || (entityName && entityName.includes('form'))) {
      const fields = (traits.semantic_layout?.fields as string[] | undefined) || [];
      const inputs = fields
        .map(
          (f) =>
            `<div style="margin-bottom:0.5rem;">` +
            `<label style="display:block;margin-bottom:0.25rem;">${f}</label>` +
            `<input type="text" name="${f}" placeholder="${f}" ` +
            `style="width:100%;padding:0.4rem 0.6rem;border:1px solid #556;border-radius:0.25rem;background:#111;color:#eee;" />` +
            `</div>`
        )
        .join('\n');
      return `<div${styleAttr} data-holo-semantic="form" data-holo-entity="${entityName || ''}">
  <form onsubmit="return false;">
    ${inputs}
    <button type="submit" style="padding:0.4rem 1rem;border-radius:0.25rem;background:#3b82f6;color:#fff;border:none;cursor:pointer;">Submit</button>
  </form>
</div>`;
    }

    // ── ALERT LIST layout ────────────────────────────────────────────────────────
    if (layoutType === 'alert_list') {
      const filterLabel = (traits.semantic_layout?.filter as string | undefined) || '';
      return `<div${styleAttr} data-holo-semantic="alert_list" data-holo-entity="${entityName || ''}">
  <ul style="list-style:none;padding:0;margin:0;" data-holo-filter="${filterLabel}">
    <li style="padding:0.4rem 0.8rem;border-bottom:1px solid #446;">(no alerts)</li>
  </ul>
</div>`;
    }

    // ── DASHBOARD GRID / generic container ───────────────────────────────────────
    if (layoutType === 'dashboard_grid' || layoutType) {
      return `<div${styleAttr} data-holo-semantic="${layoutType}" data-holo-entity="${entityName || ''}"></div>`;
    }

    // ── Entity with @content (e.g. title text or button) ────────────────────────
    if (entityName && textContent) {
      const isButton =
        entityName.includes('button') || entityName.includes('btn') || entityName.includes('submit');
      if (isButton) {
        return `<div${styleAttr} data-holo-entity="${entityName}">` +
          `<button type="button" style="padding:0.4rem 1rem;border-radius:0.25rem;background:#3b82f6;color:#fff;border:none;cursor:pointer;">${textContent}</button>` +
          `</div>`;
      }
      return `<div${styleAttr} data-holo-entity="${entityName}"><span>${textContent}</span></div>`;
    }

    // ── Entity-only (no layout, no content) — named div ─────────────────────────
    if (entityName) {
      return `<div${styleAttr} data-holo-entity="${entityName}"></div>`;
    }

    return null;
  }

  private generateHTMLNode(obj: unknown, opts: { asTemplate?: boolean } = {}): string {
    const node = obj as Record<string, unknown>;
    const traits = this.extractTraits(obj);
    const nodeType = typeof node.type === 'string' ? node.type.toLowerCase() : undefined;

    // ── Semantic entity/layout: use the dedicated semantic renderer ──────────────
    if (traits.semantic_entity || traits.semantic_layout) {
      const block = this.generateSemanticHTMLBlock(traits);
      if (block) return block;
    }

    let tag = traits.theme?.tag || traits.panel?.tag || nodeType || 'div';

    // Keyword extraction for parsing output logic
    if (
      [
        'nav',
        'section',
        'main',
        'footer',
        'form',
        'style',
        'a',
        'header',
        'h1',
        'h2',
        'h3',
      ].includes(tag)
    ) {
      // Keep structural and explicit tags
    } else if (tag === 'container') {
      tag = 'div';
    } else if (traits.link || tag === 'link') {
      tag = 'a';
    } else if (traits.button || tag === 'button') {
      tag = 'button';
    } else if (traits.image || tag === 'image') {
      tag = 'img';
    } else if (traits.input || tag === 'input') {
      tag = 'input';
    } else if (traits.text || tag === 'text') {
      tag = this.mapTextVariantToTag(traits.text?.variant || 'body');
    } else {
      tag = 'div';
    }

    const styles = this.buildStyles(traits);
    const classes = this.buildClasses(traits);
    let props = ``;

    if (traits.theme?.className) {
      classes.push(traits.theme.className);
    }
    if (traits.theme?.id) {
      props += ` id="${traits.theme.id}"`;
    }

    if (Object.keys(styles).length > 0 || traits.theme?.style) {
      let styleStr = Object.entries(styles)
        .map(([k, v]) => `${this.camelToKebab(k)}: ${v}`)
        .join('; ');
      if (traits.theme?.style) {
        styleStr += (styleStr ? '; ' : '') + traits.theme.style;
      }
      props += ` style="${styleStr}"`;
    }

    if (classes.length > 0) {
      props += ` class="${classes.join(' ')}"`;
    }
    if (traits.theme?.attributes) {
      try {
        const parsedAttrs = readJson(traits.theme.attributes) as Record<string, string>;
        for (const [key, value] of Object.entries(parsedAttrs)) {
          props += ` ${key}="${value}"`;
        }
      } catch (e) {
        // Intentionally swallowed: invalid theme attributes JSON should not break rendering
      }
    }

    // Input attributes
    if (traits.button?.onClick) props += ` onclick="${traits.button.onClick}"`;
    if (traits.form?.onSubmit) props += ` onsubmit="${traits.form.onSubmit}"`;
    if (traits.image?.src) props += ` src="${traits.image.src}"`;
    if (traits.image?.alt) props += ` alt="${traits.image.alt}"`;
    if (traits.link?.href) props += ` href="${traits.link.href}"`;
    if (traits.input?.placeholder) props += ` placeholder="${traits.input.placeholder}"`;
    if (traits.input?.type) props += ` type="${traits.input.type}"`;
    if (traits.input?.required) props += ` required`;

    // Live data-binding (hydration-free): a @fetch container renders its first
    // child as a row template; the vanilla bootstrap in generateHTMLPage clones it
    // per fetched item and interpolates {{field}} tokens. No React, no hydration —
    // so it cannot hit the Next/React app-router tunnel-hydration bug class.
    if (opts.asTemplate) props += ` data-holo-template`;
    // @count_of { source: "<into>" } → element whose text the runtime sets to the
    // live item count of the matching @fetch container (hydration-free live counter).
    if (traits.count_of?.source) props += ` data-holo-count-for="${traits.count_of.source}"`;
    if (traits.fetch) {
      const fEndpoint = traits.fetch.endpoint || '/api/data';
      const fInto = traits.fetch.into || 'data';
      const fMethod = traits.fetch.method || 'GET';
      props += ` data-holo-fetch="${fEndpoint}" data-holo-into="${fInto}" data-holo-method="${fMethod}"`;
    }

    const children = (node.children || node.objects || []) as unknown[];
    const childrenMarkup = children
      .map((child: unknown, i: number) =>
        this.generateHTMLNode(child, { asTemplate: !!traits.fetch && i === 0 })
      )
      .join('\n');

    const content =
      traits.text?.content || traits.button?.content || traits.link?.content || traits.icon?.name;

    if (tag === 'img' || tag === 'input') {
      return `<${tag}${props}>`;
    }

    return `<${tag}${props}>
      ${content ? content : ''}
      ${childrenMarkup}
    </${tag}>`;
  }

  // ============================================================================
  // UTILITIES
  // ============================================================================

  private extractTraits(obj: unknown): Record<string, any> {
    const map: Record<string, any> = {};
    const node = obj as { traits?: Array<{ name: string; config?: unknown }> };
    if (!node.traits) return map;
    for (const t of node.traits) {
      map[t.name] = t.config || {};

      // Special case for primitive traits like @tailwind which might be passed as a single string
      // instead of an object if used like @tailwind("bg-black")
      if (t.name === 'tailwind' && typeof t.config === 'string') {
        map[t.name] = { classes: t.config };
      }
    }
    return map;
  }

  private mapTextVariantToTag(variant: string): string {
    switch (variant) {
      case 'h1':
        return 'h1';
      case 'h2':
        return 'h2';
      case 'h3':
        return 'h3';
      case 'subtitle':
        return 'h4';
      case 'caption':
        return 'span';
      case 'emoji':
        return 'span';
      default:
        return 'p';
    }
  }

  private buildStyles(traits: Record<string, any>): Record<string, string> {
    const styles: Record<string, string> = {};
    const layout = traits.layout;
    const theme = traits.theme;

    if (layout) {
      if (layout.flex) {
        styles.display = 'flex';
        styles.flexDirection = layout.flex === 'row' ? 'row' : 'column';
      }
      if (layout.grid) {
        styles.display = 'grid';
        styles.gridTemplateColumns = `repeat(${layout.columns || 1}, minmax(0, 1fr))`;
      }
      if (layout.justify) styles.justifyContent = layout.justify;
      if (layout.align) styles.alignItems = layout.align;
      if (layout.gap) styles.gap = typeof layout.gap === 'number' ? `${layout.gap}px` : layout.gap;
      if (layout.padding)
        styles.padding =
          typeof layout.padding === 'number' ? `${layout.padding}px` : layout.padding;
    }

    if (theme) {
      if (theme.backgroundColor) styles.backgroundColor = theme.backgroundColor;
      if (theme.color) styles.color = theme.color;
      if (theme.padding)
        styles.padding = typeof theme.padding === 'number' ? `${theme.padding}px` : theme.padding;
      if (theme.borderRadius)
        styles.borderRadius =
          typeof theme.borderRadius === 'number' ? `${theme.borderRadius}px` : theme.borderRadius;
      if (theme.border) styles.border = theme.border;
      if (theme.borderTop) styles.borderTop = theme.borderTop;
    }

    if (traits.text) {
      if (traits.text.align) styles.textAlign = traits.text.align;
      if (traits.text.maxWidth)
        styles.maxWidth =
          typeof traits.text.maxWidth === 'number'
            ? `${traits.text.maxWidth}px`
            : traits.text.maxWidth;
      if (traits.text.weight) styles.fontWeight = traits.text.weight;
    }

    return styles;
  }

  private buildClasses(traits: Record<string, any>): string[] {
    const classes: string[] = [];

    if (traits.text) {
      if (traits.text.variant === 'h1') classes.push('text-5xl font-bold tracking-tight');
      if (traits.text.variant === 'h2') classes.push('text-3xl font-bold');
      if (traits.text.variant === 'h3') classes.push('text-xl font-semibold');
      if (traits.text.variant === 'subtitle') classes.push('text-xl text-gray-400');
      if (traits.text.variant === 'caption') classes.push('text-sm text-gray-500');
      if (traits.text.variant === 'emoji') classes.push('text-2xl');
    }

    if (traits.button) {
      classes.push('px-4 py-2 rounded-lg font-medium transition-all');
      if (traits.button.variant === 'primary')
        classes.push('bg-blue-600 hover:bg-blue-700 text-white');
      if (traits.button.variant === 'outline')
        classes.push('border border-gray-600 hover:bg-gray-800 text-white');
      if (traits.button.variant === 'ghost')
        classes.push('hover:bg-gray-800 text-gray-300 hover:text-white');
      if (traits.button.variant === 'glow')
        classes.push('bg-indigo-600 text-white glow-btn hover:bg-indigo-500');

      if (traits.button.size === 'lg') classes.push('px-6 py-3 text-lg');
      if (traits.button.size === 'sm') classes.push('px-3 py-1 text-sm');
    }

    if (traits.card) {
      if (traits.card.shadow === 'md') classes.push('shadow-md');
      if (traits.card.shadow === 'lg') classes.push('shadow-lg');
      if (traits.card.hover === 'glow') classes.push('lift-card');
    }

    if (traits.input) {
      classes.push(
        'px-4 py-2 rounded-lg border border-gray-700 bg-gray-900 text-white focus:ring-2 focus:ring-indigo-500 outline-none'
      );
    }

    if (traits.tailwind?.classes) {
      classes.push(traits.tailwind.classes);
    }

    return classes;
  }

  private camelToKebab(str: string): string {
    return str.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
  }
}
