/**
 * HoloScript NextJS Compiler
 *
 * Compiles .holo compositions into Next.js App Router page files.
 * Wraps Native2DCompiler (format: 'react') with Next.js conventions:
 * - 'use client' directive
 * - next/link, next/navigation imports
 * - Metadata exports from @metadata trait
 * - Layout generation from @layout trait
 * - @page trait for route configuration
 *
 * @module NextJSCompiler
 */

import { Native2DCompiler, type Native2DCompilerOptions } from './Native2DCompiler';
import type { HoloComposition, HoloObjectTrait } from '../parser/HoloCompositionTypes';

export interface NextJSCompilerOptions {
  outputDir?: string;
  slots?: Record<string, { component: string; importPath: string }>;
}

export interface NextJSCompileResult {
  /** Relative path for the generated file (e.g., 'pipeline/page.tsx') */
  path: string;
  /** Generated file content */
  code: string;
}

/**
 * Extract a trait config from a composition's root-level traits.
 */
function findTrait(composition: HoloComposition, traitName: string): Record<string, unknown> | null {
  const traits = (composition as unknown as { traits?: HoloObjectTrait[] }).traits;
  if (!traits) return null;
  const found = traits.find((t) => t.name === traitName);
  return found?.config as Record<string, unknown> || null;
}

/**
 * Compile a HoloComposition to a Next.js App Router page.
 */
export function compileToNextJS(
  composition: HoloComposition,
  options: NextJSCompilerOptions = {}
): NextJSCompileResult {
  const compiler = new Native2DCompiler();

  // Extract @page and @metadata traits
  const pageTrait = findTrait(composition, 'page');
  const metaTrait = findTrait(composition, 'metadata');

  const route = (pageTrait?.route as string) || `/${composition.name.toLowerCase().replace(/\s+/g, '-')}`;
  const isClient = pageTrait?.client !== false; // default to client component

  // Build slot map from options + any @slot traits in the composition
  const slotMap = options.slots || {};

  // Handle pure redirect pages
  if (pageTrait?.redirect) {
    const redirectUrl = pageTrait.redirect as string;
    const isExternal = redirectUrl.startsWith('http');
    const redirectType = isExternal ? "'replace'" : "'push'"; // Or 'replace' for both

    const lines: string[] = [
      `// @generated by HoloScript NextJSCompiler — DO NOT EDIT`,
      `import { redirect } from 'next/navigation';`,
      ``,
      `export default function RedirectPage() {`,
      `  redirect(${JSON.stringify(redirectUrl)});`,
      `}`,
    ];

    if (metaTrait) {
      const metaEntries: string[] = [];
      if (metaTrait.title) metaEntries.push(`  title: ${JSON.stringify(metaTrait.title)},`);
      if (metaTrait.description) metaEntries.push(`  description: ${JSON.stringify(metaTrait.description)},`);

      lines.push('');
      lines.push(`export const metadata = {`);
      lines.push(metaEntries.join('\n'));
      lines.push(`};`);
    }

    const routePath = route.replace(/^\//, '') || 'index';
    return {
      path: `${routePath}/page.tsx`,
      code: lines.join('\n'),
    };
  }

  // Compile the React component via Native2DCompiler
  const compilerOptions: Native2DCompilerOptions = {
    format: 'react',
    useUIComponents: true,
    slots: slotMap,
  };

  const elements = composition.ui?.elements || composition.objects || [];
  const componentCode = compiler.generateReactComponent(
    composition.name,
    elements,
    composition,
    compilerOptions
  );

  // Next.js App Router page modules should not export arbitrary named values.
  // Normalize generated component code to keep only default export + metadata.
  const pageSafeComponentCode = componentCode.replace(
    /export\s+function\s+([A-Za-z0-9_]+)\s*\(/,
    'function $1('
  );

  // Wrap in Next.js conventions
  const lines: string[] = [];

  // 'use client' directive
  if (isClient) {
    lines.push("'use client';");
    lines.push('');
  }

  // Inject the component code (which already has imports)
  lines.push(pageSafeComponentCode);

  // Generate metadata export only for server pages.
  // Next.js disallows `export const metadata` in files with `'use client'`.
  if (metaTrait && !isClient) {
    const metaEntries: string[] = [];
    if (metaTrait.title) metaEntries.push(`  title: ${JSON.stringify(metaTrait.title)},`);
    if (metaTrait.description) metaEntries.push(`  description: ${JSON.stringify(metaTrait.description)},`);

    lines.push('');
    lines.push(`export const metadata = {`);
    lines.push(metaEntries.join('\n'));
    lines.push(`};`);
  }

  // Determine output path from route
  const routePath = route.replace(/^\//, '') || 'index';
  const filePath = `${routePath}/page.tsx`;

  return {
    path: filePath,
    code: lines.join('\n'),
  };
}

/**
 * Compile multiple .holo compositions to Next.js pages.
 */
export function compileAllToNextJS(
  compositions: Array<{ name: string; composition: HoloComposition }>,
  options: NextJSCompilerOptions = {}
): NextJSCompileResult[] {
  return compositions.map(({ composition }) => compileToNextJS(composition, options));
}
