/**
 * HoloScript NextJS Compiler
 *
 * Compiles .holo compositions into Next.js App Router page files.
 * Wraps Native2DCompiler (format: 'react') with Next.js conventions:
 * - 'use client' directive
 * - next/link, next/navigation imports
 * - Metadata exports from @metadata trait (title, description, robots; server pages only)
 * - Layout generation from @layout trait
 * - @page trait for route configuration
 *
 * @module NextJSCompiler
 */

import { CompilerBase, type CapabilityTokenCredential } from './CompilerBase';
import { Native2DCompiler, type Native2DCompilerOptions } from './Native2DCompiler';
import type { HoloComposition, HoloObjectTrait } from '../parser/HoloCompositionTypes';
import type { JsonLdSceneGraph } from './SemanticSceneGraph';

export interface NextJSCompilerOptions {
  outputDir?: string;
  slots?: Record<string, { component: string; importPath: string }>;
}

export interface NextJSCompileResult {
  /** Relative path for the generated file (e.g., 'pipeline/page.tsx') */
  path: string;
  /** Generated file content */
  code: string;
}

/**
 * Extract a trait config from a composition's root-level traits.
 */
function findTrait(
  composition: HoloComposition,
  traitName: string
): Record<string, unknown> | null {
  const traits = (composition as unknown as { traits?: HoloObjectTrait[] }).traits;
  if (!traits) return null;
  const found = traits.find((t) => t.name === traitName);
  return (found?.config as Record<string, unknown>) || null;
}

/**
 * The `export const metadata = { ... }` block for a page, from its @metadata trait.
 *
 * `robots` is passed through as written: a string ("noindex") or an object
 * (`{ index: false }`), both of which Next.js accepts. It exists because a page
 * that must stay out of search results -- the invite-only refusal page, the
 * first Studio page to need it -- could not be generated without it, and a page
 * the compiler cannot express gets hand-written instead (x4dx, 2026-10-08).
 * Anything else is left out rather than guessed at.
 */
function metadataExport(metaTrait: Record<string, unknown>): string[] {
  const entries: string[] = [];
  if (metaTrait.title) entries.push(`  title: ${JSON.stringify(metaTrait.title)},`);
  if (metaTrait.description)
    entries.push(`  description: ${JSON.stringify(metaTrait.description)},`);
  const robots = metaTrait.robots;
  if (
    typeof robots === 'string' ||
    (robots !== null && typeof robots === 'object' && !Array.isArray(robots))
  ) {
    entries.push(`  robots: ${JSON.stringify(robots)},`);
  }
  return ['', `export const metadata = {`, entries.join('\n'), `};`];
}

export class NextJSCompiler extends CompilerBase {
  protected readonly compilerName = 'NextJSCompiler';

  constructor(private options: NextJSCompilerOptions = {}) {
    super();
  }

  /**
   * Compile HoloComposition AST to Next.js App Router Code
   *
   * @param composition - HoloScript AST
   * @param agentToken - JWT or UCAN token proving agent identity
   * @param outputPath - Optional output file path for scope validation
   * @param sceneGraph - Optional pre-computed SSG
   */
  public async compile(
    composition: HoloComposition,
    agentToken: string | CapabilityTokenCredential,
    outputPath?: string,
    _sceneGraph?: JsonLdSceneGraph
  ): Promise<NextJSCompileResult> {
    // 1. RBAC authorization verify
    this.validateCompilerAccess(agentToken, outputPath);

    // 2. Perform Next.js specific compilation
    return this.buildNextRoute(composition);
  }

  protected validateCompilerAccess(
    agentToken: string | CapabilityTokenCredential,
    outputPath?: string
  ): void {
    if (typeof agentToken === 'object' && agentToken !== null) {
      this.validateCapabilityAccess(agentToken as CapabilityTokenCredential, outputPath);
    } else {
      this.validateASTAccess(agentToken);
      this.validateCodeGeneration(agentToken);
      if (outputPath) {
        this.validateOutputPath(agentToken, outputPath);
      }
      this.validateSpatialZoneAccess(agentToken);
    }
  }

  private buildNextRoute(composition: HoloComposition): NextJSCompileResult {
    const compiler = new Native2DCompiler();

    // Extract @page and @metadata traits
    const pageTrait = findTrait(composition, 'page');
    const metaTrait = findTrait(composition, 'metadata');

    const route =
      (pageTrait?.route as string) || `/${composition.name.toLowerCase().replace(/\s+/g, '-')}`;
    const isClient = pageTrait?.client !== false; // default to client component

    const slotMap = this.options.slots || {};

    // Handle pure redirect pages
    if (pageTrait?.redirect) {
      const redirectUrl = pageTrait.redirect as string;
      const lines: string[] = [
        `// @generated by HoloScript NextJSCompiler — DO NOT EDIT`,
        `import { redirect } from 'next/navigation';`,
        ``,
        `export default function RedirectPage() {`,
        `  redirect(${JSON.stringify(redirectUrl)});`,
        `}`,
      ];

      if (metaTrait) {
        lines.push(...metadataExport(metaTrait));
      }

      const routePath = route.replace(/^\//, '') || 'index';
      return {
        path: `${routePath}/page.tsx`,
        code: lines.join('\n'),
      };
    }

    // Compile the React component via Native2DCompiler
    const compilerOptions: Native2DCompilerOptions = {
      format: 'react',
      useUIComponents: true,
      slots: slotMap,
    };

    const elements = composition.ui?.elements || composition.objects || [];
    const componentCode = compiler.generateReactComponent(
      composition.name,
      elements,
      composition,
      compilerOptions
    );

    // Normalize generated component code to keep only default export + metadata.
    const pageSafeComponentCode = componentCode.replace(
      /export\s+function\s+([A-Za-z0-9_]+)\s*\(/,
      'function $1('
    );

    const lines: string[] = [];

    if (isClient) {
      lines.push("'use client';");
      lines.push('');
    }

    lines.push(pageSafeComponentCode);

    if (metaTrait && !isClient) {
      lines.push(...metadataExport(metaTrait));
    }

    const routePath = route.replace(/^\//, '') || 'index';
    return {
      path: `${routePath}/page.tsx`,
      code: lines.join('\n'),
    };
  }
}
