/**
 * @fileoverview ONNX Compiler (Open Neural Network Exchange)
 * @module @holoscript/core/compiler
 *
 * PURPOSE:
 * Compile HoloScript .hsplus brain compositions to an ONNX model descriptor JSON.
 * This is a BRIDGE target — the output is a human-readable JSON descriptor that
 * describes the neural network architecture. Downstream ONNX tooling
 * (onnx-simplifier, onnxruntime, etc.) can materialise the descriptor into a
 * binary .onnx protobuf.
 *
 * Mapping rules
 * ─────────────
 * - HoloObjectDecl with @layer_type trait  → ONNX operator node
 *   - "linear"  → op_type "Gemm"
 *   - "relu"    → op_type "Relu"
 *   - "conv"    → op_type "Conv"
 *   - (default) → op_type "Gemm"
 * - @input_shape  → graph input tensor shape
 * - @output_shape → graph output tensor shape
 * - @weights      → attribute placeholder (external weights)
 * - @activation   → additional activation function node
 * - composition name → graph name
 * - No layer traits present → emit default 3-layer MLP:
 *   Input → Linear(128) → Relu → Linear(10) → Output
 *
 * Output format
 * ─────────────
 * {
 *   "ir_version": 9,
 *   "opset_import": [{ "domain": "", "version": 20 }],
 *   "graph": {
 *     "name": "<composition name>",
 *     "node": [...],
 *     "input": [...],
 *     "output": [...]
 *   },
 *   "doc_string": "Generated by HoloScript ONNXCompiler"
 * }
 */

import type {
  HoloComposition,
  HoloObjectDecl,
  HoloObjectTrait,
  HoloValue,
} from '../parser/HoloCompositionTypes.js';
import { CompilerBase, type CompilerToken } from './CompilerBase';
import { type ANSCapabilityPathValue } from '@holoscript/core-types/ans';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface ONNXCompilerOptions {
  /** Pretty-print the emitted JSON (default: true) */
  prettyPrint: boolean;
  /** ONNX IR version to declare (default: 9) */
  irVersion: number;
  /** ONNX opset version to declare (default: 20) */
  opsetVersion: number;
}

export type ONNXCompilationResult = {
  /** Serialised ONNX descriptor JSON string */
  onnxJson: string;
  /** Number of ONNX operator nodes emitted */
  nodeCount: number;
  /** Input shape extracted from @input_shape trait, or null when absent */
  inputShape: number[] | null;
};

// ---------------------------------------------------------------------------
// Internal descriptor shape (mirrors ONNX proto structure in JSON)
// ---------------------------------------------------------------------------

interface OnnxTensorShape {
  dim: Array<{ dim_value: number }>;
}

interface OnnxTypeProto {
  tensor_type: {
    elem_type: number; // 1 = FLOAT
    shape: OnnxTensorShape;
  };
}

interface OnnxValueInfo {
  name: string;
  type: OnnxTypeProto;
}

interface OnnxAttribute {
  name: string;
  type: string;
  /** String value (for references) */
  s?: string;
  /** Int list (for kernel shapes etc.) */
  ints?: number[];
  /** Float list */
  floats?: number[];
}

interface OnnxNode {
  op_type: string;
  name: string;
  input: string[];
  output: string[];
  attribute: OnnxAttribute[];
}

interface OnnxGraph {
  name: string;
  node: OnnxNode[];
  input: OnnxValueInfo[];
  output: OnnxValueInfo[];
}

interface OnnxDescriptor {
  ir_version: number;
  opset_import: Array<{ domain: string; version: number }>;
  graph: OnnxGraph;
  doc_string: string;
}

// ---------------------------------------------------------------------------
// Layer-trait names recognised by this compiler
// ---------------------------------------------------------------------------

type OnnxLayerTraitName = 'layer_type' | 'input_shape' | 'output_shape' | 'weights' | 'activation';

const ONNX_LAYER_TRAIT_NAMES: readonly OnnxLayerTraitName[] = [
  'layer_type',
  'input_shape',
  'output_shape',
  'weights',
  'activation',
];

// ---------------------------------------------------------------------------
// Op-type mapping
// ---------------------------------------------------------------------------

const LAYER_TYPE_TO_OP: Readonly<Record<string, string>> = {
  linear: 'Gemm',
  dense: 'Gemm',
  gemm: 'Gemm',
  relu: 'Relu',
  conv: 'Conv',
  convolution: 'Conv',
  sigmoid: 'Sigmoid',
  tanh: 'Tanh',
  softmax: 'Softmax',
  batchnorm: 'BatchNormalization',
  dropout: 'Dropout',
  flatten: 'Flatten',
  maxpool: 'MaxPool',
  avgpool: 'AveragePool',
  gru: 'GRU',
  lstm: 'LSTM',
};

// ONNX tensor element type enum value for FLOAT
const ELEM_TYPE_FLOAT = 1;

// ---------------------------------------------------------------------------
// Compiler
// ---------------------------------------------------------------------------

export class ONNXCompiler extends CompilerBase {
  protected readonly compilerName = 'ONNXCompiler';

  protected override getRequiredCapability(): ANSCapabilityPathValue | string {
    // ONNX is a bridge target in the AI domain — ANS entry not yet in the
    // frozen const object, so we return the path string directly.
    return '/compile/ai/onnx';
  }

  private options: ONNXCompilerOptions;

  constructor(options: Partial<ONNXCompilerOptions> = {}) {
    super();
    this.options = {
      prettyPrint: options.prettyPrint ?? true,
      irVersion: options.irVersion ?? 9,
      opsetVersion: options.opsetVersion ?? 20,
    };
  }

  override compile(
    composition: HoloComposition,
    agentToken: string,
    outputPath?: string
  ): ONNXCompilationResult {
    this.validateCompilerAccess(agentToken as CompilerToken, outputPath);

    if (!composition || composition.type !== 'Composition') {
      return this.buildFallbackResult('invalid_composition');
    }

    const compositionName =
      typeof composition.name === 'string' && composition.name.length > 0
        ? composition.name
        : 'holoscript_model';

    // Collect all objects that carry at least one ONNX layer trait
    const layerNodes = this.extractLayerNodes(composition);

    let graph: OnnxGraph;
    let inputShape: number[] | null = null;

    if (layerNodes.length === 0) {
      // Fallback: emit a canonical 3-layer MLP
      graph = this.buildDefaultMLP(compositionName);
    } else {
      const built = this.buildGraphFromNodes(compositionName, layerNodes);
      graph = built.graph;
      inputShape = built.inputShape;
    }

    const descriptor: OnnxDescriptor = {
      ir_version: this.options.irVersion,
      opset_import: [{ domain: '', version: this.options.opsetVersion }],
      graph,
      doc_string: 'Generated by HoloScript ONNXCompiler',
    };

    const onnxJson = this.options.prettyPrint
      ? JSON.stringify(descriptor, null, 2)
      : JSON.stringify(descriptor);

    return {
      onnxJson,
      nodeCount: graph.node.length,
      inputShape,
    };
  }

  // ---------------------------------------------------------------------------
  // Graph builders
  // ---------------------------------------------------------------------------

  private buildDefaultMLP(name: string): OnnxGraph {
    // 3-layer MLP: Input(784) → Linear(128) → Relu → Linear(10) → Output
    const inputName = `${name}_input`;
    const hidden = `${name}_hidden`;
    const reluOut = `${name}_relu`;
    const outputName = `${name}_output`;

    const nodes: OnnxNode[] = [
      {
        op_type: 'Gemm',
        name: `${name}_linear_0`,
        input: [inputName, `${name}_W0`, `${name}_b0`],
        output: [hidden],
        attribute: [
          { name: 'transB', type: 'INT', ints: [1] },
        ],
      },
      {
        op_type: 'Relu',
        name: `${name}_relu_0`,
        input: [hidden],
        output: [reluOut],
        attribute: [],
      },
      {
        op_type: 'Gemm',
        name: `${name}_linear_1`,
        input: [reluOut, `${name}_W1`, `${name}_b1`],
        output: [outputName],
        attribute: [
          { name: 'transB', type: 'INT', ints: [1] },
        ],
      },
    ];

    return {
      name,
      node: nodes,
      input: [this.buildTensorValueInfo(inputName, [1, 784])],
      output: [this.buildTensorValueInfo(outputName, [1, 10])],
    };
  }

  private buildGraphFromNodes(
    name: string,
    layerNodes: HoloObjectDecl[]
  ): { graph: OnnxGraph; inputShape: number[] | null } {
    const nodes: OnnxNode[] = [];
    let inputShape: number[] | null = null;
    let outputShape: number[] | null = null;

    // Resolve graph-level input/output shapes from the first node that declares them
    for (const node of layerNodes) {
      if (inputShape === null) {
        const shape = this.resolveShape(node, 'input_shape');
        if (shape !== null) inputShape = shape;
      }
      if (outputShape === null) {
        const shape = this.resolveShape(node, 'output_shape');
        if (shape !== null) outputShape = shape;
      }
    }

    // Default shapes when not declared
    const resolvedInputShape = inputShape ?? [1, 784];
    const resolvedOutputShape = outputShape ?? [1, 10];

    // Build a linear chain of ONNX nodes
    let prevTensor = `${name}_input`;
    for (let i = 0; i < layerNodes.length; i++) {
      const layerNode = layerNodes[i];
      const layerName = typeof layerNode.name === 'string' ? layerNode.name : `layer_${i}`;
      const nodeName = `${name}_${this.sanitizeId(layerName)}_${i}`;
      const outputTensor =
        i === layerNodes.length - 1 ? `${name}_output` : `${name}_tensor_${i}`;

      const opType = this.resolveOpType(layerNode);
      const attributes = this.resolveAttributes(layerNode, opType);

      // Activation function: if the node has @activation, emit a separate node after
      const activationFn = this.resolveActivation(layerNode);

      const onnxNode: OnnxNode = {
        op_type: opType,
        name: nodeName,
        input: this.buildNodeInputs(opType, prevTensor, nodeName),
        output: activationFn ? [`${outputTensor}_pre_act`] : [outputTensor],
        attribute: attributes,
      };
      nodes.push(onnxNode);

      if (activationFn) {
        const actNode: OnnxNode = {
          op_type: activationFn,
          name: `${nodeName}_act`,
          input: [`${outputTensor}_pre_act`],
          output: [outputTensor],
          attribute: [],
        };
        nodes.push(actNode);
      }

      prevTensor = outputTensor;
    }

    const graph: OnnxGraph = {
      name,
      node: nodes,
      input: [this.buildTensorValueInfo(`${name}_input`, resolvedInputShape)],
      output: [this.buildTensorValueInfo(`${name}_output`, resolvedOutputShape)],
    };

    return { graph, inputShape };
  }

  // ---------------------------------------------------------------------------
  // Trait extraction helpers
  // ---------------------------------------------------------------------------

  private extractLayerNodes(astNode: unknown): HoloObjectDecl[] {
    const matched: HoloObjectDecl[] = [];
    const seen = new Set<HoloObjectDecl>();

    const cleanNames = new Set(ONNX_LAYER_TRAIT_NAMES.map((n) => this.cleanTraitName(n)));

    const traverse = (node: unknown): void => {
      if (Array.isArray(node)) {
        for (const item of node) traverse(item);
        return;
      }
      if (!node || typeof node !== 'object') return;
      const record = node as Record<string, unknown>;
      if (
        this.isObjectDecl(record) &&
        this.nodeHasAnyTrait(record, cleanNames) &&
        !seen.has(record)
      ) {
        matched.push(record);
        seen.add(record);
      }
      for (const value of Object.values(record)) {
        if (value && typeof value === 'object') traverse(value);
      }
    };

    traverse(astNode);
    return matched;
  }

  private cleanTraitName(name: string): string {
    return name.startsWith('@') ? name.slice(1) : name;
  }

  private isObjectDecl(
    record: Record<string, unknown>
  ): record is Record<string, unknown> & HoloObjectDecl {
    return (
      (record['type'] === 'Object' || record['type'] === 'ObjectDecl') &&
      typeof record['name'] === 'string' &&
      Array.isArray(record['traits']) &&
      Array.isArray(record['properties'])
    );
  }

  private nodeHasAnyTrait(node: HoloObjectDecl, traitNames: ReadonlySet<string>): boolean {
    return node.traits.some((trait) => traitNames.has(this.cleanTraitName(String(trait.name))));
  }

  private getTrait(node: HoloObjectDecl, traitName: string): HoloObjectTrait | undefined {
    const clean = this.cleanTraitName(traitName);
    return node.traits.find((t) => this.cleanTraitName(String(t.name)) === clean);
  }

  private getTraitScalar(
    node: HoloObjectDecl,
    traitName: string,
    keys: readonly string[]
  ): HoloValue | undefined {
    const trait = this.getTrait(node, traitName);
    if (!trait) return undefined;
    const config = (trait.config ?? trait.params ?? {}) as Record<string, HoloValue>;
    for (const key of keys) {
      if (config[key] !== undefined) return config[key];
    }
    // Fallback: check object properties
    for (const key of keys) {
      const prop = node.properties.find((p) => p.key === key);
      if (prop !== undefined) return prop.value;
    }
    return undefined;
  }

  // ---------------------------------------------------------------------------
  // Op-type and attribute resolution
  // ---------------------------------------------------------------------------

  private resolveOpType(node: HoloObjectDecl): string {
    const rawType = this.getTraitScalar(node, 'layer_type', ['type', 'kind', 'op']);
    if (typeof rawType === 'string') {
      const mapped = LAYER_TYPE_TO_OP[rawType.toLowerCase()];
      if (mapped) return mapped;
      // If not in map but looks like a valid ONNX op, use it directly
      if (/^[A-Z][A-Za-z0-9]+$/.test(rawType)) return rawType;
    }
    return 'Gemm';
  }

  private resolveAttributes(node: HoloObjectDecl, opType: string): OnnxAttribute[] {
    const attrs: OnnxAttribute[] = [];

    // Gemm: add transB=1 by default so weight matrices don't need to be pre-transposed
    if (opType === 'Gemm') {
      attrs.push({ name: 'transB', type: 'INT', ints: [1] });
    }

    // Conv: kernel_shape from trait or default 3x3
    if (opType === 'Conv') {
      const kernelRaw = this.getTraitScalar(node, 'layer_type', ['kernel_shape', 'kernel']);
      const kernelShape = this.holoValueToIntArray(kernelRaw) ?? [3, 3];
      attrs.push({ name: 'kernel_shape', type: 'INTS', ints: kernelShape });
    }

    // Weights: emit as string reference (external weights placeholder)
    const weightsRef = this.getTraitScalar(node, 'weights', ['ref', 'path', 'name', 'file']);
    if (weightsRef !== undefined) {
      attrs.push({
        name: 'weights_ref',
        type: 'STRING',
        s: String(weightsRef),
      });
    }

    return attrs;
  }

  private resolveActivation(node: HoloObjectDecl): string | null {
    const raw = this.getTraitScalar(node, 'activation', ['fn', 'function', 'type', 'kind']);
    if (typeof raw !== 'string') return null;
    const mapped = LAYER_TYPE_TO_OP[raw.toLowerCase()];
    return mapped ?? null;
  }

  private resolveShape(node: HoloObjectDecl, traitName: 'input_shape' | 'output_shape'): number[] | null {
    const raw = this.getTraitScalar(node, traitName, ['shape', 'dims', 'dimensions', 'size']);
    return this.holoValueToIntArray(raw);
  }

  // ---------------------------------------------------------------------------
  // ONNX node input slot builder
  // ---------------------------------------------------------------------------

  private buildNodeInputs(opType: string, inputTensor: string, nodeName: string): string[] {
    // Gemm needs X, W, B
    if (opType === 'Gemm') {
      return [inputTensor, `${nodeName}_W`, `${nodeName}_b`];
    }
    // Conv needs X, W, (optional B)
    if (opType === 'Conv') {
      return [inputTensor, `${nodeName}_W`, `${nodeName}_b`];
    }
    // Unary / elementwise ops
    return [inputTensor];
  }

  // ---------------------------------------------------------------------------
  // Value-info builder
  // ---------------------------------------------------------------------------

  private buildTensorValueInfo(name: string, shape: number[]): OnnxValueInfo {
    return {
      name,
      type: {
        tensor_type: {
          elem_type: ELEM_TYPE_FLOAT,
          shape: {
            dim: shape.map((d) => ({ dim_value: d })),
          },
        },
      },
    };
  }

  // ---------------------------------------------------------------------------
  // Utility helpers
  // ---------------------------------------------------------------------------

  private holoValueToIntArray(value: HoloValue | undefined): number[] | null {
    if (Array.isArray(value)) {
      const ints = value
        .map((v) => (typeof v === 'number' ? Math.round(v) : parseInt(String(v), 10)))
        .filter((n) => Number.isFinite(n));
      return ints.length > 0 ? ints : null;
    }
    if (typeof value === 'string') {
      const parts = value.split(/[\s,x]+/).map((s) => parseInt(s.trim(), 10));
      const valid = parts.filter((n) => Number.isFinite(n));
      return valid.length > 0 ? valid : null;
    }
    if (typeof value === 'number' && Number.isFinite(value)) {
      return [Math.round(value)];
    }
    return null;
  }

  private sanitizeId(value: string): string {
    return value.replace(/[^A-Za-z0-9_]/g, '_').replace(/^[^A-Za-z_]+/, '') || 'node';
  }

  private buildFallbackResult(graphName: string): ONNXCompilationResult {
    const graph = this.buildDefaultMLP(graphName);
    const descriptor: OnnxDescriptor = {
      ir_version: this.options.irVersion,
      opset_import: [{ domain: '', version: this.options.opsetVersion }],
      graph,
      doc_string: 'Generated by HoloScript ONNXCompiler',
    };
    return {
      onnxJson: this.options.prettyPrint
        ? JSON.stringify(descriptor, null, 2)
        : JSON.stringify(descriptor),
      nodeCount: graph.node.length,
      inputShape: null,
    };
  }
}

export default ONNXCompiler;
