/**
 * HoloScript -> PlayCanvas Compiler
 *
 * Translates a HoloComposition AST into PlayCanvas TypeScript code.
 *
 * Emits:
 *   - pc.Application initialization
 *   - Entity creation with component-based architecture
 *   - Render component for geometry (box, sphere, cylinder, etc.)
 *   - Light components (directional, point, spot)
 *   - Camera component (perspective, orthographic)
 *   - RigidBody + Collision components for physics
 *   - Sound component for audio
 *   - Screen/Element components for UI
 *   - Animation system via Anim component
 *   - XR support via WebXR
 *
 * @version 1.0.0
 */

import type {
  HoloComposition,
  HoloObjectDecl,
  HoloSpatialGroup,
  HoloLight,
  HoloEnvironment,
  HoloCamera,
  HoloTimeline,
  HoloAudio,
  HoloZone,
  HoloUI,
  HoloTransition,
  HoloEffects,
} from '../parser/HoloCompositionTypes';
import { TraitCompositor } from '../traits/visual/TraitCompositor';
import { CompilerBase } from './CompilerBase';

export interface PlayCanvasCompilerOptions {
  className?: string;
  enablePhysics?: boolean;
  enableXR?: boolean;
  indent?: string;
}

const SHAPE_TO_PRIMITIVE: Record<string, string> = {
  sphere: 'sphere',
  orb: 'sphere',
  cube: 'box',
  box: 'box',
  cylinder: 'cylinder',
  cone: 'cone',
  pyramid: 'cone',
  plane: 'plane',
  ground: 'plane',
  torus: 'torus',
  ring: 'torus',
  capsule: 'capsule',
  disc: 'plane',
};

export class PlayCanvasCompiler extends CompilerBase {
  protected readonly compilerName = 'PlayCanvasCompiler';
  private options: Required<PlayCanvasCompilerOptions>;
  private lines: string[] = [];
  private indentLevel: number = 0;

  constructor(options: PlayCanvasCompilerOptions = {}) {
    super();
    this.options = {
      className: options.className || 'GeneratedScene',
      enablePhysics: options.enablePhysics ?? true,
      enableXR: options.enableXR ?? false,
      indent: options.indent || '  ',
    };
  }

  compile(composition: HoloComposition, agentToken: string, outputPath?: string): string {
    this.validateCompilerAccess(agentToken, outputPath);
    this.lines = [];
    this.indentLevel = 0;

    this.emit('// Auto-generated by HoloScript PlayCanvasCompiler');
    this.emit(`// Source: composition "${composition.name}"`);
    this.emit('');
    this.emitImports(composition);
    this.emit('');
    this.emit(`export class ${this.options.className} {`);
    this.indent();
    this.emit('private app: pc.Application;');
    this.emit('private canvas: HTMLCanvasElement;');
    this.emit('');
    this.emit('constructor(canvas: HTMLCanvasElement) {');
    this.indent();
    this.emit('this.canvas = canvas;');
    this.emit('this.app = new pc.Application(canvas, {');
    this.indent();
    this.emit('mouse: new pc.Mouse(canvas),');
    this.emit('touch: new pc.TouchDevice(canvas),');
    this.emit('keyboard: new pc.Keyboard(window),');
    this.dedent();
    this.emit('});');
    this.emit('this.app.setCanvasFillMode(pc.FILLMODE_FILL_WINDOW);');
    this.emit('this.app.setCanvasResolution(pc.RESOLUTION_AUTO);');
    this.dedent();
    this.emit('}');
    this.emit('');
    this.emit('async build(): Promise<void> {');
    this.indent();
    this.emitSceneSetup(composition);
    if (composition.environment) this.emitEnvironment(composition.environment);
    if (composition.lights?.length) {
      for (const light of composition.lights) this.emitLight(light);
    } else {
      this.emit('// Default light');
      this.emit('const defaultLight = new pc.Entity("defaultLight");');
      this.emit('defaultLight.addComponent("light", {');
      this.indent();
      this.emit('type: "directional",');
      this.emit('color: new pc.Color(1, 1, 1),');
      this.emit('intensity: 0.7,');
      this.emit('castShadows: true,');
      this.dedent();
      this.emit('});');
      this.emit('defaultLight.setEulerAngles(45, 30, 0);');
      this.emit('this.app.root.addChild(defaultLight);');
      this.emit('');
    }
    if (composition.camera) this.emitCamera(composition.camera);
    else {
      this.emit('// Default camera');
      this.emit('const camera = new pc.Entity("defaultCamera");');
      this.emit('camera.addComponent("camera", {');
      this.indent();
      this.emit('clearColor: new pc.Color(0.05, 0.05, 0.1),');
      this.dedent();
      this.emit('});');
      this.emit('camera.setPosition(0, 5, 10);');
      this.emit('camera.lookAt(0, 0, 0);');
      this.emit('this.app.root.addChild(camera);');
      this.emit('');
    }
    if (composition.objects?.length) for (const obj of composition.objects) this.emitObject(obj);
    if (composition.spatialGroups?.length)
      for (const g of composition.spatialGroups) this.emitGroup(g);
    if (composition.timelines?.length)
      for (const tl of composition.timelines) this.emitTimeline(tl);
    if (composition.audio?.length) for (const a of composition.audio) this.emitAudio(a);
    if (composition.zones?.length) for (const z of composition.zones) this.emitZone(z);
    if (composition.ui) this.emitUI(composition.ui);
    if (composition.effects) this.emitEffects(composition.effects);
    if (composition.transitions?.length)
      for (const t of composition.transitions) this.emitTransition(t);
    if (this.options.enableXR) this.emitXRSetup();
    this.emitStartApp();
    this.dedent();
    this.emit('}');
    this.emit('');
    this.emit('dispose(): void { this.app.destroy(); }');
    this.dedent();
    this.emit('}');
    return this.lines.join('\n');
  }

  // --- Imports ---

  private emitImports(_composition: HoloComposition): void {
    this.emit('import * as pc from "playcanvas";');
  }

  // --- Scene Setup ---

  private emitSceneSetup(_composition: HoloComposition): void {
    if (this.options.enablePhysics) {
      this.emit('this.app.systems.rigidbody?.setGravity(0, -9.81, 0);');
    }
    this.emit('');
  }

  // --- Environment ---

  private emitEnvironment(env: HoloEnvironment): void {
    for (const prop of env.properties) {
      if (prop.key === 'skybox' || prop.key === 'preset') {
        this.emit(`this.app.scene.setSkybox(null); // Skybox: "${prop.value}"`);
        this.emit(`this.app.scene.skyboxIntensity = 1.0;`);
      } else if (prop.key === 'fog' && typeof prop.value === 'object') {
        const fog = prop.value as Record<string, any>;
        this.emit(`this.app.scene.fog = pc.FOG_LINEAR;`);
        if (fog.color) this.emit(`this.app.scene.fogColor = ${this.toPlayCanvasColor(fog.color)};`);
        if (fog.near !== undefined) this.emit(`this.app.scene.fogStart = ${fog.near};`);
        if (fog.far !== undefined) this.emit(`this.app.scene.fogEnd = ${fog.far};`);
      } else if (prop.key === 'ambient_light') {
        this.emit(
          `this.app.scene.ambientLight = new pc.Color(${prop.value}, ${prop.value}, ${prop.value});`
        );
      } else if (prop.key === 'ground') {
        this.emit('const ground = new pc.Entity("ground");');
        this.emit('ground.addComponent("render", { type: "plane" });');
        this.emit('ground.setLocalScale(100, 1, 100);');
        if (typeof prop.value === 'object' && prop.value !== null) {
          const g = prop.value as Record<string, any>;
          if (g.color) {
            this.emit('const groundMat = new pc.StandardMaterial();');
            this.emit(`groundMat.diffuse = ${this.toPlayCanvasColor(g.color)};`);
            this.emit('groundMat.update();');
            this.emit('ground.render!.meshInstances[0].material = groundMat;');
          }
        }
        this.emit('this.app.root.addChild(ground);');
      }
    }
    this.emit('');
  }

  // --- Objects ---

  private emitObject(obj: HoloObjectDecl, parentVar?: string): void {
    const v = this.sanitizeName(obj.name);
    let geom = 'cube',
      modelSrc: string | undefined,
      textContent: string | undefined;
    let position: any[] | undefined, rotation: any[] | undefined, scale: any, size: any;
    const mat: Record<string, any> = {};

    for (const p of obj.properties) {
      switch (p.key) {
        case 'geometry':
        case 'mesh':
        case 'type':
          if (typeof p.value === 'string') geom = p.value;
          break;
        case 'position':
          if (Array.isArray(p.value)) position = p.value;
          break;
        case 'rotation':
          if (Array.isArray(p.value)) rotation = p.value;
          break;
        case 'scale':
          scale = p.value;
          break;
        case 'size':
          size = p.value;
          break;
        case 'color':
          mat.color = p.value;
          break;
        case 'roughness':
          mat.roughness = p.value;
          break;
        case 'metalness':
        case 'metallic':
          mat.metalness = p.value;
          break;
        case 'opacity':
          mat.opacity = p.value;
          break;
        case 'emissive':
          mat.emissive = p.value;
          break;
        case 'emissive_intensity':
        case 'emissiveIntensity':
          mat.emissiveIntensity = p.value;
          break;
        case 'material':
          if (typeof p.value === 'object' && p.value !== null)
            Object.assign(mat, p.value as Record<string, any>);
          break;
        case 'model':
        case 'src':
          if (typeof p.value === 'string') modelSrc = p.value;
          break;
        case 'text':
          if (typeof p.value === 'string') textContent = p.value;
          break;
      }
    }

    this.emit(`// Object: ${obj.name}`);
    this.emit(`const ${v} = new pc.Entity("${obj.name}");`);

    if (modelSrc) {
      this.emit(`// Model: ${modelSrc} — load via asset registry`);
      this.emit(`${v}.addComponent("render", { type: "asset" });`);
    } else if (geom === 'text' || textContent) {
      this.emit(`${v}.addComponent("element", {`);
      this.indent();
      this.emit(`type: "text",`);
      this.emit(`text: "${textContent || ''}",`);
      this.emit(`fontSize: 48,`);
      this.emit(`color: new pc.Color(1, 1, 1),`);
      this.emit(`anchor: new pc.Vec4(0.5, 0.5, 0.5, 0.5),`);
      this.dedent();
      this.emit('});');
    } else {
      const prim = this.mapShapeToPrimitive(geom);
      this.emit(`${v}.addComponent("render", { type: "${prim}" });`);

      if (Object.keys(mat).length > 0) {
        this.emit(`const ${v}Mat = new pc.StandardMaterial();`);
        if (mat.color) this.emit(`${v}Mat.diffuse = ${this.toPlayCanvasColor(mat.color)};`);
        if (mat.roughness !== undefined) this.emit(`${v}Mat.shininess = ${(1 - mat.roughness) * 100};`);
        if (mat.metalness !== undefined) this.emit(`${v}Mat.metalness = ${mat.metalness};`);
        if (mat.opacity !== undefined && mat.opacity < 1) {
          this.emit(`${v}Mat.opacity = ${mat.opacity};`);
          this.emit(`${v}Mat.blendType = pc.BLEND_NORMAL;`);
        }
        if (mat.emissive) this.emit(`${v}Mat.emissive = ${this.toPlayCanvasColor(mat.emissive)};`);
        if (mat.emissiveIntensity !== undefined)
          this.emit(`${v}Mat.emissiveIntensity = ${mat.emissiveIntensity};`);
        this.emit(`${v}Mat.update();`);
        this.emit(`${v}.render!.meshInstances[0].material = ${v}Mat;`);
      }
    }

    if (position) this.emit(`${v}.setPosition(${position[0]}, ${position[1]}, ${position[2]});`);
    if (rotation) this.emit(`${v}.setEulerAngles(${rotation[0]}, ${rotation[1]}, ${rotation[2]});`);
    if (scale) {
      if (Array.isArray(scale))
        this.emit(`${v}.setLocalScale(${scale[0]}, ${scale[1]}, ${scale[2]});`);
      else
        this.emit(`${v}.setLocalScale(${scale}, ${scale}, ${scale});`);
    }
    if (size) {
      const s = typeof size === 'number' ? size : 1;
      this.emit(`${v}.setLocalScale(${s}, ${s}, ${s});`);
    }

    // Traits
    for (const trait of obj.traits || []) {
      if (trait.name === 'grabbable') {
        this.emit(`${v}.addComponent("button", { active: true });`);
        this.emit(`${v}.button!.on("click", () => { console.log("Picked: ${obj.name}"); });`);
      } else if (trait.name === 'physics' || trait.name === 'collidable') {
        const mt = (trait.config?.type || 'dynamic') === 'static' ? 'static' : 'dynamic';
        this.emit(`${v}.addComponent("rigidbody", {`);
        this.indent();
        this.emit(`type: "${mt}",`);
        this.emit(`mass: ${trait.config?.mass ?? 1},`);
        if (trait.config?.restitution !== undefined)
          this.emit(`restitution: ${trait.config.restitution},`);
        if (trait.config?.friction !== undefined)
          this.emit(`friction: ${trait.config.friction},`);
        this.dedent();
        this.emit('});');
        this.emit(`${v}.addComponent("collision", { type: "${this.mapShapeToPrimitive(geom)}" });`);
      } else if (trait.name === 'hoverable') {
        this.emit(`${v}.addComponent("button", { active: true });`);
        this.emit(`${v}.button!.on("mouseenter", () => { /* hover enter */ });`);
        this.emit(`${v}.button!.on("mouseleave", () => { /* hover exit */ });`);
      } else if (trait.name === 'accessible') {
        this.emit(
          `// @accessible: role="${trait.config?.role || 'generic'}" for "${obj.name}"`
        );
      } else if (trait.name === 'shadow') {
        this.emit(`${v}.render!.castShadows = true;`);
        this.emit(`${v}.render!.receiveShadows = true;`);
      } else {
        this.emit(`// @${trait.name}: ${JSON.stringify(trait.config || {})}`);
      }
    }

    // TraitCompositor batch composition
    if (obj.traits && Array.isArray(obj.traits) && obj.traits.length > 0) {
      const traitNames = obj.traits.map((t: any) => t.name as string);
      const compositor = new TraitCompositor();
      const composed = compositor.compose(traitNames);
      if (Object.keys(composed).length > 0) {
        const matVar = `${v}ComposedMat`;
        this.emit(`// TraitCompositor: composed ${traitNames.join(' + ')}`);
        this.emit(`const ${matVar} = new pc.StandardMaterial();`);
        if (composed.color) this.emit(`${matVar}.diffuse = ${this.toPlayCanvasColor(composed.color)};`);
        if (composed.roughness !== undefined) this.emit(`${matVar}.shininess = ${(1 - composed.roughness) * 100};`);
        if (composed.metalness !== undefined) this.emit(`${matVar}.metalness = ${composed.metalness};`);
        if (composed.opacity !== undefined && composed.opacity < 1) {
          this.emit(`${matVar}.opacity = ${composed.opacity};`);
          this.emit(`${matVar}.blendType = pc.BLEND_NORMAL;`);
        }
        if (composed.emissive) this.emit(`${matVar}.emissive = ${this.toPlayCanvasColor(composed.emissive)};`);
        if (composed.emissiveIntensity !== undefined) this.emit(`${matVar}.emissiveIntensity = ${composed.emissiveIntensity};`);
        this.emit(`${matVar}.update();`);
        this.emit(`${v}.render!.meshInstances[0].material = ${matVar};`);
      }
    }

    const parent = parentVar || 'this.app.root';
    this.emit(`${parent}.addChild(${v});`);

    if (obj.children?.length) for (const child of obj.children) this.emitObject(child, v);
    this.emit('');
  }

  // --- Groups ---

  private emitGroup(group: HoloSpatialGroup, parentVar?: string): void {
    const v = this.sanitizeName(group.name);
    this.emit(`const ${v} = new pc.Entity("${group.name}");`);
    for (const p of group.properties) {
      if (p.key === 'position' && Array.isArray(p.value))
        this.emit(`${v}.setPosition(${p.value[0]}, ${p.value[1]}, ${p.value[2]});`);
      else if (p.key === 'rotation' && Array.isArray(p.value))
        this.emit(`${v}.setEulerAngles(${p.value[0]}, ${p.value[1]}, ${p.value[2]});`);
      else if (p.key === 'scale') {
        if (Array.isArray(p.value))
          this.emit(`${v}.setLocalScale(${p.value[0]}, ${p.value[1]}, ${p.value[2]});`);
        else
          this.emit(`${v}.setLocalScale(${p.value}, ${p.value}, ${p.value});`);
      }
    }
    const parent = parentVar || 'this.app.root';
    this.emit(`${parent}.addChild(${v});`);
    for (const obj of group.objects) this.emitObject(obj, v);
    if (group.groups) for (const sub of group.groups) this.emitGroup(sub, v);
    this.emit('');
  }

  // --- Lights ---

  private emitLight(light: HoloLight): void {
    const v = this.sanitizeName(light.name);
    let pos: any[] | undefined, color: any, intensity: number | undefined;
    let dir: any[] | undefined,
      castShadow = false,
      angle: number | undefined,
      dist: number | undefined;

    for (const p of light.properties) {
      if (p.key === 'position' && Array.isArray(p.value)) pos = p.value;
      else if (p.key === 'color') color = p.value;
      else if (p.key === 'intensity') intensity = p.value as number;
      else if (p.key === 'direction' && Array.isArray(p.value)) dir = p.value;
      else if (p.key === 'cast_shadow' || p.key === 'castShadow') castShadow = !!p.value;
      else if (p.key === 'angle') angle = p.value as number;
      else if (p.key === 'distance') dist = p.value as number;
    }

    const pcType = this.mapLightType(light.lightType);
    this.emit(`const ${v} = new pc.Entity("${light.name}");`);
    this.emit(`${v}.addComponent("light", {`);
    this.indent();
    this.emit(`type: "${pcType}",`);
    if (color) this.emit(`color: ${this.toPlayCanvasColor(color)},`);
    if (intensity !== undefined) this.emit(`intensity: ${intensity},`);
    if (castShadow) this.emit('castShadows: true,');
    if (dist !== undefined) this.emit(`range: ${dist},`);
    if (angle !== undefined && (pcType === 'spot')) this.emit(`outerConeAngle: ${angle * (180 / Math.PI)},`);
    this.dedent();
    this.emit('});');
    if (pos) this.emit(`${v}.setPosition(${pos[0]}, ${pos[1]}, ${pos[2]});`);
    if (dir) this.emit(`${v}.setEulerAngles(${this.directionToEuler(dir)});`);
    this.emit('this.app.root.addChild(' + v + ');');
    this.emit('');
  }

  // --- Camera ---

  private emitCamera(cam: HoloCamera): void {
    let fov: number | undefined, pos: any[] | undefined, lookAt: any[] | undefined;
    let near: number | undefined, far: number | undefined;
    for (const p of cam.properties) {
      if (p.key === 'fov' || p.key === 'field_of_view') fov = p.value as number;
      else if (p.key === 'position' && Array.isArray(p.value)) pos = p.value;
      else if ((p.key === 'look_at' || p.key === 'lookAt') && Array.isArray(p.value))
        lookAt = p.value;
      else if (p.key === 'near') near = p.value as number;
      else if (p.key === 'far') far = p.value as number;
    }

    this.emit('const camera = new pc.Entity("camera");');
    this.emit('camera.addComponent("camera", {');
    this.indent();
    this.emit('clearColor: new pc.Color(0.05, 0.05, 0.1),');
    if (cam.cameraType === 'orthographic') {
      this.emit('projection: pc.PROJECTION_ORTHOGRAPHIC,');
    }
    if (fov !== undefined) this.emit(`fov: ${fov},`);
    if (near !== undefined) this.emit(`nearClip: ${near},`);
    if (far !== undefined) this.emit(`farClip: ${far},`);
    this.dedent();
    this.emit('});');
    if (pos) this.emit(`camera.setPosition(${pos[0]}, ${pos[1]}, ${pos[2]});`);
    else this.emit('camera.setPosition(0, 5, 10);');
    if (lookAt) this.emit(`camera.lookAt(${lookAt[0]}, ${lookAt[1]}, ${lookAt[2]});`);
    else this.emit('camera.lookAt(0, 0, 0);');
    this.emit('this.app.root.addChild(camera);');
    this.emit('');
  }

  // --- Timeline ---

  private emitTimeline(timeline: HoloTimeline): void {
    const v = this.sanitizeName(timeline.name);
    this.emit(`// Timeline: "${timeline.name}"`);
    for (const entry of timeline.entries) {
      const a = entry.action;
      if (a.kind === 'animate') {
        this.emit(`// @${entry.time}s: animate ${a.target} ${JSON.stringify(a.properties)}`);
      } else if (a.kind === 'emit') {
        this.emit(`// @${entry.time}s: emit "${a.event}"`);
      } else if (a.kind === 'call') {
        this.emit(`// @${entry.time}s: call ${a.method}()`);
      }
    }
    if (timeline.autoplay) this.emit(`// autoplay: ${timeline.loop ? 'loop' : 'once'}`);
    this.emit('');
  }

  // --- Audio ---

  private emitAudio(audio: HoloAudio): void {
    const v = this.sanitizeName(audio.name);
    let src = '',
      volume = 1,
      loop = false,
      spatial = false;
    let position: any[] | undefined, dist: number | undefined;
    for (const p of audio.properties) {
      if (p.key === 'src' || p.key === 'source') src = String(p.value);
      else if (p.key === 'volume') volume = p.value as number;
      else if (p.key === 'loop') loop = !!p.value;
      else if (p.key === 'spatial') spatial = !!p.value;
      else if (p.key === 'position' && Array.isArray(p.value)) position = p.value;
      else if (p.key === 'distance') dist = p.value as number;
    }
    this.emit(`const ${v} = new pc.Entity("${audio.name}");`);
    this.emit(`${v}.addComponent("sound");`);
    this.emit(`${v}.sound!.addSlot("default", {`);
    this.indent();
    this.emit(`asset: null, // Load "${src}" via asset registry`);
    this.emit(`loop: ${loop},`);
    this.emit(`volume: ${volume},`);
    this.emit(`autoPlay: true,`);
    if (dist !== undefined) this.emit(`maxDistance: ${dist},`);
    if (spatial) this.emit('positional: true,');
    this.dedent();
    this.emit('});');
    if (position) this.emit(`${v}.setPosition(${position[0]}, ${position[1]}, ${position[2]});`);
    this.emit(`this.app.root.addChild(${v});`);
    this.emit('');
  }

  // --- Zone ---

  private emitZone(zone: HoloZone): void {
    const v = this.sanitizeName(zone.name);
    let shape = 'box',
      position: any[] | undefined,
      size: any,
      radius: number | undefined;
    for (const p of zone.properties) {
      if (p.key === 'shape') shape = String(p.value);
      else if (p.key === 'position' && Array.isArray(p.value)) position = p.value;
      else if (p.key === 'size') size = p.value;
      else if (p.key === 'radius') radius = p.value as number;
    }
    this.emit(`const ${v} = new pc.Entity("${zone.name}");`);
    if (shape === 'sphere') {
      this.emit(`${v}.addComponent("collision", { type: "sphere", radius: ${radius || 5} });`);
    } else {
      const s = Array.isArray(size) ? size : [size || 5, size || 5, size || 5];
      this.emit(`${v}.addComponent("collision", { type: "box", halfExtents: new pc.Vec3(${s[0] / 2}, ${s[1] / 2}, ${s[2] / 2}) });`);
    }
    this.emit(`${v}.addComponent("rigidbody", { type: "static" });`);
    if (position) this.emit(`${v}.setPosition(${position[0]}, ${position[1]}, ${position[2]});`);
    if (zone.handlers?.length) {
      for (const h of zone.handlers) {
        const event = h.event === 'on_enter' ? 'triggerenter' : h.event === 'on_exit' ? 'triggerleave' : h.event;
        this.emit(`${v}.collision!.on("${event}", (result: any) => { /* ${h.event} */ });`);
      }
    }
    this.emit(`this.app.root.addChild(${v});`);
    this.emit('');
  }

  // --- UI ---

  private emitUI(ui: HoloUI): void {
    this.emit('const screenEntity = new pc.Entity("screen");');
    this.emit('screenEntity.addComponent("screen", { screenSpace: true, referenceResolution: new pc.Vec2(1280, 720) });');
    this.emit('this.app.root.addChild(screenEntity);');
    for (const el of ui.elements) {
      const v = this.sanitizeName(el.name);
      let elType = 'text',
        text = '',
        fontSize = 24,
        color = '#ffffff',
        bg: string | undefined;
      for (const p of el.properties) {
        if (p.key === 'type') elType = String(p.value);
        else if (p.key === 'text') text = String(p.value);
        else if (p.key === 'font_size' || p.key === 'fontSize') fontSize = p.value as number;
        else if (p.key === 'color') color = String(p.value);
        else if (p.key === 'background') bg = String(p.value);
      }
      this.emit(`const ${v} = new pc.Entity("${el.name}");`);
      if (elType === 'button') {
        this.emit(`${v}.addComponent("element", {`);
        this.indent();
        this.emit(`type: "text",`);
        this.emit(`text: "${text}",`);
        this.emit(`fontSize: ${fontSize},`);
        this.emit(`color: ${this.toPlayCanvasColor(color)},`);
        this.emit(`anchor: new pc.Vec4(0.5, 0.5, 0.5, 0.5),`);
        this.emit(`pivot: new pc.Vec2(0.5, 0.5),`);
        this.emit(`width: 150,`);
        this.emit(`height: 40,`);
        this.dedent();
        this.emit('});');
        this.emit(`${v}.addComponent("button", { active: true });`);
      } else if (elType === 'progress') {
        this.emit(`${v}.addComponent("element", {`);
        this.indent();
        this.emit('type: "image",');
        this.emit('anchor: new pc.Vec4(0.5, 0.5, 0.5, 0.5),');
        this.emit('width: 200,');
        this.emit('height: 20,');
        this.dedent();
        this.emit('});');
      } else {
        this.emit(`${v}.addComponent("element", {`);
        this.indent();
        this.emit(`type: "text",`);
        this.emit(`text: "${text}",`);
        this.emit(`fontSize: ${fontSize},`);
        this.emit(`color: ${this.toPlayCanvasColor(color)},`);
        this.emit(`anchor: new pc.Vec4(0.5, 0.5, 0.5, 0.5),`);
        this.dedent();
        this.emit('});');
      }
      this.emit(`screenEntity.addChild(${v});`);
    }
    this.emit('');
  }

  // --- Effects ---

  private emitEffects(effects: HoloEffects): void {
    for (const fx of effects.effects) {
      const p = fx.properties;
      switch (fx.effectType) {
        case 'bloom':
          this.emit('// Post-processing: Bloom');
          this.emit('this.app.scene.rendering.toneMapping = pc.TONEMAP_ACES;');
          if (p.intensity !== undefined) this.emit(`// bloom intensity: ${p.intensity}`);
          break;
        case 'ssao':
          this.emit('// Post-processing: SSAO');
          if (p.radius !== undefined) this.emit(`// ssao radius: ${p.radius}`);
          break;
        case 'vignette':
          this.emit('// Post-processing: Vignette');
          if (p.weight !== undefined) this.emit(`// vignette weight: ${p.weight}`);
          break;
        case 'tone_mapping':
          this.emit('this.app.scene.rendering.toneMapping = pc.TONEMAP_ACES;');
          break;
        default:
          this.emit(`// Effect "${fx.effectType}": ${JSON.stringify(p)}`);
      }
    }
    this.emit('');
  }

  // --- Transition ---

  private emitTransition(tr: HoloTransition): void {
    let target: string | undefined, effect: string | undefined, duration: number | undefined;
    for (const p of tr.properties) {
      if (p.key === 'target') target = String(p.value);
      else if (p.key === 'effect') effect = String(p.value);
      else if (p.key === 'duration') duration = p.value as number;
    }
    this.emit(
      `// Transition "${tr.name}": navigate to "${target || '?'}" with ${effect || 'fade'} over ${duration || 1}s`
    );
  }

  // --- XR ---

  private emitXRSetup(): void {
    this.emit('if (this.app.xr.supported) {');
    this.indent();
    this.emit('this.app.xr.start(this.app.root.findByName("camera")?.camera!, pc.XRTYPE_VR, pc.XRSPACE_LOCAL);');
    this.dedent();
    this.emit('}');
    this.emit('');
  }

  // --- Start App ---

  private emitStartApp(): void {
    this.emit('this.app.start();');
    this.emit('window.addEventListener("resize", () => { this.app.resizeCanvas(); });');
  }

  // --- Value Conversion Helpers ---

  private toPlayCanvasColor(value: any): string {
    if (typeof value === 'string' && value.startsWith('#')) {
      const h = value.slice(1);
      const r = parseInt(h.substring(0, 2), 16) / 255;
      const g = parseInt(h.substring(2, 4), 16) / 255;
      const b = parseInt(h.substring(4, 6), 16) / 255;
      return `new pc.Color(${r.toFixed(3)}, ${g.toFixed(3)}, ${b.toFixed(3)})`;
    }
    if (typeof value === 'object' && value !== null && 'r' in value) {
      const r = value.r > 1 ? value.r / 255 : value.r;
      const g = value.g > 1 ? value.g / 255 : value.g;
      const b = value.b > 1 ? value.b / 255 : value.b;
      return `new pc.Color(${r.toFixed(3)}, ${g.toFixed(3)}, ${b.toFixed(3)})`;
    }
    return 'new pc.Color(1, 1, 1)';
  }

  private mapShapeToPrimitive(type: string): string {
    return SHAPE_TO_PRIMITIVE[type] || 'box';
  }

  private mapLightType(type: string): string {
    switch (type) {
      case 'hemisphere':
      case 'ambient':
        return 'directional';
      case 'directional':
        return 'directional';
      case 'point':
        return 'point';
      case 'spot':
        return 'spot';
      case 'area':
        return 'point';
      default:
        return 'directional';
    }
  }

  private directionToEuler(dir: any[]): string {
    // Simplified: direction vector to Euler angles
    const x = dir[0] || 0, y = dir[1] || 0, z = dir[2] || 0;
    const pitch = Math.atan2(-y, Math.sqrt(x * x + z * z)) * (180 / Math.PI);
    const yaw = Math.atan2(x, z) * (180 / Math.PI);
    return `${pitch.toFixed(1)}, ${yaw.toFixed(1)}, 0`;
  }

  // --- Emit Helpers ---

  private emit(line: string): void {
    this.lines.push(this.options.indent.repeat(this.indentLevel) + line);
  }
  private indent(): void {
    this.indentLevel++;
  }
  private dedent(): void {
    this.indentLevel = Math.max(0, this.indentLevel - 1);
  }
  private sanitizeName(name: string): string {
    return name.replace(/[^a-zA-Z0-9_]/g, '_');
  }
}
