import { describe, it, expect, beforeEach } from 'vitest';
import { PlayCanvasCompiler } from './PlayCanvasCompiler';
import { registerAllPresets } from '../traits/visual';
import type {
  HoloComposition,
  HoloObjectDecl,
  HoloLight,
  HoloCamera,
  HoloSpatialGroup,
  HoloTimeline,
  HoloAudio,
  HoloZone,
  HoloUI,
  HoloEffects,
  HoloTransition,
  HoloEnvironment,
} from '../parser/HoloCompositionTypes';

// Ensure TraitVisualRegistry is populated for TraitCompositor integration tests
registerAllPresets();

// ============================================================================
// Helpers
// ============================================================================

function createComposition(overrides: Partial<HoloComposition> = {}): HoloComposition {
  return {
    type: 'HoloComposition',
    name: 'TestScene',
    objects: [],
    spatialGroups: [],
    lights: [],
    timelines: [],
    audio: [],
    zones: [],
    transitions: [],
    ...overrides,
  } as HoloComposition;
}

function createObject(name: string, overrides: Partial<HoloObjectDecl> = {}): HoloObjectDecl {
  return {
    type: 'ObjectDecl',
    name,
    properties: [],
    traits: [],
    children: [],
    ...overrides,
  } as HoloObjectDecl;
}

function prop(key: string, value: any): { key: string; value: any } {
  return { key, value };
}

function trait(
  name: string,
  config?: Record<string, any>
): { name: string; config: Record<string, any> } {
  return { name, config: config || {} };
}

function createLight(overrides: Partial<HoloLight> & { lightType?: string } = {}): HoloLight {
  return {
    name: 'TestLight',
    lightType: overrides.lightType || 'point',
    properties: overrides.properties || [prop('position', [0, 5, 0]), prop('intensity', 1.0)],
    ...overrides,
  } as HoloLight;
}

// ============================================================================
// Tests
// ============================================================================

describe('PlayCanvasCompiler', () => {
  let compiler: PlayCanvasCompiler;

  beforeEach(() => {
    compiler = new PlayCanvasCompiler();
  });

  // --------------------------------------------------------------------------
  // Constructor
  // --------------------------------------------------------------------------

  describe('constructor', () => {
    it('should create with default options', () => {
      expect(compiler).toBeDefined();
      expect(compiler).toBeInstanceOf(PlayCanvasCompiler);
    });

    it('should accept custom class name', () => {
      const c = new PlayCanvasCompiler({ className: 'MyScene' });
      const output = c.compile(createComposition());
      expect(output).toContain('export class MyScene');
    });

    it('should accept custom indent', () => {
      const c = new PlayCanvasCompiler({ indent: '    ' });
      const output = c.compile(createComposition());
      expect(output).toContain('    ');
    });

    it('should default className to GeneratedScene', () => {
      const output = compiler.compile(createComposition());
      expect(output).toContain('export class GeneratedScene');
    });
  });

  // --------------------------------------------------------------------------
  // Basic Compilation
  // --------------------------------------------------------------------------

  describe('compile()', () => {
    it('should produce a string', () => {
      const result = compiler.compile(createComposition());
      expect(typeof result).toBe('string');
    });

    it('should include auto-generated comment', () => {
      const output = compiler.compile(createComposition());
      expect(output).toContain('// Auto-generated by HoloScript PlayCanvasCompiler');
    });

    it('should include source composition name', () => {
      const output = compiler.compile(createComposition({ name: 'MyWorld' }));
      expect(output).toContain('Source: composition "MyWorld"');
    });

    it('should emit imports', () => {
      const output = compiler.compile(createComposition());
      expect(output).toContain('import * as pc from "playcanvas"');
    });

    it('should emit the class structure', () => {
      const output = compiler.compile(createComposition());
      expect(output).toContain('export class GeneratedScene');
      expect(output).toContain('private app: pc.Application');
      expect(output).toContain('constructor(canvas: HTMLCanvasElement)');
    });

    it('should emit build method', () => {
      const output = compiler.compile(createComposition());
      expect(output).toContain('async build(): Promise<void>');
    });

    it('should emit dispose method', () => {
      const output = compiler.compile(createComposition());
      expect(output).toContain('dispose(): void');
      expect(output).toContain('this.app.destroy()');
    });

    it('should emit app.start()', () => {
      const output = compiler.compile(createComposition());
      expect(output).toContain('this.app.start()');
    });

    it('should emit default light when no lights specified', () => {
      const output = compiler.compile(createComposition({ lights: [] }));
      expect(output).toContain('defaultLight');
      expect(output).toContain('"light"');
    });

    it('should emit default camera when no camera specified', () => {
      const output = compiler.compile(createComposition());
      expect(output).toContain('defaultCamera');
      expect(output).toContain('"camera"');
    });

    it('should emit canvas fill mode', () => {
      const output = compiler.compile(createComposition());
      expect(output).toContain('setCanvasFillMode');
    });

    it('should emit resize handler', () => {
      const output = compiler.compile(createComposition());
      expect(output).toContain('resizeCanvas');
    });
  });

  // --------------------------------------------------------------------------
  // Imports
  // --------------------------------------------------------------------------

  describe('imports', () => {
    it('should include PlayCanvas import', () => {
      const output = compiler.compile(createComposition());
      expect(output).toContain('import * as pc from "playcanvas"');
    });
  });

  // --------------------------------------------------------------------------
  // Objects
  // --------------------------------------------------------------------------

  describe('objects', () => {
    it('should emit entity for basic object', () => {
      const output = compiler.compile(
        createComposition({
          objects: [createObject('MyCube')],
        })
      );
      expect(output).toContain('new pc.Entity("MyCube")');
    });

    it('should emit render component for geometry', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('MySphere', {
              properties: [prop('geometry', 'sphere')],
            } as any),
          ],
        })
      );
      expect(output).toContain('"sphere"');
      expect(output).toContain('"render"');
    });

    it('should map cube to box primitive', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('MyCube', {
              properties: [prop('geometry', 'cube')],
            } as any),
          ],
        })
      );
      expect(output).toContain('"box"');
    });

    it('should emit position', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Obj', {
              properties: [prop('position', [1, 2, 3])],
            } as any),
          ],
        })
      );
      expect(output).toContain('setPosition(1, 2, 3)');
    });

    it('should emit rotation', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Obj', {
              properties: [prop('rotation', [45, 90, 0])],
            } as any),
          ],
        })
      );
      expect(output).toContain('setEulerAngles(45, 90, 0)');
    });

    it('should emit uniform scale', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Obj', {
              properties: [prop('scale', 2)],
            } as any),
          ],
        })
      );
      expect(output).toContain('setLocalScale(2, 2, 2)');
    });

    it('should emit array scale', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Obj', {
              properties: [prop('scale', [1, 2, 3])],
            } as any),
          ],
        })
      );
      expect(output).toContain('setLocalScale(1, 2, 3)');
    });

    it('should emit material with color', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Obj', {
              properties: [prop('color', '#ff0000')],
            } as any),
          ],
        })
      );
      expect(output).toContain('StandardMaterial');
      expect(output).toContain('diffuse');
    });

    it('should emit material with roughness', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Obj', {
              properties: [prop('roughness', 0.5)],
            } as any),
          ],
        })
      );
      expect(output).toContain('shininess');
    });

    it('should emit material with opacity', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Obj', {
              properties: [prop('opacity', 0.5)],
            } as any),
          ],
        })
      );
      expect(output).toContain('opacity');
      expect(output).toContain('BLEND_NORMAL');
    });

    it('should emit material with metalness', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Obj', {
              properties: [prop('metalness', 0.8)],
            } as any),
          ],
        })
      );
      expect(output).toContain('metalness');
    });

    it('should emit material with emissive', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Obj', {
              properties: [prop('emissive', '#00ff00')],
            } as any),
          ],
        })
      );
      expect(output).toContain('emissive');
    });

    it('should emit text element for text object', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Label', {
              properties: [prop('text', 'Hello World')],
            } as any),
          ],
        })
      );
      expect(output).toContain('"element"');
      expect(output).toContain('"text"');
      expect(output).toContain('Hello World');
    });

    it('should emit model loading comment for src', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Model', {
              properties: [prop('src', 'model.glb')],
            } as any),
          ],
        })
      );
      expect(output).toContain('Model: model.glb');
      expect(output).toContain('"asset"');
    });

    it('should add entity to app root', () => {
      const output = compiler.compile(
        createComposition({
          objects: [createObject('Obj')],
        })
      );
      expect(output).toContain('this.app.root.addChild');
    });

    it('should emit grabbable trait as button component', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Grab', {
              traits: [trait('grabbable')],
            } as any),
          ],
        })
      );
      expect(output).toContain('"button"');
      expect(output).toContain('click');
    });

    it('should emit physics/collidable trait as rigidbody', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Phys', {
              traits: [trait('physics')],
            } as any),
          ],
        })
      );
      expect(output).toContain('"rigidbody"');
      expect(output).toContain('"collision"');
    });

    it('should emit static physics', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Wall', {
              traits: [trait('physics', { type: 'static' })],
            } as any),
          ],
        })
      );
      expect(output).toContain('"static"');
    });

    it('should emit physics mass', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Heavy', {
              traits: [trait('physics', { mass: 10 })],
            } as any),
          ],
        })
      );
      expect(output).toContain('mass: 10');
    });

    it('should emit shadow trait', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Obj', {
              traits: [trait('shadow')],
            } as any),
          ],
        })
      );
      expect(output).toContain('castShadows');
      expect(output).toContain('receiveShadows');
    });

    it('should emit hoverable trait', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Obj', {
              traits: [trait('hoverable')],
            } as any),
          ],
        })
      );
      expect(output).toContain('mouseenter');
      expect(output).toContain('mouseleave');
    });

    it('should emit accessible trait comment', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Obj', {
              traits: [trait('accessible', { role: 'button' })],
            } as any),
          ],
        })
      );
      expect(output).toContain('@accessible');
      expect(output).toContain('button');
    });

    it('should emit unknown trait as comment', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Obj', {
              traits: [trait('custom_trait', { foo: 'bar' })],
            } as any),
          ],
        })
      );
      expect(output).toContain('@custom_trait');
    });

    it('should emit children under parent variable', () => {
      const child = createObject('Child', {
        properties: [prop('geometry', 'sphere')],
      } as any);
      const parent = createObject('Parent', {
        children: [child],
      } as any);
      const output = compiler.compile(
        createComposition({
          objects: [parent],
        })
      );
      expect(output).toContain('Child');
      expect(output).toContain('Parent');
    });

    it('should handle all geometry types', () => {
      const geos = ['sphere', 'cube', 'cylinder', 'cone', 'plane', 'torus', 'capsule'];
      for (const g of geos) {
        const output = compiler.compile(
          createComposition({
            objects: [createObject(`Obj_${g}`, { properties: [prop('geometry', g)] } as any)],
          })
        );
        expect(output).toContain('addComponent("render"');
      }
    });

    it('should handle material object property', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Obj', {
              properties: [prop('material', { roughness: 0.3, metalness: 0.9 })],
            } as any),
          ],
        })
      );
      expect(output).toContain('shininess');
      expect(output).toContain('metalness');
    });
  });

  // --------------------------------------------------------------------------
  // Spatial Groups
  // --------------------------------------------------------------------------

  describe('spatial groups', () => {
    it('should emit entity for group', () => {
      const output = compiler.compile(
        createComposition({
          spatialGroups: [
            {
              name: 'MyGroup',
              objects: [],
              properties: [],
            },
          ] as any,
        })
      );
      expect(output).toContain('new pc.Entity("MyGroup")');
    });

    it('should emit group with position', () => {
      const output = compiler.compile(
        createComposition({
          spatialGroups: [
            {
              name: 'G1',
              objects: [],
              properties: [prop('position', [1, 2, 3])],
            },
          ] as any,
        })
      );
      expect(output).toContain('setPosition(1, 2, 3)');
    });

    it('should emit group with rotation', () => {
      const output = compiler.compile(
        createComposition({
          spatialGroups: [
            {
              name: 'G1',
              objects: [],
              properties: [prop('rotation', [0, 45, 0])],
            },
          ] as any,
        })
      );
      expect(output).toContain('setEulerAngles(0, 45, 0)');
    });

    it('should emit group with scale', () => {
      const output = compiler.compile(
        createComposition({
          spatialGroups: [
            {
              name: 'G1',
              objects: [],
              properties: [prop('scale', 2)],
            },
          ] as any,
        })
      );
      expect(output).toContain('setLocalScale(2, 2, 2)');
    });

    it('should add children objects to group', () => {
      const output = compiler.compile(
        createComposition({
          spatialGroups: [
            {
              name: 'Arena',
              objects: [createObject('Fighter')],
              properties: [],
            },
          ] as any,
        })
      );
      expect(output).toContain('Arena');
      expect(output).toContain('Fighter');
    });

    it('should support nested groups', () => {
      const output = compiler.compile(
        createComposition({
          spatialGroups: [
            {
              name: 'Outer',
              objects: [],
              properties: [],
              groups: [
                {
                  name: 'Inner',
                  objects: [createObject('DeepObj')],
                  properties: [],
                },
              ],
            },
          ] as any,
        })
      );
      expect(output).toContain('Outer');
      expect(output).toContain('Inner');
      expect(output).toContain('DeepObj');
    });
  });

  // --------------------------------------------------------------------------
  // Lights
  // --------------------------------------------------------------------------

  describe('lights', () => {
    it('should emit point light', () => {
      const output = compiler.compile(
        createComposition({
          lights: [createLight({ lightType: 'point' })],
        })
      );
      expect(output).toContain('"point"');
      expect(output).toContain('"light"');
    });

    it('should emit directional light', () => {
      const output = compiler.compile(
        createComposition({
          lights: [createLight({ lightType: 'directional' })],
        })
      );
      expect(output).toContain('"directional"');
    });

    it('should emit spot light', () => {
      const output = compiler.compile(
        createComposition({
          lights: [
            createLight({
              lightType: 'spot',
              properties: [prop('position', [0, 5, 0]), prop('angle', Math.PI / 4)],
            }),
          ],
        })
      );
      expect(output).toContain('"spot"');
      expect(output).toContain('outerConeAngle');
    });

    it('should emit hemisphere as directional', () => {
      const output = compiler.compile(
        createComposition({
          lights: [createLight({ lightType: 'hemisphere' })],
        })
      );
      expect(output).toContain('"directional"');
    });

    it('should emit light color', () => {
      const output = compiler.compile(
        createComposition({
          lights: [
            createLight({ properties: [prop('color', '#ff0000'), prop('position', [0, 5, 0])] }),
          ],
        })
      );
      expect(output).toContain('pc.Color');
    });

    it('should emit light intensity', () => {
      const output = compiler.compile(
        createComposition({
          lights: [
            createLight({ properties: [prop('intensity', 2.0), prop('position', [0, 5, 0])] }),
          ],
        })
      );
      expect(output).toContain('intensity: 2');
    });

    it('should emit cast shadows', () => {
      const output = compiler.compile(
        createComposition({
          lights: [
            createLight({ properties: [prop('cast_shadow', true), prop('position', [0, 5, 0])] }),
          ],
        })
      );
      expect(output).toContain('castShadows: true');
    });

    it('should emit light range', () => {
      const output = compiler.compile(
        createComposition({
          lights: [
            createLight({ properties: [prop('distance', 50), prop('position', [0, 5, 0])] }),
          ],
        })
      );
      expect(output).toContain('range: 50');
    });

    it('should add light to root', () => {
      const output = compiler.compile(
        createComposition({
          lights: [createLight()],
        })
      );
      expect(output).toContain('this.app.root.addChild');
    });
  });

  // --------------------------------------------------------------------------
  // Camera
  // --------------------------------------------------------------------------

  describe('camera', () => {
    it('should emit camera entity', () => {
      const cam: HoloCamera = {
        cameraType: 'perspective',
        properties: [prop('position', [0, 5, -10])],
      } as any;
      const output = compiler.compile(createComposition({ camera: cam }));
      expect(output).toContain('new pc.Entity("camera")');
      expect(output).toContain('"camera"');
    });

    it('should emit orthographic camera', () => {
      const cam: HoloCamera = {
        cameraType: 'orthographic',
        properties: [],
      } as any;
      const output = compiler.compile(createComposition({ camera: cam }));
      expect(output).toContain('PROJECTION_ORTHOGRAPHIC');
    });

    it('should emit camera position', () => {
      const cam: HoloCamera = {
        cameraType: 'perspective',
        properties: [prop('position', [5, 10, 15])],
      } as any;
      const output = compiler.compile(createComposition({ camera: cam }));
      expect(output).toContain('setPosition(5, 10, 15)');
    });

    it('should emit camera lookAt', () => {
      const cam: HoloCamera = {
        cameraType: 'perspective',
        properties: [prop('look_at', [0, 0, 0])],
      } as any;
      const output = compiler.compile(createComposition({ camera: cam }));
      expect(output).toContain('lookAt(0, 0, 0)');
    });

    it('should emit camera fov', () => {
      const cam: HoloCamera = {
        cameraType: 'perspective',
        properties: [prop('fov', 75)],
      } as any;
      const output = compiler.compile(createComposition({ camera: cam }));
      expect(output).toContain('fov: 75');
    });

    it('should emit camera near/far', () => {
      const cam: HoloCamera = {
        cameraType: 'perspective',
        properties: [prop('near', 0.1), prop('far', 1000)],
      } as any;
      const output = compiler.compile(createComposition({ camera: cam }));
      expect(output).toContain('nearClip: 0.1');
      expect(output).toContain('farClip: 1000');
    });
  });

  // --------------------------------------------------------------------------
  // Audio
  // --------------------------------------------------------------------------

  describe('audio', () => {
    it('should emit sound entity', () => {
      const audio: HoloAudio = {
        name: 'BGMusic',
        properties: [prop('src', 'music.mp3')],
      } as any;
      const output = compiler.compile(createComposition({ audio: [audio] }));
      expect(output).toContain('new pc.Entity("BGMusic")');
      expect(output).toContain('"sound"');
    });

    it('should emit loop setting', () => {
      const audio: HoloAudio = {
        name: 'Loop',
        properties: [prop('loop', true), prop('src', 'test.mp3')],
      } as any;
      const output = compiler.compile(createComposition({ audio: [audio] }));
      expect(output).toContain('loop: true');
    });

    it('should emit volume setting', () => {
      const audio: HoloAudio = {
        name: 'Quiet',
        properties: [prop('volume', 0.5), prop('src', 'test.mp3')],
      } as any;
      const output = compiler.compile(createComposition({ audio: [audio] }));
      expect(output).toContain('volume: 0.5');
    });

    it('should emit spatial audio', () => {
      const audio: HoloAudio = {
        name: 'Spatial',
        properties: [prop('spatial', true), prop('src', 'test.mp3')],
      } as any;
      const output = compiler.compile(createComposition({ audio: [audio] }));
      expect(output).toContain('positional: true');
    });
  });

  // --------------------------------------------------------------------------
  // Zones
  // --------------------------------------------------------------------------

  describe('zones', () => {
    it('should emit zone with box collision', () => {
      const zone: HoloZone = {
        name: 'SafeZone',
        properties: [prop('size', [10, 10, 10])],
        handlers: [],
      } as any;
      const output = compiler.compile(createComposition({ zones: [zone] }));
      expect(output).toContain('"collision"');
      expect(output).toContain('"box"');
    });

    it('should emit zone with sphere collision', () => {
      const zone: HoloZone = {
        name: 'Sphere',
        properties: [prop('shape', 'sphere'), prop('radius', 8)],
        handlers: [],
      } as any;
      const output = compiler.compile(createComposition({ zones: [zone] }));
      expect(output).toContain('"sphere"');
      expect(output).toContain('radius: 8');
    });

    it('should emit zone position', () => {
      const zone: HoloZone = {
        name: 'Z1',
        properties: [prop('position', [5, 0, 5])],
        handlers: [],
      } as any;
      const output = compiler.compile(createComposition({ zones: [zone] }));
      expect(output).toContain('setPosition(5, 0, 5)');
    });

    it('should emit zone trigger handlers', () => {
      const zone: HoloZone = {
        name: 'Trigger',
        properties: [],
        handlers: [
          { event: 'on_enter', body: {} },
          { event: 'on_exit', body: {} },
        ],
      } as any;
      const output = compiler.compile(createComposition({ zones: [zone] }));
      expect(output).toContain('triggerenter');
      expect(output).toContain('triggerleave');
    });
  });

  // --------------------------------------------------------------------------
  // UI
  // --------------------------------------------------------------------------

  describe('ui', () => {
    it('should emit screen entity', () => {
      const ui: HoloUI = {
        elements: [{ name: 'Label', properties: [prop('type', 'text'), prop('text', 'Hello')] }],
      } as any;
      const output = compiler.compile(createComposition({ ui }));
      expect(output).toContain('screenEntity');
      expect(output).toContain('"screen"');
    });

    it('should emit text element', () => {
      const ui: HoloUI = {
        elements: [{ name: 'Title', properties: [prop('type', 'text'), prop('text', 'Game')] }],
      } as any;
      const output = compiler.compile(createComposition({ ui }));
      expect(output).toContain('"text"');
      expect(output).toContain('Game');
    });

    it('should emit button element', () => {
      const ui: HoloUI = {
        elements: [{ name: 'Btn', properties: [prop('type', 'button'), prop('text', 'Start')] }],
      } as any;
      const output = compiler.compile(createComposition({ ui }));
      expect(output).toContain('"button"');
      expect(output).toContain('Start');
    });

    it('should emit progress element', () => {
      const ui: HoloUI = {
        elements: [{ name: 'Bar', properties: [prop('type', 'progress')] }],
      } as any;
      const output = compiler.compile(createComposition({ ui }));
      expect(output).toContain('"image"');
    });
  });

  // --------------------------------------------------------------------------
  // Effects
  // --------------------------------------------------------------------------

  describe('effects', () => {
    it('should emit bloom effect', () => {
      const effects: HoloEffects = {
        effects: [{ effectType: 'bloom', properties: { intensity: 0.5 } }],
      } as any;
      const output = compiler.compile(createComposition({ effects }));
      expect(output).toContain('Bloom');
      expect(output).toContain('toneMapping');
    });

    it('should emit ssao effect', () => {
      const effects: HoloEffects = {
        effects: [{ effectType: 'ssao', properties: { radius: 2 } }],
      } as any;
      const output = compiler.compile(createComposition({ effects }));
      expect(output).toContain('SSAO');
    });

    it('should emit tone_mapping effect', () => {
      const effects: HoloEffects = {
        effects: [{ effectType: 'tone_mapping', properties: {} }],
      } as any;
      const output = compiler.compile(createComposition({ effects }));
      expect(output).toContain('TONEMAP_ACES');
    });

    it('should emit unknown effect as comment', () => {
      const effects: HoloEffects = {
        effects: [{ effectType: 'custom_fx', properties: { amount: 3 } }],
      } as any;
      const output = compiler.compile(createComposition({ effects }));
      expect(output).toContain('custom_fx');
    });
  });

  // --------------------------------------------------------------------------
  // Environment
  // --------------------------------------------------------------------------

  describe('environment', () => {
    it('should emit skybox setup', () => {
      const env: HoloEnvironment = {
        properties: [prop('skybox', 'sunset')],
      } as any;
      const output = compiler.compile(createComposition({ environment: env }));
      expect(output).toContain('skybox');
      expect(output).toContain('sunset');
    });

    it('should emit fog setup', () => {
      const env: HoloEnvironment = {
        properties: [prop('fog', { color: '#888888', near: 10, far: 100 })],
      } as any;
      const output = compiler.compile(createComposition({ environment: env }));
      expect(output).toContain('FOG_LINEAR');
      expect(output).toContain('fogStart');
      expect(output).toContain('fogEnd');
    });

    it('should emit ambient light', () => {
      const env: HoloEnvironment = {
        properties: [prop('ambient_light', 0.3)],
      } as any;
      const output = compiler.compile(createComposition({ environment: env }));
      expect(output).toContain('ambientLight');
    });

    it('should emit ground', () => {
      const env: HoloEnvironment = {
        properties: [prop('ground', { color: '#336633' })],
      } as any;
      const output = compiler.compile(createComposition({ environment: env }));
      expect(output).toContain('ground');
      expect(output).toContain('"plane"');
    });
  });

  // --------------------------------------------------------------------------
  // Transitions
  // --------------------------------------------------------------------------

  describe('transitions', () => {
    it('should emit transition comment', () => {
      const tr: HoloTransition = {
        name: 'GoToLevel2',
        properties: [prop('target', 'Level2'), prop('effect', 'fade'), prop('duration', 2)],
      } as any;
      const output = compiler.compile(createComposition({ transitions: [tr] }));
      expect(output).toContain('Transition "GoToLevel2"');
      expect(output).toContain('Level2');
      expect(output).toContain('fade');
    });
  });

  // --------------------------------------------------------------------------
  // XR
  // --------------------------------------------------------------------------

  describe('XR support', () => {
    it('should emit XR setup when enabled', () => {
      const c = new PlayCanvasCompiler({ enableXR: true });
      const output = c.compile(createComposition());
      expect(output).toContain('this.app.xr.supported');
      expect(output).toContain('XRTYPE_VR');
    });

    it('should NOT emit XR when disabled', () => {
      const c = new PlayCanvasCompiler({ enableXR: false });
      const output = c.compile(createComposition());
      expect(output).not.toContain('XRTYPE_VR');
    });
  });

  // --------------------------------------------------------------------------
  // Physics
  // --------------------------------------------------------------------------

  describe('physics setup', () => {
    it('should set gravity when physics enabled', () => {
      const c = new PlayCanvasCompiler({ enablePhysics: true });
      const output = c.compile(createComposition());
      expect(output).toContain('setGravity');
      expect(output).toContain('-9.81');
    });

    it('should NOT set gravity when physics disabled', () => {
      const c = new PlayCanvasCompiler({ enablePhysics: false });
      const output = c.compile(createComposition());
      expect(output).not.toContain('setGravity');
    });
  });

  // --------------------------------------------------------------------------
  // Color Conversion
  // --------------------------------------------------------------------------

  describe('color conversion', () => {
    it('should convert hex to pc.Color', () => {
      const output = compiler.compile(
        createComposition({
          objects: [createObject('Obj', { properties: [prop('color', '#ff0000')] } as any)],
        })
      );
      expect(output).toContain('new pc.Color(1.000, 0.000, 0.000)');
    });

    it('should handle white color', () => {
      const output = compiler.compile(
        createComposition({
          objects: [createObject('Obj', { properties: [prop('color', '#ffffff')] } as any)],
        })
      );
      expect(output).toContain('new pc.Color(1.000, 1.000, 1.000)');
    });

    it('should handle object color format', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Obj', { properties: [prop('color', { r: 255, g: 128, b: 0 })] } as any),
          ],
        })
      );
      expect(output).toContain('pc.Color');
    });
  });

  // --------------------------------------------------------------------------
  // Timeline
  // --------------------------------------------------------------------------

  describe('timeline', () => {
    it('should emit timeline comments', () => {
      const tl: HoloTimeline = {
        name: 'Intro',
        entries: [
          {
            time: 0,
            action: { kind: 'animate', target: 'cube', properties: { position: [0, 1, 0] } },
          },
          { time: 1, action: { kind: 'emit', event: 'start' } },
          { time: 2, action: { kind: 'call', method: 'doSomething' } },
        ],
        autoplay: true,
        loop: true,
      } as any;
      const output = compiler.compile(createComposition({ timelines: [tl] }));
      expect(output).toContain('Timeline: "Intro"');
      expect(output).toContain('autoplay');
    });
  });

  // --------------------------------------------------------------------------
  // TraitCompositor Integration
  // --------------------------------------------------------------------------

  describe('trait compositor', () => {
    it('should apply TraitCompositor for multi-trait objects', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('MultiTrait', {
              traits: [trait('glowing'), trait('emissive')],
            } as any),
          ],
        })
      );
      expect(output).toContain('TraitCompositor');
    });

    it('should compose material when compositor returns properties', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('GlowObj', {
              traits: [trait('glowing'), trait('transparent')],
            } as any),
          ],
        })
      );
      // Should have composition comment and material creation
      expect(output).toContain('composed');
      expect(output).toContain('StandardMaterial');
    });
  });

  // --------------------------------------------------------------------------
  // Complex Compositions
  // --------------------------------------------------------------------------

  describe('complex compositions', () => {
    it('should compile full scene with multiple components', () => {
      const output = compiler.compile(
        createComposition({
          name: 'FullScene',
          environment: { properties: [prop('ambient_light', 0.5)] } as any,
          lights: [
            createLight({ name: 'Sun', lightType: 'directional' }),
            createLight({ name: 'Fill', lightType: 'point' }),
          ],
          camera: { cameraType: 'perspective', properties: [prop('position', [0, 5, -10])] } as any,
          objects: [
            createObject('Floor', {
              properties: [prop('geometry', 'plane'), prop('scale', 10)],
            } as any),
            createObject('Cube', {
              properties: [
                prop('geometry', 'cube'),
                prop('position', [0, 1, 0]),
                prop('color', '#00ff00'),
              ],
            } as any),
          ],
          spatialGroups: [
            {
              name: 'Props',
              objects: [
                createObject('Sphere', { properties: [prop('geometry', 'sphere')] } as any),
              ],
              properties: [prop('position', [5, 0, 0])],
            },
          ] as any,
        })
      );
      expect(output).toContain('FullScene');
      expect(output).toContain('Sun');
      expect(output).toContain('Fill');
      expect(output).toContain('Floor');
      expect(output).toContain('Cube');
      expect(output).toContain('Props');
      expect(output).toContain('Sphere');
    });

    it('should compile scene with physics objects', () => {
      const output = compiler.compile(
        createComposition({
          objects: [
            createObject('Ball', {
              properties: [prop('geometry', 'sphere'), prop('position', [0, 5, 0])],
              traits: [trait('physics', { mass: 2, restitution: 0.8 }), trait('grabbable')],
            } as any),
          ],
        })
      );
      expect(output).toContain('rigidbody');
      expect(output).toContain('mass: 2');
      expect(output).toContain('restitution: 0.8');
      expect(output).toContain('button');
    });
  });
});
