/**
 * Shared scene presets extracted from the retired R3FCompiler.
 * Used by GLTFPipeline, USDZPipeline, and HoloScriptLSP for material/environment resolution.
 */

export const MATERIAL_PRESETS: Record<string, Record<string, unknown>> = {
  plastic: { roughness: 0.5, metalness: 0.0, clearcoat: 0.1 },
  metal: { roughness: 0.2, metalness: 1.0 },
  chrome: { roughness: 0.05, metalness: 1.0, envMapIntensity: 1.5 },
  gold: { roughness: 0.3, metalness: 1.0, color: '#ffd700' },
  copper: { roughness: 0.4, metalness: 1.0, color: '#b87333' },
  glass: {
    roughness: 0.0,
    metalness: 0.0,
    transmission: 0.95,
    ior: 1.5,
    thickness: 0.5,
    transparent: true,
  },
  crystal: {
    roughness: 0.0,
    metalness: 0.1,
    transmission: 0.9,
    ior: 2.0,
    iridescence: 1.0,
    iridescenceIOR: 1.3,
  },
  wood: { roughness: 0.8, metalness: 0.0 },
  fabric: {
    roughness: 0.95,
    metalness: 0.0,
    sheen: 0.5,
    sheenRoughness: 0.8,
    sheenColor: '#ffffff',
  },
  rubber: { roughness: 0.9, metalness: 0.0 },
  leather: {
    roughness: 0.7,
    metalness: 0.0,
    sheen: 0.3,
    sheenRoughness: 0.6,
    sheenColor: '#3d2b1f',
  },
  water: {
    roughness: 0.0,
    metalness: 0.0,
    transmission: 0.9,
    ior: 1.33,
    transparent: true,
    color: '#006994',
  },
  emissive: { roughness: 0.5, metalness: 0.0, emissiveIntensity: 2.0 },
  hologram: {
    roughness: 0.0,
    metalness: 0.3,
    transparent: true,
    opacity: 0.6,
    emissiveIntensity: 1.0,
  },
  stone: { roughness: 0.85, metalness: 0.0, color: '#808080' },
  marble: { roughness: 0.15, metalness: 0.0, color: '#F0EDE6', envMapIntensity: 0.8 },
  shiny: { roughness: 0.05, metalness: 0.3, envMapIntensity: 1.5, clearcoat: 0.8 },
  neon: {
    roughness: 0.0,
    metalness: 0.0,
    emissiveIntensity: 3.0,
    transparent: true,
    opacity: 0.9,
  },
  toon: { roughness: 1.0, metalness: 0.0 },
  wireframe: { roughness: 0.5, metalness: 0.5, wireframe: true },
  velvet: {
    roughness: 1.0,
    metalness: 0.0,
    sheen: 1.0,
    sheenRoughness: 0.8,
    sheenColor: '#ffffff',
    clearcoat: 0.3,
  },
  xray: { roughness: 0.0, metalness: 0.0, transparent: true, opacity: 0.3, emissiveIntensity: 0.5 },
  gradient: { roughness: 0.5, metalness: 0.0 },
  matte: { roughness: 1.0, metalness: 0.0 },

  // ===========================================================================
  // REALISTIC FABRICS — differentiated by sheen, roughness, and anisotropy
  // ===========================================================================
  cotton: {
    roughness: 0.95,
    metalness: 0.0,
    sheen: 0.6,
    sheenRoughness: 0.9,
    sheenColor: '#ffffff',
  },
  polyester: {
    roughness: 0.7,
    metalness: 0.0,
    sheen: 0.8,
    sheenRoughness: 0.4,
    sheenColor: '#e8e8e8',
  },
  silk: {
    roughness: 0.3,
    metalness: 0.0,
    sheen: 1.0,
    sheenRoughness: 0.2,
    sheenColor: '#fffaf0',
    anisotropy: 0.8,
    anisotropyRotation: 0,
  },
  satin: {
    roughness: 0.25,
    metalness: 0.0,
    sheen: 0.9,
    sheenRoughness: 0.15,
    sheenColor: '#fff5ee',
    anisotropy: 0.6,
    anisotropyRotation: 0,
  },
  linen: {
    roughness: 0.9,
    metalness: 0.0,
    sheen: 0.4,
    sheenRoughness: 0.85,
    sheenColor: '#f5f0e8',
  },
  wool: {
    roughness: 1.0,
    metalness: 0.0,
    sheen: 0.7,
    sheenRoughness: 1.0,
    sheenColor: '#e8dcc8',
  },
  denim: {
    roughness: 0.85,
    metalness: 0.0,
    color: '#2b4570',
    sheen: 0.5,
    sheenRoughness: 0.7,
    sheenColor: '#4a6fa5',
  },
  canvas: {
    roughness: 0.95,
    metalness: 0.0,
    color: '#c8b88a',
    sheen: 0.3,
    sheenRoughness: 0.9,
    sheenColor: '#d4c9a8',
  },
  burlap: {
    roughness: 1.0,
    metalness: 0.0,
    color: '#8b7355',
    sheen: 0.2,
    sheenRoughness: 1.0,
    sheenColor: '#a08060',
  },

  // ===========================================================================
  // SKIN & ORGANIC — differentiated by subsurface scattering
  // ===========================================================================
  skin: {
    roughness: 0.5,
    metalness: 0.0,
    color: '#e8b89d',
    thickness: 0.8,
    attenuationColor: '#cc4422',
    attenuationDistance: 0.5,
  },
  skin_dark: {
    roughness: 0.45,
    metalness: 0.0,
    color: '#8d5524',
    thickness: 1.0,
    attenuationColor: '#661111',
    attenuationDistance: 0.3,
  },
  // Dragon / creature material presets
  dragon_bone: {
    roughness: 0.35,
    metalness: 0.15,
    color: '#e8dcc8',
  },
  dragon_leather: {
    roughness: 0.8,
    metalness: 0.0,
    color: '#5c3a21',
  },
  dragon_scale: {
    roughness: 0.25,
    metalness: 0.4,
    color: '#1a0d3d',
  },
  obsidian: {
    roughness: 0.05,
    metalness: 0.1,
    color: '#0d0d0d',
    clearcoat: 0.9,
    clearcoatRoughness: 0.1,
    envMapIntensity: 1.2,
  },
  skin_pale: {
    roughness: 0.55,
    metalness: 0.0,
    color: '#fde0c8',
    thickness: 0.6,
    attenuationColor: '#ee5533',
    attenuationDistance: 0.6,
  },
  candle_wax: {
    roughness: 0.7,
    metalness: 0.0,
    color: '#fff8dc',
    thickness: 2.0,
    attenuationColor: '#ffaa44',
    attenuationDistance: 0.3,
    transmission: 0.15,
  },
  jade: {
    roughness: 0.2,
    metalness: 0.0,
    color: '#00a86b',
    thickness: 1.5,
    attenuationColor: '#004d32',
    attenuationDistance: 1.0,
    transmission: 0.1,
  },
  milk: {
    roughness: 0.3,
    metalness: 0.0,
    color: '#fdfff5',
    thickness: 1.0,
    attenuationColor: '#fff5d6',
    attenuationDistance: 0.2,
    transmission: 0.6,
    ior: 1.35,
  },
  leaf: {
    roughness: 0.6,
    metalness: 0.0,
    color: '#228b22',
    thickness: 0.3,
    attenuationColor: '#44cc22',
    attenuationDistance: 0.5,
  },
  honey: {
    roughness: 0.1,
    metalness: 0.0,
    color: '#eb9605',
    thickness: 1.5,
    attenuationColor: '#cc6600',
    attenuationDistance: 0.4,
    transmission: 0.7,
    ior: 1.5,
  },

  // ===========================================================================
  // MUD & EARTH — differentiated by roughness, color, and subtle properties
  // ===========================================================================
  clay_mud: {
    roughness: 0.95,
    metalness: 0.0,
    color: '#8b4513',
    thickness: 0.5,
    attenuationColor: '#663311',
    attenuationDistance: 0.8,
  },
  sandy_mud: {
    roughness: 0.85,
    metalness: 0.02,
    color: '#c2a66b',
  },
  wet_mud: {
    roughness: 0.4,
    metalness: 0.0,
    color: '#3d2b1f',
    clearcoat: 0.6,
    clearcoatRoughness: 0.2,
  },
  dry_earth: {
    roughness: 1.0,
    metalness: 0.0,
    color: '#9b7653',
  },
  peat: {
    roughness: 0.9,
    metalness: 0.0,
    color: '#2d1f0e',
  },
  red_clay: {
    roughness: 0.95,
    metalness: 0.0,
    color: '#cc4b2e',
    thickness: 0.4,
    attenuationColor: '#993322',
    attenuationDistance: 0.6,
  },
  volcanic_ash: {
    roughness: 0.8,
    metalness: 0.05,
    color: '#3c3c3c',
  },
  wet_sand: {
    roughness: 0.6,
    metalness: 0.02,
    color: '#c2b280',
    clearcoat: 0.3,
    clearcoatRoughness: 0.4,
  },
  dry_sand: {
    roughness: 0.95,
    metalness: 0.02,
    color: '#e0cc8e',
  },

  // ===========================================================================
  // METALS (BRUSHED/ANISOTROPIC) — directional roughness
  // ===========================================================================
  brushed_steel: {
    roughness: 0.35,
    metalness: 1.0,
    color: '#c0c0c0',
    anisotropy: 0.7,
    anisotropyRotation: 0,
  },
  brushed_aluminum: {
    roughness: 0.3,
    metalness: 1.0,
    color: '#d0d0d0',
    anisotropy: 0.8,
    anisotropyRotation: 0,
  },
  brushed_copper: {
    roughness: 0.35,
    metalness: 1.0,
    color: '#b87333',
    anisotropy: 0.6,
    anisotropyRotation: 0,
  },
  cast_iron: {
    roughness: 0.7,
    metalness: 0.9,
    color: '#3a3a3a',
  },
  bronze: {
    roughness: 0.45,
    metalness: 1.0,
    color: '#cd7f32',
  },
  silver: {
    roughness: 0.15,
    metalness: 1.0,
    color: '#c0c0c0',
    envMapIntensity: 1.3,
  },
  platinum: {
    roughness: 0.2,
    metalness: 1.0,
    color: '#e5e4e2',
    envMapIntensity: 1.2,
  },
  rust: {
    roughness: 0.9,
    metalness: 0.3,
    color: '#8b3a15',
  },

  // ===========================================================================
  // HAIR & FIBERS — anisotropy-driven
  // ===========================================================================
  hair_dark: {
    roughness: 0.35,
    metalness: 0.0,
    color: '#1a1209',
    anisotropy: 1.0,
    anisotropyRotation: Math.PI / 2,
    sheen: 0.3,
    sheenRoughness: 0.3,
    sheenColor: '#2a2219',
  },
  hair_blonde: {
    roughness: 0.3,
    metalness: 0.0,
    color: '#c8a55a',
    anisotropy: 1.0,
    anisotropyRotation: Math.PI / 2,
    sheen: 0.4,
    sheenRoughness: 0.25,
    sheenColor: '#d4b86a',
  },
  hair_red: {
    roughness: 0.35,
    metalness: 0.0,
    color: '#8b3a15',
    anisotropy: 1.0,
    anisotropyRotation: Math.PI / 2,
    sheen: 0.35,
    sheenRoughness: 0.3,
    sheenColor: '#a04520',
  },

  // ===========================================================================
  // WET SURFACES — clearcoat simulates water film
  // ===========================================================================
  wet_stone: {
    roughness: 0.3,
    metalness: 0.0,
    color: '#606060',
    clearcoat: 0.8,
    clearcoatRoughness: 0.1,
  },
  wet_wood: {
    roughness: 0.4,
    metalness: 0.0,
    color: '#5a3a1a',
    clearcoat: 0.7,
    clearcoatRoughness: 0.15,
  },
  wet_concrete: {
    roughness: 0.5,
    metalness: 0.0,
    color: '#707070',
    clearcoat: 0.5,
    clearcoatRoughness: 0.2,
  },

  // ===========================================================================
  // FOOD & ORGANIC — SSS-heavy
  // ===========================================================================
  fruit: {
    roughness: 0.4,
    metalness: 0.0,
    color: '#ff4444',
    thickness: 0.8,
    attenuationColor: '#cc2200',
    attenuationDistance: 0.5,
    clearcoat: 0.3,
    clearcoatRoughness: 0.2,
  },
  cheese: {
    roughness: 0.7,
    metalness: 0.0,
    color: '#ffc125',
    thickness: 1.2,
    attenuationColor: '#cc9900',
    attenuationDistance: 0.4,
  },
  bread: {
    roughness: 0.95,
    metalness: 0.0,
    color: '#c4a35a',
    thickness: 0.3,
    attenuationColor: '#8b6914',
    attenuationDistance: 0.8,
  },
  chocolate: {
    roughness: 0.5,
    metalness: 0.0,
    color: '#3b1e08',
    clearcoat: 0.2,
    clearcoatRoughness: 0.3,
  },

  // ===========================================================================
  // COATED SURFACES — clearcoat-driven
  // ===========================================================================
  car_paint: {
    roughness: 0.1,
    metalness: 0.0,
    clearcoat: 1.0,
    clearcoatRoughness: 0.05,
  },
  lacquer: {
    roughness: 0.05,
    metalness: 0.0,
    clearcoat: 1.0,
    clearcoatRoughness: 0.02,
  },
  varnished_wood: {
    roughness: 0.3,
    metalness: 0.0,
    color: '#8b5e3c',
    clearcoat: 0.9,
    clearcoatRoughness: 0.1,
  },
  glazed_ceramic: {
    roughness: 0.15,
    metalness: 0.0,
    color: '#f0ede6',
    clearcoat: 0.8,
    clearcoatRoughness: 0.05,
  },
  enamel: {
    roughness: 0.1,
    metalness: 0.0,
    clearcoat: 0.9,
    clearcoatRoughness: 0.03,
  },

  // ===========================================================================
  // IRIDESCENT — thin-film interference
  // ===========================================================================
  soap_bubble: {
    roughness: 0.0,
    metalness: 0.0,
    transmission: 0.9,
    ior: 1.33,
    transparent: true,
    opacity: 0.3,
    iridescence: 1.0,
    iridescenceIOR: 1.5,
  },
  oil_slick: {
    roughness: 0.0,
    metalness: 0.1,
    color: '#1a1a2e',
    iridescence: 1.0,
    iridescenceIOR: 1.8,
  },
  beetle_shell: {
    roughness: 0.2,
    metalness: 0.3,
    color: '#0a3d0a',
    iridescence: 0.8,
    iridescenceIOR: 1.6,
    clearcoat: 0.5,
    clearcoatRoughness: 0.1,
  },
  pearl: {
    roughness: 0.15,
    metalness: 0.0,
    color: '#fdeef4',
    iridescence: 0.6,
    iridescenceIOR: 1.3,
    sheen: 0.3,
    sheenRoughness: 0.2,
    sheenColor: '#fff0f5',
  },
  abalone: {
    roughness: 0.1,
    metalness: 0.1,
    color: '#e0f0e8',
    iridescence: 1.0,
    iridescenceIOR: 1.5,
  },

  // ===========================================================================
  // GEMSTONES — transmission + IOR + iridescence
  // ===========================================================================
  diamond: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#ffffff',
    transmission: 0.95,
    ior: 2.417,
    thickness: 0.5,
    transparent: true,
  },
  ruby: {
    roughness: 0.05,
    metalness: 0.0,
    color: '#e0115f',
    transmission: 0.4,
    ior: 1.76,
    thickness: 1.0,
  },
  sapphire: {
    roughness: 0.05,
    metalness: 0.0,
    color: '#0f52ba',
    transmission: 0.4,
    ior: 1.77,
    thickness: 1.0,
  },
  emerald: {
    roughness: 0.1,
    metalness: 0.0,
    color: '#50c878',
    transmission: 0.3,
    ior: 1.57,
    thickness: 1.2,
  },
  amber: {
    roughness: 0.1,
    metalness: 0.0,
    color: '#ffbf00',
    transmission: 0.6,
    ior: 1.55,
    thickness: 2.0,
    transparent: true,
    attenuationColor: '#cc6600',
    attenuationDistance: 1.0,
  },
  opal: {
    roughness: 0.15,
    metalness: 0.0,
    color: '#e8e0d0',
    iridescence: 0.9,
    iridescenceIOR: 1.45,
    transmission: 0.1,
    ior: 1.45,
  },
  amethyst: {
    roughness: 0.05,
    metalness: 0.0,
    color: '#9966cc',
    transmission: 0.5,
    ior: 1.54,
    thickness: 1.0,
    transparent: true,
  },
  topaz: {
    roughness: 0.02,
    metalness: 0.0,
    color: '#ffc87c',
    transmission: 0.7,
    ior: 1.63,
    thickness: 0.8,
    transparent: true,
  },
  turquoise: {
    roughness: 0.6,
    metalness: 0.0,
    color: '#40e0d0',
  },
  lapis_lazuli: {
    roughness: 0.4,
    metalness: 0.0,
    color: '#26619c',
    clearcoat: 0.3,
    clearcoatRoughness: 0.1,
  },

  // ===========================================================================
  // MORE METALS — extended metallic palette
  // ===========================================================================
  titanium: {
    roughness: 0.25,
    metalness: 1.0,
    color: '#878681',
  },
  tungsten: {
    roughness: 0.3,
    metalness: 1.0,
    color: '#696969',
  },
  tin: {
    roughness: 0.35,
    metalness: 1.0,
    color: '#b0b0b0',
    envMapIntensity: 0.8,
  },
  lead: {
    roughness: 0.6,
    metalness: 0.9,
    color: '#595959',
  },
  brass: {
    roughness: 0.35,
    metalness: 1.0,
    color: '#b5a642',
  },
  wrought_iron: {
    roughness: 0.7,
    metalness: 0.85,
    color: '#2c2c2c',
  },
  mercury: {
    roughness: 0.0,
    metalness: 1.0,
    color: '#d4d4d4',
    envMapIntensity: 2.0,
  },

  // ===========================================================================
  // NATURAL / WEATHER — environmental surfaces
  // ===========================================================================
  snow: {
    roughness: 0.8,
    metalness: 0.0,
    color: '#f0f8ff',
    thickness: 0.5,
    attenuationColor: '#c8e0ff',
    attenuationDistance: 2.0,
  },
  fresh_snow: {
    roughness: 0.6,
    metalness: 0.0,
    color: '#ffffff',
    sheen: 0.3,
    sheenRoughness: 0.5,
    sheenColor: '#e8f0ff',
  },
  frost: {
    roughness: 0.3,
    metalness: 0.0,
    color: '#e8f4f8',
    transmission: 0.15,
    ior: 1.31,
    clearcoat: 0.4,
    clearcoatRoughness: 0.1,
  },
  ice: {
    roughness: 0.1,
    metalness: 0.0,
    color: '#d6eaf8',
    transmission: 0.8,
    ior: 1.31,
    transparent: true,
  },
  moss: {
    roughness: 1.0,
    metalness: 0.0,
    color: '#4a7c3f',
    sheen: 0.2,
    sheenRoughness: 1.0,
    sheenColor: '#5a9c4f',
  },
  lichen: {
    roughness: 0.9,
    metalness: 0.0,
    color: '#8fa37a',
  },
  bark: {
    roughness: 0.95,
    metalness: 0.0,
    color: '#5c4033',
  },
  dried_leaves: {
    roughness: 0.9,
    metalness: 0.0,
    color: '#8b6914',
    thickness: 0.1,
    attenuationColor: '#664400',
    attenuationDistance: 0.3,
  },

  // ===========================================================================
  // AGED / WEATHERED — patina, tarnish, wear
  // ===========================================================================
  patina: {
    roughness: 0.6,
    metalness: 0.4,
    color: '#4a9c7e',
  },
  tarnished_silver: {
    roughness: 0.5,
    metalness: 0.7,
    color: '#8a8a7a',
  },
  aged_bronze: {
    roughness: 0.55,
    metalness: 0.6,
    color: '#6b8e5a',
  },
  weathered_wood: {
    roughness: 0.95,
    metalness: 0.0,
    color: '#8a8070',
  },
  cracked_paint: {
    roughness: 0.8,
    metalness: 0.0,
    color: '#c8c0b0',
  },
  oxidized_copper: {
    roughness: 0.65,
    metalness: 0.5,
    color: '#2e8b57',
  },

  // ===========================================================================
  // CONSTRUCTION — architectural materials
  // ===========================================================================
  asphalt: {
    roughness: 0.9,
    metalness: 0.0,
    color: '#3a3a3a',
  },
  cement: {
    roughness: 0.85,
    metalness: 0.0,
    color: '#a0a0a0',
  },
  tile_ceramic: {
    roughness: 0.2,
    metalness: 0.0,
    color: '#e8e0d0',
    clearcoat: 0.6,
    clearcoatRoughness: 0.05,
  },
  tile_porcelain: {
    roughness: 0.1,
    metalness: 0.0,
    color: '#f5f5f5',
    clearcoat: 0.8,
    clearcoatRoughness: 0.02,
  },
  linoleum: {
    roughness: 0.6,
    metalness: 0.0,
    color: '#c0b090',
    clearcoat: 0.2,
    clearcoatRoughness: 0.3,
  },
  drywall: {
    roughness: 1.0,
    metalness: 0.0,
    color: '#f0ece0',
  },
  rebar: {
    roughness: 0.6,
    metalness: 0.9,
    color: '#5a4a3a',
  },
  stucco: {
    roughness: 0.95,
    metalness: 0.0,
    color: '#e8dcc8',
  },
  gravel: {
    roughness: 1.0,
    metalness: 0.02,
    color: '#8a8070',
  },

  // ===========================================================================
  // LEATHER VARIANTS — sheen + clearcoat differentiation
  // ===========================================================================
  suede: {
    roughness: 1.0,
    metalness: 0.0,
    color: '#8b6914',
    sheen: 0.6,
    sheenRoughness: 1.0,
    sheenColor: '#a07828',
  },
  patent_leather: {
    roughness: 0.05,
    metalness: 0.0,
    color: '#1a1a1a',
    clearcoat: 1.0,
    clearcoatRoughness: 0.02,
  },
  distressed_leather: {
    roughness: 0.8,
    metalness: 0.0,
    color: '#5a3a1a',
    sheen: 0.15,
    sheenRoughness: 0.8,
    sheenColor: '#4a3010',
  },
  nubuck: {
    roughness: 0.95,
    metalness: 0.0,
    color: '#c8a882',
    sheen: 0.5,
    sheenRoughness: 0.9,
    sheenColor: '#d4b892',
  },

  // ===========================================================================
  // RUBBER VARIANTS
  // ===========================================================================
  tire_rubber: {
    roughness: 0.85,
    metalness: 0.0,
    color: '#1a1a1a',
  },
  silicone: {
    roughness: 0.6,
    metalness: 0.0,
    color: '#e0e0e0',
    thickness: 0.5,
    attenuationColor: '#cccccc',
    attenuationDistance: 1.0,
    transmission: 0.05,
  },
  latex: {
    roughness: 0.3,
    metalness: 0.0,
    color: '#ffefd5',
    clearcoat: 0.5,
    clearcoatRoughness: 0.1,
    thickness: 0.3,
    attenuationColor: '#ffcc88',
    attenuationDistance: 0.5,
  },
  eraser: {
    roughness: 0.95,
    metalness: 0.0,
    color: '#ff6b81',
  },

  // ===========================================================================
  // LIQUIDS — transmission + animated surface hints
  // ===========================================================================
  lava: {
    roughness: 0.8,
    metalness: 0.0,
    color: '#ff4400',
    emissive: '#ff2200',
    emissiveIntensity: 3.0,
  },
  blood: {
    roughness: 0.2,
    metalness: 0.0,
    color: '#8b0000',
    clearcoat: 0.7,
    clearcoatRoughness: 0.05,
    thickness: 1.0,
    attenuationColor: '#440000',
    attenuationDistance: 0.3,
  },
  oil_liquid: {
    roughness: 0.05,
    metalness: 0.0,
    color: '#1a1a0a',
    clearcoat: 0.9,
    clearcoatRoughness: 0.02,
  },
  molten_metal: {
    roughness: 0.15,
    metalness: 0.8,
    color: '#ff8c00',
    emissive: '#ff6600',
    emissiveIntensity: 5.0,
  },
  syrup: {
    roughness: 0.1,
    metalness: 0.0,
    color: '#8b4513',
    transmission: 0.4,
    ior: 1.49,
    thickness: 2.0,
    attenuationColor: '#663300',
    attenuationDistance: 0.5,
  },

  // ===========================================================================
  // BLACKBODY / THERMAL — temperature-driven emission
  // ===========================================================================
  heated_metal_low: {
    roughness: 0.5,
    metalness: 0.9,
    color: '#4a4a4a',
    emissive: '#ff1a00',
    emissiveIntensity: 1.5,
  },
  heated_metal_mid: {
    roughness: 0.4,
    metalness: 0.8,
    color: '#5a5a5a',
    emissive: '#ff6600',
    emissiveIntensity: 3.0,
  },
  heated_metal_hot: {
    roughness: 0.3,
    metalness: 0.7,
    color: '#6a6a6a',
    emissive: '#ffcc00',
    emissiveIntensity: 5.0,
  },
  heated_metal_white: {
    roughness: 0.2,
    metalness: 0.6,
    color: '#8a8a8a',
    emissive: '#ffffff',
    emissiveIntensity: 8.0,
  },
  ember: {
    roughness: 0.9,
    metalness: 0.0,
    color: '#2a0a00',
    emissive: '#ff4400',
    emissiveIntensity: 2.0,
  },
  coal: {
    roughness: 0.85,
    metalness: 0.0,
    color: '#1a1a1a',
    emissive: '#cc2200',
    emissiveIntensity: 0.5,
  },

  // ===========================================================================
  // SPECIAL EFFECTS — sparkle, glow, energy
  // ===========================================================================
  glitter: {
    roughness: 0.2,
    metalness: 0.8,
    color: '#ffd700',
    envMapIntensity: 2.0,
  },
  sequin: {
    roughness: 0.05,
    metalness: 1.0,
    envMapIntensity: 2.5,
    iridescence: 0.3,
  },
  mica: {
    roughness: 0.3,
    metalness: 0.2,
    color: '#c8b888',
    iridescence: 0.4,
    iridescenceIOR: 1.58,
    sheen: 0.2,
    sheenRoughness: 0.3,
    sheenColor: '#d4c498',
  },
  fluorescent_green: {
    roughness: 0.5,
    metalness: 0.0,
    color: '#39ff14',
    emissive: '#39ff14',
    emissiveIntensity: 1.5,
  },
  fluorescent_orange: {
    roughness: 0.5,
    metalness: 0.0,
    color: '#ff6700',
    emissive: '#ff6700',
    emissiveIntensity: 1.5,
  },
  fluorescent_pink: {
    roughness: 0.5,
    metalness: 0.0,
    color: '#ff1493',
    emissive: '#ff1493',
    emissiveIntensity: 1.5,
  },
  glow_in_dark: {
    roughness: 0.7,
    metalness: 0.0,
    color: '#2a3a2a',
    emissive: '#44ff44',
    emissiveIntensity: 0.8,
  },
  plasma: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#4400ff',
    emissive: '#8844ff',
    emissiveIntensity: 4.0,
    transparent: true,
    opacity: 0.7,
  },
  energy_field: {
    roughness: 0.0,
    metalness: 0.0,
    emissive: '#00ccff',
    emissiveIntensity: 3.0,
    transparent: true,
    opacity: 0.4,
    transmission: 0.6,
  },
  force_field: {
    roughness: 0.0,
    metalness: 0.0,
    emissive: '#00ff88',
    emissiveIntensity: 2.0,
    transparent: true,
    opacity: 0.2,
    iridescence: 0.8,
    iridescenceIOR: 1.5,
  },

  // ===========================================================================
  // RETROREFLECTIVE — safety, signage
  // ===========================================================================
  safety_vest: {
    roughness: 0.6,
    metalness: 0.0,
    color: '#ccff00',
    emissive: '#ccff00',
    emissiveIntensity: 0.3,
  },
  road_sign: {
    roughness: 0.4,
    metalness: 0.1,
    color: '#ffffff',
    envMapIntensity: 1.8,
    emissive: '#ffffff',
    emissiveIntensity: 0.2,
  },
  reflective_tape: {
    roughness: 0.2,
    metalness: 0.3,
    color: '#e0e0e0',
    envMapIntensity: 2.5,
  },

  // ===========================================================================
  // MISC — everything else in the real world
  // ===========================================================================
  chalkboard: {
    roughness: 0.9,
    metalness: 0.0,
    color: '#2a3a2a',
  },
  chalk: {
    roughness: 1.0,
    metalness: 0.0,
    color: '#ffffff',
  },
  charcoal: {
    roughness: 0.9,
    metalness: 0.0,
    color: '#1a1a1a',
  },
  cork: {
    roughness: 0.95,
    metalness: 0.0,
    color: '#b88a50',
  },
  felt: {
    roughness: 1.0,
    metalness: 0.0,
    color: '#5a8a5a',
    sheen: 0.4,
    sheenRoughness: 1.0,
    sheenColor: '#6a9a6a',
  },
  sponge: {
    roughness: 1.0,
    metalness: 0.0,
    color: '#e8c840',
  },
  porcelain: {
    roughness: 0.1,
    metalness: 0.0,
    color: '#f8f4f0',
    clearcoat: 0.7,
    clearcoatRoughness: 0.02,
  },
  terracotta: {
    roughness: 0.85,
    metalness: 0.0,
    color: '#cc6644',
  },
  concrete_polished: {
    roughness: 0.3,
    metalness: 0.0,
    color: '#a0a0a0',
    clearcoat: 0.3,
    clearcoatRoughness: 0.15,
  },
  rope: {
    roughness: 1.0,
    metalness: 0.0,
    color: '#c4a35a',
    sheen: 0.2,
    sheenRoughness: 1.0,
    sheenColor: '#b89848',
  },
  wicker: {
    roughness: 0.9,
    metalness: 0.0,
    color: '#a08050',
  },
  parchment: {
    roughness: 0.8,
    metalness: 0.0,
    color: '#f0e6c8',
    thickness: 0.1,
    attenuationColor: '#d4c0a0',
    attenuationDistance: 0.2,
  },

  // ===========================================================================
  // ANIMATED MATERIALS — time-driven surface effects (wired to scene.time)
  // These set metadata flags that the runtime uses to drive animated shaders.
  // ===========================================================================
  flowing_water: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#006994',
    transmission: 0.85,
    ior: 1.33,
    transparent: true,
    _animated: { pattern: 'flow', speed: 0.8, amplitude: 0.3 },
  },
  rippling_water: {
    roughness: 0.05,
    metalness: 0.0,
    color: '#005577',
    transmission: 0.8,
    ior: 1.33,
    transparent: true,
    _animated: { pattern: 'ripple', speed: 1.0, amplitude: 0.4 },
  },
  flickering_fire: {
    roughness: 0.8,
    metalness: 0.0,
    color: '#ff4400',
    emissive: '#ff2200',
    emissiveIntensity: 3.0,
    _animated: { pattern: 'flicker', speed: 3.0, amplitude: 0.6 },
  },
  pulsing_glow: {
    roughness: 0.5,
    metalness: 0.0,
    emissive: '#00ff88',
    emissiveIntensity: 2.0,
    _animated: { pattern: 'pulse', speed: 1.5, amplitude: 0.5 },
  },
  breathing_light: {
    roughness: 0.3,
    metalness: 0.0,
    emissive: '#4488ff',
    emissiveIntensity: 1.5,
    _animated: { pattern: 'breathe', speed: 0.5, amplitude: 0.8 },
  },
  scrolling_lava: {
    roughness: 0.8,
    metalness: 0.0,
    color: '#ff4400',
    emissive: '#ff2200',
    emissiveIntensity: 4.0,
    _animated: { pattern: 'scroll', speed: 0.3, amplitude: 1.0 },
  },
  waving_grass: {
    roughness: 0.9,
    metalness: 0.0,
    color: '#228b22',
    sheen: 0.2,
    sheenRoughness: 0.8,
    sheenColor: '#44cc22',
    _animated: { pattern: 'wave', speed: 0.8, amplitude: 0.2 },
  },
  flickering_neon: {
    roughness: 0.0,
    metalness: 0.0,
    emissive: '#ff00ff',
    emissiveIntensity: 3.5,
    transparent: true,
    opacity: 0.9,
    _animated: { pattern: 'flicker', speed: 5.0, amplitude: 0.4 },
  },
  pulsing_crystal: {
    roughness: 0.0,
    metalness: 0.1,
    transmission: 0.8,
    ior: 2.0,
    iridescence: 0.8,
    iridescenceIOR: 1.3,
    emissive: '#8844ff',
    emissiveIntensity: 1.0,
    _animated: { pattern: 'pulse', speed: 0.8, amplitude: 0.6 },
  },
  animated_hologram: {
    roughness: 0.0,
    metalness: 0.3,
    transparent: true,
    opacity: 0.5,
    emissive: '#00ccff',
    emissiveIntensity: 1.5,
    _animated: { pattern: 'scroll', speed: 1.5, amplitude: 0.3 },
  },
  boiling_surface: {
    roughness: 0.7,
    metalness: 0.0,
    color: '#cc4400',
    emissive: '#ff6600',
    emissiveIntensity: 2.0,
    _animated: { pattern: 'noise', speed: 2.0, amplitude: 0.5 },
  },
  shimmer_heat: {
    roughness: 0.0,
    metalness: 0.0,
    transparent: true,
    opacity: 0.15,
    _animated: { pattern: 'wave', speed: 2.0, amplitude: 0.1 },
  },

  // ===========================================================================
  // VOLUMETRIC MATERIALS — metadata for ray-marched volume rendering
  // These presets describe volumetric phenomena; the runtime renders them via
  // a ray marching pass on a bounding box/sphere geometry.
  // ===========================================================================
  fog: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#c0c0c0',
    transparent: true,
    opacity: 0.3,
    _volumetric: { type: 'fog', density: 0.3, scattering: 0.8, absorption: 0.05 },
  },
  dense_fog: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#a0a0a0',
    transparent: true,
    opacity: 0.5,
    _volumetric: { type: 'fog', density: 0.7, scattering: 0.9, absorption: 0.1 },
  },
  smoke: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#404040',
    transparent: true,
    opacity: 0.4,
    _volumetric: {
      type: 'smoke',
      density: 0.5,
      scattering: 0.3,
      absorption: 0.4,
      riseSpeed: 0.5,
      turbulence: 0.6,
    },
  },
  campfire_smoke: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#505050',
    transparent: true,
    opacity: 0.35,
    _volumetric: {
      type: 'smoke',
      density: 0.4,
      scattering: 0.25,
      absorption: 0.5,
      riseSpeed: 0.8,
      turbulence: 0.4,
    },
  },
  fire_volume: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#ff4400',
    emissive: '#ff2200',
    emissiveIntensity: 4.0,
    transparent: true,
    opacity: 0.7,
    _volumetric: {
      type: 'fire',
      density: 0.6,
      scattering: 0.1,
      absorption: 0.2,
      riseSpeed: 1.2,
      turbulence: 0.7,
      temperature: 2500,
    },
  },
  candle_flame: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#ffaa33',
    emissive: '#ff8800',
    emissiveIntensity: 3.0,
    transparent: true,
    opacity: 0.6,
    _volumetric: {
      type: 'fire',
      density: 0.4,
      scattering: 0.05,
      absorption: 0.1,
      riseSpeed: 0.3,
      turbulence: 0.2,
      temperature: 1800,
    },
  },
  clouds: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#ffffff',
    transparent: true,
    opacity: 0.6,
    _volumetric: {
      type: 'clouds',
      density: 0.4,
      scattering: 0.95,
      absorption: 0.02,
      noiseScale: 2.0,
      octaves: 6,
    },
  },
  storm_clouds: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#3a3a4a',
    transparent: true,
    opacity: 0.8,
    _volumetric: {
      type: 'clouds',
      density: 0.7,
      scattering: 0.6,
      absorption: 0.15,
      noiseScale: 1.5,
      octaves: 6,
    },
  },
  dust_motes: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#c8b888',
    transparent: true,
    opacity: 0.15,
    _volumetric: { type: 'dust', density: 0.1, scattering: 0.5, absorption: 0.02 },
  },
  mist: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#e0e8f0',
    transparent: true,
    opacity: 0.25,
    _volumetric: {
      type: 'mist',
      density: 0.2,
      scattering: 0.85,
      absorption: 0.03,
      heightFalloff: 1.5,
    },
  },
  steam: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#e8e8e8',
    transparent: true,
    opacity: 0.3,
    _volumetric: {
      type: 'steam',
      density: 0.35,
      scattering: 0.7,
      absorption: 0.05,
      riseSpeed: 1.0,
      turbulence: 0.3,
    },
  },
  aurora_borealis: {
    roughness: 0.0,
    metalness: 0.0,
    emissive: '#00ff88',
    emissiveIntensity: 2.0,
    transparent: true,
    opacity: 0.3,
    _volumetric: {
      type: 'aurora',
      density: 0.15,
      scattering: 0.1,
      absorption: 0.01,
      emissionIntensity: 2.0,
    },
  },
  nebula: {
    roughness: 0.0,
    metalness: 0.0,
    emissive: '#ff44aa',
    emissiveIntensity: 1.5,
    transparent: true,
    opacity: 0.4,
    _volumetric: {
      type: 'nebula',
      density: 0.25,
      scattering: 0.3,
      absorption: 0.05,
      emissionIntensity: 1.5,
      noiseScale: 1.0,
    },
  },
  underwater_caustics: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#003366',
    transparent: true,
    opacity: 0.2,
    _volumetric: { type: 'underwater', density: 0.15, scattering: 0.6, absorption: 0.1 },
  },
  god_rays: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#ffffd0',
    transparent: true,
    opacity: 0.15,
    emissive: '#ffff88',
    emissiveIntensity: 0.5,
    _volumetric: { type: 'god_rays', density: 0.1, scattering: 0.9, absorption: 0.01 },
  },
  neon_gas: {
    roughness: 0.0,
    metalness: 0.0,
    emissive: '#ff4400',
    emissiveIntensity: 3.0,
    transparent: true,
    opacity: 0.5,
    _volumetric: {
      type: 'neon_gas',
      density: 0.3,
      scattering: 0.2,
      absorption: 0.05,
      emissionIntensity: 3.0,
    },
  },
  explosion: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#ff6600',
    emissive: '#ff4400',
    emissiveIntensity: 6.0,
    transparent: true,
    opacity: 0.8,
    _volumetric: {
      type: 'fire',
      density: 0.8,
      scattering: 0.15,
      absorption: 0.3,
      riseSpeed: 2.0,
      turbulence: 1.0,
      temperature: 4000,
    },
  },
  toxic_gas: {
    roughness: 0.0,
    metalness: 0.0,
    color: '#44cc00',
    emissive: '#33aa00',
    emissiveIntensity: 1.0,
    transparent: true,
    opacity: 0.35,
    _volumetric: {
      type: 'smoke',
      density: 0.3,
      scattering: 0.4,
      absorption: 0.2,
      riseSpeed: 0.2,
      turbulence: 0.3,
    },
  },
  magical_mist: {
    roughness: 0.0,
    metalness: 0.0,
    emissive: '#8844ff',
    emissiveIntensity: 1.5,
    transparent: true,
    opacity: 0.3,
    iridescence: 0.6,
    iridescenceIOR: 1.5,
    _volumetric: {
      type: 'mist',
      density: 0.2,
      scattering: 0.5,
      absorption: 0.03,
      emissionIntensity: 1.5,
    },
  },
  // --- Architectural & Natural Stone ---
  brick: { roughness: 0.9, metalness: 0.0, color: '#a6523c' },
  concrete: { roughness: 0.88, metalness: 0.0, color: '#8a8a8a' },
  granite: { roughness: 0.6, metalness: 0.0, color: '#666670' },
  sandstone: { roughness: 0.85, metalness: 0.0, color: '#cca66e' },
  slate: { roughness: 0.7, metalness: 0.0, color: '#3f4450' },
  adobe: { roughness: 0.95, metalness: 0.0, color: '#bf9160' },
  plaster: { roughness: 0.82, metalness: 0.0, color: '#ebe8de' },
  // --- Plant & Cellulose ---
  bamboo: { roughness: 0.65, metalness: 0.0, color: '#b3a84d' },
  paper: { roughness: 0.9, metalness: 0.0, color: '#f3f0e5' },
  cardboard: { roughness: 0.88, metalness: 0.0, color: '#b88c58' },
  // --- Organic & Animal ---
  bone: { roughness: 0.7, metalness: 0.0, color: '#e0d4b5' },
  ivory: { roughness: 0.35, metalness: 0.0, color: '#f0e8c5', envMapIntensity: 0.4 },
  coral: { roughness: 0.75, metalness: 0.0, color: '#f2614d' },
  shell: {
    roughness: 0.25,
    metalness: 0.05,
    color: '#f5ede0',
    iridescence: 0.8,
    iridescenceIOR: 1.5,
    envMapIntensity: 0.6,
  },
  thatch: { roughness: 0.95, metalness: 0.0, color: '#c0a84a' },
  // --- Synthetic & Engineered ---
  resin: {
    roughness: 0.08,
    metalness: 0.0,
    transmission: 0.75,
    ior: 1.5,
    color: '#e8c46a',
    transparent: true,
    opacity: 0.88,
  },
  foam: { roughness: 0.95, metalness: 0.0, color: '#f0f0f0' },
  composite: { roughness: 0.5, metalness: 0.25, color: '#333338' },
  carbon_fiber: {
    roughness: 0.28,
    metalness: 0.6,
    color: '#111114',
    envMapIntensity: 1.2,
    clearcoat: 0.6,
    clearcoatRoughness: 0.1,
  },
  kevlar: { roughness: 0.82, metalness: 0.0, color: '#ccbb66' },
  fiberglass: {
    roughness: 0.3,
    metalness: 0.05,
    transmission: 0.4,
    ior: 1.45,
    color: '#e0ede0',
    transparent: true,
    opacity: 0.92,
  },
  stained_glass: {
    roughness: 0.05,
    metalness: 0.0,
    transmission: 0.85,
    ior: 1.52,
    color: '#cc44ff',
    transparent: true,
    opacity: 0.75,
    thickness: 0.3,
  },
};

export const ENVIRONMENT_PRESETS: Record<string, Record<string, unknown>> = {
  forest_sunset: {
    background: true,
    envPreset: 'sunset',
    fog: { color: '#ff9966', near: 10, far: 100 },
    ground: { color: '#2d5a27' },
    lighting: {
      ambient: { color: '#ffa366', intensity: 0.3 },
      directional: { color: '#ff7700', intensity: 1.5, position: [10, 20, 5], shadows: true },
    },
  },
  cyberpunk_city: {
    background: true,
    envPreset: 'night',
    fog: { color: '#0a0020', near: 5, far: 60 },
    ground: { color: '#1a1a2e' },
    lighting: {
      ambient: { color: '#220044', intensity: 0.2 },
      directional: { color: '#ff00ff', intensity: 0.5, position: [5, 15, 5], shadows: true },
      points: [
        { color: '#00ffff', intensity: 3, position: [-5, 3, -5], distance: 15 },
        { color: '#ff00ff', intensity: 3, position: [5, 3, 5], distance: 15 },
      ],
    },
    postprocessing: { bloom: { intensity: 1.5, luminanceThreshold: 0.1 } },
  },
  space_void: {
    background: true,
    envPreset: 'night',
    lighting: {
      ambient: { color: '#111133', intensity: 0.1 },
      directional: { color: '#ffffff', intensity: 0.5, position: [0, 10, 0], shadows: false },
    },
  },
  studio: {
    background: true,
    envPreset: 'studio',
    ground: { color: '#cccccc' },
    lighting: {
      ambient: { color: '#ffffff', intensity: 0.4 },
      directional: { color: '#ffffff', intensity: 1.0, position: [5, 10, 5], shadows: true },
    },
  },
  underwater: {
    background: true,
    envPreset: 'dawn',
    fog: { color: '#003366', near: 2, far: 40 },
    ground: { color: '#1a3a4a' },
    lighting: {
      ambient: { color: '#004488', intensity: 0.3 },
      directional: { color: '#66aacc', intensity: 0.8, position: [0, 20, 0], shadows: true },
    },
  },
  desert: {
    background: true,
    envPreset: 'sunset',
    fog: { color: '#d4a574', near: 20, far: 150 },
    ground: { color: '#c4a35a' },
    lighting: {
      ambient: { color: '#f5deb3', intensity: 0.4 },
      directional: { color: '#ffffcc', intensity: 2.0, position: [15, 30, 10], shadows: true },
    },
  },
};
