/**
 * HoloScript -> Vanilla Three.js Compiler
 *
 * Translates a HoloComposition AST into vanilla Three.js TypeScript code.
 * Bypasses React Three Fiber (R3F) for bundle-critical deployments where
 * the React runtime overhead is unacceptable.
 *
 * Emits:
 *   - Scene initialization with WebGLRenderer
 *   - BufferGeometry mesh creation
 *   - MeshStandardMaterial setup
 *   - Light components (AmbientLight, DirectionalLight, PointLight, SpotLight)
 *   - PerspectiveCamera / OrthographicCamera setup
 *   - Shadow maps
 *   - Animation loop via requestAnimationFrame
 *   - Group/Object3D hierarchy
 *
 * @version 1.0.0
 */

import type {
  HoloComposition,
  HoloObjectDecl,
  HoloSpatialGroup,
  HoloLight,
  HoloEnvironment,
  HoloCamera,
  HoloAudio,
  HoloZone,
} from '../parser/HoloCompositionTypes';
import { TraitCompositor } from '../traits/visual/TraitCompositor';
import { ProvenanceSemiring } from './traits/ProvenanceSemiring';
import { CompilerBase } from './CompilerBase';
import { ANSCapabilityPath, type ANSCapabilityPathValue } from '@holoscript/core-types/ans';

export interface ThreeJSCompilerOptions {
  /** Class name for the generated scene class. @default 'GeneratedScene' */
  className?: string;
  /** Enable shadow maps on the renderer. @default true */
  enableShadows?: boolean;
  /** Include a basic post-processing pass (UnrealBloomPass). @default false */
  enablePostProcessing?: boolean;
  /** Indentation string. @default '  ' */
  indent?: string;
  /** When set, emits a `// Provenance Hash:` banner. */
  provenanceHash?: string;
}

/** Maps HoloScript geometry names to Three.js geometry constructors */
const SHAPE_TO_THREE_GEOMETRY: Record<string, string> = {
  sphere: 'SphereGeometry',
  orb: 'SphereGeometry',
  cube: 'BoxGeometry',
  box: 'BoxGeometry',
  cylinder: 'CylinderGeometry',
  cone: 'ConeGeometry',
  pyramid: 'ConeGeometry',
  plane: 'PlaneGeometry',
  ground: 'PlaneGeometry',
  torus: 'TorusGeometry',
  ring: 'TorusGeometry',
  capsule: 'CapsuleGeometry',
};

export class ThreeJSCompiler extends CompilerBase {
  protected readonly compilerName = 'ThreeJSCompiler';

  protected override getRequiredCapability(): ANSCapabilityPathValue {
    return ANSCapabilityPath.R3F;
  }

  private options: Required<ThreeJSCompilerOptions>;
  private lines: string[] = [];
  private indentLevel = 0;

  constructor(options: ThreeJSCompilerOptions = {}) {
    super();
    this.options = {
      className: options.className ?? 'GeneratedScene',
      enableShadows: options.enableShadows ?? true,
      enablePostProcessing: options.enablePostProcessing ?? false,
      indent: options.indent ?? '  ',
      provenanceHash: options.provenanceHash ?? '',
    };
  }

  compile(composition: HoloComposition, agentToken: string, outputPath?: string): string {
    // ─── Agent Identity Verification ───────────────────────────────────────
    this.validateCompilerAccess(agentToken, outputPath);
    // ───────────────────────────────────────────────────────────────────────
    this.lines = [];
    this.indentLevel = 0;

    this.emit('// Auto-generated by HoloScript ThreeJSCompiler');
    this.emit(
      `// Source: composition "${this.escapeStringValue(composition.name as string, 'TypeScript')}"`
    );
    if (this.options.provenanceHash) {
      this.emit(`// Provenance Hash: ${this.options.provenanceHash}`);
    }
    this.emit('');

    this.emitImports(composition);
    this.emit('');

    this.emit(`export class ${this.options.className} {`);
    this.indent();
    this.emit('private scene: THREE.Scene;');
    this.emit('private renderer: THREE.WebGLRenderer;');
    this.emit('private camera: THREE.PerspectiveCamera;');
    this.emit('private canvas: HTMLCanvasElement;');
    this.emit('private frameId: number = 0;');
    this.emit('');

    this.emit('constructor(canvas: HTMLCanvasElement) {');
    this.indent();
    this.emit('this.canvas = canvas;');
    this.emit('this.scene = new THREE.Scene();');
    this.emit(
      'this.renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: false });'
    );
    this.emit('this.renderer.setPixelRatio(window.devicePixelRatio);');
    this.emit('this.renderer.setSize(canvas.clientWidth, canvas.clientHeight);');
    if (this.options.enableShadows) {
      this.emit('this.renderer.shadowMap.enabled = true;');
      this.emit('this.renderer.shadowMap.type = THREE.PCFSoftShadowMap;');
    }
    this.emit(
      'this.camera = new THREE.PerspectiveCamera(75, canvas.clientWidth / canvas.clientHeight, 0.1, 1000);'
    );
    this.emit('this.camera.position.set(0, 2, 10);');
    this.dedent();
    this.emit('}');
    this.emit('');

    this.emit('async build(): Promise<void> {');
    this.indent();

    if (composition.environment) this.emitEnvironment(composition.environment);

    if (composition.lights?.length) {
      for (const light of composition.lights) this.emitLight(light);
    } else {
      this.emit('// Default lighting');
      this.emit('const ambientLight = new THREE.AmbientLight(0xffffff, 0.6);');
      this.emit('this.scene.add(ambientLight);');
      this.emit('const dirLight = new THREE.DirectionalLight(0xffffff, 0.8);');
      this.emit('dirLight.position.set(5, 10, 5);');
      if (this.options.enableShadows) {
        this.emit('dirLight.castShadow = true;');
        this.emit('dirLight.shadow.mapSize.set(2048, 2048);');
      }
      this.emit('this.scene.add(dirLight);');
      this.emit('');
    }

    if (composition.camera) this.emitCamera(composition.camera);

    if (composition.objects?.length) {
      for (const obj of composition.objects) this.emitObject(obj);
    }
    if (composition.spatialGroups?.length) {
      for (const g of composition.spatialGroups) this.emitGroup(g);
    }
    if (composition.zones?.length) {
      for (const z of composition.zones) this.emitZone(z);
    }
    if (composition.audio?.length) {
      for (const a of composition.audio) this.emitAudio(a);
    }

    this.emitRenderLoop();
    this.dedent();
    this.emit('}');
    this.emit('');

    this.emit('dispose(): void {');
    this.indent();
    this.emit('cancelAnimationFrame(this.frameId);');
    this.emit('this.renderer.dispose();');
    this.emit('this.scene.clear();');
    this.dedent();
    this.emit('}');

    this.dedent();
    this.emit('}');
    return this.lines.join('\n');
  }

  // --- Imports ---

  private emitImports(_composition: HoloComposition): void {
    this.emit('import * as THREE from "three";');
    if (this.options.enablePostProcessing) {
      this.emit('import { EffectComposer } from "three/addons/postprocessing/EffectComposer.js";');
      this.emit(
        'import { RenderPass } from "three/addons/postprocessing/RenderPass.js";'
      );
      this.emit(
        'import { UnrealBloomPass } from "three/addons/postprocessing/UnrealBloomPass.js";'
      );
    }
  }

  // --- Environment ---

  private emitEnvironment(env: HoloEnvironment): void {
    for (const prop of env.properties) {
      if (prop.key === 'background' || prop.key === 'skybox' || prop.key === 'preset') {
        if (typeof prop.value === 'string' && prop.value.startsWith('#')) {
          this.emit(`this.scene.background = new THREE.Color(${this.toThreeColorHex(prop.value)});`);
        } else {
          this.emit(`// skybox: "${prop.value}" — load via THREE.CubeTextureLoader`);
        }
      } else if (prop.key === 'fog' && typeof prop.value === 'object') {
        const fog = prop.value as Record<string, unknown>;
        const near = fog.near ?? 10;
        const far = fog.far ?? 100;
        const color = this.toThreeColorHex(fog.color ?? '#cccccc');
        this.emit(`this.scene.fog = new THREE.Fog(${color}, ${near}, ${far});`);
      } else if (prop.key === 'ambient_light') {
        this.emit(
          `this.scene.add(new THREE.AmbientLight(0xffffff, ${prop.value ?? 0.5}));`
        );
      } else if (prop.key === 'ground') {
        this.emit(
          `const groundGeom = new THREE.PlaneGeometry(100, 100);`
        );
        this.emit(
          `const groundMat = new THREE.MeshStandardMaterial({ color: 0x888888, roughness: 0.8 });`
        );
        this.emit(`const ground = new THREE.Mesh(groundGeom, groundMat);`);
        this.emit(`ground.rotation.x = -Math.PI / 2;`);
        if (this.options.enableShadows) {
          this.emit(`ground.receiveShadow = true;`);
        }
        this.emit(`this.scene.add(ground);`);
      }
    }
    this.emit('');
  }

  // --- Objects ---

  private emitObject(obj: HoloObjectDecl, parentVar?: string): void {
    const v = this.sanitizeName(obj.name);
    let geom = 'cube';
    let modelSrc: string | undefined;
    let textContent: string | undefined;
    let position: unknown[] | undefined;
    let rotation: unknown[] | undefined;
    let scale: unknown;
    let size: unknown;
    const mat: Record<string, unknown> = {};

    for (const p of obj.properties) {
      switch (p.key) {
        case 'geometry':
        case 'mesh':
        case 'type':
          if (typeof p.value === 'string') geom = p.value;
          break;
        case 'position':
          if (Array.isArray(p.value)) position = p.value;
          break;
        case 'rotation':
          if (Array.isArray(p.value)) rotation = p.value;
          break;
        case 'scale':
          scale = p.value;
          break;
        case 'size':
          size = p.value;
          break;
        case 'color':
          mat.color = p.value;
          break;
        case 'roughness':
          mat.roughness = p.value;
          break;
        case 'metalness':
        case 'metallic':
          mat.metalness = p.value;
          break;
        case 'opacity':
          mat.opacity = p.value;
          break;
        case 'emissive':
          mat.emissive = p.value;
          break;
        case 'emissive_intensity':
        case 'emissiveIntensity':
          mat.emissiveIntensity = p.value;
          break;
        case 'material':
          if (typeof p.value === 'object' && p.value !== null)
            Object.assign(mat, p.value as Record<string, unknown>);
          break;
        case 'model':
        case 'src':
        case 'source':
          if (typeof p.value === 'string') modelSrc = p.value;
          break;
        case 'text':
          if (typeof p.value === 'string') textContent = p.value;
          break;
      }
    }

    this.emit(`// Object: ${this.escapeStringValue(obj.name as string, 'TypeScript')}`);

    if (modelSrc) {
      this.emit(`// GLTFLoader required for model: "${modelSrc}"`);
      this.emit(`// import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";`);
      this.emit(`const ${v}Loader = new GLTFLoader();`);
      this.emit(
        `const ${v}Gltf = await new Promise<THREE.Group>((resolve, reject) => { ${v}Loader.load("${modelSrc}", (g) => resolve(g.scene), undefined, reject); });`
      );
      this.emit(`const ${v} = ${v}Gltf;`);
      this.emit(`this.scene.add(${v});`);
    } else if (geom === 'text' || textContent) {
      this.emit(`// Text geometry requires THREE.FontLoader / troika-three-text`);
      this.emit(`const ${v}Geom = new THREE.PlaneGeometry(2, 0.5);`);
      this.emit(
        `const ${v}Mat = new THREE.MeshBasicMaterial({ color: 0xffffff, transparent: true });`
      );
      this.emit(`const ${v} = new THREE.Mesh(${v}Geom, ${v}Mat);`);
      this.emit(`// Text content: "${textContent || ''}"`);
      this.emit(`this.scene.add(${v});`);
    } else {
      const geomArgs = this.geometryArgs(geom, size);
      const geomClass = SHAPE_TO_THREE_GEOMETRY[geom] ?? 'BoxGeometry';
      this.emit(`const ${v}Geom = new THREE.${geomClass}(${geomArgs});`);

      const matProps = this.buildMaterialProps(mat);
      this.emit(`const ${v}Mat = new THREE.MeshStandardMaterial({ ${matProps} });`);
      this.emit(`const ${v} = new THREE.Mesh(${v}Geom, ${v}Mat);`);
      this.emit(`this.scene.add(${v});`);
    }

    if (position)
      this.emit(`${v}.position.set(${position[0]}, ${position[1]}, ${position[2]});`);
    if (rotation)
      this.emit(`${v}.rotation.set(${rotation[0]}, ${rotation[1]}, ${rotation[2]});`);
    if (scale) {
      if (Array.isArray(scale)) {
        this.emit(`${v}.scale.set(${scale[0]}, ${scale[1]}, ${scale[2]});`);
      } else {
        this.emit(`${v}.scale.setScalar(${scale});`);
      }
    }
    if (parentVar) this.emit(`${parentVar}.add(${v});`);

    // Pre-process Physics Traits via ProvenanceSemiring
    const physicsTraits = (obj.traits || []).filter(
      (t) => t.name === 'physics' || t.name === 'collidable'
    );
    if (physicsTraits.length > 0) {
      const semiring = new ProvenanceSemiring();
      const applications = physicsTraits.map((t) => ({
        name: t.name as string,
        config: (t.config || {}) as Record<string, unknown>,
        context: obj.provenance?.context,
      }));
      const { config: physicsConfig } = semiring.add(applications);
      const isStatic = (physicsConfig.type || 'dynamic') === 'static';
      this.emit(
        `// @physics — mass: ${physicsConfig.mass ?? 1}, type: ${isStatic ? 'static' : 'dynamic'}`
      );
      this.emit(
        `// Use a physics library (cannon-es, rapier, ammo.js) to attach a rigid body to ${v}`
      );
    }

    // Trait rendering
    for (const trait of obj.traits || []) {
      if (trait.name === 'physics' || trait.name === 'collidable') {
        continue; // Handled above via ProvenanceSemiring
      } else if (trait.name === 'shadow') {
        if (this.options.enableShadows) {
          this.emit(`${v}.castShadow = true;`);
          this.emit(`${v}.receiveShadow = true;`);
        }
      } else if (trait.name === 'grabbable') {
        this.emit(`// @grabbable — attach raycaster pointer-down handler to ${v}`);
      } else if (trait.name === 'hoverable') {
        this.emit(`// @hoverable — attach raycaster pointer-move handler to ${v}`);
      } else if (trait.name === 'gaussian_splat') {
        this.emit(
          `// @gaussian_splat — use @mkkellogg/gaussian-splats-3d or three-splat for ${v}`
        );
      } else if (trait.name === 'object_tracking') {
        this.emit(`// @object_tracking — WebXR hit-test for ${v}`);
      } else if (trait.name === 'eye_tracked') {
        this.emit(`// @eye_tracked — WebXR eye tracking for ${v}`);
      } else if (trait.name === 'controlnet') {
        this.emit(
          `// @controlnet(model: "${(trait.config as Record<string, unknown>)?.model || 'canny'}") — route to inference API for ${v}`
        );
      } else {
        this.emit(
          `// @${this.escapeStringValue(trait.name as string, 'TypeScript')}: ${JSON.stringify(trait.config || {})}`
        );
      }
    }

    // TraitCompositor: multi-trait visual merge
    if (obj.traits && obj.traits.length > 0) {
      const traitNames = obj.traits.map((t) => t.name);
      const compositor = new TraitCompositor();
      const composed = compositor.compose(traitNames);
      if (Object.keys(composed).length > 0) {
        this.emit(`// TraitCompositor: composed ${traitNames.join(' + ')}`);
        const composedProps = this.buildMaterialProps(composed as Record<string, unknown>);
        if (composedProps) {
          this.emit(
            `Object.assign((${v}.material as THREE.MeshStandardMaterial), { ${composedProps} });`
          );
        }
      }
    }

    if (obj.children?.length) {
      for (const child of obj.children) this.emitObject(child, v);
    }
    this.emit('');
  }

  // --- Groups ---

  private emitGroup(group: HoloSpatialGroup, parentVar?: string): void {
    const v = this.sanitizeName(group.name);
    this.emit(
      `const ${v} = new THREE.Group(); // "${this.escapeStringValue(group.name as string, 'TypeScript')}"`
    );
    for (const p of group.properties) {
      if (p.key === 'position' && Array.isArray(p.value))
        this.emit(`${v}.position.set(${p.value[0]}, ${p.value[1]}, ${p.value[2]});`);
      else if (p.key === 'rotation' && Array.isArray(p.value))
        this.emit(`${v}.rotation.set(${p.value[0]}, ${p.value[1]}, ${p.value[2]});`);
      else if (p.key === 'scale') {
        if (Array.isArray(p.value)) {
          this.emit(`${v}.scale.set(${p.value[0]}, ${p.value[1]}, ${p.value[2]});`);
        } else {
          this.emit(`${v}.scale.setScalar(${p.value});`);
        }
      }
    }
    const addTarget = parentVar ? parentVar : 'this.scene';
    this.emit(`${addTarget}.add(${v});`);

    for (const obj of group.objects) this.emitObject(obj, v);
    if (group.groups) {
      for (const sub of group.groups) this.emitGroup(sub, v);
    }
    this.emit('');
  }

  // --- Lights ---

  private emitLight(light: HoloLight): void {
    const v = this.sanitizeName(light.name);
    let position: unknown[] | undefined;
    let color: unknown;
    let intensity: number | undefined;
    let direction: unknown[] | undefined;
    let castShadow = false;
    let angle: number | undefined;
    let distance: number | undefined;
    let penumbra: number | undefined;

    for (const p of light.properties) {
      if (p.key === 'position' && Array.isArray(p.value)) position = p.value;
      else if (p.key === 'color') color = p.value;
      else if (p.key === 'intensity') intensity = p.value as number;
      else if (p.key === 'direction' && Array.isArray(p.value)) direction = p.value;
      else if (p.key === 'cast_shadow' || p.key === 'castShadow') castShadow = !!p.value;
      else if (p.key === 'angle') angle = p.value as number;
      else if (p.key === 'distance') distance = p.value as number;
      else if (p.key === 'penumbra') penumbra = p.value as number;
    }

    const colorHex = this.toThreeColorHex(color ?? '#ffffff');
    const intStr = intensity !== undefined ? String(intensity) : '1.0';

    switch (light.lightType) {
      case 'hemisphere':
      case 'ambient':
        this.emit(`const ${v} = new THREE.AmbientLight(${colorHex}, ${intStr});`);
        this.emit(`this.scene.add(${v});`);
        break;
      case 'directional': {
        this.emit(`const ${v} = new THREE.DirectionalLight(${colorHex}, ${intStr});`);
        const pos = position ?? direction ?? [5, 10, 5];
        this.emit(`${v}.position.set(${pos[0]}, ${pos[1]}, ${pos[2]});`);
        if (castShadow && this.options.enableShadows) {
          this.emit(`${v}.castShadow = true;`);
          this.emit(`${v}.shadow.mapSize.set(2048, 2048);`);
          this.emit(`${v}.shadow.camera.near = 0.1;`);
          this.emit(`${v}.shadow.camera.far = 500;`);
        }
        this.emit(`this.scene.add(${v});`);
        break;
      }
      case 'point': {
        const distStr = distance !== undefined ? String(distance) : '0';
        this.emit(
          `const ${v} = new THREE.PointLight(${colorHex}, ${intStr}, ${distStr});`
        );
        if (position) this.emit(`${v}.position.set(${position[0]}, ${position[1]}, ${position[2]});`);
        if (castShadow && this.options.enableShadows) this.emit(`${v}.castShadow = true;`);
        this.emit(`this.scene.add(${v});`);
        break;
      }
      case 'spot': {
        const angleRad =
          angle !== undefined ? `${angle} * Math.PI / 180` : 'Math.PI / 6';
        const pen = penumbra ?? 0.1;
        this.emit(
          `const ${v} = new THREE.SpotLight(${colorHex}, ${intStr}, ${distance ?? 0}, ${angleRad}, ${pen});`
        );
        if (position) this.emit(`${v}.position.set(${position[0]}, ${position[1]}, ${position[2]});`);
        if (castShadow && this.options.enableShadows) this.emit(`${v}.castShadow = true;`);
        this.emit(`this.scene.add(${v});`);
        break;
      }
      default:
        this.emit(`// Light "${light.lightType}" not mapped — using AmbientLight fallback`);
        this.emit(`const ${v} = new THREE.AmbientLight(${colorHex}, ${intStr});`);
        this.emit(`this.scene.add(${v});`);
    }
    this.emit('');
  }

  // --- Camera ---

  private emitCamera(camera: HoloCamera): void {
    let position: unknown[] | undefined;
    let target: unknown[] | undefined;
    let fov: number | undefined;
    let near: number | undefined;
    let far: number | undefined;

    for (const p of camera.properties) {
      if (p.key === 'position' && Array.isArray(p.value)) position = p.value;
      else if (p.key === 'target' && Array.isArray(p.value)) target = p.value;
      else if (p.key === 'fov') fov = p.value as number;
      else if (p.key === 'near') near = p.value as number;
      else if (p.key === 'far') far = p.value as number;
    }

    if (fov !== undefined) this.emit(`this.camera.fov = ${fov};`);
    if (near !== undefined) this.emit(`this.camera.near = ${near};`);
    if (far !== undefined) this.emit(`this.camera.far = ${far};`);
    if (position)
      this.emit(
        `this.camera.position.set(${position[0]}, ${position[1]}, ${position[2]});`
      );
    if (target) {
      this.emit(
        `this.camera.lookAt(new THREE.Vector3(${target[0]}, ${target[1]}, ${target[2]}));`
      );
    }
    this.emit(`this.camera.updateProjectionMatrix();`);
    this.emit('');
  }

  // --- Audio ---

  private emitAudio(audio: HoloAudio): void {
    const v = this.sanitizeName(audio.name);
    let src = '';
    let loop = false;
    let volume = 1;
    let spatial = false;
    for (const p of audio.properties) {
      if (p.key === 'src' || p.key === 'source') src = String(p.value);
      else if (p.key === 'loop') loop = !!p.value;
      else if (p.key === 'volume') volume = p.value as number;
      else if (p.key === 'spatial') spatial = !!p.value;
    }
    if (spatial) {
      this.emit(`const ${v}Listener = new THREE.AudioListener();`);
      this.emit(`this.camera.add(${v}Listener);`);
      this.emit(`const ${v} = new THREE.PositionalAudio(${v}Listener);`);
    } else {
      this.emit(`const ${v}Listener = new THREE.AudioListener();`);
      this.emit(`this.camera.add(${v}Listener);`);
      this.emit(`const ${v} = new THREE.Audio(${v}Listener);`);
    }
    this.emit(`const ${v}Loader = new THREE.AudioLoader();`);
    this.emit(
      `${v}Loader.load("${src}", (buffer) => { ${v}.setBuffer(buffer); ${v}.setLoop(${loop}); ${v}.setVolume(${volume}); ${v}.play(); });`
    );
    this.emit('');
  }

  // --- Zones ---

  private emitZone(zone: HoloZone): void {
    const v = this.sanitizeName(zone.name);
    let shape = 'box';
    let position: unknown[] | undefined;
    let size: unknown;
    let radius: number | undefined;

    for (const p of zone.properties) {
      if (p.key === 'shape') shape = String(p.value);
      else if (p.key === 'position' && Array.isArray(p.value)) position = p.value;
      else if (p.key === 'size') size = p.value;
      else if (p.key === 'radius') radius = p.value as number;
    }

    if (shape === 'sphere') {
      this.emit(
        `const ${v}Geom = new THREE.SphereGeometry(${radius ?? 5}, 16, 16);`
      );
    } else {
      const s = Array.isArray(size) ? size : [size ?? 5, size ?? 5, size ?? 5];
      this.emit(`const ${v}Geom = new THREE.BoxGeometry(${s[0]}, ${s[1]}, ${s[2]});`);
    }
    this.emit(
      `const ${v}Mat = new THREE.MeshBasicMaterial({ color: 0x00ff00, wireframe: true, visible: false });`
    );
    this.emit(`const ${v} = new THREE.Mesh(${v}Geom, ${v}Mat);`);
    if (position) this.emit(`${v}.position.set(${position[0]}, ${position[1]}, ${position[2]});`);
    this.emit(`this.scene.add(${v}); // trigger zone (invisible)`);

    if (zone.handlers?.length) {
      this.emit(
        `// Zone handlers: attach raycaster intersection checks for ${v}`
      );
      for (const h of zone.handlers) {
        this.emit(
          `// on ${this.escapeStringValue(h.event as string, 'TypeScript')}: implement via raycaster.intersectObject(${v})`
        );
      }
    }
    this.emit('');
  }

  // --- Render Loop ---

  private emitRenderLoop(): void {
    this.emit('// Render loop');
    this.emit('const animate = (): void => {');
    this.indent();
    this.emit('this.frameId = requestAnimationFrame(animate);');
    this.emit('this.renderer.render(this.scene, this.camera);');
    this.dedent();
    this.emit('};');
    this.emit('animate();');
    this.emit('');
    this.emit('// Resize handler');
    this.emit('window.addEventListener("resize", () => {');
    this.indent();
    this.emit('const w = this.canvas.clientWidth, h = this.canvas.clientHeight;');
    this.emit('this.renderer.setSize(w, h);');
    this.emit('this.camera.aspect = w / h;');
    this.emit('this.camera.updateProjectionMatrix();');
    this.dedent();
    this.emit('});');
  }

  // --- Value Helpers ---

  private toThreeColorHex(value: unknown): string {
    if (typeof value === 'string' && value.startsWith('#')) {
      return `0x${value.slice(1)}`;
    }
    if (typeof value === 'number') return `0x${value.toString(16).padStart(6, '0')}`;
    return '0xffffff';
  }

  private buildMaterialProps(mat: Record<string, unknown>): string {
    const parts: string[] = [];
    if (mat.color !== undefined) {
      parts.push(`color: ${this.toThreeColorHex(mat.color)}`);
    }
    if (mat.roughness !== undefined) parts.push(`roughness: ${mat.roughness}`);
    if (mat.metalness !== undefined) parts.push(`metalness: ${mat.metalness}`);
    if (mat.opacity !== undefined && (mat.opacity as number) < 1) {
      parts.push(`opacity: ${mat.opacity}`, 'transparent: true');
    }
    if (mat.emissive !== undefined) {
      parts.push(`emissive: ${this.toThreeColorHex(mat.emissive)}`);
    }
    if (mat.emissiveIntensity !== undefined) {
      parts.push(`emissiveIntensity: ${mat.emissiveIntensity}`);
    }
    return parts.join(', ');
  }

  private geometryArgs(type: string, size: unknown): string {
    const s = typeof size === 'number' ? size : 1;
    switch (type) {
      case 'sphere':
      case 'orb':
        return `${s * 0.5}, 32, 32`;
      case 'cube':
      case 'box':
        return `${s}, ${s}, ${s}`;
      case 'cylinder':
        return `${s * 0.5}, ${s * 0.5}, ${s * 2}, 32`;
      case 'cone':
      case 'pyramid':
        return `${s * 0.5}, ${s * 2}, ${type === 'pyramid' ? 4 : 32}`;
      case 'plane':
      case 'ground':
        return `${s}, ${s}`;
      case 'torus':
      case 'ring':
        return `${s * 0.5}, ${s * 0.15}, 16, 64`;
      case 'capsule':
        return `${s * 0.3}, ${s * 0.6}, 4, 16`;
      default:
        return `${s}, ${s}, ${s}`;
    }
  }

  // --- Emit Helpers ---

  private emit(line: string): void {
    this.lines.push(this.options.indent.repeat(this.indentLevel) + line);
  }
  private indent(): void {
    this.indentLevel++;
  }
  private dedent(): void {
    this.indentLevel = Math.max(0, this.indentLevel - 1);
  }
  private sanitizeName(name: string): string {
    return name.replace(/[^a-zA-Z0-9_]/g, '_');
  }
}
