/**
 * Vector2DCompiler — HoloScript composition → @generated 2D-vector SVG React component.
 *
 * The missing native target: HoloScript could render 3D (R3F), UI layout (Native2DCompiler),
 * and ray-marched SDF — but had NO path for flat 2D VECTOR graphics / data-viz (polylines,
 * rings, spokes, plotted points). This target fills that gap so charts and stat-webs are
 * authored in HoloScript and emitted with an `@generated by HoloScript` header (satisfying the
 * render-surface-native freeze natively, not via allowlist).
 *
 * Two layers:
 *  - low-level vector primitives: `line | polyline | polygon | circle | text | group`
 *    (objects whose `kind`/`type` property names the primitive; coords in props).
 *  - high-level chart composites: `radar` (axes + series → the compiler computes the polar
 *    layout and expands to primitives). The radar is consumer #1; more chart kinds slot in
 *    beside it.
 *
 * Reusable across any 2D-vector page; the agent-ability stat-web is its first consumer.
 *
 * The primitive/radar emitters + property accessors live in `./vector2d/emit` as a shared,
 * byte-stable vocabulary reusable by future 2D-vector / native-panel targets (factored 2026-06-14;
 * behaviour guarded by __tests__/Vector2DCompiler.test.ts).
 */

import type { HoloComposition, HoloObjectDecl } from '../parser/HoloCompositionTypes';
import { strProp, esc, emitPrimitive, emitRadar } from './vector2d/emit';

export interface Vector2DCompileOptions {
  /** Component name; defaults to the composition name. */
  componentName?: string;
  /** SVG viewBox width/height. */
  width?: number;
  height?: number;
}
export interface Vector2DCompileResult {
  code: string;
  componentName: string;
}

const HEADER = '// @generated by HoloScript Vector2DCompiler — DO NOT EDIT\n';

// ── compiler ─────────────────────────────────────────────────────────────────
export class Vector2DCompiler {
  compile(
    composition: HoloComposition,
    options: Vector2DCompileOptions = {}
  ): Vector2DCompileResult {
    const objects = (composition.objects || []) as HoloObjectDecl[];
    const width = options.width ?? 460;
    const height = options.height ?? 440;
    const rawName = options.componentName || composition.name || 'Vector2D';
    const componentName = rawName.replace(/[^A-Za-z0-9_]/g, '') || 'Vector2D';

    const body: string[] = [];
    const axes = objects.filter((o) => strProp(o, 'kind') === 'axis' || o.name.startsWith('axis'));
    const series = objects.filter(
      (o) => strProp(o, 'kind') === 'series' || o.name.startsWith('series')
    );
    for (const obj of objects) {
      const declared = strProp(obj, 'kind');
      if (declared === 'radar' || obj.name === 'radar') body.push(...emitRadar(obj, axes, series));
      else if (declared && declared !== 'axis' && declared !== 'series')
        body.push(...emitPrimitive(obj, declared));
    }

    const svg = body.map((l) => '        ' + l).join('\n');
    const code = `${HEADER}import React from 'react';

export default function ${componentName}() {
  return (
    <div style={{ maxWidth: ${width + 60}, margin: '0 auto', padding: 24 }}>
      <svg viewBox="0 0 ${width} ${height}" style={{ width: '100%', height: 'auto' }} role="img" aria-label="${esc(rawName)}">
${svg}
      </svg>
    </div>
  );
}
`;
    return { code, componentName };
  }
}

export default Vector2DCompiler;
