/**
 * HoloScript → visionOS Swift / RealityKit Compiler
 *
 * Translates a HoloComposition AST into a Swift file targeting
 * Apple's RealityKit framework for visionOS.
 *
 * Emits:
 *   - A Swift struct conforming to ImmersiveSpace / RealityView
 *   - Entity creation using ModelEntity, AnchorEntity
 *   - PBR materials via PhysicallyBasedMaterial / SimpleMaterial
 *   - Spatial audio via AudioFileGroupResource
 *   - Physics via PhysicsBodyComponent, CollisionComponent
 *   - Environment via ImageBasedLight
 *
 * @version 1.0.0
 */

import type {
  HoloComposition,
  HoloObjectDecl,
  HoloSpatialGroup,
  HoloLight,
  HoloEnvironment,
  HoloTimeline,
  HoloAudio,
  HoloZone,
  HoloTransition,
  HoloEffects,
  HoloValue,
} from '../parser/HoloCompositionTypes';
import { generateTraitCode, getRequiredImports, getMinVisionOSVersion } from './VisionOSTraitMap';
import { CompilerBase } from './CompilerBase';
import { filterCompositionForPlatform } from './PlatformConditionalCompilerMixin';
import { ANSCapabilityPath, type ANSCapabilityPathValue } from '@holoscript/core-types/ans';
import {
  compileDomainBlocks,
  compileMaterialBlock,
  compilePhysicsBlock,
  compileParticleBlock,
  compilePostProcessingBlock,
  compileAudioSourceBlock,
  compileWeatherBlock,
  materialToVisionOS,
  physicsToVisionOS,
  particlesToVisionOS,
  audioSourceToVisionOS,
} from './DomainBlockCompilerMixin';
import type { CompiledPostProcessing, CompiledWeather } from './DomainBlockCompilerMixin';

export interface VisionOSCompilerOptions {
  structName?: string;
  indent?: string;
  useRealityComposerPro?: boolean;
}

interface VisionOSWindowDescriptor {
  objectName: string;
  type: string;
  scale: [number, number, number];
  minSize?: [number, number];
  maxSize?: [number, number];
  cornerRadius?: number;
  glassBackground: boolean;
  opacity: number;
}

interface VisionOSOrnamentDescriptor {
  objectName: string;
  attachTo: string;
  position: string;
  offset: [number, number, number];
  ui: Record<string, HoloValue>;
}

export class VisionOSCompiler extends CompilerBase {
  protected readonly compilerName = 'VisionOSCompiler';

  protected override getRequiredCapability(): ANSCapabilityPathValue {
    return ANSCapabilityPath.VISIONOS;
  }

  private options: Required<VisionOSCompilerOptions>;
  private lines: string[] = [];
  private indentLevel: number = 0;

  constructor(options: VisionOSCompilerOptions = {}) {
    super();
    this.options = {
      structName: options.structName || 'GeneratedScene',
      indent: options.indent || '    ',
      useRealityComposerPro: options.useRealityComposerPro ?? false,
    };
  }

  compile(composition: HoloComposition, agentToken: string, outputPath?: string): string {
    this.validateCompilerAccess(agentToken, outputPath);
    composition = filterCompositionForPlatform(composition, 'visionos');
    this.lines = [];
    this.indentLevel = 0;

    this.emit('// Auto-generated by HoloScript VisionOSCompiler');
    this.emit(
      `// Source: composition "${this.escapeStringValue(composition.name as string, 'Swift')}"`
    );
    this.emit('// Do not edit manually — regenerate from .holo source');
    this.emit('');
    this.emit('import SwiftUI');
    this.emit('import RealityKit');
    this.emit('import RealityKitContent');

    // Dynamic imports based on traits used
    const allTraits = this.collectAllTraits(composition);
    const sharePlayConfig = this.getSharePlayConfig(composition);
    const requiredImports = getRequiredImports(allTraits);
    for (const imp of requiredImports) {
      this.emit(`import ${imp}`);
    }
    if (sharePlayConfig && !requiredImports.includes('GroupActivities')) {
      this.emit('import GroupActivities');
    }
    if (composition.audio?.length && !requiredImports.includes('AVFoundation')) {
      this.emit('import AVFoundation');
    }

    // Check minimum visionOS version
    const minVersion = getMinVisionOSVersion(allTraits);
    if (minVersion !== '1.0') {
      this.emit(`// Requires visionOS ${minVersion}+`);
    }
    this.emit('');

    const volumetricWindows = this.collectVolumetricWindows(composition);
    const ornaments = this.collectOrnaments(composition);
    if (volumetricWindows.length > 0) {
      this.compileVolumetricWindowDescriptorType();
      this.emit('');
    }

    // State class
    if (composition.state) {
      this.emit('@Observable');
      this.emit(`class ${this.options.structName}State {`);
      this.indentLevel++;
      for (const prop of composition.state.properties) {
        const swiftType = this.toSwiftType(prop.value);
        const swiftVal = this.toSwiftValue(prop.value);
        this.emit(
          `var ${this.escapeStringValue(prop.key as string, 'Swift')}: ${swiftType} = ${swiftVal}`
        );
      }
      this.indentLevel--;
      this.emit('}');
      this.emit('');
    }

    // Main view struct
    this.emit(`struct ${this.options.structName}: View {`);
    this.indentLevel++;

    if (composition.state) {
      this.emit(`@State private var state = ${this.options.structName}State()`);
      this.emit('');
    }

    this.emit('var body: some View {');
    this.indentLevel++;
    this.emit('RealityView { content in');
    this.indentLevel++;

    // Build scene
    this.emit('let root = Entity()');
    this.emit(`root.name = "${this.escapeStringValue(composition.name as string, 'Swift')}"`);

    // Environment
    if (composition.environment) {
      this.compileEnvironment(composition.environment);
    }

    // Lights
    if (composition.lights) {
      for (const light of composition.lights) {
        this.compileLight(light);
      }
    }

    // Objects
    if (composition.objects) {
      for (const obj of composition.objects) {
        this.compileObject(obj, 'root');
      }
    }

    // Spatial groups
    if (composition.spatialGroups) {
      for (const group of composition.spatialGroups) {
        this.compileSpatialGroup(group, 'root');
      }
    }

    // Audio
    if (composition.audio) {
      for (const audio of composition.audio) {
        this.compileAudio(audio);
      }
    }

    // Zones
    if (composition.zones) {
      for (const zone of composition.zones) {
        this.compileZone(zone);
      }
    }

    this.emit('');
    this.emit('content.add(root)');

    this.indentLevel--;
    this.emit('}');

    // Gesture attachments
    const grabbables =
      composition.objects?.filter((o) => o.traits?.some((t) => t.name === 'grabbable')) || [];
    if (grabbables.length > 0) {
      this.emit('.gesture(DragGesture().targetedToAnyEntity().onChanged { value in');
      this.indentLevel++;
      this.emit(
        'value.entity.position = value.convert(value.location3D, from: .local, to: .scene)'
      );
      this.indentLevel--;
      this.emit('})');
    }

    this.indentLevel--;
    this.emit('}');

    // Timeline methods
    if (composition.timelines) {
      for (const tl of composition.timelines) {
        this.compileTimeline(tl);
      }
    }

    // Transition methods
    if (composition.transitions) {
      for (const tr of composition.transitions) {
        this.compileTransition(tr);
      }
    }

    if (volumetricWindows.length > 0) {
      this.compileVolumetricWindowScenes(volumetricWindows, ornaments);
    }

    if (sharePlayConfig) {
      this.compileSharePlaySupport(sharePlayConfig);
    }

    this.indentLevel--;
    this.emit('}');

    // Effects comments
    if (composition.effects) {
      this.emit('');
      this.compileEffects(composition.effects);
    }

    // v4.2: Domain Blocks (materials, physics, particles, post-processing, audio, weather)
    this.compileVisionOSDomainBlocks(composition);

    return this.lines.join('\n');
  }

  private compileVisionOSDomainBlocks(composition: HoloComposition): void {
    const domainBlocks = composition.domainBlocks ?? [];
    if (domainBlocks.length === 0) return;

    this.emit('');
    this.emit('// === v4.2 Domain Blocks ===');

    let blockIdx = 0;
    const compiled = compileDomainBlocks(
      domainBlocks,
      {
        material: (block) => {
          const mat = compileMaterialBlock(block);
          return materialToVisionOS(mat, `db${blockIdx++}`);
        },
        physics: (block) => {
          const phys = compilePhysicsBlock(block);
          return physicsToVisionOS(phys, `db${blockIdx++}`);
        },
        vfx: (block) => {
          const ps = compileParticleBlock(block);
          return particlesToVisionOS(ps, `db${blockIdx++}`);
        },
        postfx: (block) => {
          const pp = compilePostProcessingBlock(block);
          return `// Post-Processing: ${(pp as CompiledPostProcessing).keyword} — configure via RealityKit RenderCallbacks`;
        },
        audio: (block) => {
          const audio = compileAudioSourceBlock(block);
          return audioSourceToVisionOS(audio, `db${blockIdx++}`);
        },
        weather: (block) => {
          const weather = compileWeatherBlock(block);
          const w = weather as CompiledWeather;
          const layers = w.layers
            .map((l) => `// Layer: ${l.type} — ${JSON.stringify(l.properties)}`)
            .join('\n');
          return `// Weather: ${w.keyword} "${w.name || ''}" — implement via custom RealityKit particles\n${layers}`;
        },
      },
      (block) =>
        `// Domain block: ${block.domain}/${block.keyword} "${this.escapeStringValue(block.name as string, 'Swift')}"`
    );

    for (const line of compiled) {
      for (const l of line.split('\n')) {
        this.emit(l);
      }
    }
  }

  private compileEnvironment(env: HoloEnvironment): void {
    this.emit('');
    this.emit('// === Environment ===');
    for (const prop of env.properties) {
      if (prop.key === 'preset' || prop.key === 'skybox') {
        this.emit(`// Environment preset: "${prop.value}" — configure via ImageBasedLight`);
        this.emit('if let iblResource = try? await EnvironmentResource(named: "IBL") {');
        this.indentLevel++;
        this.emit('let iblComponent = ImageBasedLightComponent(source: .single(iblResource))');
        this.emit('root.components.set(iblComponent)');
        this.emit('root.components.set(ImageBasedLightReceiverComponent(imageBasedLight: root))');
        this.indentLevel--;
        this.emit('}');
      } else if (prop.key === 'fog' && typeof prop.value === 'object') {
        this.emit(
          `// Fog: ${JSON.stringify(prop.value)} — not natively supported, use post-processing`
        );
      } else if (prop.key === 'ambient_light') {
        this.emit(`// Ambient light: ${prop.value} — handled via IBL intensity`);
      } else if (prop.key === 'style') {
        // Fidelity gap closure for CG-005 (environment.style)
        const style = String(prop.value).toLowerCase();
        if (style.includes('immersive')) {
          this.emit('root.components.set(ImmersionStyleComponent(style: .full))');
        } else if (style.includes('mixed')) {
          this.emit('root.components.set(ImmersionStyleComponent(style: .mixed))');
        } else if (style.includes('progressive')) {
          this.emit('root.components.set(ImmersionStyleComponent(style: .progressive))');
        } else {
          this.emit(`// Environment style: "${prop.value}"`);
        }
      }
    }
  }

  private compileLight(light: HoloLight): void {
    const varName = this.sanitizeName(light.name);
    this.emit('');
    this.emit(`// Light: ${this.escapeStringValue(light.name as string, 'Swift')}`);

    // RealityKit uses PointLightComponent / DirectionalLightComponent / SpotLightComponent
    const typeMap: Record<string, string> = {
      directional: 'DirectionalLightComponent',
      point: 'PointLightComponent',
      spot: 'SpotLightComponent',
    };
    const rkType = typeMap[light.lightType];

    if (rkType) {
      this.emit(`let ${varName} = Entity()`);
      this.emit(`${varName}.name = "${this.escapeStringValue(light.name as string, 'Swift')}"`);

      const colorProp = light.properties.find((p) => p.key === 'color');
      const intensityProp = light.properties.find((p) => p.key === 'intensity');
      const posProp = light.properties.find((p) => p.key === 'position');

      if (light.lightType === 'point') {
        this.emit(`var ${varName}Light = PointLightComponent()`);
        if (colorProp)
          this.emit(`${varName}Light.color = .init(${this.toUIColor(colorProp.value)})`);
        if (intensityProp)
          this.emit(`${varName}Light.intensity = ${(intensityProp.value as number) * 1000}`);
      } else if (light.lightType === 'directional') {
        this.emit(`var ${varName}Light = DirectionalLightComponent()`);
        if (colorProp)
          this.emit(`${varName}Light.color = .init(${this.toUIColor(colorProp.value)})`);
        if (intensityProp)
          this.emit(`${varName}Light.intensity = ${(intensityProp.value as number) * 1000}`);
      } else if (light.lightType === 'spot') {
        this.emit(`var ${varName}Light = SpotLightComponent()`);
        if (colorProp)
          this.emit(`${varName}Light.color = .init(${this.toUIColor(colorProp.value)})`);
        if (intensityProp)
          this.emit(`${varName}Light.intensity = ${(intensityProp.value as number) * 1000}`);
      }

      this.emit(`${varName}.components.set(${varName}Light)`);

      if (posProp && Array.isArray(posProp.value)) {
        this.emit(`${varName}.position = ${this.toSIMD3(posProp.value)}`);
      }

      this.emit(`root.addChild(${varName})`);
    } else {
      this.emit(`// Light type "${light.lightType}" not directly supported in RealityKit`);
    }
  }

  private compileObject(obj: HoloObjectDecl, parentVar: string): void {
    // Check if this is a UI component
    if (this.isUIComponent(obj)) {
      this.compileUIComponent(obj, parentVar);
      return;
    }

    const varName = this.sanitizeName(obj.name);
    const geometry = this.findObjProp(obj, 'geometry');
    const modelSource = this.getModelSource(obj, geometry);
    const meshType =
      this.findObjProp(obj, 'mesh') || this.findObjProp(obj, 'type') || geometry || 'cube';
    const isText = meshType === 'text';
    const isModel = !!modelSource || meshType === 'model';
    const isLight = ['directional', 'point', 'spot', 'hemisphere', 'ambient', 'area'].includes(
      meshType as string
    );
    const isSparkles = meshType === 'sparkles';

    this.emit('');
    this.emit(`// Object: ${this.escapeStringValue(obj.name as string, 'Swift')}`);

    if (isLight) {
      this.emit(
        `// Light object "${this.escapeStringValue(obj.name as string, 'Swift')}" — handled via light components`
      );
      return;
    }

    if (isText) {
      this.emit(`let ${varName} = Entity()`);
      this.emit(`${varName}.name = "${this.escapeStringValue(obj.name as string, 'Swift')}"`);
      const text = this.findObjProp(obj, 'text');
      const fontSize = this.findObjProp(obj, 'font_size') || 0.1;
      if (text) {
        this.emit(`let ${varName}Mesh = MeshResource.generateText("${text}",`);
        this.emit(`    extrusionDepth: 0.001,`);
        this.emit(`    font: .systemFont(ofSize: CGFloat(${(fontSize as number) * 10})),`);
        this.emit(`    containerFrame: .zero,`);
        this.emit(`    alignment: .center,`);
        this.emit(`    lineBreakMode: .byWordWrapping)`);
        this.emit(
          `${varName}.components.set(ModelComponent(mesh: ${varName}Mesh, materials: [SimpleMaterial(color: ${this.toUIColor(this.findObjProp(obj, 'color') || '#ffffff')}, isMetallic: false)]))`
        );
      }
    } else if (isModel) {
      const src = modelSource ?? 'MissingModel';
      this.emit(`let ${varName}Mesh = MeshResource.generateBox(size: 0.1) // collision proxy`);
      this.emit(
        `let ${varName} = try! await ModelEntity(named: "${this.escapeStringValue(String(src), 'Swift')}", in: realityKitContentBundle)`
      );
      this.emit(`${varName}.name = "${this.escapeStringValue(obj.name as string, 'Swift')}"`);
    } else if (isSparkles) {
      this.emit(`// Sparkles: use ParticleEmitterComponent in visionOS 2.0+`);
      this.emit(`let ${varName}Mesh = MeshResource.generateBox(size: 0.1) // interaction proxy`);
      this.emit(`let ${varName} = Entity()`);
      this.emit(`${varName}.name = "${this.escapeStringValue(obj.name as string, 'Swift')}"`);
    } else {
      // Mesh entity
      const meshMap: Record<string, string> = {
        sphere: '.generateSphere(radius: 0.5)',
        box: '.generateBox(size: 1.0)',
        cube: '.generateBox(size: 1.0)',
        plane: '.generatePlane(width: 1.0, depth: 1.0)',
        cylinder: '.generateBox(size: 1.0)', // No cylinder in RealityKit, use box
        cone: '.generateBox(size: 1.0)',
        torus: '.generateBox(size: 1.0)',
      };

      const meshGen = meshMap[meshType as string] || '.generateBox(size: 1.0)';
      const size = this.findObjProp(obj, 'size');
      const radius = this.findObjProp(obj, 'radius');

      let meshCall = meshGen;
      if (meshType === 'sphere' && radius) {
        meshCall = `.generateSphere(radius: ${radius})`;
      } else if ((meshType === 'box' || meshType === 'cube') && size) {
        if (Array.isArray(size)) {
          meshCall = `.generateBox(width: ${size[0]}, height: ${size[1]}, depth: ${size[2]})`;
        } else {
          meshCall = `.generateBox(size: ${size})`;
        }
      } else if (meshType === 'plane' && size) {
        meshCall = `.generatePlane(width: ${size}, depth: ${size})`;
      }

      this.emit(`let ${varName}Mesh = MeshResource${meshCall}`);

      // Material
      const material = this.findObjProp(obj, 'material');
      if (material && typeof material === 'object') {
        const mat = material as Record<string, any>;
        this.emit(`var ${varName}Material = PhysicallyBasedMaterial()`);
        if (mat.color)
          this.emit(`${varName}Material.baseColor = .init(tint: ${this.toUIColor(mat.color)})`);
        if (mat.roughness !== undefined)
          this.emit(`${varName}Material.roughness = .init(floatLiteral: ${mat.roughness})`);
        if (mat.metalness !== undefined)
          this.emit(`${varName}Material.metallic = .init(floatLiteral: ${mat.metalness})`);
        if (mat.emissive)
          this.emit(
            `${varName}Material.emissiveColor = .init(color: ${this.toUIColor(mat.emissive)})`
          );
        if (mat.emissiveIntensity)
          this.emit(`${varName}Material.emissiveIntensity = ${mat.emissiveIntensity}`);
        this.emit(
          `let ${varName} = ModelEntity(mesh: ${varName}Mesh, materials: [${varName}Material])`
        );
      } else {
        this.emit(
          `let ${varName} = ModelEntity(mesh: ${varName}Mesh, materials: [SimpleMaterial()])`
        );
      }

      this.emit(`${varName}.name = "${this.escapeStringValue(obj.name as string, 'Swift')}"`);
    }

    this.compileObjectTraits(obj, varName);
    this.compileVolumetricWindowMetadata(obj, varName);
    this.compileObjectAnimations(obj, varName);
    this.compileObjectEventHandlers(obj, varName);

    // Position, rotation, scale
    const pos = this.findObjProp(obj, 'position');
    if (pos) this.emit(`${varName}.position = ${this.toSIMD3(pos)}`);
    const rot = this.findObjProp(obj, 'rotation');
    if (rot && Array.isArray(rot)) {
      // Convert degrees to radians for RealityKit
      const radX = ((rot[0] as number) * Math.PI) / 180;
      const radY = ((rot[1] as number) * Math.PI) / 180;
      const radZ = ((rot[2] as number) * Math.PI) / 180;
      this.emit(
        `${varName}.orientation = simd_quatf(angle: ${radX.toFixed(4)}, axis: SIMD3<Float>(1, 0, 0)) * simd_quatf(angle: ${radY.toFixed(4)}, axis: SIMD3<Float>(0, 1, 0)) * simd_quatf(angle: ${radZ.toFixed(4)}, axis: SIMD3<Float>(0, 0, 1))`
      );
    }
    const scale = this.findObjProp(obj, 'scale');
    if (scale) this.emit(`${varName}.scale = ${this.toSIMD3(scale)}`);

    this.emit(`${parentVar}.addChild(${varName})`);

    // Children
    if (obj.children) {
      for (const child of obj.children) {
        this.compileObject(child, varName);
      }
    }
  }

  private compileSpatialGroup(group: HoloSpatialGroup, parentVar: string): void {
    const varName = this.sanitizeName(group.name);
    this.emit('');
    this.emit(`// Spatial Group: ${this.escapeStringValue(group.name as string, 'Swift')}`);
    this.emit(`let ${varName} = Entity()`);
    this.emit(`${varName}.name = "${this.escapeStringValue(group.name as string, 'Swift')}"`);

    for (const prop of group.properties) {
      if (prop.key === 'position' && Array.isArray(prop.value)) {
        this.emit(`${varName}.position = ${this.toSIMD3(prop.value)}`);
      }
    }

    this.emit(`${parentVar}.addChild(${varName})`);

    for (const obj of group.objects) {
      this.compileObject(obj, varName);
    }

    if (group.groups) {
      for (const sub of group.groups) {
        this.compileSpatialGroup(sub, varName);
      }
    }
  }

  private compileAudio(audio: HoloAudio): void {
    const varName = this.sanitizeName(audio.name);
    this.emit('');
    this.emit(`// Audio: ${this.escapeStringValue(audio.name as string, 'Swift')}`);
    this.emit(`let ${varName} = Entity()`);
    this.emit(`${varName}.name = "${this.escapeStringValue(audio.name as string, 'Swift')}"`);

    const src = audio.properties.find((p) => p.key === 'src' || p.key === 'source')?.value;
    const spatial = audio.properties.find((p) => p.key === 'spatial')?.value;

    if (src) {
      this.emit(`if let audioResource = try? await AudioFileResource(named: "${src}") {`);
      this.indentLevel++;
      if (spatial) {
        this.emit(`let audioController = ${varName}.prepareAudio(audioResource)`);
        this.emit(`${varName}.components.set(SpatialAudioComponent())`);
      } else {
        this.emit(`let audioController = ${varName}.prepareAudio(audioResource)`);
        this.emit(`${varName}.components.set(AmbientAudioComponent())`);
      }
      this.emit('audioController.play()');
      this.indentLevel--;
      this.emit('}');
    }

    const pos = audio.properties.find((p) => p.key === 'position')?.value;
    if (pos) this.emit(`${varName}.position = ${this.toSIMD3(pos)}`);

    this.emit(`root.addChild(${varName})`);
  }

  private compileZone(zone: HoloZone): void {
    const varName = this.sanitizeName(zone.name);
    this.emit('');
    this.emit(`// Zone: ${this.escapeStringValue(zone.name as string, 'Swift')}`);
    this.emit(`let ${varName} = Entity()`);
    this.emit(`${varName}.name = "${this.escapeStringValue(zone.name as string, 'Swift')}"`);

    const shape = zone.properties.find((p) => p.key === 'shape')?.value;
    if (shape === 'box') {
      const size = zone.properties.find((p) => p.key === 'size')?.value;
      if (size && Array.isArray(size)) {
        this.emit(
          `${varName}.components.set(CollisionComponent(shapes: [.generateBox(size: ${this.toSIMD3(size)})]))`
        );
      }
    } else if (shape === 'sphere') {
      const radius = zone.properties.find((p) => p.key === 'radius')?.value;
      if (radius) {
        this.emit(
          `${varName}.components.set(CollisionComponent(shapes: [.generateSphere(radius: ${radius})]))`
        );
      }
    }

    const pos = zone.properties.find((p) => p.key === 'position')?.value;
    if (pos) this.emit(`${varName}.position = ${this.toSIMD3(pos)}`);

    this.emit(`// Zone handlers: ${zone.handlers?.map((h) => h.event).join(', ') || 'none'}`);
    this.emit(`root.addChild(${varName})`);
  }

  private compileTimeline(tl: HoloTimeline): void {
    const varName = this.sanitizeName(tl.name);
    this.emit('');
    this.emit(`func play${varName}() async {`);
    this.indentLevel++;

    let lastTime = 0;
    for (const entry of tl.entries) {
      const delay = entry.time - lastTime;
      if (delay > 0) {
        this.emit(`try? await Task.sleep(nanoseconds: ${Math.round(delay * 1_000_000_000)})`);
      }

      if (entry.action.kind === 'animate') {
        this.emit(
          `// Animate "${entry.action.target}": ${JSON.stringify(entry.action.properties)}`
        );
      } else if (entry.action.kind === 'emit') {
        this.emit(`// Emit: "${entry.action.event}"`);
      } else if (entry.action.kind === 'call') {
        this.emit(`// Call: ${entry.action.method}`);
      }

      lastTime = entry.time;
    }

    if (tl.loop) {
      this.emit(`await play${varName}() // loop`);
    }

    this.indentLevel--;
    this.emit('}');
  }

  private compileTransition(tr: HoloTransition): void {
    const varName = this.sanitizeName(tr.name);
    this.emit('');
    this.emit(`func ${varName}() {`);
    this.indentLevel++;

    const target = tr.properties.find((p) => p.key === 'target')?.value;
    this.emit(`// Transition to: "${target}"`);
    this.emit(`// Effect: ${tr.properties.find((p) => p.key === 'effect')?.value || 'default'}`);

    this.indentLevel--;
    this.emit('}');
  }

  private compileObjectTraits(obj: HoloObjectDecl, varName: string): void {
    if (!obj.traits) return;

    for (const trait of obj.traits) {
      const config = trait.config || {};
      const traitCode = generateTraitCode(trait.name, varName, config);
      for (const line of traitCode) {
        if (line) this.emit(line);
      }
    }
  }

  private compileVolumetricWindowDescriptorType(): void {
    this.emit('struct VolumetricWindowDescriptor {');
    this.indentLevel++;
    this.emit('let id: String');
    this.emit('let type: String');
    this.emit('let minSize: CGSize?');
    this.emit('let maxSize: CGSize?');
    this.emit('let cornerRadius: CGFloat?');
    this.emit('let glassBackground: Bool');
    this.emit('let opacity: Double');
    this.indentLevel--;
    this.emit('}');
  }

  private compileVolumetricWindowMetadata(obj: HoloObjectDecl, varName: string): void {
    const descriptor = this.getVolumetricWindowDescriptor(obj);
    if (!descriptor) return;

    this.emit(`let ${varName}VolumetricWindow = VolumetricWindowDescriptor(`);
    this.indentLevel++;
    this.emit(`id: "${this.escapeStringValue(descriptor.objectName, 'Swift')}",`);
    this.emit(`type: "${this.escapeStringValue(descriptor.type, 'Swift')}",`);
    this.emit(`minSize: ${this.toCGSizeValue(descriptor.minSize)}, // min_size`);
    this.emit(`maxSize: ${this.toCGSizeValue(descriptor.maxSize)}, // max_size`);
    this.emit(`cornerRadius: ${this.toOptionalNumber(descriptor.cornerRadius)}, // corner_radius`);
    this.emit(
      `glassBackground: ${descriptor.glassBackground ? 'true' : 'false'}, // glass_background`
    );
    this.emit(`opacity: ${descriptor.opacity} // opacity`);
    this.indentLevel--;
    this.emit(')');
    this.emit(`_ = ${varName}VolumetricWindow`);
    this.emit(`${varName}.components.set(OpacityComponent(opacity: ${descriptor.opacity}))`);
  }

  private compileVolumetricWindowScenes(
    windows: VisionOSWindowDescriptor[],
    ornaments: VisionOSOrnamentDescriptor[]
  ): void {
    this.emit('');
    this.emit('@SceneBuilder');
    this.emit('static func windowScenes() -> some Scene {');
    this.indentLevel++;

    for (const window of windows) {
      const windowOrnaments = ornaments.filter(
        (ornament) => ornament.attachTo === window.objectName
      );
      this.emit(`WindowGroup(id: "${this.escapeStringValue(window.objectName, 'Swift')}") {`);
      this.indentLevel++;
      this.emit('Self()');
      if (window.minSize || window.maxSize) {
        this.emit(`.frame(${this.toFrameArguments(window)})`);
      }
      if (window.cornerRadius !== undefined) {
        this.emit(`.clipShape(RoundedRectangle(cornerRadius: ${window.cornerRadius}))`);
      }
      if (window.glassBackground) {
        this.emit('.glassBackgroundEffect()');
      }
      if (window.opacity !== 1) {
        this.emit(`.opacity(${window.opacity})`);
      }
      for (const ornament of windowOrnaments) {
        this.compileOrnamentModifier(ornament);
      }
      this.indentLevel--;
      this.emit('}');
      this.emit('.windowStyle(.volumetric)');
      this.emit(
        `.defaultSize(width: ${window.scale[0]}, height: ${window.scale[1]}, depth: ${window.scale[2]}, in: .meters)`
      );
    }

    this.indentLevel--;
    this.emit('}');
  }

  private compileOrnamentModifier(ornament: VisionOSOrnamentDescriptor): void {
    const anchor = this.toAttachmentAnchor(ornament.position);
    const alignment = this.toContentAlignment(ornament.position);
    this.emit(
      `.ornament(visibility: .visible, attachmentAnchor: ${anchor}, contentAlignment: ${alignment}) {`
    );
    this.indentLevel++;
    this.compileOrnamentContent(ornament);
    this.emit(`.offset(x: ${ornament.offset[0]}, y: ${ornament.offset[1]})`);
    this.indentLevel--;
    this.emit('}');
  }

  private compileOrnamentContent(ornament: VisionOSOrnamentDescriptor): void {
    const uiType = String(ornament.ui.type ?? 'button');
    if (uiType === 'toolbar') {
      const items = Array.isArray(ornament.ui.items) ? ornament.ui.items : [];
      this.emit('HStack {');
      this.indentLevel++;
      for (const item of items) {
        this.emit(
          `Button { } label: { Image(systemName: "${this.escapeStringValue(String(item), 'Swift')}") }`
        );
      }
      this.indentLevel--;
      this.emit('}');
      if (ornament.ui.style === 'glass') {
        this.emit('.glassBackgroundEffect()');
      }
      return;
    }

    const icon = String(ornament.ui.icon ?? 'circle');
    this.emit(
      `Button { } label: { Image(systemName: "${this.escapeStringValue(icon, 'Swift')}") }`
    );
    this.emit('.glassBackgroundEffect()');
  }

  private compileObjectAnimations(obj: HoloObjectDecl, varName: string): void {
    const animations = this.getObjectDirectives(obj, 'animation');
    for (const animation of animations) {
      const body = this.asRecord(animation.body);
      const name = this.sanitizeName(String(animation.name ?? 'Animation'));
      const property = String(body?.property ?? 'transform');
      const from = this.toOptionalNumeric(body?.from) ?? 0;
      const to = this.toOptionalNumeric(body?.to) ?? 0;
      const durationMs = this.toOptionalNumeric(body?.duration) ?? 1000;
      const durationSeconds = durationMs / 1000;
      const axis = property.endsWith('.x')
        ? '1, 0, 0'
        : property.endsWith('.z')
          ? '0, 0, 1'
          : '0, 1, 0';
      const animationVar = `${varName}${name}Animation`;

      this.emit(
        `// animation "${this.escapeStringValue(String(animation.name ?? name), 'Swift')}" -> RealityKit AnimationResource`
      );
      this.emit(`let ${animationVar} = FromToByAnimation<Transform>(`);
      this.indentLevel++;
      this.emit(`name: "${this.escapeStringValue(String(animation.name ?? name), 'Swift')}",`);
      this.emit(
        `from: Transform(rotation: simd_quatf(angle: Float(${from}) * .pi / 180, axis: SIMD3<Float>(${axis}))), // ${property} from: ${from}`
      );
      this.emit(
        `to: Transform(rotation: simd_quatf(angle: Float(${to}) * .pi / 180, axis: SIMD3<Float>(${axis}))), // to: ${to}`
      );
      this.emit(`duration: ${durationSeconds},`);
      this.emit('bindTarget: .transform');
      this.indentLevel--;
      this.emit(')');
      this.emit(
        `if let ${animationVar}Resource = try? AnimationResource.generate(with: ${animationVar}) {`
      );
      this.indentLevel++;
      this.emit(`${varName}.playAnimation(${animationVar}Resource.repeat())`);
      this.indentLevel--;
      this.emit('}');
    }
  }

  private compileObjectEventHandlers(obj: HoloObjectDecl, varName: string): void {
    const eventNames = (obj.properties ?? [])
      .map((property) => property.key)
      .filter((key) => key.startsWith('on_'));
    if (eventNames.length === 0) return;

    this.emit(
      `let ${varName}EventHandlers = [${eventNames.map((name) => `"${name}"`).join(', ')}]`
    );
    this.emit(`_ = ${varName}EventHandlers`);
    this.emit(`${varName}.components.set(InputTargetComponent())`);
    for (const eventName of eventNames) {
      this.emit(`// ${eventName} wired through targeted SwiftUI/RealityView gestures`);
      if (eventName === 'on_gaze_tap') {
        const target = this.findObjProp(obj, 'attach_to');
        if (typeof target === 'string') {
          this.emit(`// close_window("${this.escapeStringValue(target, 'Swift')}")`);
          this.emit(`// dismissWindow(id: "${this.escapeStringValue(target, 'Swift')}")`);
        }
      }
    }
  }

  private compileSharePlaySupport(config: Record<string, HoloValue>): void {
    const activityType = String(config.activity_type ?? 'holoscript_activity');
    const sync = this.asRecord(config.sync);
    const syncKeys = sync ? Object.keys(sync).filter((key) => sync[key] === true) : [];
    const syncKeyList = syncKeys
      .map((key) => `"${this.escapeStringValue(key, 'Swift')}"`)
      .join(', ');

    this.emit('');
    this.emit(`struct ${this.options.structName}GroupActivity: GroupActivity {`);
    this.indentLevel++;
    this.emit('var metadata: GroupActivityMetadata {');
    this.indentLevel++;
    this.emit('var metadata = GroupActivityMetadata()');
    this.emit(`metadata.title = "${this.escapeStringValue(activityType, 'Swift')}"`);
    this.emit('metadata.type = .generic');
    this.emit('return metadata');
    this.indentLevel--;
    this.emit('}');
    this.indentLevel--;
    this.emit('}');
    this.emit(`static let sharePlaySyncKeys = [${syncKeyList}] // sync`);
    this.emit('static func activateSharePlay() {');
    this.indentLevel++;
    this.emit('Task {');
    this.indentLevel++;
    this.emit(`for await session in ${this.options.structName}GroupActivity.sessions() {`);
    this.indentLevel++;
    this.emit('await session.join()');
    this.emit('let messenger = GroupSessionMessenger(session: session)');
    this.emit('_ = messenger');
    this.indentLevel--;
    this.emit('}');
    this.indentLevel--;
    this.emit('}');
    this.indentLevel--;
    this.emit('}');
  }

  private compileEffects(effects: HoloEffects): void {
    this.emit('// === Post-Processing Notes ===');
    this.emit('// visionOS uses system-level rendering; post-processing is limited.');
    for (const effect of effects.effects) {
      this.emit(`// Effect: ${effect.effectType} — ${JSON.stringify(effect.properties)}`);
    }
  }

  /**
   * Compile UI component to SwiftUI attachment
   */
  private compileUIComponent(obj: HoloObjectDecl, parentVar: string): void {
    const varName = this.sanitizeName(obj.name);
    const uiType = (this.findObjProp(obj, 'type') as string) || 'panel';

    this.emit('');
    this.emit(`// UI Component: ${this.escapeStringValue(obj.name as string, 'Swift')}`);

    switch (uiType) {
      case 'ui_panel':
        this.compileUIPanel(obj, varName, parentVar);
        break;
      case 'ui_button':
        this.compileUIButton(obj, varName, parentVar);
        break;
      case 'ui_text':
        this.compileUIText(obj, varName, parentVar);
        break;
      case 'ui_slider':
        this.compileUISlider(obj, varName, parentVar);
        break;
      case 'ui_input':
        this.compileUIInput(obj, varName, parentVar);
        break;
      case 'ui_image':
        this.compileUIImage(obj, varName, parentVar);
        break;
      default:
        this.emit(`// Unknown UI component type: ${uiType}`);
    }
  }

  private compileUIPanel(obj: HoloObjectDecl, varName: string, parentVar: string): void {
    const width = this.findObjProp(obj, 'width') || 400;
    const height = this.findObjProp(obj, 'height') || 300;
    const pos = this.findObjProp(obj, 'position') as number[] | undefined;

    this.emit(
      `// SwiftUI Panel attachment for "${this.escapeStringValue(obj.name as string, 'Swift')}"`
    );
    this.emit(`let ${varName} = Entity()`);
    this.emit(`${varName}.name = "${this.escapeStringValue(obj.name as string, 'Swift')}"`);

    if (pos) {
      this.emit(`${varName}.position = ${this.toSIMD3(pos)}`);
    }

    this.emit(`// Attach SwiftUI view via ViewAttachmentComponent`);
    this.emit(`// ${varName}.components.set(ViewAttachmentComponent {`);
    this.emit(`//     VStack {`);

    // Compile children
    if (obj.children) {
      for (const child of obj.children) {
        this.emit(`//         // Child: ${this.escapeStringValue(child.name as string, 'Swift')}`);
      }
    }

    this.emit(`//     }`);
    this.emit(`//     .frame(width: ${width}, height: ${height})`);
    this.emit(`// })`);
    this.emit(`${parentVar}.addChild(${varName})`);
  }

  private compileUIButton(obj: HoloObjectDecl, varName: string, parentVar: string): void {
    const text = this.findObjProp(obj, 'text') || 'Button';
    const pos = this.findObjProp(obj, 'position') as number[] | undefined;

    this.emit(`let ${varName} = Entity()`);
    this.emit(`${varName}.name = "${this.escapeStringValue(obj.name as string, 'Swift')}"`);

    if (pos) {
      this.emit(`${varName}.position = ${this.toSIMD3(pos)}`);
    }

    this.emit(`// SwiftUI Button: "${text}"`);
    this.emit(`// Implement via ViewAttachmentComponent with Button { Text("${text}") }`);
    this.emit(`${varName}.components.set(InputTargetComponent())`);
    this.emit(
      `${varName}.components.set(CollisionComponent(shapes: [.generateBox(size: SIMD3<Float>(0.2, 0.08, 0.01))]))`
    );
    this.emit(`${parentVar}.addChild(${varName})`);
  }

  private compileUIText(obj: HoloObjectDecl, varName: string, parentVar: string): void {
    const content = this.findObjProp(obj, 'content') || this.findObjProp(obj, 'text') || '';
    const fontSize = this.findObjProp(obj, 'fontSize') || 16;
    const color = this.findObjProp(obj, 'color') || '#ffffff';

    this.emit(`let ${varName}Mesh = MeshResource.generateText("${content}",`);
    this.emit(`    extrusionDepth: 0.001,`);
    this.emit(`    font: .systemFont(ofSize: ${fontSize}),`);
    this.emit(`    containerFrame: .zero,`);
    this.emit(`    alignment: .center,`);
    this.emit(`    lineBreakMode: .byWordWrapping)`);
    this.emit(
      `let ${varName} = ModelEntity(mesh: ${varName}Mesh, materials: [SimpleMaterial(color: ${this.toUIColor(color)}, isMetallic: false)])`
    );
    this.emit(`${varName}.name = "${this.escapeStringValue(obj.name as string, 'Swift')}"`);
    this.emit(`${parentVar}.addChild(${varName})`);
  }

  private compileUISlider(obj: HoloObjectDecl, varName: string, parentVar: string): void {
    const min = this.findObjProp(obj, 'min') ?? 0;
    const max = this.findObjProp(obj, 'max') ?? 100;
    const value = this.findObjProp(obj, 'value') ?? 50;
    const pos = this.findObjProp(obj, 'position') as number[] | undefined;

    this.emit(`let ${varName} = Entity()`);
    this.emit(`${varName}.name = "${this.escapeStringValue(obj.name as string, 'Swift')}"`);

    if (pos) {
      this.emit(`${varName}.position = ${this.toSIMD3(pos)}`);
    }

    this.emit(`// SwiftUI Slider: min=${min}, max=${max}, value=${value}`);
    this.emit(
      `// Implement via ViewAttachmentComponent with Slider(value: $value, in: ${min}...${max})`
    );
    this.emit(`${varName}.components.set(InputTargetComponent())`);
    this.emit(`${parentVar}.addChild(${varName})`);
  }

  private compileUIInput(obj: HoloObjectDecl, varName: string, parentVar: string): void {
    const placeholder = this.findObjProp(obj, 'placeholder') || '';
    const pos = this.findObjProp(obj, 'position') as number[] | undefined;

    this.emit(`let ${varName} = Entity()`);
    this.emit(`${varName}.name = "${this.escapeStringValue(obj.name as string, 'Swift')}"`);

    if (pos) {
      this.emit(`${varName}.position = ${this.toSIMD3(pos)}`);
    }

    this.emit(`// SwiftUI TextField with placeholder: "${placeholder}"`);
    this.emit(
      `// Implement via ViewAttachmentComponent with TextField("${placeholder}", text: $text)`
    );
    this.emit(`${varName}.components.set(InputTargetComponent())`);
    this.emit(`${parentVar}.addChild(${varName})`);
  }

  private compileUIImage(obj: HoloObjectDecl, varName: string, parentVar: string): void {
    const src = this.findObjProp(obj, 'src') || '';
    const width = this.findObjProp(obj, 'width') || 100;
    const height = this.findObjProp(obj, 'height') || 100;
    const pos = this.findObjProp(obj, 'position') as number[] | undefined;

    this.emit(`let ${varName} = Entity()`);
    this.emit(`${varName}.name = "${this.escapeStringValue(obj.name as string, 'Swift')}"`);

    if (pos) {
      this.emit(`${varName}.position = ${this.toSIMD3(pos)}`);
    }

    this.emit(`// Image: ${src} (${width}x${height})`);
    this.emit(
      `let ${varName}Mesh = MeshResource.generatePlane(width: ${(width as number) / 1000}, depth: ${(height as number) / 1000})`
    );
    this.emit(`if let texture = try? await TextureResource(named: "${src}") {`);
    this.indentLevel++;
    this.emit(`var ${varName}Material = UnlitMaterial()`);
    this.emit(`${varName}Material.color = .init(texture: .init(texture))`);
    this.emit(
      `${varName}.components.set(ModelComponent(mesh: ${varName}Mesh, materials: [${varName}Material]))`
    );
    this.indentLevel--;
    this.emit(`}`);
    this.emit(`${parentVar}.addChild(${varName})`);
  }

  /**
   * Check if object is a UI component
   */
  private isUIComponent(obj: HoloObjectDecl): boolean {
    const type = this.findObjProp(obj, 'type') as string | undefined;
    const uiTypes = ['ui_panel', 'ui_button', 'ui_text', 'ui_slider', 'ui_input', 'ui_image'];
    return uiTypes.includes(type || '');
  }

  /**
   * Get all traits used in composition for imports
   */
  private collectAllTraits(composition: HoloComposition): string[] {
    const traits: string[] = [];

    const collectFromObject = (obj: HoloObjectDecl) => {
      if (obj.traits) {
        for (const trait of obj.traits) {
          if (!traits.includes(trait.name)) {
            traits.push(trait.name);
          }
        }
      }
      if (obj.children) {
        obj.children.forEach(collectFromObject);
      }
    };

    composition.objects?.forEach(collectFromObject);
    composition.spatialGroups?.forEach((group) => {
      group.objects.forEach(collectFromObject);
    });

    return traits;
  }

  private collectVolumetricWindows(composition: HoloComposition): VisionOSWindowDescriptor[] {
    const windows: VisionOSWindowDescriptor[] = [];
    const collectFromObject = (obj: HoloObjectDecl) => {
      const descriptor = this.getVolumetricWindowDescriptor(obj);
      if (descriptor) {
        windows.push(descriptor);
      }
      obj.children?.forEach(collectFromObject);
    };

    composition.objects?.forEach(collectFromObject);
    composition.spatialGroups?.forEach((group) => {
      group.objects.forEach(collectFromObject);
    });

    return windows;
  }

  private collectOrnaments(composition: HoloComposition): VisionOSOrnamentDescriptor[] {
    const ornaments: VisionOSOrnamentDescriptor[] = [];
    const collectFromObject = (obj: HoloObjectDecl) => {
      const descriptor = this.getOrnamentDescriptor(obj);
      if (descriptor) {
        ornaments.push(descriptor);
      }
      obj.children?.forEach(collectFromObject);
    };

    composition.objects?.forEach(collectFromObject);
    composition.spatialGroups?.forEach((group) => {
      group.objects.forEach(collectFromObject);
    });

    return ornaments;
  }

  // ─── Helpers ───────────────────────────────────────────────────────────

  private emit(line: string): void {
    this.lines.push(this.options.indent.repeat(this.indentLevel) + line);
  }

  private sanitizeName(name: string): string {
    return name.replace(/[^a-zA-Z0-9_]/g, '_');
  }

  private toSIMD3(arr: HoloValue): string {
    if (Array.isArray(arr) && arr.length >= 3) {
      return `SIMD3<Float>(${arr[0]}, ${arr[1]}, ${arr[2]})`;
    }
    return `SIMD3<Float>(${arr}, ${arr}, ${arr})`;
  }

  private toUIColor(value: HoloValue): string {
    if (typeof value === 'string' && value.startsWith('#')) {
      const hex = value.slice(1);
      const r = parseInt(hex.substring(0, 2), 16) / 255;
      const g = parseInt(hex.substring(2, 4), 16) / 255;
      const b = parseInt(hex.substring(4, 6), 16) / 255;
      return `.init(red: ${r.toFixed(3)}, green: ${g.toFixed(3)}, blue: ${b.toFixed(3)}, alpha: 1.0)`;
    }
    return '.white';
  }

  private toSwiftType(value: HoloValue): string {
    if (typeof value === 'number') return Number.isInteger(value) ? 'Int' : 'Float';
    if (typeof value === 'boolean') return 'Bool';
    if (typeof value === 'string') return 'String';
    if (Array.isArray(value)) return '[Any]';
    return 'Any';
  }

  private toSwiftValue(value: HoloValue): string {
    if (typeof value === 'number') return Number.isInteger(value) ? `${value}` : `${value}`;
    if (typeof value === 'boolean') return value ? 'true' : 'false';
    if (typeof value === 'string') return `"${this.escapeStringValue(value, 'Swift')}"`;
    if (value === null) return 'nil';
    return 'nil';
  }

  private findObjProp(obj: HoloObjectDecl, key: string): HoloValue | undefined {
    return obj.properties?.find((p) => p.key === key)?.value;
  }

  private getVolumetricWindowDescriptor(obj: HoloObjectDecl): VisionOSWindowDescriptor | undefined {
    const windowConfig = this.findObjProp(obj, 'window');
    const hasWindowTrait = obj.traits?.some(
      (trait) => trait.name === 'window' || trait.name === 'volumetric_window'
    );
    if (!hasWindowTrait && !windowConfig) return undefined;

    const config = this.asRecord(windowConfig);
    const type = String(config?.type ?? 'volumetric');
    if (type !== 'volumetric') return undefined;

    const scale = this.toNumberTuple3(this.findObjProp(obj, 'scale'), [0.6, 0.4, 0.12]);
    return {
      objectName: obj.name,
      type,
      scale,
      minSize: this.toNumberTuple2(config?.min_size),
      maxSize: this.toNumberTuple2(config?.max_size),
      cornerRadius: this.toOptionalNumeric(config?.corner_radius),
      glassBackground: Boolean(config?.glass_background ?? false),
      opacity: this.toOptionalNumeric(config?.opacity) ?? 1,
    };
  }

  private getOrnamentDescriptor(obj: HoloObjectDecl): VisionOSOrnamentDescriptor | undefined {
    const hasOrnamentTrait = obj.traits?.some((trait) => trait.name === 'ornament');
    const attachTo = this.findObjProp(obj, 'attach_to');
    if (!hasOrnamentTrait || typeof attachTo !== 'string') return undefined;

    return {
      objectName: obj.name,
      attachTo,
      position: String(this.findObjProp(obj, 'position') ?? 'bottom'),
      offset: this.toNumberTuple3(this.findObjProp(obj, 'offset'), [0, 0, 0]),
      ui: this.asRecord(this.findObjProp(obj, 'ui')) ?? {},
    };
  }

  private getSharePlayConfig(composition: HoloComposition): Record<string, HoloValue> | undefined {
    return this.asRecord(composition.metadata?.shareplay);
  }

  private getModelSource(
    obj: HoloObjectDecl,
    geometry: HoloValue | undefined
  ): HoloValue | undefined {
    const explicit = this.findObjProp(obj, 'model') || this.findObjProp(obj, 'src');
    if (explicit) return explicit;
    if (typeof geometry === 'string' && /\.(usd|usdz|reality)$/i.test(geometry)) {
      return geometry;
    }
    return undefined;
  }

  private getObjectDirectives(
    obj: HoloObjectDecl,
    type: string
  ): Array<{ type?: unknown; name?: unknown; body?: unknown }> {
    if (!Array.isArray(obj.directives)) return [];
    return obj.directives
      .filter((directive): directive is { type?: unknown; name?: unknown; body?: unknown } =>
        Boolean(directive && typeof directive === 'object' && 'type' in directive)
      )
      .filter((directive) => directive.type === type);
  }

  private asRecord(value: unknown): Record<string, HoloValue> | undefined {
    if (!value || typeof value !== 'object' || Array.isArray(value) || '__bind' in value) {
      return undefined;
    }
    return value as Record<string, HoloValue>;
  }

  private toOptionalNumeric(value: HoloValue | undefined): number | undefined {
    return typeof value === 'number' ? value : undefined;
  }

  private toNumberTuple2(value: HoloValue | undefined): [number, number] | undefined {
    if (
      Array.isArray(value) &&
      value.length >= 2 &&
      typeof value[0] === 'number' &&
      typeof value[1] === 'number'
    ) {
      return [value[0], value[1]];
    }
    return undefined;
  }

  private toNumberTuple3(
    value: HoloValue | undefined,
    fallback: [number, number, number]
  ): [number, number, number] {
    if (
      Array.isArray(value) &&
      value.length >= 3 &&
      typeof value[0] === 'number' &&
      typeof value[1] === 'number' &&
      typeof value[2] === 'number'
    ) {
      return [value[0], value[1], value[2]];
    }
    return fallback;
  }

  private toCGSizeValue(size: [number, number] | undefined): string {
    if (!size) return 'nil';
    return `CGSize(width: ${size[0]}, height: ${size[1]})`;
  }

  private toOptionalNumber(value: number | undefined): string {
    return value === undefined ? 'nil' : String(value);
  }

  private toFrameArguments(window: VisionOSWindowDescriptor): string {
    const args: string[] = [];
    if (window.minSize) {
      args.push(`minWidth: ${window.minSize[0]}`, `minHeight: ${window.minSize[1]}`);
    }
    if (window.maxSize) {
      args.push(`maxWidth: ${window.maxSize[0]}`, `maxHeight: ${window.maxSize[1]}`);
    }
    return args.join(', ');
  }

  private toAttachmentAnchor(position: string): string {
    const anchors: Record<string, string> = {
      top: '.scene(.top)',
      bottom: '.scene(.bottom)',
      leading: '.scene(.leading)',
      trailing: '.scene(.trailing)',
      'top-left': '.scene(.topLeading)',
      'top-right': '.scene(.topTrailing)',
      'bottom-left': '.scene(.bottomLeading)',
      'bottom-right': '.scene(.bottomTrailing)',
    };
    return anchors[position] ?? '.scene(.bottom)';
  }

  private toContentAlignment(position: string): string {
    const alignments: Record<string, string> = {
      top: '.top',
      bottom: '.bottom',
      leading: '.leading',
      trailing: '.trailing',
      'top-left': '.topLeading',
      'top-right': '.topTrailing',
      'bottom-left': '.bottomLeading',
      'bottom-right': '.bottomTrailing',
    };
    return alignments[position] ?? '.bottom';
  }
}
