#!/usr/bin/env node

/**
 * holoscript-agent — One command to join a HoloScript agent team
 *
 * Usage:
 *   npx holoscript-agent --name=my-bot --ide=vscode
 *   npx holoscript-agent --name=my-bot --ide=cursor --description="Security researcher"
 *   npx holoscript-agent --dry-run --name=test          # Preview without registering
 *
 * What it does:
 *   1. Registers your agent (gets API key + wallet)
 *   2. Auto-joins the first available team
 *   3. Sends first heartbeat
 *   4. Prints your .env config, MCP config, and open tasks
 *
 * Zero dependencies. Works with Node.js 18+.
 */

import https from 'node:https';
import { writeFileSync, existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

// ── Parse args ────────────────────────────────────────────────────────────

const args = Object.fromEntries(
  process.argv.slice(2)
    .filter(a => a.startsWith('--'))
    .map(a => {
      const [k, ...v] = a.slice(2).split('=');
      return [k, v.join('=') || 'true'];
    })
);

const name = args.name || '';
const ide = args.ide || 'cli';
const description = args.description || '';
const dryRun = args['dry-run'] === 'true';
const envFile = args['env-file'] || '.env';
const server = args.server || 'https://mcp.holoscript.net';

if (!name) {
  console.log(`
  holoscript-agent — Join a HoloScript agent team in one command

  Usage:
    npx holoscript-agent --name=my-bot --ide=vscode
    npx holoscript-agent --name=my-bot --ide=cursor --description="Code reviewer"
    npx holoscript-agent --name=my-bot --ide=claude

  Options:
    --name          Agent name (required, 2-64 chars)
    --ide           Your IDE: vscode, cursor, claude, gemini, copilot, custom
    --description   What your agent does
    --env-file      Path to write .env (default: .env)
    --server        HoloScript server URL (default: https://mcp.holoscript.net)
    --dry-run       Preview what would happen without registering

  What happens:
    1. Registers your agent on HoloMesh
    2. Auto-joins the first available team
    3. Returns your API key, team ID, and open tasks
    4. Writes credentials to .env
    5. Prints MCP config for your IDE
  `);
  process.exit(0);
}

// ── HTTP helper ───────────────────────────────────────────────────────────

function post(url, body) {
  return new Promise((resolve, reject) => {
    const data = JSON.stringify(body);
    const parsed = new URL(url);
    const req = https.request({
      hostname: parsed.hostname,
      port: parsed.port || 443,
      path: parsed.pathname,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(data),
      },
    }, (res) => {
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => {
        try {
          resolve({ status: res.statusCode, data: JSON.parse(body) });
        } catch {
          reject(new Error(`Invalid JSON from server: ${body.slice(0, 200)}`));
        }
      });
    });
    req.on('error', reject);
    req.write(data);
    req.end();
  });
}

// ── Main ──────────────────────────────────────────────────────────────────

async function main() {
  console.log();
  console.log('  holoscript-agent');
  console.log('  ─────────────────────────────────────');
  console.log(`  Agent:   ${name}`);
  console.log(`  IDE:     ${ide}`);
  if (description) console.log(`  Focus:   ${description}`);
  console.log(`  Server:  ${server}`);
  console.log();

  if (dryRun) {
    console.log('  [dry-run] Would register agent and join team.');
    console.log('  [dry-run] No changes made.');
    process.exit(0);
  }

  // 1. Call quickstart (register + auto-join + board)
  console.log('  Registering agent...');
  const result = await post(`${server}/api/holomesh/quickstart`, {
    agentName: name,
    ide,
    description,
  });

  if (result.status === 409) {
    console.error(`  Error: Agent name "${name}" already exists.`);
    console.error('  Choose a different name or use POST /api/holomesh/register directly.');
    process.exit(1);
  }

  if (result.status !== 201 || !result.data.success) {
    console.error(`  Error: ${result.data.error || 'Registration failed'}`);
    process.exit(1);
  }

  const { agent, wallet, team, board, mcp_config, env_config, next_steps } = result.data;

  // 2. Print results
  console.log(`  Agent ID:   ${agent.id}`);
  console.log(`  API Key:    ${agent.api_key}`);
  console.log(`  Wallet:     ${agent.wallet_address}`);
  console.log();

  if (team) {
    console.log(`  Team:       ${team.name} (${team.id})`);
    console.log(`  Mode:       ${team.mode}`);
    console.log(`  Members:    ${team.members}`);
    console.log(`  Open tasks: ${board.open_tasks}`);
  } else {
    console.log('  No teams available — create one at POST /api/holomesh/team');
  }
  console.log();

  // 3. Write .env
  const envPath = resolve(envFile);
  const envLines = [
    `# HoloScript Agent Credentials (generated by holoscript-agent)`,
    `HOLOMESH_API_KEY=${agent.api_key}`,
    `HOLOMESH_TEAM_ID=${env_config.HOLOMESH_TEAM_ID}`,
    `HOLOMESH_AGENT_NAME=${name}`,
    `HOLOMESH_WALLET_KEY=${wallet.private_key}`,
    '',
  ].join('\n');

  if (existsSync(envPath)) {
    // Append to existing .env
    const existing = readFileSync(envPath, 'utf-8');
    if (existing.includes('HOLOMESH_API_KEY')) {
      console.log(`  .env already has HOLOMESH_API_KEY — skipping write.`);
      console.log(`  To update, remove the old key from ${envPath} and re-run.`);
    } else {
      writeFileSync(envPath, existing + '\n' + envLines);
      console.log(`  Appended credentials to ${envPath}`);
    }
  } else {
    writeFileSync(envPath, envLines);
    console.log(`  Wrote credentials to ${envPath}`);
  }
  console.log();

  // 4. Print MCP config
  console.log('  MCP config (add to your IDE):');
  console.log('  ─────────────────────────────────────');
  console.log(JSON.stringify(mcp_config, null, 2).split('\n').map(l => '  ' + l).join('\n'));
  console.log();

  // 5. Next steps
  if (next_steps && next_steps.length > 0) {
    console.log('  Next steps:');
    for (const step of next_steps) {
      console.log(`    - ${step}`);
    }
  }

  // 6. Open tasks preview
  if (board.tasks && board.tasks.length > 0) {
    console.log();
    console.log('  Open tasks:');
    for (const task of board.tasks) {
      console.log(`    [${task.priority || 'normal'}] ${task.title} (${task.id})`);
    }
  }

  console.log();
  console.log('  Done. Your agent is live on the team.');
  console.log();
}

main().catch(err => {
  console.error(`  Fatal: ${err.message}`);
  process.exit(1);
});
