/**
 * CorticalDepthRouter — v1.0
 *
 * Enriches BrainCoord.cortical_depth based on the processing stage of a
 * PillarSlice as it moves through the uAAL pipeline.
 *
 * Biological grounding (Paper 33 §2.2 — Identity 2)
 * ─────────────────────────────────────────────────
 * The neocortex's six-layer laminar structure encodes a processing depth
 * hierarchy that maps directly to slice pipeline stages:
 *
 *   Layer 1   (diffuse neuromodulation)  → global context / monitoring
 *   Layer 2–3 (cortico-cortical)         → association / lateral integration
 *   Layer 4   (thalamo-cortical relay)   → primary input (raw slices)
 *   Layer 5   (cortico-subcortical)      → output projection (GRPO-ready)
 *   Layer 6   (cortico-thalamic)         → gain control / shutdown signals
 *
 * CorticalDepthRouter classifies slices into one of four pipeline stages and
 * writes the corresponding cortical_depth into the slice's BrainCoord.
 *
 * Pipeline stages
 * ───────────────
 *   raw         → depth 4  (thalamo-cortical relay: slice just arrived from Pillar)
 *   association → depth 3  (lateral integration: slice enriched by PillarJEPA)
 *   output      → depth 5  (output projection: GRPO-ready training slice)
 *   monitoring  → depth 1  (global context: integrity / diversity watchdog)
 *   shutdown    → depth 6  (cortico-thalamic: shutdown/init signals)
 *
 * Integration
 * ───────────
 * CorticalDepthRouter is called by SliceEmitter before emitting a TrainingSlice.
 * It writes cortical_depth back into the brain_coord field without touching
 * the original SimulationContract digest (the slice itself is read-only).
 *
 * Design: pure function + TraitHandler wrapper.
 * Pure function: `routeDepth(stage) → CorticalDepth`
 * TraitHandler: consumes `cortical:route { stage, brain_coord }` →
 *               emits    `cortical:routed { brain_coord }` with depth written.
 *
 * References:
 *   Paper 33 §2.2  — cortical layers ≡ processing depth hierarchy
 *   SliceEmitter   — consumer of enriched TrainingSlice.brain_coord
 *   BrainCoordMapper — provides the (x,y,z) coordinate; this router adds depth
 *   RecursiveMAS   — arxiv:2604.25917 (inner/outer loop ≡ depth 4 / depth 5)
 */

import type { TraitHandler, HSPlusNode, TraitContext, TraitEvent } from '../TraitTypes';
import type { BrainCoord } from './SemanticCollaborationContract';

// ─── Stage taxonomy ───────────────────────────────────────────────────────────

/**
 * Slice processing stage in the uAAL pipeline.
 *
 *   raw         — freshly generated by a Pillar; not yet enriched
 *   association — passed through PillarJEPA context encoder; cross-domain
 *   output      — GRPO-ready; paired with reward signal
 *   monitoring  — integrity / diversity watchdog (LatentIntegrityLayer output)
 *   shutdown    — init or shutdown signal domain slice
 */
export type SliceStage = 'raw' | 'association' | 'output' | 'monitoring' | 'shutdown';

/**
 * Cortical layer depth (1–6) assigned by CorticalDepthRouter.
 */
export type CorticalDepth = 1 | 2 | 3 | 4 | 5 | 6;

/**
 * Stage → cortical depth mapping table.
 * Derived from the laminar processing hierarchy (Paper 33 Table 1).
 */
const STAGE_DEPTH_MAP: Record<SliceStage, CorticalDepth> = {
  raw:         4,  // thalamo-cortical relay — primary input
  association: 3,  // cortico-cortical — lateral integration (PillarJEPA)
  output:      5,  // cortico-subcortical — GRPO output projection
  monitoring:  1,  // diffuse neuromodulation — integrity / diversity watch
  shutdown:    6,  // cortico-thalamic — gain control / shutdown
};

// ─── Pure routing function ────────────────────────────────────────────────────

/**
 * Return the cortical depth for a given pipeline stage.
 *
 * @param stage — The slice's current processing stage.
 * @returns CorticalDepth (1–6) corresponding to the stage.
 */
export function routeDepth(stage: SliceStage): CorticalDepth {
  return STAGE_DEPTH_MAP[stage];
}

/**
 * Enrich a BrainCoord with the cortical_depth for the given stage.
 * Returns a new BrainCoord — the input is not mutated.
 * The SimulationContract digest lives on the TrainingSlice, not the BrainCoord,
 * so writing cortical_depth here does not invalidate the receipt.
 *
 * @param coord — Base BrainCoord from BrainCoordMapper (x, y, z populated).
 * @param stage — Processing stage of the slice.
 * @returns A new BrainCoord with cortical_depth set.
 */
export function enrichCoord(coord: BrainCoord, stage: SliceStage): BrainCoord {
  return { ...coord, cortical_depth: routeDepth(stage) };
}

/**
 * Infer the most likely SliceStage from a BrainCoord's existing cortical_depth.
 * Used when re-hydrating slices from storage.
 *
 * If multiple stages share the same depth, returns the first match in priority
 * order: raw > association > output > monitoring > shutdown.
 */
export function inferStage(depth: CorticalDepth): SliceStage {
  for (const [stage, d] of Object.entries(STAGE_DEPTH_MAP) as [SliceStage, CorticalDepth][]) {
    if (d === depth) return stage;
  }
  return 'raw'; // fallback
}

// ─── Config ───────────────────────────────────────────────────────────────────

export interface CorticalDepthRouterConfig {
  /**
   * Emit cortical:routed events.
   * Default: true.
   */
  emit_events: boolean;
}

// ─── TraitHandler ─────────────────────────────────────────────────────────────

/**
 * CorticalDepthRouter as a TraitHandler.
 *
 * Events consumed:
 *   cortical:route  { stage: SliceStage, brain_coord: BrainCoord }
 *
 * Events emitted:
 *   cortical:routed { brain_coord: BrainCoord, stage: SliceStage, depth: CorticalDepth }
 */
export const corticalDepthRouterHandler: TraitHandler = {
  id: 'CorticalDepthRouter',

  defaultConfig(): CorticalDepthRouterConfig {
    return { emit_events: true };
  },

  onEvent(
    _node: HSPlusNode,
    config: CorticalDepthRouterConfig,
    context: TraitContext,
    event: TraitEvent,
  ): void {
    if (event.type !== 'cortical:route') return;

    const payload = event as unknown as {
      stage: SliceStage;
      brain_coord: BrainCoord;
    };

    const { stage, brain_coord } = payload;
    if (!stage || !brain_coord) return;

    const routed = enrichCoord(brain_coord, stage);
    const depth = routed.cortical_depth;

    if (config.emit_events) {
      context.emit?.('cortical:routed', { brain_coord: routed, stage, depth });
    }
  },
};
