/**
 * Shared panel types for HoloScript Studio
 *
 * Extracted to avoid circular dependencies between
 * RightPanelSidebar ↔ useDomainFilter.
 */

export type PanelTab =
  | 'safety'
  | 'marketplace'
  | 'platform'
  | 'traits'
  | 'physics'
  | 'simulation'
  | 'ai'
  | 'dialogue'
  | 'ecs'
  | 'animation'
  | 'behavior'
  | 'audio'
  | 'procgen'
  | 'multiplayer'
  | 'shader'
  | 'combat'
  | 'pathfinding'
  | 'particles'
  | 'camera'
  | 'inventory'
  | 'terrain'
  | 'lighting'
  | 'cinematic'
  | 'collaboration'
  | 'security'
  | 'scripting'
  | 'saveload'
  | 'profiler'
  | 'compiler'
  | 'lod'
  | 'statemachine'
  | 'input'
  | 'network'
  | 'culture'
  | 'timeline'
  | 'scene'
  | 'assets'
  | 'state'
  | 'viewport'
  | 'bus'
  | 'presets'
  | 'agent'
  | 'board'
  // HoloMesh tabs (rendered in RightPanelSidebar's "HoloMesh" category)
  | 'fleet'
  | 'inbox'
  | 'mode'
  | 'identity'
  | 'knowledge'
  | 'absorb'
  | 'bounties'
  | 'character'
  | 'models'
  | 'templates'
  | 'diagnostics'
  | 'pipeline'
  | 'runtimeTier';
