import { defineConfig } from 'tsup';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));

export default defineConfig({
  entry: { 'index': 'src/index.ts' },
  format: ['cjs', 'esm'],
  // dts disabled while platform shares the mid-flight Vec3 migration
  // with engine — same source-level TS errors crash tsup's dts pass.
  // Engine tolerates via build.mjs+tolerateFailure; platform uses bare
  // tsup so we drop dts here until migration completes.
  // Restore once task_1777164512763_x545 (engine Vec3 migration) lands.
  //
  // Emit a permissive ambient stub via onSuccess so package.json's
  // declared `types: './dist/index.d.ts'` resolves for downstream
  // consumers (studio + others). Without this, raw `tsc --noEmit`
  // (deploy pre-flight) reports TS7016 implicit-any imports across
  // every site that touches `@holoscript/platform`. Studio's
  // next.config.js replaces the runtime module with empty-module.js so
  // type-only references don't need precise shapes — `unknown` index
  // signatures are honest about that.
  dts: false,
  onSuccess: async () => {
    const distDir = join(__dirname, 'dist');
    const stub = `// Auto-generated by tsup.config.ts — see comment block above.
// Permissive ambient stub: tsup's dts pass is disabled mid-Vec3-migration.
// Restore real dts once task_1777164512763_x545 lands.
//
// Generic any-typed catch-all named exports — covers every site studio
// + downstream consumers reach into. Studio's next.config.js replaces
// the runtime module with empty-module.js so type precision isn't
// required; this stub just exists to satisfy raw \`tsc --noEmit\`.

// Security
export const createSandbox: any;
export type Sandbox = any;
export type SandboxExecutionResult = any;

// Marketplace — declared as both value and type (consumers use both).
// Permissive index signature satisfies arbitrary method/prop access
// (publish, rate, get, search, etc.) without locking the contract.
declare class MarketplaceRegistryClass {
  [key: string]: any;
}
export const MarketplaceRegistry: typeof MarketplaceRegistryClass;
export type MarketplaceRegistry = MarketplaceRegistryClass;
export type ContentCategory = any;
export const createSubmission: any;
export const verifySubmission: any;
export const publishSubmission: any;

// Composition / AST
export type ASTNode = any;

// Catch-all: any other named import resolves to \`any\`.
declare const __platformCatchAll: any;
export default __platformCatchAll;
`;
    writeFileSync(join(distDir, 'index.d.ts'), stub, 'utf8');
    writeFileSync(join(distDir, 'index.d.cts'), stub, 'utf8');
  },
  splitting: false,
  sourcemap: true,
  clean: true,
  external: [
    '@holoscript/core',
    /^@holoscript\/core\//,
    '@holoscript/mesh',
    /^@holoscript\/mesh\//,
    '@holoscript/platform',
    // Externalize engine + framework so tsup's rollup-dts pass doesn't follow
    // pnpm symlinks into their source. Engine has a mid-flight Vec3 migration
    // whose source-level type errors are tolerated by engine's own build.mjs
    // but would otherwise crash any consumer's whole-program dts walk.
    // See task_1777143308566_wewf and packages/mesh/tsup.config.ts.
    '@holoscript/engine',
    /^@holoscript\/engine\//,
    '@holoscript/framework',
    /^@holoscript\/framework\//,
  ],
});
