'use client';

// @generated by HoloScript MultiTargetFanoutPanelCompiler - DO NOT EDIT
// source: packages/studio/src/lib/studio/multi-target/multi_target_fanout.holo

import {
  Box,
  Bot,
  Braces,
  Cpu,
  Gamepad2,
  GitBranch,
  Headphones,
  Layers3,
  Play,
  ReceiptText,
} from 'lucide-react';

export const MULTI_TARGET_PROMPT =
  'Compile the Neon Orchard Launchpad to browser/WebGPU, Unity, robot simulation, XR headset, service/MCP, and an asset pack with one merged receipt.';

export const MULTI_TARGET_SOURCE = `composition MultiTargetFanoutRun {
  metadata {
    matrixSource: "CG-757"
    refines: "CG-092"
    competitor: "Omma"
    prompt: "${MULTI_TARGET_PROMPT}"
    receipt: "multi-target-fanout.v1"
  }

  source "neon-orchard-launchpad" {
    imports: ["assets/drone.glb", "assets/orchard-telemetry.csv", "assets/quest-beats.json"]
    authority: "user-owned .holo"
  }

  parallel_compile "omma-counterfan" {
    isolation: "per-target-job"
    streamStatus: true
    compareTargetDiffs: true
    mergeReceiptsInto: "receipt-pack://multi-target-fanout.v1"

    target "browser-webgpu-r3f" {
      class: "web"
      tools: ["compile_to_webgpu", "compile_to_r3f"]
      artifact: "artifacts/web/neon-orchard/"
      status: "ready"
      receipt: "receipt://browser-webgpu-r3f"
    }

    target "unity-gameplay" {
      class: "game-engine"
      tools: ["compile_to_unity"]
      artifact: "artifacts/unity/NeonOrchard.unitypackage"
      status: "ready"
      receipt: "receipt://unity-gameplay"
    }

    target "robot-sim" {
      class: "robotics-sim"
      tools: ["compile_to_urdf", "compile_to_sdf"]
      artifact: "artifacts/robot/neon-orchard.urdf"
      status: "ready"
      receipt: "receipt://robot-sim"
    }

    target "xr-headset" {
      class: "xr"
      tools: ["compile_to_openxr", "compile_to_visionos"]
      artifact: "artifacts/xr/neon-orchard-openxr.zip"
      status: "ready"
      receipt: "receipt://xr-headset"
    }

    target "service-mcp" {
      class: "service"
      tools: ["compile_to_node_service", "compile_to_mcp_config"]
      artifact: "artifacts/service/neon-orchard-mcp/"
      status: "ready"
      receipt: "receipt://service-mcp"
    }

    target "asset-pack" {
      class: "assets"
      tools: ["compile_to_gltf", "compile_to_usdz"]
      artifact: "artifacts/assets/neon-orchard-pack.zip"
      status: "ready"
      receipt: "receipt://asset-pack"
    }
  }
}
`;

export const FANOUT_TARGETS = [
  {
    id: 'browser-webgpu-r3f',
    label: 'Browser',
    detail: 'WebGPU + R3F preview',
    status: 'ready',
    icon: Cpu,
  },
  {
    id: 'unity-gameplay',
    label: 'Unity',
    detail: 'gameplay package',
    status: 'ready',
    icon: Gamepad2,
  },
  {
    id: 'robot-sim',
    label: 'Robot/sim',
    detail: 'URDF + SDF',
    status: 'ready',
    icon: Bot,
  },
  {
    id: 'xr-headset',
    label: 'XR',
    detail: 'OpenXR + visionOS',
    status: 'ready',
    icon: Headphones,
  },
  {
    id: 'service-mcp',
    label: 'Service/MCP',
    detail: 'Node service + config',
    status: 'ready',
    icon: Braces,
  },
  {
    id: 'asset-pack',
    label: 'Asset pack',
    detail: 'glTF + USDZ bundle',
    status: 'ready',
    icon: Box,
  },
] as const;

export const FANOUT_RECEIPT_PACK = [
  'browser-webgpu-r3f',
  'unity-gameplay',
  'robot-sim',
  'xr-headset',
  'service-mcp',
  'asset-pack',
] as const;

interface MultiTargetFanoutPanelProps {
  onDispatch: () => void;
}

export function MultiTargetFanoutPanel({ onDispatch }: MultiTargetFanoutPanelProps) {
  return (
    <aside
      data-testid="multi-target-fanout"
      className="absolute right-3 top-3 z-20 w-[min(500px,calc(100%-1.5rem))] overflow-hidden rounded-2xl border border-violet-300/25 bg-[#080612]/90 text-white shadow-2xl shadow-violet-950/35 backdrop-blur-xl"
    >
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_20%_15%,rgba(168,85,247,0.24),transparent_33%),radial-gradient(circle_at_90%_70%,rgba(34,211,238,0.16),transparent_30%)]" />
      <div className="relative space-y-3 p-3">
        <div className="flex flex-wrap items-center gap-2">
          <span className="rounded-full border border-violet-200/30 bg-violet-300/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.22em] text-violet-100">
            Prompt → Multi-target fan-out
          </span>
          <span className="rounded-full border border-cyan-300/25 bg-cyan-300/10 px-2 py-0.5 text-[10px] text-cyan-100">
            6 isolated jobs · 1 receipt pack
          </span>
        </div>

        <div className="grid gap-3 md:grid-cols-[0.92fr_1.08fr]">
          <div className="space-y-2">
            <h2 className="text-lg font-semibold leading-tight text-white">
              Same source, six bodies. Omma gets variants; HoloScript gets artifacts.
            </h2>
            <p className="text-[11px] leading-relaxed text-violet-50/75">
              Dispatch browser, Unity, robot/sim, XR, service/MCP, and asset-pack compiles from one
              HoloScript source. Each target streams status and lands in a merged proof bundle.
            </p>
            <button
              type="button"
              data-testid="multi-target-dispatch"
              onClick={onDispatch}
              className="group inline-flex items-center gap-2 rounded-xl bg-violet-300 px-3 py-2 text-[12px] font-bold text-studio-bg shadow-lg shadow-violet-950/30 transition hover:-translate-y-0.5 hover:bg-white"
            >
              <Play className="h-3.5 w-3.5 transition group-hover:scale-110" />
              Dispatch fan-out
            </button>
          </div>

          <div className="rounded-xl border border-white/10 bg-black/25 p-2">
            <div className="mb-2 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-violet-100">
              <GitBranch className="h-3.5 w-3.5 text-cyan-200" />
              target classes
            </div>
            <div className="grid grid-cols-2 gap-1.5">
              {FANOUT_TARGETS.map(({ id, label, detail, icon: Icon }) => (
                <div key={id} className="rounded-lg border border-white/10 bg-white/[0.045] p-2">
                  <div className="flex items-center gap-1.5 text-[10px] font-semibold text-white">
                    <Icon className="h-3.5 w-3.5 text-violet-200" />
                    {label}
                  </div>
                  <div className="mt-0.5 text-[9px] text-violet-50/60">{detail}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="flex items-center justify-between rounded-xl border border-cyan-200/20 bg-cyan-300/10 px-3 py-2 text-[10px] text-cyan-50">
          <span className="inline-flex items-center gap-1.5 font-semibold">
            <ReceiptText className="h-3.5 w-3.5" />
            receipt-pack://multi-target-fanout.v1
          </span>
          <span className="inline-flex items-center gap-1.5 text-cyan-100/80">
            <Layers3 className="h-3.5 w-3.5" />
            inspect target diffs
          </span>
        </div>
      </div>
    </aside>
  );
}
