'use client';

// @generated by HoloScript PortabilityHeadToHeadPanelCompiler - DO NOT EDIT
// source: packages/studio/src/lib/studio/portability/omma_portability_head_to_head.holo

import { ArrowRight, Box, Code2, Cpu, Gamepad2, Headphones, Network, ReceiptText } from 'lucide-react';

export const PORTABILITY_COMPARISON_LINE =
  'Omma builds a beautiful browser app you can publish; HoloScript builds portable, verifiable source you own and can run across domains';

export const PORTABILITY_PROMPT =
  'Build the Neon Orchard Launchpad once, then show where the same source goes next: browser, Unity, robot/sim, XR, service/MCP, assets, and provenance receipts.';

export const PORTABILITY_SOURCE = `composition OmmaPortabilityHeadToHead {
  metadata {
    matrixSource: "CG-758"
    competitor: "Omma"
    receipt: "omma-portability-head-to-head.v1"
    comparisonLine: "${PORTABILITY_COMPARISON_LINE}"
  }

  prompt "${PORTABILITY_PROMPT}"

  proof "same-prompt-where-it-goes-next" {
    source: "packages/studio/src/lib/studio/time-to-wow/time_to_wow_path.holo"
    fanout: "packages/studio/src/lib/studio/multi-target/multi_target_fanout.holo"
    browserPreview: "studio://create?demo=time-to-wow"
    receiptPack: "receipt-pack://multi-target-fanout.v1"
  }

  artifact "browser-preview" {
    label: "Browser/WebGPU preview"
    href: "artifacts/web/neon-orchard/"
    targetClass: "browser"
  }

  artifact "unity-package" {
    label: "Unity gameplay package"
    href: "artifacts/unity/NeonOrchard.unitypackage"
    targetClass: "unity"
  }

  artifact "robot-sim" {
    label: "Robot/sim URDF + SDF"
    href: "artifacts/robot/neon-orchard.urdf"
    targetClass: "robot-sim"
  }

  artifact "xr-headset" {
    label: "XR/headset OpenXR bundle"
    href: "artifacts/xr/neon-orchard-openxr.zip"
    targetClass: "xr"
  }

  artifact "service-mcp" {
    label: "Service/MCP artifact"
    href: "artifacts/service/neon-orchard-mcp/"
    targetClass: "service"
  }

  artifact "provenance-pack" {
    label: "CAEL/provenance receipt pack"
    href: "receipt-pack://multi-target-fanout.v1"
    targetClass: "receipt"
  }
}
`;

export const PORTABILITY_ARTIFACTS = [
  { id: 'source', label: 'HoloScript source', href: 'time_to_wow_path.holo', icon: Code2 },
  { id: 'browser', label: 'Browser/WebGPU', href: 'artifacts/web/neon-orchard/', icon: Cpu },
  { id: 'unity', label: 'Unity package', href: 'artifacts/unity/NeonOrchard.unitypackage', icon: Gamepad2 },
  { id: 'robot', label: 'Robot/sim', href: 'artifacts/robot/neon-orchard.urdf', icon: Network },
  { id: 'xr', label: 'XR/headset', href: 'artifacts/xr/neon-orchard-openxr.zip', icon: Headphones },
  { id: 'assets', label: 'Asset pack', href: 'artifacts/assets/neon-orchard-pack.zip', icon: Box },
  { id: 'receipt', label: 'CAEL receipt pack', href: 'receipt-pack://multi-target-fanout.v1', icon: ReceiptText },
] as const;

interface PortabilityHeadToHeadPanelProps {
  onOpenDemo: () => void;
}

export function PortabilityHeadToHeadPanel({ onOpenDemo }: PortabilityHeadToHeadPanelProps) {
  return (
    <aside
      data-testid="portability-head-to-head"
      className="absolute bottom-3 left-1/2 z-20 w-[min(760px,calc(100%-1.5rem))] -translate-x-1/2 overflow-hidden rounded-2xl border border-emerald-300/25 bg-[#03100d]/90 text-white shadow-2xl shadow-emerald-950/35 backdrop-blur-xl"
    >
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_15%_50%,rgba(16,185,129,0.22),transparent_32%),radial-gradient(circle_at_85%_10%,rgba(56,189,248,0.16),transparent_28%)]" />
      <div className="relative grid gap-3 p-3 md:grid-cols-[1fr_1.2fr]">
        <div className="space-y-2">
          <span className="rounded-full border border-emerald-200/30 bg-emerald-300/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.22em] text-emerald-100">
            Same prompt · where it goes next
          </span>
          <h2 className="text-lg font-semibold leading-tight">
            One prompt is not the finish line. It is the fork in the road.
          </h2>
          <p className="text-[11px] leading-relaxed text-emerald-50/75">
            {PORTABILITY_COMPARISON_LINE}.
          </p>
          <button
            type="button"
            data-testid="portability-open-demo"
            onClick={onOpenDemo}
            className="inline-flex items-center gap-2 rounded-xl bg-emerald-300 px-3 py-2 text-[12px] font-bold text-studio-bg shadow-lg shadow-emerald-950/30 transition hover:-translate-y-0.5 hover:bg-white"
          >
            Open portability demo
            <ArrowRight className="h-3.5 w-3.5" />
          </button>
        </div>

        <div className="grid grid-cols-2 gap-1.5 md:grid-cols-3">
          {PORTABILITY_ARTIFACTS.map(({ id, label, href, icon: Icon }) => (
            <div key={id} className="rounded-lg border border-white/10 bg-white/[0.045] p-2">
              <div className="flex items-center gap-1.5 text-[10px] font-semibold text-white">
                <Icon className="h-3.5 w-3.5 text-emerald-200" />
                {label}
              </div>
              <div className="mt-0.5 truncate text-[9px] text-emerald-50/60">{href}</div>
            </div>
          ))}
        </div>
      </div>
    </aside>
  );
}
