'use client';

// @generated by HoloScript TimeToWowPathPanelCompiler - DO NOT EDIT
// source: packages/studio/src/lib/studio/time-to-wow/time_to_wow_path.holo

import { Box, Download, FileJson2, FolderGit2, Image, Music2, Play, Sparkles } from 'lucide-react';

export const TIME_TO_WOW_PROMPT =
  'Build a playable neon orchard gallery with a glTF drone, PBR crystal grove, CSV telemetry, JSON quest data, spatial audio, and publish/export controls.';

export const TIME_TO_WOW_SOURCE = `scene "Neon Orchard Launchpad" {
  metadata {
    prompt: "${TIME_TO_WOW_PROMPT}"
    source: "studio://prompt-to-running-project"
    receipt: "time-to-wow.v1"
  }

  import model "assets/drone.glb" as surveyDrone
  import data "assets/orchard-telemetry.csv" as telemetry
  import data "assets/quest-beats.json" as questBeats
  import audio "assets/ambient_space.mp3" as ambientScore

  camera "director" {
    position: [6, 4, 8]
    lookAt: [0, 1, 0]
    fov: 48
  }

  light "sunset-key" {
    type: "directional"
    intensity: 3.2
    color: "#ffb86b"
    position: [3, 8, 4]
  }

  object "pbr-crystal-grove" {
    mesh: "icosahedron"
    material: {
      type: "advanced_pbr"
      baseColor: "#7cf7ff"
      metallic: 0.2
      roughness: 0.18
      emissive: "#2457ff"
      emissiveIntensity: 0.65
    }
    transform: { position: [0, 1.2, 0], scale: [1.8, 1.8, 1.8] }
    traits: ["@grabbable", "@physics", "@audio_reactive"]
  }

  object "survey-drone-preview" {
    model: surveyDrone
    transform: { position: [-2.5, 2.1, -1], scale: [0.9, 0.9, 0.9] }
    traits: ["@orbit_path", "@inspectable"]
  }

  object "telemetry-ribbon" {
    data: telemetry
    visualization: "csv_line_ribbon"
    transform: { position: [0, 0.25, -2.8], scale: [4, 1, 1] }
  }

  quest "first-pixel-tour" {
    beats: questBeats
    startsWith: "walk_to_crystal"
  }

  audio "ambient-score" {
    src: ambientScore
    spatial: true
    loop: true
    volume: 0.42
  }

  publish {
    formats: ["web", "gltf", "glb", "zip"]
    controls: ["preview", "share", "export"]
  }
}
`;

export const TIME_TO_WOW_ASSETS = [
  { kind: 'GLB', label: 'survey drone', icon: Box },
  { kind: 'JSON', label: 'quest beats', icon: FileJson2 },
  { kind: 'CSV', label: 'telemetry ribbon', icon: FolderGit2 },
  { kind: 'PBR', label: 'crystal material', icon: Image },
  { kind: 'AUDIO', label: 'spatial score', icon: Music2 },
] as const;

interface TimeToWowPathPanelProps {
  onStart: () => void;
}

export function TimeToWowPathPanel({ onStart }: TimeToWowPathPanelProps) {
  return (
    <aside
      data-testid="time-to-wow-path"
      className="absolute left-3 top-3 z-20 w-[min(520px,calc(100%-1.5rem))] overflow-hidden rounded-2xl border border-cyan-300/25 bg-[#050713]/88 text-white shadow-2xl shadow-cyan-950/30 backdrop-blur-xl"
    >
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_15%_20%,rgba(34,211,238,0.24),transparent_34%),radial-gradient(circle_at_90%_10%,rgba(251,146,60,0.18),transparent_30%)]" />
      <div className="relative grid gap-3 p-3 md:grid-cols-[1.1fr_0.9fr]">
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <span className="rounded-full border border-cyan-200/30 bg-cyan-300/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.22em] text-cyan-100">
              Prompt → Running Project
            </span>
            <span className="rounded-full border border-emerald-300/25 bg-emerald-300/10 px-2 py-0.5 text-[10px] text-emerald-100">
              live preview + source
            </span>
          </div>
          <h2 className="max-w-md text-lg font-semibold leading-tight text-white">
            First pixel in one click, with the receipts still visible.
          </h2>
          <p className="text-[11px] leading-relaxed text-cyan-50/75">
            Seed a multi-file Studio project: HoloScript source, running viewport, asset ingest,
            inline PBR/audio/data generation affordances, and publish/export controls on screen.
          </p>
          <button
            type="button"
            data-testid="time-to-wow-start"
            onClick={onStart}
            className="group inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-3 py-2 text-[12px] font-bold text-studio-bg shadow-lg shadow-cyan-950/30 transition hover:-translate-y-0.5 hover:bg-white"
          >
            <Play className="h-3.5 w-3.5 transition group-hover:scale-110" />
            Build running project
          </button>
        </div>

        <div className="rounded-xl border border-white/10 bg-black/25 p-2">
          <div className="mb-2 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-cyan-100">
            <Sparkles className="h-3.5 w-3.5 text-orange-200" />
            created on start
          </div>
          <div className="grid grid-cols-2 gap-1.5">
            {TIME_TO_WOW_ASSETS.map(({ kind, label, icon: Icon }) => (
              <div key={kind} className="rounded-lg border border-white/10 bg-white/[0.045] p-2">
                <div className="flex items-center gap-1.5 text-[10px] font-semibold text-white">
                  <Icon className="h-3.5 w-3.5 text-cyan-200" />
                  {kind}
                </div>
                <div className="mt-0.5 text-[9px] text-cyan-50/60">{label}</div>
              </div>
            ))}
            <div className="rounded-lg border border-orange-200/25 bg-orange-300/10 p-2">
              <div className="flex items-center gap-1.5 text-[10px] font-semibold text-orange-50">
                <Download className="h-3.5 w-3.5" />
                EXPORT
              </div>
              <div className="mt-0.5 text-[9px] text-orange-50/70">web · glTF · GLB · zip</div>
            </div>
          </div>
        </div>
      </div>
    </aside>
  );
}
