// @vitest-environment jsdom
/**
 * The page a refused sign-in lands on (lib/inviteAllowlist.ts INVITE_ONLY_PATH).
 *
 * It is generated from holo-pages/invite-only/page.holo by the NextJSCompiler
 * (x4dx, 2026-10-08). It arrived hand-written in #516, which turned the
 * render-surface gate red on main. These checks pin what a refused visitor
 * sees, so the move to a generated page cannot quietly change it:
 *   - the one sentence saying Studio is invite-only,
 *   - one way out, back to the home page,
 *   - nothing that needs a session,
 *   - the tab title, and noindex so the refusal stays out of search results.
 */
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import { describe, expect, it } from 'vitest';

import { INVITE_ONLY_PATH } from '@/lib/inviteAllowlist';
import InviteOnlyPage, { metadata } from '../page';

const pageDir = dirname(dirname(fileURLToPath(import.meta.url)));
const studioRoot = join(pageDir, '..', '..', '..');

describe('invite-only page (what a refused visitor sees)', () => {
  it('says Studio is invite-only and offers exactly one way back home', () => {
    render(<InviteOnlyPage />);

    const message = screen.getByText('Studio is invite-only right now.');
    expect(message.tagName).toBe('P');
    expect(message).toHaveClass('text-center', 'text-lg', 'text-studio-text');

    const links = screen.getAllByRole('link');
    expect(links).toHaveLength(1);
    expect(links[0]).toHaveTextContent('Back to home');
    expect(links[0]).toHaveAttribute('href', '/');
    expect(links[0]).toHaveClass('text-sm', 'text-studio-muted', 'hover:underline');
  });

  it('centres the message in a full-height main region', () => {
    render(<InviteOnlyPage />);

    const main = screen.getByRole('main');
    expect(main).toHaveClass('flex', 'min-h-screen', 'items-center', 'justify-center', 'p-8');
    expect(main).toContainElement(screen.getByText('Studio is invite-only right now.'));
  });

  it('ships its title and keeps the refusal out of search results', () => {
    expect(metadata).toEqual({
      title: 'Invite-only | HoloScript Studio',
      robots: { index: false },
    });
  });

  it('is the generated page at the path the proxy sends refused visitors to', () => {
    const page = join(pageDir, 'page.tsx');
    const source = join(studioRoot, 'holo-pages', INVITE_ONLY_PATH.slice(1), 'page.holo');
    expect(INVITE_ONLY_PATH).toBe('/invite-only');
    expect(existsSync(source)).toBe(true);

    const code = readFileSync(page, 'utf8');
    expect(code.split('\n', 1)[0]).toMatch(/^\/\/ @generated by HoloScript NextJSCompiler/);
    // A server page: Next.js drops metadata from client components, and a
    // session hook here would make the refusal page depend on a session.
    expect(code).not.toMatch(/['"]use client['"]/);
    expect(code).not.toMatch(/next-auth|useSession|getServerSession/);
  });
});
