/**
 * AIGlassesCompiler -- Full Test Suite
 *
 * Covers:
 *   - Compile result structure (all 5 output files)
 *   - Glimmer layout generation (Card, Text, Button, ListItem, TitleChip)
 *   - Touchpad gesture input mapping from controller traits
 *   - Voice command handler generation from event blocks
 *   - AI Glasses form factor constraints (no depth, limited FOV, ambient display)
 *   - Manifest with xr_projected display category
 *   - Gradle with Glimmer + Projected dependencies
 *   - AIGlassesTraitMap coverage tracking
 *   - RBAC validation
 *   - Trait code generation
 *   - Unsupported traits produce correct comments
 */
import { describe, it, expect, beforeEach, vi } from 'vitest';
import { AIGlassesCompiler } from '../AIGlassesCompiler';
import type { AIGlassesCompileResult, AIGlassesCompilerOptions } from '../AIGlassesCompiler';
import type { HoloComposition, HoloObjectDecl } from '../../parser/HoloCompositionTypes';

// Mock RBAC for tests (W.013 pattern)
vi.mock('../identity/AgentRBAC', async (importOriginal) => {
  const actual = await importOriginal();
  return {
    ...actual,
    getRBAC: () => ({ checkAccess: () => ({ allowed: true }) }),
  };
});

// ─── Test Helpers ────────────────────────────────────────────────────────────

function makeComp(overrides: Partial<HoloComposition> = {}): HoloComposition {
  return {
    name: 'TestScene',
    objects: [],
    lights: [],
    timelines: [],
    transitions: [],
    ...overrides,
  } as HoloComposition;
}

function makeObj(
  name: string,
  props: Array<{ key: string; value: unknown }> = [],
  traits: any[] = []
): HoloObjectDecl {
  return {
    name,
    properties: props.map(({ key, value }) => ({ key, value })),
    traits,
    children: [],
  } as any;
}

// ═══════════════════════════════════════════════════════════════════════════════
// TESTS
// ═══════════════════════════════════════════════════════════════════════════════

describe('AIGlassesCompiler', () => {
  let compiler: AIGlassesCompiler;

  beforeEach(() => {
    compiler = new AIGlassesCompiler({
      packageName: 'com.test.glasses',
      activityName: 'TestGlassesActivity',
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // COMPILE RESULT STRUCTURE
  // ═══════════════════════════════════════════════════════════════════════════

  describe('Compile Result Structure', () => {
    it('returns all five output files', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result).toHaveProperty('activityFile');
      expect(result).toHaveProperty('glimmerLayoutFile');
      expect(result).toHaveProperty('voiceHandlersFile');
      expect(result).toHaveProperty('manifestFile');
      expect(result).toHaveProperty('buildGradle');
    });

    it('all output files are non-empty strings', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      for (const key of Object.keys(result)) {
        expect(typeof result[key]).toBe('string');
        expect(result[key].length).toBeGreaterThan(0);
      }
    });

    it('uses custom package name in all files', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.activityFile).toContain('package com.test.glasses');
      expect(result.glimmerLayoutFile).toContain('package com.test.glasses');
      expect(result.voiceHandlersFile).toContain('package com.test.glasses');
      expect(result.manifestFile).toContain('com.test.glasses');
      expect(result.buildGradle).toContain('com.test.glasses');
    });

    it('uses custom activity name', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.activityFile).toContain('class TestGlassesActivity');
    });

    it('uses default options when none provided', () => {
      const defaultCompiler = new AIGlassesCompiler();
      const result = defaultCompiler.compile(makeComp(), 'test-token');
      expect(result.activityFile).toContain('package com.holoscript.glasses');
      expect(result.activityFile).toContain('class GlassesActivity');
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // ACTIVITY FILE
  // ═══════════════════════════════════════════════════════════════════════════

  describe('Activity File', () => {
    it('contains auto-generated header', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.activityFile).toContain('Auto-generated by HoloScript AIGlassesCompiler');
    });

    it('extends ComponentActivity', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.activityFile).toContain('ComponentActivity()');
    });

    it('uses @OptIn(ExperimentalProjectedApi::class)', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.activityFile).toContain('@OptIn(ExperimentalProjectedApi::class)');
    });

    it('imports GlimmerTheme and Glimmer components', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.activityFile).toContain('import androidx.xr.glimmer.GlimmerTheme');
      expect(result.activityFile).toContain('import androidx.xr.glimmer.Card');
      expect(result.activityFile).toContain('import androidx.xr.glimmer.Button');
      expect(result.activityFile).toContain('import androidx.xr.glimmer.Text');
      expect(result.activityFile).toContain('import androidx.xr.glimmer.ListItem');
      expect(result.activityFile).toContain('import androidx.xr.glimmer.TitleChip');
    });

    it('imports Jetpack Projected API', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.activityFile).toContain('import androidx.xr.projected.ProjectedContext');
      expect(result.activityFile).toContain(
        'import androidx.xr.projected.ProjectedDeviceController'
      );
      expect(result.activityFile).toContain(
        'import androidx.xr.projected.ProjectedDisplayController'
      );
    });

    it('initializes ProjectedDeviceController in lifecycleScope', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.activityFile).toContain('ProjectedDeviceController.create');
      expect(result.activityFile).toContain('CAPABILITY_VISUAL_UI');
    });

    it('initializes ProjectedDisplayController', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.activityFile).toContain('ProjectedDisplayController.create');
    });

    it('wraps content in GlimmerTheme', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.activityFile).toContain('GlimmerTheme {');
    });

    it('cleans up displayController on destroy', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.activityFile).toContain('displayController?.close()');
      expect(result.activityFile).toContain('displayController = null');
    });

    it('includes audio setup when composition has audio', () => {
      const comp = makeComp({
        audio: [{ type: 'Audio', name: 'bg', properties: [] } as any],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.activityFile).toContain('SoundPool');
      expect(result.activityFile).toContain('AudioAttributes');
    });

    it('omits audio imports when no audio', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.activityFile).not.toContain('import android.media.SoundPool');
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // GLIMMER LAYOUT FILE
  // ═══════════════════════════════════════════════════════════════════════════

  describe('Glimmer Layout File', () => {
    it('generates @Composable screen function', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.glimmerLayoutFile).toContain('@Composable');
      expect(result.glimmerLayoutFile).toContain('TestSceneGlassesScreen(');
    });

    it('includes visual UI capability check', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.glimmerLayoutFile).toContain('isVisualUiSupported && areVisualsOn');
    });

    it('includes audio-only fallback', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.glimmerLayoutFile).toContain('Audio Guidance Mode Active');
    });

    it('generates TitleChip for composition name', () => {
      const result = compiler.compile(makeComp({ name: 'MyGlassesApp' }), 'test-token');
      expect(result.glimmerLayoutFile).toContain('TitleChip(title = "MyGlassesApp")');
    });

    it('converts 3D model objects to Glimmer Card', () => {
      const comp = makeComp({
        objects: [
          makeObj('Robot', [
            { key: 'model', value: 'robot.glb' },
            { key: 'position', value: [1, 2, 3] },
          ]),
        ],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('Card(');
      expect(result.glimmerLayoutFile).toContain('Text("Robot")');
      expect(result.glimmerLayoutFile).toContain('Text("3D Model: robot.glb")');
      expect(result.glimmerLayoutFile).toContain('Text("Position: 1, 2, 3")');
    });

    it('converts text objects to Text composable', () => {
      const comp = makeComp({
        objects: [makeObj('Label', [{ key: 'text', value: 'Hello World' }])],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('Text("Hello World")');
    });

    it('converts primitive objects to ListItem', () => {
      const comp = makeComp({
        objects: [makeObj('Cube', [{ key: 'mesh', value: 'cube' }])],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('ListItem(');
      expect(result.glimmerLayoutFile).toContain('Text("Cube")');
      expect(result.glimmerLayoutFile).toContain('Text("Type: cube")');
    });

    it('includes Close button', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.glimmerLayoutFile).toContain('Button(onClick = onClose)');
      expect(result.glimmerLayoutFile).toContain('Text("Close")');
    });

    it('uses surface(focusable = false) on outer Box', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.glimmerLayoutFile).toContain('.surface(focusable = false)');
    });

    it('generates state variables from composition state', () => {
      const comp = makeComp({
        state: {
          type: 'State',
          properties: [
            { key: 'score', value: 0 },
            { key: 'name', value: 'Player' },
          ],
        } as any,
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('var score by remember { mutableStateOf(0) }');
      expect(result.glimmerLayoutFile).toContain(
        'var name by remember { mutableStateOf("Player") }'
      );
    });

    it('generates individual object composables', () => {
      const comp = makeComp({
        objects: [makeObj('InfoPanel')],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('fun InfoPanelCard(');
    });

    it('generates UI button elements', () => {
      const comp = makeComp({
        ui: {
          type: 'UI',
          elements: [
            {
              name: 'StartBtn',
              properties: [
                { key: 'type', value: 'button' },
                { key: 'label', value: 'Start' },
              ],
            },
          ],
        } as any,
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain(
        'Button(onClick = { /* StartBtn */ }) { Text("Start") }'
      );
    });

    it('handles color values on text objects', () => {
      const comp = makeComp({
        objects: [
          makeObj('Title', [
            { key: 'text', value: 'Score' },
            { key: 'color', value: '#FF5500' },
          ]),
        ],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('Color(0xFFFF5500)');
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // TOUCHPAD GESTURE INPUT MAPPING
  // ═══════════════════════════════════════════════════════════════════════════

  describe('Touchpad Gesture Input Mapping', () => {
    it('maps clickable trait to touchpad tap', () => {
      const comp = makeComp({
        objects: [makeObj('MenuItem', [], [{ name: 'clickable', config: {} }])],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('touchpad tap handler');
      expect(result.glimmerLayoutFile).toContain('surface(focusable = true)');
    });

    it('maps hoverable trait to touchpad focus', () => {
      const comp = makeComp({
        objects: [makeObj('Card', [], [{ name: 'hoverable', config: {} }])],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('touchpad focus replaces hover');
    });

    it('maps draggable trait to touchpad swipe', () => {
      const comp = makeComp({
        objects: [makeObj('List', [], [{ name: 'draggable', config: { direction: 'vertical' } }])],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('touchpad swipe gesture');
      expect(result.glimmerLayoutFile).toContain('vertical');
    });

    it('marks grabbable as unsupported', () => {
      const comp = makeComp({
        objects: [makeObj('Cube', [], [{ name: 'grabbable', config: {} }])],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('UNSUPPORTED on AI Glasses');
      expect(result.glimmerLayoutFile).toContain('no hand/controller tracking');
    });

    it('maps glasses_touchpad trait correctly', () => {
      const comp = makeComp({
        objects: [makeObj('NavItem', [], [{ name: 'glasses_touchpad', config: {} }])],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('touchpad input on glasses temple arm');
      expect(result.glimmerLayoutFile).toContain('tap, swipe');
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // VOICE COMMAND HANDLERS
  // ═══════════════════════════════════════════════════════════════════════════

  describe('Voice Command Handlers', () => {
    it('generates voice handlers file', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.voiceHandlersFile).toContain('object VoiceCommands');
    });

    it('extracts commands from glasses_voice trait', () => {
      const comp = makeComp({
        objects: [
          makeObj(
            'VoiceControl',
            [],
            [{ name: 'glasses_voice', config: { commands: ['start', 'stop', 'next'] } }]
          ),
        ],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.voiceHandlersFile).toContain('"start"');
      expect(result.voiceHandlersFile).toContain('"stop"');
      expect(result.voiceHandlersFile).toContain('"next"');
      expect(result.voiceHandlersFile).toContain('handleCommand');
    });

    it('generates SpeechRecognizer setup in activity when voice traits present', () => {
      const comp = makeComp({
        objects: [
          makeObj('VoiceCtrl', [], [{ name: 'glasses_voice', config: { commands: ['play'] } }]),
        ],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.activityFile).toContain('SpeechRecognizer');
      expect(result.activityFile).toContain('setupVoiceCommands');
      expect(result.activityFile).toContain('RecognitionListener');
    });

    it('generates empty handlers when no event blocks', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.voiceHandlersFile).toContain('emptyList<String>()');
      expect(result.voiceHandlersFile).toContain('handleCommand(command: String): Boolean = false');
    });

    it('cleans up SpeechRecognizer on destroy', () => {
      const comp = makeComp({
        logic: { type: 'Logic', rules: [{ action: 'test' }] } as any,
      });
      const voiceCompiler = new AIGlassesCompiler({
        packageName: 'com.test.glasses',
        activityName: 'TestGlassesActivity',
        enableVoiceCommands: true,
      });
      const result = voiceCompiler.compile(comp, 'test-token');
      expect(result.activityFile).toContain('speechRecognizer?.destroy()');
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // FORM FACTOR CONSTRAINTS
  // ═══════════════════════════════════════════════════════════════════════════

  describe('AI Glasses Form Factor Constraints', () => {
    it('marks physics traits as unsupported', () => {
      const comp = makeComp({
        objects: [makeObj('Ball', [], [{ name: 'physics', config: {} }])],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('UNSUPPORTED on AI Glasses');
      expect(result.glimmerLayoutFile).toContain('no physics simulation');
    });

    it('marks 3D visual traits as unsupported', () => {
      const traits = ['billboard', 'lod', 'particle_emitter', 'shadow_caster', 'shadow_receiver'];
      for (const traitName of traits) {
        const comp = makeComp({
          objects: [makeObj('Obj', [], [{ name: traitName, config: {} }])],
        });
        const result = compiler.compile(comp, 'test-token');
        expect(result.glimmerLayoutFile).toContain('UNSUPPORTED on AI Glasses');
      }
    });

    it('marks hand_tracking as unsupported', () => {
      const comp = makeComp({
        objects: [makeObj('Hand', [], [{ name: 'hand_tracking', config: {} }])],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('UNSUPPORTED on AI Glasses');
      expect(result.glimmerLayoutFile).toContain('no hand tracking sensors');
    });

    it('marks eye_tracking as unsupported', () => {
      const comp = makeComp({
        objects: [makeObj('Gaze', [], [{ name: 'eye_tracking', config: {} }])],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('UNSUPPORTED on AI Glasses');
      expect(result.glimmerLayoutFile).toContain('no eye tracking sensors');
    });

    it('marks immersive mode as unsupported', () => {
      const comp = makeComp({
        objects: [makeObj('Env', [], [{ name: 'immersive', config: {} }])],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('UNSUPPORTED on AI Glasses');
      expect(result.glimmerLayoutFile).toContain('no immersive mode');
    });

    it('marks spatial_audio as unsupported', () => {
      const comp = makeComp({
        objects: [makeObj('Sound', [], [{ name: 'spatial_audio', config: {} }])],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('UNSUPPORTED on AI Glasses');
      expect(result.glimmerLayoutFile).toContain('no spatial audio hardware');
    });

    it('marks anchor as unsupported (screen-fixed display)', () => {
      const comp = makeComp({
        objects: [makeObj('Pin', [], [{ name: 'anchor', config: {} }])],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('UNSUPPORTED on AI Glasses');
      expect(result.glimmerLayoutFile).toContain('no world anchoring');
    });

    it('supports accessible trait', () => {
      const comp = makeComp({
        objects: [
          makeObj('NavItem', [], [{ name: 'accessible', config: { label: 'Navigation Button' } }]),
        ],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('contentDescription = "Navigation Button"');
    });

    it('supports animated trait with 2-second transitions', () => {
      const comp = makeComp({
        objects: [makeObj('Panel', [], [{ name: 'animated', config: {} }])],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('2000');
      expect(result.glimmerLayoutFile).toContain('glasses-optimized');
    });

    it('supports high_contrast for transparent display', () => {
      const comp = makeComp({
        objects: [makeObj('UI', [], [{ name: 'high_contrast', config: {} }])],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('CRITICAL for AI Glasses');
      expect(result.glimmerLayoutFile).toContain('additive display');
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // MANIFEST FILE
  // ═══════════════════════════════════════════════════════════════════════════

  describe('Manifest File', () => {
    it('contains xr_projected display category', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.manifestFile).toContain('android:requiredDisplayCategory="xr_projected"');
    });

    it('includes package name', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.manifestFile).toContain('package="com.test.glasses"');
    });

    it('includes activity name', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.manifestFile).toContain('.TestGlassesActivity');
    });

    it('includes Bluetooth permission', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.manifestFile).toContain('android.permission.BLUETOOTH_CONNECT');
    });

    it('includes RECORD_AUDIO when voice commands enabled', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.manifestFile).toContain('android.permission.RECORD_AUDIO');
    });

    it('includes CAMERA when camera enabled', () => {
      const cameraCompiler = new AIGlassesCompiler({
        enableCamera: true,
      });
      const result = cameraCompiler.compile(makeComp(), 'test-token');
      expect(result.manifestFile).toContain('android.permission.CAMERA');
    });

    it('omits CAMERA when camera disabled', () => {
      const noCameraCompiler = new AIGlassesCompiler({
        enableCamera: false,
        enableVoiceCommands: false,
      });
      const result = noCameraCompiler.compile(makeComp(), 'test-token');
      expect(result.manifestFile).not.toContain('android.permission.CAMERA');
    });

    it('includes ARCore metadata as optional', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.manifestFile).toContain('com.google.ar.core');
      expect(result.manifestFile).toContain('android:value="optional"');
    });

    it('uses composition name as app label', () => {
      const result = compiler.compile(makeComp({ name: 'MyGlassesApp' }), 'test-token');
      expect(result.manifestFile).toContain('android:label="MyGlassesApp"');
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // BUILD GRADLE
  // ═══════════════════════════════════════════════════════════════════════════

  describe('Build Gradle', () => {
    it('includes Glimmer dependency', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.buildGradle).toContain('androidx.xr.glimmer:glimmer');
    });

    it('includes Projected dependency', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.buildGradle).toContain('androidx.xr.projected:projected');
    });

    it('includes XR Runtime dependency', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.buildGradle).toContain('androidx.xr.runtime:runtime');
    });

    it('includes ARCore dependency', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.buildGradle).toContain('androidx.xr.arcore:arcore');
    });

    it('includes CameraX when camera enabled', () => {
      const cameraCompiler = new AIGlassesCompiler({ enableCamera: true });
      const result = cameraCompiler.compile(makeComp(), 'test-token');
      expect(result.buildGradle).toContain('androidx.camera:camera-core');
      expect(result.buildGradle).toContain('androidx.camera:camera-lifecycle');
    });

    it('omits CameraX when camera disabled', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.buildGradle).not.toContain('camera-core');
    });

    it('targets Java 17', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.buildGradle).toContain('JavaVersion.VERSION_17');
      expect(result.buildGradle).toContain('jvmTarget = "17"');
    });

    it('enables compose build feature', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.buildGradle).toContain('compose = true');
    });

    it('uses configured minSdk and targetSdk', () => {
      const customCompiler = new AIGlassesCompiler({ minSdk: 33, targetSdk: 36 });
      const result = customCompiler.compile(makeComp(), 'test-token');
      expect(result.buildGradle).toContain('minSdk = 33');
      expect(result.buildGradle).toContain('targetSdk = 36');
    });

    it('includes Kotlin Compose plugin', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.buildGradle).toContain('org.jetbrains.kotlin.plugin.compose');
    });

    it('does NOT include SceneCore or Filament (headset-only deps)', () => {
      const result = compiler.compile(makeComp(), 'test-token');
      expect(result.buildGradle).not.toContain('scenecore');
      expect(result.buildGradle).not.toContain('filament');
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // TRAIT CODE GENERATION
  // ═══════════════════════════════════════════════════════════════════════════

  describe('Trait Code Generation', () => {
    it('generates glimmer_card trait code', () => {
      const comp = makeComp({
        objects: [
          makeObj(
            'Info',
            [],
            [{ name: 'glimmer_card', config: { title: 'Weather', action_label: 'Details' } }]
          ),
        ],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('Card(');
      expect(result.glimmerLayoutFile).toContain('Text("Weather")');
      expect(result.glimmerLayoutFile).toContain('Text("Details")');
    });

    it('generates glasses_display trait code', () => {
      const comp = makeComp({
        objects: [
          makeObj('Display', [], [{ name: 'glasses_display', config: { brightness: 0.8 } }]),
        ],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('ProjectedDeviceController.create');
      expect(result.glimmerLayoutFile).toContain('CAPABILITY_VISUAL_UI');
    });

    it('generates projected_camera trait code', () => {
      const comp = makeComp({
        objects: [
          makeObj('Camera', [], [{ name: 'projected_camera', config: { resolution: '1080p' } }]),
        ],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('ProjectedContext.createProjectedDeviceContext');
      expect(result.glimmerLayoutFile).toContain('ProcessCameraProvider');
    });

    it('generates audio trait code', () => {
      const comp = makeComp({
        objects: [
          makeObj(
            'Alert',
            [],
            [{ name: 'audio', config: { src: 'notification.mp3', volume: 0.5 } }]
          ),
        ],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('SoundPool');
      expect(result.glimmerLayoutFile).toContain('notification.mp3');
      expect(result.glimmerLayoutFile).toContain('0.5f');
    });

    it('handles unknown traits gracefully', () => {
      const comp = makeComp({
        objects: [makeObj('Obj', [], [{ name: 'nonexistent_trait', config: {} }])],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('no AI Glasses mapping defined');
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // CHILDREN & RECURSION
  // ═══════════════════════════════════════════════════════════════════════════

  describe('Children and Recursive Processing', () => {
    it('processes nested children', () => {
      const comp = makeComp({
        objects: [
          {
            name: 'Parent',
            properties: [{ key: 'mesh', value: 'box' }],
            traits: [],
            children: [
              makeObj('Child1', [{ key: 'text', value: 'hello' }]),
              makeObj('Child2', [{ key: 'mesh', value: 'sphere' }]),
            ],
          } as any,
        ],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.glimmerLayoutFile).toContain('Parent');
      expect(result.glimmerLayoutFile).toContain('hello');
      expect(result.glimmerLayoutFile).toContain('Child2');
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // RBAC VALIDATION
  // ═══════════════════════════════════════════════════════════════════════════

  describe('RBAC Validation', () => {
    it('accepts valid token', () => {
      expect(() => compiler.compile(makeComp(), 'test-token')).not.toThrow();
    });

    it('accepts empty token (backwards compatibility)', () => {
      expect(() => compiler.compile(makeComp(), '')).not.toThrow();
    });

    it('compiles without token (backwards compatibility)', () => {
      expect(() => (compiler as any).compile(makeComp())).not.toThrow();
    });
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// AI GLASSES TRAIT MAP TESTS
// ═══════════════════════════════════════════════════════════════════════════════

describe('AIGlassesTraitMap', () => {
  // Import directly for unit tests
  let traitMap: typeof import('../AIGlassesTraitMap');

  beforeEach(async () => {
    traitMap = await import('../AIGlassesTraitMap');
  });

  describe('Coverage Report', () => {
    it('generates a coverage report', () => {
      const report = traitMap.generateCoverageReport([]);
      expect(report).toHaveProperty('total');
      expect(report).toHaveProperty('full');
      expect(report).toHaveProperty('partial');
      expect(report).toHaveProperty('comment');
      expect(report).toHaveProperty('unsupported');
      expect(report).toHaveProperty('coveragePercent');
      expect(report).toHaveProperty('fullCoveragePercent');
      expect(report).toHaveProperty('formFactorAnalysis');
      expect(report).toHaveProperty('headsetComparison');
    });

    it('has more than 0 total traits', () => {
      const report = traitMap.generateCoverageReport([]);
      expect(report.total).toBeGreaterThan(0);
    });

    it('has full implementation traits', () => {
      const report = traitMap.generateCoverageReport([]);
      expect(report.full.length).toBeGreaterThan(0);
    });

    it('has unsupported traits due to form factor', () => {
      const report = traitMap.generateCoverageReport([]);
      expect(report.unsupported.length).toBeGreaterThan(0);
    });

  describe('AI_TRAIT_MAP vision', () => {
    it('vision is full and generates ImageLabeling for default classification task', () => {
      const mapping = traitMap.getTraitMapping('vision');
      expect(mapping).toBeDefined();
      expect(mapping!.level).toBe('full');
      const code = traitMap.generateTraitCode('vision', 'cam', {});
      expect(code.some((l) => l.includes('ImageLabeling'))).toBe(true);
      expect(code.some((l) => l.includes('cam'))).toBe(true);
      expect(code.every((l) => !l.toUpperCase().includes('TODO'))).toBe(true);
    });

    it('vision generates TextRecognition for text_recognition task', () => {
      const code = traitMap.generateTraitCode('vision', 'textScan', { task: 'text_recognition' });
      expect(code.some((l) => l.includes('TextRecognition'))).toBe(true);
      expect(code.some((l) => l.includes('textScan'))).toBe(true);
    });

    it('vision generates FaceDetection for face_detection task', () => {
      const code = traitMap.generateTraitCode('vision', 'faceNode', { task: 'face_detection' });
      expect(code.some((l) => l.includes('FaceDetection'))).toBe(true);
    });

    it('vision generates BarcodeScanning for barcode task', () => {
      const code = traitMap.generateTraitCode('vision', 'scanner', { task: 'barcode' });
      expect(code.some((l) => l.includes('BarcodeScanning'))).toBe(true);
    });

    it('vision declares ML Kit imports', () => {
      const imports = traitMap.getRequiredImports(['vision']);
      expect(imports.some((i) => i.includes('mlkit'))).toBe(true);
    });
  });

    it('blocked reasons explain form factor constraints', () => {
      const report = traitMap.generateCoverageReport([]);
      for (const reason of Object.values(report.formFactorAnalysis.blockReasons)) {
        expect(reason).toContain('UNSUPPORTED');
      }
    });

    it('compares with Android XR headset traits', () => {
      const headsetTraits = [
        'grabbable',
        'hand_tracking',
        'eye_tracking',
        'spatial_audio',
        'anchor',
        'immersive',
        'volume',
        'physics',
      ];
      const report = traitMap.generateCoverageReport(headsetTraits);
      expect(report.headsetComparison.headsetOnly.length).toBeGreaterThanOrEqual(0);
      expect(report.headsetComparison.bothFormFactors.length).toBeGreaterThan(0);
    });
  });

  describe('Coverage Summary', () => {
    it('generates readable summary string', () => {
      const summary = traitMap.getCoverageSummary([]);
      expect(summary).toContain('AI Glasses Trait Coverage Report');
      expect(summary).toContain('Full:');
      expect(summary).toContain('Unsupported:');
      expect(summary).toContain('form factor constraint');
    });
  });

  describe('Trait Listing', () => {
    it('lists all traits', () => {
      const all = traitMap.listAllTraits();
      expect(all.length).toBeGreaterThan(0);
      expect(all).toContain('glimmer_card');
      expect(all).toContain('glasses_touchpad');
      expect(all).toContain('glasses_voice');
    });

    it('lists traits by level', () => {
      const full = traitMap.listTraitsByLevel('full');
      const unsupported = traitMap.listTraitsByLevel('unsupported');
      expect(full.length).toBeGreaterThan(0);
      expect(unsupported.length).toBeGreaterThan(0);
      expect(full).toContain('glimmer_card');
      expect(unsupported).toContain('physics');
    });
  });

  describe('Trait Code Generation', () => {
    it('generates code for glimmer_card', () => {
      const code = traitMap.generateTraitCode('glimmer_card', 'myCard', { title: 'Test' });
      expect(code.length).toBeGreaterThan(0);
      expect(code.join('\n')).toContain('Card(');
      expect(code.join('\n')).toContain('Test');
    });

    it('generates code for glasses_voice with commands', () => {
      const code = traitMap.generateTraitCode('glasses_voice', 'voice', {
        commands: ['play', 'pause'],
      });
      expect(code.join('\n')).toContain('SpeechRecognizer');
      expect(code.join('\n')).toContain('play');
      expect(code.join('\n')).toContain('pause');
    });

    it('generates unsupported comment for physics', () => {
      const code = traitMap.generateTraitCode('physics', 'obj', {});
      expect(code.join('\n')).toContain('UNSUPPORTED');
    });

    it('handles unknown trait gracefully', () => {
      const code = traitMap.generateTraitCode('nonexistent', 'x', {});
      expect(code.join('\n')).toContain('no AI Glasses mapping defined');
    });
  });

  describe('Required Imports', () => {
    it('returns imports for Glimmer traits', () => {
      const imports = traitMap.getRequiredImports(['glimmer_card', 'glimmer_button']);
      expect(imports).toContain('androidx.xr.glimmer.Card');
      expect(imports).toContain('androidx.xr.glimmer.Button');
    });

    it('returns imports for Projected traits', () => {
      const imports = traitMap.getRequiredImports(['glasses_display']);
      expect(imports).toContain('androidx.xr.projected.ProjectedDisplayController');
      expect(imports).toContain('androidx.xr.projected.ProjectedDeviceController');
    });

    it('returns empty array for unsupported traits', () => {
      const imports = traitMap.getRequiredImports(['physics', 'grabbable']);
      expect(imports.length).toBe(0);
    });

    it('deduplicates imports', () => {
      const imports = traitMap.getRequiredImports([
        'glimmer_card',
        'glimmer_button',
        'glimmer_text',
      ]);
      const unique = new Set(imports);
      expect(imports.length).toBe(unique.size);
    });
  });

  describe('Min SDK Version', () => {
    it('returns at least 30 for AI Glasses', () => {
      const sdk = traitMap.getMinSdkVersion([]);
      expect(sdk).toBeGreaterThanOrEqual(30);
    });
  });

  describe('Upgraded Traits — full level', () => {
    it('hoverable is full and generates Modifier.surface(focusable = true)', () => {
      const mapping = traitMap.getTraitMapping('hoverable');
      expect(mapping).toBeDefined();
      expect(mapping!.level).toBe('full');
      const code = traitMap.generateTraitCode('hoverable', 'infoCard', {});
      expect(code.some((l) => l.includes('focusable = true'))).toBe(true);
      expect(code.some((l) => l.includes('infoCard'))).toBe(true);
      expect(code.every((l) => !l.toUpperCase().includes('TODO'))).toBe(true);
    });

    it('hoverable declares Glimmer surface imports', () => {
      const imports = traitMap.getRequiredImports(['hoverable']);
      expect(imports.some((i) => i.includes('glimmer'))).toBe(true);
    });

    it('draggable is full and generates touchpad swipe modifier', () => {
      const mapping = traitMap.getTraitMapping('draggable');
      expect(mapping).toBeDefined();
      expect(mapping!.level).toBe('full');
      const code = traitMap.generateTraitCode('draggable', 'scrollList', { direction: 'vertical' });
      expect(code.some((l) => l.includes('focusable = true') || l.includes('swipe'))).toBe(true);
      expect(code.some((l) => l.includes('scrollList'))).toBe(true);
      expect(code.some((l) => l.includes('vertical'))).toBe(true);
      expect(code.every((l) => !l.toUpperCase().includes('TODO'))).toBe(true);
    });

    it('draggable horizontal direction is emitted in code', () => {
      const code = traitMap.generateTraitCode('draggable', 'nav', { direction: 'horizontal' });
      expect(code.some((l) => l.includes('horizontal'))).toBe(true);
    });

    it('ai_npc_brain is full and generates Gemini Nano GenerativeModel', () => {
      const mapping = traitMap.getTraitMapping('ai_npc_brain');
      expect(mapping).toBeDefined();
      expect(mapping!.level).toBe('full');
      const code = traitMap.generateTraitCode('ai_npc_brain', 'assistant', {
        model: 'gemini-nano',
        max_tokens: 128,
        temperature: 0.5,
      });
      expect(code.some((l) => l.includes('GenerativeModel'))).toBe(true);
      expect(code.some((l) => l.includes('gemini-nano'))).toBe(true);
      expect(code.some((l) => l.includes('assistant'))).toBe(true);
      expect(code.some((l) => l.includes('generateResponse'))).toBe(true);
      expect(code.every((l) => !l.toUpperCase().includes('TODO'))).toBe(true);
    });

    it('ai_npc_brain uses custom max_tokens and temperature', () => {
      const code = traitMap.generateTraitCode('ai_npc_brain', 'bot', {
        max_tokens: 512,
        temperature: 0.9,
      });
      expect(code.some((l) => l.includes('512'))).toBe(true);
      expect(code.some((l) => l.includes('0.9'))).toBe(true);
    });

    it('ai_npc_brain declares AICore imports', () => {
      const imports = traitMap.getRequiredImports(['ai_npc_brain']);
      expect(imports.some((i) => i.includes('aicore') || i.includes('GenerativeModel'))).toBe(true);
    });
  });
});

describe('AIGlasses batch 4 — promoted partials', () => {
  let traitMap: typeof import('../AIGlassesTraitMap');
  beforeEach(async () => {
    traitMap = await import('../AIGlassesTraitMap');
  });

  it('plane_detection is full and generates ARCore session', () => {
    const mapping = traitMap.getTraitMapping('plane_detection');
    expect(mapping).toBeDefined();
    expect(mapping!.level).toBe('full');
    const code = traitMap.generateTraitCode('plane_detection', 'planeNode', {});
    expect(code.some((l) => l.includes('Session'))).toBe(true);
    expect(code.some((l) => l.includes('planeNode'))).toBe(true);
    expect(code.every((l) => !l.toUpperCase().includes('TODO'))).toBe(true);
  });

  it('plane_detection with vertical plane type', () => {
    const code = traitMap.generateTraitCode('plane_detection', 'wall', { plane_type: 'vertical' });
    expect(code.some((l) => l.includes('HORIZONTAL_AND_VERTICAL'))).toBe(true);
  });

  it('geospatial is full and generates LocationManager code', () => {
    const mapping = traitMap.getTraitMapping('geospatial');
    expect(mapping).toBeDefined();
    expect(mapping!.level).toBe('full');
    const code = traitMap.generateTraitCode('geospatial', 'geoNode', {});
    expect(code.some((l) => l.includes('LocationManager'))).toBe(true);
    expect(code.some((l) => l.includes('geoNode'))).toBe(true);
    expect(code.every((l) => !l.toUpperCase().includes('TODO'))).toBe(true);
  });

  it('geospatial with coarse accuracy', () => {
    const code = traitMap.generateTraitCode('geospatial', 'gps', { accuracy: 'coarse' });
    expect(code.some((l) => l.includes('ACCURACY_COARSE'))).toBe(true);
  });

  it('animated is full and generates AnimatedVisibility', () => {
    const mapping = traitMap.getTraitMapping('animated');
    expect(mapping).toBeDefined();
    expect(mapping!.level).toBe('full');
    const code = traitMap.generateTraitCode('animated', 'panel', {});
    expect(code.some((l) => l.includes('AnimatedVisibility'))).toBe(true);
    expect(code.some((l) => l.includes('panel'))).toBe(true);
    expect(code.every((l) => !l.toUpperCase().includes('TODO'))).toBe(true);
  });

  it('animated uses custom duration', () => {
    const code = traitMap.generateTraitCode('animated', 'elem', { duration: 500 });
    expect(code.some((l) => l.includes('500'))).toBe(true);
  });

  it('ai_vision is full and generates object detection code', () => {
    const mapping = traitMap.getTraitMapping('ai_vision');
    expect(mapping).toBeDefined();
    expect(mapping!.level).toBe('full');
    const code = traitMap.generateTraitCode('ai_vision', 'detector', {});
    expect(code.some((l) => l.includes('ObjectDetection') || l.includes('detection'))).toBe(true);
    expect(code.some((l) => l.includes('detector'))).toBe(true);
    expect(code.every((l) => !l.toUpperCase().includes('TODO'))).toBe(true);
  });
});
