import { createHash } from 'crypto';
import { describe, it, expect, beforeEach, vi } from 'vitest';
import { AndroidXRCompiler } from '../AndroidXRCompiler';
import { parseHolo } from '../../parser/HoloCompositionParser';
import type { HoloComposition } from '../../parser/HoloCompositionTypes';

function hashRecordStrings(obj: Record<string, unknown>): string {
  const parts: string[] = [];
  for (const k of Object.keys(obj).sort()) {
    const v = obj[k];
    if (typeof v === 'string') {
      parts.push(`${k}:${createHash('sha256').update(v, 'utf8').digest('hex')}`);
    } else if (v && typeof v === 'object' && !Array.isArray(v)) {
      parts.push(`${k}:${hashRecordStrings(v as Record<string, unknown>)}`);
    }
  }
  return createHash('sha256').update(parts.join('|'), 'utf8').digest('hex');
}
import type { AndroidXRCompileResult } from '../AndroidXRCompiler';

vi.mock('../identity/AgentRBAC', async (importOriginal) => {
  const actual = await importOriginal();
  return {
    ...actual,
    getRBAC: () => ({ checkAccess: () => ({ allowed: true }) }),
  };
});

function minimalComposition(overrides: any = {}) {
  return {
    name: 'TestScene',
    objects: [],
    lights: [],
    spatialGroups: [],
    audio: [],
    timelines: [],
    transitions: [],
    zones: [],
    ...overrides,
  };
}

/** Parse .holo source that must read without an error. */
function parseClean(source: string): HoloComposition {
  const result = parseHolo(source);
  expect(result.errors).toEqual([]);
  expect(result.ast).toBeDefined();
  return result.ast as HoloComposition;
}

describe('AndroidXRCompiler', () => {
  let compiler: AndroidXRCompiler;

  beforeEach(() => {
    compiler = new AndroidXRCompiler({ packageName: 'com.test.app', activityName: 'TestActivity' });
  });

  // ─── Result structure ─────────────────────────────────────────────

  it('returns AndroidXRCompileResult with all files', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result).toHaveProperty('activityFile');
    expect(result).toHaveProperty('stateFile');
    expect(result).toHaveProperty('nodeFactoryFile');
    expect(result).toHaveProperty('manifestFile');
    expect(result).toHaveProperty('buildGradle');
  });

  // ─── Activity file ────────────────────────────────────────────────

  it('emits package declaration', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.activityFile).toContain('package com.test.app');
  });

  it('emits activity class name', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.activityFile).toContain('class TestActivity : ComponentActivity()');
  });

  it('emits auto-generated header comment', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.activityFile).toContain('Auto-generated by HoloScript AndroidXRCompiler');
  });

  it('emits provenance hash in activity when provenanceHash is set', () => {
    const h = 'abc123provenance';
    const c = new AndroidXRCompiler({
      packageName: 'com.test.app',
      activityName: 'TestActivity',
      provenanceHash: h,
    });
    const result = c.compile(minimalComposition(), 'test-token');
    expect(result.activityFile).toContain(`// Provenance Hash: ${h}`);
  });

  it('emits Compose Scene function', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.activityFile).toContain('TestSceneScene()');
  });

  it('emits Subspace block', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.activityFile).toContain('Subspace {');
  });

  it('emits Android XR runtime config import when useARCore is true', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.activityFile).toContain('androidx.xr.runtime.Config');
    expect(result.activityFile).toContain('xrSession.configure(Config())');
  });

  it('omits Android XR runtime config when useARCore is false', () => {
    compiler = new AndroidXRCompiler({ useARCore: false });
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.activityFile).not.toContain('androidx.xr.runtime.Config');
    expect(result.activityFile).not.toContain('xrSession.configure(Config())');
  });

  it('emits Filament imports when useFilament is true', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.activityFile).toContain('com.google.android.filament');
  });

  it('compiles object with position', () => {
    const comp = minimalComposition({
      objects: [
        {
          name: 'myBox',
          properties: [
            { key: 'position', value: [1, 2, 3] },
            { key: 'mesh', value: 'box' },
          ],
          traits: [],
          children: [],
        },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.activityFile).toContain('Vector3(1f, 2f, 3f)');
    expect(result.activityFile).toContain('Quaternion.Identity');
    expect(result.activityFile).toContain('myBox');
  });

  it('compiles light with type and intensity', () => {
    const comp = minimalComposition({
      lights: [
        { name: 'sun', lightType: 'directional', properties: [{ key: 'intensity', value: 1.5 }] },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.activityFile).toContain('LightManager.Type.DIRECTIONAL');
    expect(result.activityFile).toContain('Intensity: 150000f lux');
  });

  it('compiles audio with SoundPool', () => {
    const comp = minimalComposition({
      audio: [
        {
          name: 'bgMusic',
          properties: [
            { key: 'src', value: 'bgm' },
            { key: 'loop', value: true },
          ],
        },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.activityFile).toContain('SoundPool');
    expect(result.activityFile).toContain('bgMusic');
  });

  it('sanitizes names with special characters', () => {
    const comp = minimalComposition({
      objects: [
        {
          name: 'my-special.box!',
          properties: [{ key: 'mesh', value: 'box' }],
          traits: [],
          children: [],
        },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.activityFile).toContain('my_special_box_');
  });

  it('filters @platform() blocks for Android XR before Kotlin generation', () => {
    const comp = minimalComposition({
      objects: [
        {
          name: 'androidPanel',
          properties: [{ key: 'mesh', value: 'box' }],
          traits: [],
          children: [],
          platformConstraint: { include: ['androidxr'], exclude: [] },
        },
        {
          name: 'visionPanel',
          properties: [{ key: 'mesh', value: 'box' }],
          traits: [],
          children: [],
          platformConstraint: { include: ['visionos'], exclude: [] },
        },
        {
          name: 'sharedPanel',
          properties: [{ key: 'mesh', value: 'box' }],
          traits: [],
          children: [],
        },
      ],
    });

    const result = compiler.compile(comp, 'test-token');
    expect(result.activityFile).toContain('androidPanel');
    expect(result.activityFile).toContain('sharedPanel');
    expect(result.activityFile).not.toContain('visionPanel');
  });

  it('compiles state with mutableStateOf', () => {
    const comp = minimalComposition({
      state: {
        properties: [
          { key: 'count', value: 0 },
          { key: 'label', value: 'hello' },
        ],
      },
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.activityFile).toContain('mutableStateOf(0)');
    expect(result.activityFile).toContain('mutableStateOf("hello")');
  });

  it('compiles hand tracking trait imports', () => {
    const comp = minimalComposition({
      objects: [
        { name: 'hand', properties: [], traits: [{ name: 'hand_tracking' }], children: [] },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.activityFile).toContain('InputEvent');
  });

  // ─── DP3: URI-based 3D model loading ──────────────────────────────

  it('compiles model object with URI-based GltfModel (DP3)', () => {
    const comp = minimalComposition({
      objects: [
        {
          name: 'myModel',
          properties: [
            { key: 'model', value: 'models/robot.glb' },
            { key: 'position', value: [0, 1, -2] },
          ],
          traits: [],
          children: [],
        },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.activityFile).toContain(
      'glTF model "models/robot.glb" is exposed through XRNodeFactory.loadGltfModel(...)'
    );
    expect(result.nodeFactoryFile).toContain(
      'GltfModel.create(session, Uri.parse("models/robot.glb"))'
    );
    expect(result.nodeFactoryFile).toContain('GltfModelEntity.create(');
    expect(result.activityFile).not.toContain('ArModelNode');
  });

  // ─── DP3: Face tracking with 68 blendshapes ──────────────────────

  it('emits face tracking imports when face_tracking trait is present (DP3)', () => {
    const comp = minimalComposition({
      objects: [
        {
          name: 'avatar',
          properties: [],
          traits: [{ name: 'face_tracking', config: {} }],
          children: [],
        },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.activityFile).toContain('FaceBlendShapeType');
    expect(result.activityFile).toContain('FaceTrackingMode');
    expect(result.activityFile).toContain('Face.getUserFace');
  });

  it('emits specific blendshape reads when configured (DP3)', () => {
    const comp = minimalComposition({
      objects: [
        {
          name: 'avatar',
          properties: [],
          traits: [
            { name: 'face_tracking', config: { blendshapes: ['JAW_DROP', 'EYES_CLOSED_L'] } },
          ],
          children: [],
        },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.activityFile).toContain('FACE_BLEND_SHAPE_TYPE_JAW_DROP');
    expect(result.activityFile).toContain('FACE_BLEND_SHAPE_TYPE_EYES_CLOSED_L');
  });

  // ─── DP3: UserSubspace head-following UI ──────────────────────────

  it('emits UserSubspace import for follows_head trait (DP3)', () => {
    const comp = minimalComposition({
      objects: [
        {
          name: 'hud',
          properties: [
            { key: 'width', value: 500 },
            { key: 'height', value: 300 },
          ],
          traits: [{ name: 'follows_head', config: { distance: 2.0 } }],
          children: [],
        },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.activityFile).toContain('UserSubspace');
  });

  it('wraps head-following objects in UserSubspace composable (DP3)', () => {
    const comp = minimalComposition({
      objects: [
        {
          name: 'menu',
          properties: [],
          traits: [{ name: 'follows_head', config: {} }],
          children: [],
        },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.activityFile).toContain('UserSubspace {');
    expect(result.activityFile).toContain('head-following');
  });

  // ─── DP3: DRM-protected video via SurfaceEntity ──────────────────

  it('emits DRM video with SurfaceEntity.SurfaceProtection.PROTECTED (DP3)', () => {
    const comp = minimalComposition({
      objects: [
        {
          name: 'moviePlayer',
          properties: [],
          traits: [
            {
              name: 'drm_video',
              config: {
                uri: 'https://example.com/movie.mpd',
                license_uri: 'https://license.example.com/widevine',
                stereo_mode: 'SIDE_BY_SIDE',
                shape: 'quad',
              },
            },
          ],
          children: [],
        },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.activityFile).toContain('SurfaceEntity.SurfaceProtection.PROTECTED');
    expect(result.activityFile).toContain('C.WIDEVINE_UUID');
    expect(result.activityFile).toContain('ExoPlayer');
  });

  it('emits sphere shape for 360 DRM video (DP3)', () => {
    const comp = minimalComposition({
      objects: [
        {
          name: 'video360',
          properties: [],
          traits: [
            {
              name: 'drm_video',
              config: { shape: 'sphere', radius: 10 },
            },
          ],
          children: [],
        },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.activityFile).toContain('SurfaceEntity.Shape.Sphere(10f)');
  });

  // ─── DP3: SceneCore import updates ────────────────────────────────

  it('emits GltfModel and GltfModelEntity imports (DP3)', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.activityFile).toContain('import androidx.xr.scenecore.GltfModel');
    expect(result.activityFile).toContain('import androidx.xr.scenecore.GltfModelEntity');
    expect(result.activityFile).toContain('import androidx.xr.scenecore.SurfaceEntity');
    expect(result.activityFile).toContain('import androidx.xr.scenecore.SpatialCapability');
  });

  it('compiles timeline with animation', () => {
    const comp = minimalComposition({
      timelines: [
        {
          name: 'intro',
          loop: true,
          entries: [{ time: 0, action: { kind: 'animate', properties: { opacity: 1 } } }],
        },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.activityFile).toContain('playTimeline_intro');
    expect(result.activityFile).toContain('AnimatorSet');
  });

  it('compiles transition', () => {
    const comp = minimalComposition({
      transitions: [
        {
          name: 'fadeOut',
          properties: [
            { key: 'target', value: 'scene2' },
            { key: 'duration', value: 1.0 },
          ],
        },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.activityFile).toContain('transition_fadeOut');
    expect(result.activityFile).toContain('1000L');
  });

  // ─── State file ───────────────────────────────────────────────────

  it('generates state file with XRSceneState class', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.stateFile).toContain('class XRSceneState : ViewModel()');
    expect(result.stateFile).toContain('package com.test.app');
  });

  it('generates state file with state properties', () => {
    const comp = minimalComposition({
      state: {
        properties: [
          { key: 'score', value: 0 },
          { key: 'active', value: true },
        ],
      },
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.stateFile).toContain('score');
    expect(result.stateFile).toContain('active');
    expect(result.stateFile).toContain('MutableLiveData');
  });

  it('generates state file with XR-specific state', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.stateFile).toContain('spatialCapabilities');
    expect(result.stateFile).toContain('activeEntities');
    expect(result.stateFile).toContain('selectedEntity');
  });

  it('generates state file with reset function', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.stateFile).toContain('fun reset()');
  });

  // ─── Node Factory file ────────────────────────────────────────────

  it('generates node factory file with XRNodeFactory', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.nodeFactoryFile).toContain('object XRNodeFactory');
    expect(result.nodeFactoryFile).toContain('package com.test.app');
  });

  it('generates node factory with GltfModel loading', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.nodeFactoryFile).toContain('loadGltfModel');
    expect(result.nodeFactoryFile).toContain('GltfModel.create');
    expect(result.nodeFactoryFile).toContain('GltfModelEntity');
  });

  it('generates node factory methods for objects', () => {
    const comp = minimalComposition({
      objects: [
        {
          name: 'Robot',
          properties: [{ key: 'model', value: 'models/robot.glb' }],
          traits: [],
          children: [],
        },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.nodeFactoryFile).toContain('createRobot');
    expect(result.nodeFactoryFile).toContain('models/robot.glb');
  });

  // ─── Manifest file ────────────────────────────────────────────────

  it('generates manifest with XR permissions', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.manifestFile).toContain('uses-permission');
    expect(result.manifestFile).toContain('android.permission.CAMERA');
    expect(result.manifestFile).toContain('android.hardware.xr.headtracking');
  });

  it('generates manifest with XR category', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.manifestFile).toContain('com.google.intent.category.XR');
  });

  it('generates manifest with activity name', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.manifestFile).toContain('.TestActivity');
  });

  it('adds hand tracking permission when hand_tracking trait is used', () => {
    const comp = minimalComposition({
      objects: [
        { name: 'hand', properties: [], traits: [{ name: 'hand_tracking' }], children: [] },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.manifestFile).toContain('android.permission.HAND_TRACKING');
  });

  it('adds face tracking permission when face_tracking trait is used', () => {
    const comp = minimalComposition({
      objects: [
        {
          name: 'avatar',
          properties: [],
          traits: [{ name: 'face_tracking', config: {} }],
          children: [],
        },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.manifestFile).toContain('android.permission.FACE_TRACKING');
  });

  it('adds optional android.hardware.camera.ar when occlusion_mesh trait is used (Film3D ARCore depth)', () => {
    const comp = minimalComposition({
      objects: [
        {
          name: 'stage',
          properties: [],
          traits: [{ name: 'occlusion_mesh', config: {} }],
          children: [],
        },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.manifestFile).toContain('android.hardware.camera.ar');
    expect(result.manifestFile).toMatch(/android\.hardware\.camera\.ar" android:required="false"/);
  });

  it('adds required android.hardware.camera.ar when arCameraHardwareRequired is true', () => {
    const c = new AndroidXRCompiler({
      packageName: 'com.test.app',
      activityName: 'TestActivity',
      arCameraHardwareRequired: true,
    });
    const comp = minimalComposition({
      objects: [
        {
          name: 'stage',
          properties: [],
          traits: [{ name: 'environment_probe', config: {} }],
          children: [],
        },
      ],
    });
    const result = c.compile(comp, 'test-token');
    expect(result.manifestFile).toMatch(/android\.hardware\.camera\.ar" android:required="true"/);
  });

  // ─── Build Gradle file ────────────────────────────────────────────

  it('generates build.gradle.kts with dependencies', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.buildGradle).toContain('dependencies');
    expect(result.buildGradle).toContain('androidx.xr.scenecore');
    expect(result.buildGradle).toContain('androidx.xr.arcore');
  });

  it('generates build.gradle.kts with compose support', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.buildGradle).toContain('compose = true');
    expect(result.buildGradle).toContain('androidx.compose');
  });

  it('generates build.gradle.kts with package name', () => {
    const result = compiler.compile(minimalComposition(), 'test-token');
    expect(result.buildGradle).toContain('com.test.app');
  });

  it('includes Media3 dependencies when DRM video traits are used', () => {
    const comp = minimalComposition({
      objects: [
        {
          name: 'player',
          properties: [],
          traits: [{ name: 'drm_video', config: { uri: 'test.mpd' } }],
          children: [],
        },
      ],
    });
    const result = compiler.compile(comp, 'test-token');
    expect(result.buildGradle).toContain('media3-exoplayer');
  });

  describe('W4-T3 Wave-1 characterization (split gate)', () => {
    it('AndroidXRCompiler fingerprint for empty Wave1 gate composition', () => {
      const comp = minimalComposition({ name: 'Wave1SplitCharacterization' });
      const out = compiler.compile(comp, 'test-token');
      // Updated 2026-06-21: SceneCore alpha16-compatible runtime Session, Vector3 pose,
      // and capability-gated depth/probe comments keep the Android XR reference buildable.
      expect(hashRecordStrings(out as unknown as Record<string, unknown>)).toBe(
        '7b1988c05bcd692341dec78de7e224dbc509c2acf9d27897a4dc93b515e0da25'
      );
    });
  });

  // ─── Film3D: Soundstage grounding (Quest 3 — occlusion_mesh + environment_probe) ─────

  describe('Soundstage grounding — Quest 3 validation', () => {
    it('combined occlusion_mesh + environment_probe emits camera.ar manifest feature', () => {
      const comp = minimalComposition({
        objects: [
          {
            name: 'soundstage_occlusion',
            properties: [],
            traits: [{ name: 'occlusion_mesh', config: {} }],
            children: [],
          },
          {
            name: 'hdr_environment',
            properties: [],
            traits: [{ name: 'environment_probe', config: {} }],
            children: [],
          },
        ],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.manifestFile).toContain('android.hardware.camera.ar');
    });

    it('occlusion_mesh emits depth guard code (isDepthSupported + DepthMode.AUTOMATIC) in activity', () => {
      const comp = minimalComposition({
        objects: [
          {
            name: 'soundstage_occlusion',
            properties: [],
            traits: [{ name: 'occlusion_mesh', config: {} }],
            children: [],
          },
        ],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.activityFile).toContain('Depth occlusion requested for soundstage_occlusion');
      expect(result.activityFile).toContain(
        'Activate strictly if depth API is physically supported on-device'
      );
      expect(result.activityFile).not.toContain('Config.DepthMode.AUTOMATIC');
    });

    it('environment_probe emits a capability-gated runtime marker in activity', () => {
      const comp = minimalComposition({
        objects: [
          {
            name: 'hdr_environment',
            properties: [],
            traits: [{ name: 'environment_probe', config: {} }],
            children: [],
          },
        ],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.activityFile).toContain('Environment probe requested for hdr_environment');
      expect(result.activityFile).toContain('capability check required');
      expect(result.activityFile).not.toContain('createEnvironmentProbe');
    });

    it('FILM3D_XR triple (occlusion_mesh + environment_probe + gaze_interactable) emits all grounding code', () => {
      const comp = minimalComposition({
        objects: [
          {
            name: 'soundstage_occlusion',
            properties: [],
            traits: [{ name: 'occlusion_mesh', config: {} }],
            children: [],
          },
          {
            name: 'hdr_environment',
            properties: [],
            traits: [{ name: 'environment_probe', config: {} }],
            children: [],
          },
          {
            name: 'director_hud',
            properties: [],
            traits: [{ name: 'gaze_interactable', config: {} }],
            children: [],
          },
        ],
      });
      const result = compiler.compile(comp, 'test-token');
      expect(result.manifestFile).toContain('android.hardware.camera.ar');
      expect(result.activityFile).toContain('Depth occlusion requested for soundstage_occlusion');
      expect(result.activityFile).toContain('Environment probe requested for hdr_environment');
      expect(result.activityFile).not.toContain('Config.DepthMode.AUTOMATIC');
    });

    it('combined traits add camera.ar manifest entry only once (deduplication)', () => {
      const comp = minimalComposition({
        objects: [
          {
            name: 'soundstage_occlusion',
            properties: [],
            traits: [{ name: 'occlusion_mesh', config: {} }],
            children: [],
          },
          {
            name: 'hdr_environment',
            properties: [],
            traits: [{ name: 'environment_probe', config: {} }],
            children: [],
          },
        ],
      });
      const result = compiler.compile(comp, 'test-token');
      const occurrences = (result.manifestFile.match(/android\.hardware\.camera\.ar/g) ?? [])
        .length;
      expect(occurrences).toBe(1);
    });
  });

  // ─── Convenience export ───────────────────────────────────────────

  it('exports compileToAndroidXR convenience function', async () => {
    const mod = await import('../AndroidXRCompiler');
    expect(mod.compileToAndroidXR).toBeTypeOf('function');
  });

  // ─── Scene blocks ─────────────────────────────────────────────────
  // The parser keeps a scene's contents on composition.scenes, not composition.objects.

  describe('scene blocks', () => {
    const crate = `object "SceneCrate" {
      geometry: "sphere"
      position: [1.5, 2.5, -3.5]
    }`;
    const glasses = () =>
      new AndroidXRCompiler({
        packageName: 'com.test.app',
        activityName: 'TestActivity',
        formFactor: 'glasses',
      });

    it('compiles an object written only inside a scene like the same object at the top level', () => {
      const inScene = parseClean(`composition "Scenes" {\n  scene "Main" {\n    ${crate}\n  }\n}`);
      const atTop = parseClean(`composition "Scenes" {\n  ${crate}\n}`);
      expect(inScene.objects).toEqual([]);

      const result = compiler.compile(inScene, 'test-token');
      expect(result.activityFile).toContain(
        'val SceneCrate = Entity.create(xrSession, "SceneCrate", Pose(Vector3(1.5f, 2.5f, -3.5f), Quaternion.Identity))'
      );
      expect(result.activityFile).toContain('// Geometry: IcoSphereShape');
      expect(result.nodeFactoryFile).toContain(
        'fun createSceneCrate(session: XRSession): Entity {'
      );
      expect(result).toEqual(compiler.compile(atTop, 'test-token'));
    });

    it('does the same on the glasses screen', () => {
      const inScene = parseClean(`composition "Scenes" {\n  scene "Main" {\n    ${crate}\n  }\n}`);
      const atTop = parseClean(`composition "Scenes" {\n  ${crate}\n}`);

      const result = glasses().compile(inScene, 'test-token');
      expect(result.activityFile).toContain('headlineContent = { Text("SceneCrate") }');
      expect(result.nodeFactoryFile).toContain(
        'fun createSceneCrate(session: XRSession): Entity {'
      );
      expect(result).toEqual(glasses().compile(atTop, 'test-token'));
    });

    it("emits top-level objects first, then each scene's objects in scene order", () => {
      const result = compiler.compile(
        parseClean(`composition "Scenes" {
  scene "First" {
    object "InFirst" { geometry: "cube" }
  }
  object "AtTop" { geometry: "cube" }
  scene "Second" {
    object "InSecond" { geometry: "cube" }
  }
}`),
        'test-token'
      );
      const order = (text: string, prefix: string) =>
        ['AtTop', 'InFirst', 'InSecond'].map((n) => text.indexOf(`${prefix}${n}`));
      for (const [text, prefix] of [
        [result.activityFile, '// Object: '],
        [result.nodeFactoryFile, 'fun create'],
      ]) {
        const at = order(text, prefix);
        expect(at.every((i) => i >= 0)).toBe(true);
        expect([...at].sort((a, b) => a - b)).toEqual(at);
      }
    });

    it('uses the environment written inside a scene when the composition has none', () => {
      const result = compiler.compile(
        parseClean(`composition "Scenes" {
  scene "Main" {
    environment { skybox: "sunset" }
  }
}`),
        'test-token'
      );
      expect(result.activityFile).toContain('// Preset: "sunset"');
      expect(result.activityFile).not.toContain('WARNING');
    });

    it("names a scene environment it does not apply, and says the composition's own applies", () => {
      // The composition's own environment is written after the scene; it still wins.
      const source = `composition "Scenes" {
  scene "Night" {
    environment { skybox: "night" }
  }
  environment { skybox: "sunset" }
}`;
      const result = compiler.compile(parseClean(source), 'test-token');
      expect(result.activityFile).toContain('// Preset: "sunset"');
      expect(result.activityFile).not.toContain('"night"');
      expect(result.activityFile).toContain(
        `// WARNING: the environment in scene "Night" is not applied: this output is one world with one environment, and the composition's own environment applies.`
      );
      // The glasses screen draws no environment, so there is none to say is not applied.
      expect(glasses().compile(parseClean(source), 'test-token').activityFile).not.toContain(
        'WARNING'
      );
    });

    it('leaves out a scene object whose name is already taken, and names it', () => {
      const result = compiler.compile(
        parseClean(`composition "Scenes" {
  scene "Day" {
    object "Ground" { geometry: "plane" }
  }
  scene "Night" {
    object "Ground" { geometry: "plane" }
    object "Moon" { geometry: "sphere" }
  }
}`),
        'test-token'
      );
      // One scope has one `val Ground`, and one factory one `createGround`.
      expect(result.activityFile.match(/val Ground = /g)).toHaveLength(1);
      expect(result.nodeFactoryFile.match(/fun createGround\(/g)).toHaveLength(1);
      expect(result.activityFile).toContain('val Moon = Entity.create(');
      expect(result.activityFile).toContain(
        '// WARNING: object "Ground" in scene "Night" is not built: this output is one world, and another object in it already uses the name "Ground".'
      );
    });

    // Objects are not the only names in the activity's Subspace: every part below declares the
    // `val` named beside it there, and the activity has an `xrSession` of its own. A scene
    // object that would declare one again is left out the same way, and the WARNING says what
    // has it. A sound's `val` is derived from its name (`WindId`).
    const declarations = (text: string, name: string) =>
      text.match(new RegExp(`\\bval ${name} = `, 'g')) ?? [];

    it.each([
      ['a light', 'light "Ground" point { intensity: 1 }', 'Ground', 1],
      [
        'a group',
        'spatial_group "Ground" {\n    object "Lamp" { mesh: "sphere" }\n  }',
        'Ground',
        1,
      ],
      ['a zone', 'zone "Ground" { shape: "box" }', 'Ground', 1],
      ['a sound', 'audio "Wind" { src: "wind.ogg" }', 'WindId', 1],
      ['the XR session', '', 'xrSession', 0],
      ['the sound pool', 'audio "Wind" { src: "wind.ogg" }', 'soundPool', 0],
    ])('leaves out a scene object whose val %s already declares', (by, part, name, declaredBy) => {
      const result = compiler.compile(
        parseClean(`composition "Parts" {
  ${part}
  scene "Level" {
    object "${name}" { geometry: "cube" }
    object "Crate" { geometry: "cube" }
  }
}`),
        'test-token'
      );
      // `xrSession` and `soundPool` are properties of the activity, so there is no `val` to count.
      expect(declarations(result.activityFile, name)).toHaveLength(declaredBy);
      expect(result.activityFile).toContain('val Crate = Entity.create(');
      expect(result.activityFile).toContain(
        `// WARNING: object "${name}" in scene "Level" is not built: this output is one world, and ${by} in it already uses the name "${name}".`
      );
    });

    it('counts the vals a part derives from its name, both ways round', () => {
      const result = compiler.compile(
        parseClean(`composition "Derived" {
  object "Floor" {
    geometry: "box"
    material: { color: "#888888" }
  }
  light "CrateColor" point { intensity: 1 }
  scene "Level" {
    object "FloorColor" { geometry: "cube" }
    object "Crate" {
      geometry: "box"
      material: { color: "#aa5500" }
    }
  }
}`),
        'test-token'
      );
      // Floor's material colour is the `val FloorColor`.
      expect(declarations(result.activityFile, 'FloorColor')).toHaveLength(1);
      expect(result.activityFile).toContain(
        '// WARNING: object "FloorColor" in scene "Level" is not built: this output is one world, and another object in it already uses the name "FloorColor".'
      );
      // Building Crate would declare `CrateColor` for its material, and the light has `CrateColor`.
      expect(declarations(result.activityFile, 'CrateColor')).toHaveLength(1);
      expect(declarations(result.activityFile, 'Crate')).toHaveLength(0);
      expect(result.activityFile).toContain(
        '// WARNING: object "Crate" in scene "Level" is not built: this output is one world, and a light in it already uses the name "CrateColor".'
      );
    });

    it('counts the objects inside an object and inside a spatial group: they are in the same scope', () => {
      const result = compiler.compile(
        parseClean(`composition "Nested" {
  object "Leg" { geometry: "cylinder" }
  spatial_group "Props" {
    object "Lamp" { mesh: "sphere" }
  }
  scene "Level" {
    object "Table" {
      geometry: "box"
      object "Leg" { geometry: "cylinder" }
    }
    object "Lamp" { geometry: "cube" }
    object "Desk" {
      geometry: "box"
      object "Drawer" { geometry: "box" }
    }
    object "Chest" {
      geometry: "box"
      object "Drawer" { geometry: "box" }
    }
  }
}`),
        'test-token'
      );
      for (const name of ['Leg', 'Lamp', 'Drawer', 'Desk']) {
        expect(declarations(result.activityFile, name)).toHaveLength(1);
      }
      // Desk is built with the Drawer inside it; the others would declare a second one.
      for (const left of ['Table', 'Chest']) {
        expect(declarations(result.activityFile, left)).toHaveLength(0);
      }
      for (const [object, taken] of [
        ['Table', 'Leg'],
        ['Lamp', 'Lamp'],
        ['Chest', 'Drawer'],
      ]) {
        expect(result.activityFile).toContain(
          `// WARNING: object "${object}" in scene "Level" is not built: this output is one world, and another object in it already uses the name "${taken}".`
        );
      }
      expect(result.activityFile.match(/WARNING/g)).toHaveLength(3);
    });

    it('counts an object inside an object on the headset only: the glasses screen declares no val for it', () => {
      // Children get a `val` in the Subspace but no method in the node factory, which has one per
      // top-level object. So a scene object named like a child clashes on the headset, and on the
      // glasses screen it does not.
      const source = `composition "Nested" {
  object "Parent" {
    geometry: "box"
    object "Kid" { geometry: "cube" }
  }
  scene "Level" {
    object "Kid" { geometry: "cube" }
  }
}`;
      const headset = compiler.compile(parseClean(source), 'test-token');
      expect(declarations(headset.activityFile, 'Kid')).toHaveLength(1);
      expect(headset.nodeFactoryFile).not.toContain('fun createKid(');
      expect(headset.activityFile).toContain(
        '// WARNING: object "Kid" in scene "Level" is not built: this output is one world, and another object in it already uses the name "Kid".'
      );

      const onGlasses = glasses().compile(parseClean(source), 'test-token');
      expect(onGlasses.nodeFactoryFile.match(/fun createKid\(/g)).toHaveLength(1);
      expect(onGlasses.activityFile.match(/Text\("Kid"\)/g)).toHaveLength(2);
      expect(onGlasses.activityFile).not.toContain('WARNING');
    });

    it('builds a second object that has the same trait: the vals a trait derives from each name clash with nothing', () => {
      const result = compiler.compile(
        parseClean(`composition "Traits" {
  object "Face1" {
    @face_tracking
    geometry: "cube"
  }
  scene "Level" {
    object "Face2" {
      @face_tracking
      geometry: "cube"
    }
  }
}`),
        'test-token'
      );
      for (const name of ['Face1', 'Face2']) {
        expect(declarations(result.activityFile, name)).toHaveLength(1);
        expect(declarations(result.activityFile, `${name}Face`)).toHaveLength(1);
      }
      expect(result.activityFile).not.toContain('WARNING');
    });

    it('leaves out a scene object that would add a second method to the node factory', () => {
      // Each object is `create` + its name with the first letter capitalized, so "crate" and
      // "Crate" are one method, and the factory has a `createDefaultEntity` of its own.
      const source = `composition "Factory" {
  light "Sun" directional { intensity: 1 }
  object "Crate" { geometry: "cube" }
  scene "Level" {
    object "crate" { geometry: "cube" }
    object "DefaultEntity" { geometry: "cube" }
    object "Barrel" { geometry: "cube" }
  }
}`;
      for (const make of [() => compiler, glasses]) {
        const result = make().compile(parseClean(source), 'test-token');
        expect(result.nodeFactoryFile.match(/fun createCrate\(/g)).toHaveLength(1);
        expect(result.nodeFactoryFile.match(/fun createDefaultEntity\(/g)).toHaveLength(1);
        expect(result.nodeFactoryFile).toContain('fun createBarrel(session: XRSession): Entity {');
        expect(result.activityFile).toContain(
          '// WARNING: object "crate" in scene "Level" is not built: this output is one world, and another object in it already uses the name "createCrate".'
        );
        expect(result.activityFile).toContain(
          '// WARNING: object "DefaultEntity" in scene "Level" is not built: this output is one world, and the node factory in it already uses the name "createDefaultEntity".'
        );
        expect(result.activityFile.match(/WARNING/g)).toHaveLength(2);
      }
    });

    it('builds a scene object that shares its name with a light on the glasses screen: it declares no val there', () => {
      const result = glasses().compile(
        parseClean(`composition "Parts" {
  light "Ground" point { intensity: 1 }
  scene "Level" {
    object "Ground" { geometry: "cube" }
  }
}`),
        'test-token'
      );
      expect(result.activityFile).toContain('headlineContent = { Text("Ground") }');
      expect(result.nodeFactoryFile).toContain('fun createGround(session: XRSession): Entity {');
      expect(result.activityFile).not.toContain('WARNING');
    });

    it('reads the traits written on a scene object: they reach the manifest', () => {
      const result = compiler.compile(
        parseClean(`composition "Scenes" {
  scene "Main" {
    object "Hand" {
      @hand_tracking
      geometry: "cube"
    }
  }
}`),
        'test-token'
      );
      expect(result.manifestFile).toContain('android.permission.HAND_TRACKING');
      expect(compiler.compile(minimalComposition(), 'test-token').manifestFile).not.toContain(
        'android.permission.HAND_TRACKING'
      );
    });

    it('builds only the scene objects this platform keeps, and only they take names', () => {
      // The parser does not attach a @platform() written inside a scene, so it is set on the AST.
      const comp = parseClean(`composition "Scenes" {
  scene "Level" {
    object "PhoneOnly" { geometry: "cube" }
    object "Hero" { geometry: "sphere" }
    object "Hero" { geometry: "box" }
  }
}`);
      const [phoneOnly, heroForOthers, heroForAndroidXR] = comp.scenes![0].objects;
      phoneOnly.platformConstraint = { include: ['ios'], exclude: [] };
      heroForOthers.platformConstraint = { include: ['visionos'], exclude: [] };
      heroForAndroidXR.platformConstraint = { include: ['android-xr'], exclude: [] };

      for (const make of [() => compiler, glasses]) {
        const result = make().compile(structuredClone(comp), 'test-token');
        expect(result.activityFile).not.toContain('PhoneOnly');
        expect(result.nodeFactoryFile).not.toContain('PhoneOnly');
        expect(result.nodeFactoryFile.match(/fun createHero\(/g)).toHaveLength(1);
        expect(result.activityFile).not.toContain('WARNING');
      }
      expect(compiler.compile(structuredClone(comp), 'test-token').activityFile).toContain(
        '// Geometry: BoxShape'
      );
    });

    it('lets a scene object use the name of a top-level object this platform excludes', () => {
      const result = compiler.compile(
        parseClean(`composition "Scenes" {
  @platform(visionos) object "Hero" { geometry: "sphere" }
  scene "Level" {
    object "Hero" { geometry: "box" }
  }
}`),
        'test-token'
      );
      expect(result.activityFile.match(/val Hero = /g)).toHaveLength(1);
      expect(result.nodeFactoryFile.match(/fun createHero\(/g)).toHaveLength(1);
      expect(result.activityFile).not.toContain('WARNING');
    });

    it('builds a scene object that clashes with nothing exactly as if it were written at the top level', () => {
      const parts = `light "Sun" directional { intensity: 1 }
  environment { skybox: "sunset" }
  object "Floor" {
    geometry: "box"
    material: { color: "#888888" }
  }
  spatial_group "Props" {
    object "Lamp" { mesh: "sphere" }
  }
  audio "Wind" { src: "wind.ogg" }
  zone "Pad" { shape: "box" }`;
      const barrel = `object "Barrel" {
    geometry: "cylinder"
    material: { color: "#aa5500" }
  }`;
      for (const make of [() => compiler, glasses]) {
        const inScene = make().compile(
          parseClean(`composition "C" {\n  ${parts}\n  scene "Level" {\n    ${barrel}\n  }\n}`),
          'test-token'
        );
        const atTop = make().compile(
          parseClean(`composition "C" {\n  ${parts}\n  ${barrel}\n}`),
          'test-token'
        );
        expect(inScene.activityFile).not.toContain('WARNING');
        expect(inScene).toEqual(atTop);
      }
    });
  });
});
