/**
 * GodotCompiler — Production Test Suite
 *
 * Covers: header, extends/class_name, state vars, object meshes,
 * text/model/sparkles, physics (RigidBody3D/StaticBody3D), materials,
 * lights, camera, audio (spatial vs flat), zones, timelines, transitions, UI.
 */
import { describe, it, expect, vi } from 'vitest';
import { GodotCompiler } from '../GodotCompiler';
import type { HoloComposition } from '../../parser/HoloCompositionTypes';

vi.mock('../identity/AgentRBAC', async (importOriginal) => {
  const actual = await importOriginal();
  return {
    ...actual,
    getRBAC: () => ({ checkAccess: () => ({ allowed: true }) }),
  };
});

function makeComp(overrides: Partial<HoloComposition> = {}): HoloComposition {
  return { name: 'TestScene', objects: [], ...overrides } as HoloComposition;
}

describe('GodotCompiler — Production', () => {
  // ─── Header & Structure ───────────────────────────────────────────────────

  it('emits auto-generated header comment', () => {
    const gd = new GodotCompiler().compile(makeComp({ name: 'ForestLevel' }), 'test-token');
    expect(gd).toContain('Auto-generated by HoloScript GodotCompiler');
    expect(gd).toContain('"ForestLevel"');
  });

  it('emits extends Node3D', () => {
    const gd = new GodotCompiler().compile(makeComp(), 'test-token');
    expect(gd).toContain('extends Node3D');
  });

  it('emits class_name with default GeneratedScene', () => {
    const gd = new GodotCompiler().compile(makeComp(), 'test-token');
    expect(gd).toContain('class_name GeneratedScene');
  });

  it('respects custom className option', () => {
    const gd = new GodotCompiler({ className: 'BossArena' }).compile(makeComp(), 'test-token');
    expect(gd).toContain('class_name BossArena');
  });

  it('emits godot version in header', () => {
    const gd = new GodotCompiler({ godotVersion: '4.1' }).compile(makeComp(), 'test-token');
    expect(gd).toContain('4.1');
  });

  it('emits _ready(): function', () => {
    const gd = new GodotCompiler().compile(makeComp(), 'test-token');
    expect(gd).toContain('func _ready():');
  });

  // ─── State Variables ──────────────────────────────────────────────────────

  it('compiles integer state to var', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        state: { properties: [{ key: 'health', value: 100 }] } as any,
      }),
      'test-token'
    );
    expect(gd).toContain('var health = 100');
  });

  it('compiles boolean state to true/false', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        state: { properties: [{ key: 'invincible', value: false }] } as any,
      }),
      'test-token'
    );
    expect(gd).toContain('var invincible = false');
  });

  it('compiles string state with quotes', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        state: { properties: [{ key: 'zone', value: 'ice' }] } as any,
      }),
      'test-token'
    );
    expect(gd).toContain('var zone = "ice"');
  });

  it('compiles array state to GDScript array literal', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        state: { properties: [{ key: 'ids', value: [1, 2, 3] }] } as any,
      }),
      'test-token'
    );
    expect(gd).toContain('var ids = [1, 2, 3]');
  });

  // ─── Object Primitives ────────────────────────────────────────────────────

  it('compiles box/cube to BoxMesh', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          { name: 'crate', properties: [{ key: 'mesh', value: 'box' }], traits: [] },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('MeshInstance3D.new()');
    expect(gd).toContain('BoxMesh.new()');
    expect(gd).toContain('crate.name = "crate"');
  });

  it('compiles sphere to SphereMesh', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          { name: 'ball', properties: [{ key: 'mesh', value: 'sphere' }], traits: [] },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('SphereMesh.new()');
  });

  it('compiles plane to PlaneMesh', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          { name: 'floor', properties: [{ key: 'mesh', value: 'plane' }], traits: [] },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('PlaneMesh.new()');
  });

  it('compiles torus to TorusMesh', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          { name: 'ring', properties: [{ key: 'mesh', value: 'torus' }], traits: [] },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('TorusMesh.new()');
  });

  it('adds object to parent via add_child', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          { name: 'item', properties: [{ key: 'mesh', value: 'cube' }], traits: [] },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('self.add_child(item)');
  });

  // ─── Special Object Types ─────────────────────────────────────────────────

  it('compiles text object to Label3D', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          {
            name: 'sign',
            properties: [
              { key: 'mesh', value: 'text' },
              { key: 'text', value: 'Game Over' },
            ],
            traits: [],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('Label3D.new()');
    expect(gd).toContain('.text = "Game Over"');
  });

  it('compiles model object via load', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          {
            name: 'pine',
            properties: [{ key: 'model', value: 'pine_tree' }],
            traits: [],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('load("res://models/pine_tree.glb").instantiate()');
  });

  it('compiles sparkles object to GPUParticles3D', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          {
            name: 'stars',
            properties: [{ key: 'mesh', value: 'sparkles' }],
            traits: [],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('GPUParticles3D.new()');
  });

  // ─── Physics Traits ───────────────────────────────────────────────────────

  it('compiles physics trait to RigidBody3D wrapper', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          {
            name: 'boulder',
            properties: [{ key: 'mesh', value: 'sphere' }],
            traits: [{ name: 'physics', config: {} }],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('RigidBody3D.new()');
    expect(gd).toContain('CollisionShape3D.new()');
  });

  it('compiles collidable trait to StaticBody3D', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          {
            name: 'wall',
            properties: [{ key: 'mesh', value: 'box' }],
            traits: [{ name: 'collidable', config: {} }],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('StaticBody3D.new()');
  });

  it('compiles cloth trait comment to SoftBody3D', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          {
            name: 'cape',
            properties: [{ key: 'mesh', value: 'plane' }],
            traits: [{ name: 'cloth', config: {} }],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('SoftBody3D.new()');
  });

  // ─── Transforms ───────────────────────────────────────────────────────────

  it('compiles position to Vector3', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          {
            name: 'obj',
            properties: [
              { key: 'mesh', value: 'cube' },
              { key: 'position', value: [2, 4, 6] },
            ],
            traits: [],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('position = Vector3(2, 4, 6)');
  });

  it('compiles rotation to rotation_degrees', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          {
            name: 'obj',
            properties: [
              { key: 'mesh', value: 'cube' },
              { key: 'rotation', value: [0, 45, 0] },
            ],
            traits: [],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('rotation_degrees = Vector3(0, 45, 0)');
  });

  it('compiles scale property', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          {
            name: 'obj',
            properties: [
              { key: 'mesh', value: 'cube' },
              { key: 'scale', value: [2, 2, 2] },
            ],
            traits: [],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('scale = Vector3(2, 2, 2)');
  });

  // ─── Materials ────────────────────────────────────────────────────────────

  it('compiles material to StandardMaterial3D with albedo color', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          {
            name: 'gem',
            properties: [
              { key: 'mesh', value: 'sphere' },
              { key: 'material', value: { color: '#4488ff' } },
            ],
            traits: [],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('StandardMaterial3D.new()');
    expect(gd).toContain('albedo_color = Color.html(');
  });

  it('compiles material roughness and metalness', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          {
            name: 'metal',
            properties: [
              { key: 'mesh', value: 'cube' },
              { key: 'material', value: { roughness: 0.2, metalness: 0.9 } },
            ],
            traits: [],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('roughness = 0.2');
    expect(gd).toContain('metallic = 0.9');
  });

  it('compiles emissive material', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        objects: [
          {
            name: 'neon',
            properties: [
              { key: 'mesh', value: 'cube' },
              { key: 'material', value: { emissive: '#ff00ff' } },
            ],
            traits: [],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('emission_enabled = true');
    expect(gd).toContain('emission = Color.html(');
  });

  // ─── Lights ───────────────────────────────────────────────────────────────

  it('compiles directional light to DirectionalLight3D', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        lights: [
          { name: 'sun', lightType: 'directional', properties: [{ key: 'intensity', value: 1 }] },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('DirectionalLight3D.new()');
    expect(gd).toContain('light_energy = 1');
    expect(gd).toContain('add_child(sun)');
  });

  it('compiles point light to OmniLight3D', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        lights: [{ name: 'lamp', lightType: 'point', properties: [] }] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('OmniLight3D.new()');
  });

  it('compiles spot light to SpotLight3D', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        lights: [{ name: 'torch', lightType: 'spot', properties: [] }] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('SpotLight3D.new()');
  });

  it('compiles light color as Color.html()', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        lights: [
          {
            name: 'sun',
            lightType: 'directional',
            properties: [{ key: 'color', value: '#ffffcc' }],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('light_color = Color.html(');
  });

  it('compiles light shadow_enabled', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        lights: [
          {
            name: 'sun',
            lightType: 'directional',
            properties: [{ key: 'cast_shadow', value: true }],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('shadow_enabled = true');
  });

  // ─── Camera ───────────────────────────────────────────────────────────────

  it('compiles camera with fov and cam.current = true', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        camera: { properties: [{ key: 'fov', value: 90 }] } as any,
      }),
      'test-token'
    );
    expect(gd).toContain('Camera3D.new()');
    expect(gd).toContain('cam.fov = 90');
    expect(gd).toContain('cam.current = true');
    expect(gd).toContain('add_child(cam)');
  });

  it('compiles camera near/far', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        camera: {
          properties: [
            { key: 'near', value: 0.05 },
            { key: 'far', value: 500 },
          ],
        } as any,
      }),
      'test-token'
    );
    expect(gd).toContain('cam.near = 0.05');
    expect(gd).toContain('cam.far = 500');
  });

  // ─── Audio ────────────────────────────────────────────────────────────────

  it('compiles non-spatial audio to AudioStreamPlayer', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        audio: [{ name: 'bgm', properties: [{ key: 'src', value: 'music.ogg' }] }] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('AudioStreamPlayer.new()');
    expect(gd).toContain('load("res://audio/music.ogg")');
    expect(gd).toContain('bgm.play()');
  });

  it('compiles spatial audio to AudioStreamPlayer3D', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        audio: [
          {
            name: 'sfx',
            properties: [
              { key: 'spatial', value: true },
              { key: 'src', value: 'boom.wav' },
            ],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('AudioStreamPlayer3D.new()');
  });

  it('compiles audio loop via finished.connect', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        audio: [{ name: 'loop_music', properties: [{ key: 'loop', value: true }] }] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('finished.connect');
    expect(gd).toContain('.play()');
  });

  // ─── Zones ────────────────────────────────────────────────────────────────

  it('compiles box zone to Area3D with BoxShape3D', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        zones: [
          {
            name: 'checkpoint',
            properties: [{ key: 'shape', value: 'box' }],
            handlers: [],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('Area3D.new()');
    expect(gd).toContain('CollisionShape3D.new()');
    expect(gd).toContain('BoxShape3D.new()');
    expect(gd).toContain('add_child(checkpoint)');
  });

  it('compiles sphere zone to SphereShape3D with radius', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        zones: [
          {
            name: 'pickup',
            properties: [
              { key: 'shape', value: 'sphere' },
              { key: 'radius', value: 3 },
            ],
            handlers: [],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('SphereShape3D.new()');
    expect(gd).toContain('shape.radius = 3');
  });

  it('compiles zone on_enter handler to body_entered.connect', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        zones: [
          {
            name: 'trap',
            properties: [{ key: 'shape', value: 'box' }],
            handlers: [{ event: 'on_enter' }],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('body_entered.connect');
  });

  it('compiles zone on_exit handler to body_exited.connect', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        zones: [
          {
            name: 'escape',
            properties: [{ key: 'shape', value: 'box' }],
            handlers: [{ event: 'on_exit' }],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('body_exited.connect');
  });

  // ─── Timelines ────────────────────────────────────────────────────────────

  it('autoplay timeline calls _play_ function', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        timelines: [{ name: 'cutscene', autoplay: true, loop: false, entries: [] }] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('_play_cutscene()');
    expect(gd).toContain('func _play_cutscene():');
  });

  it('timeline uses create_tween', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        timelines: [{ name: 'seq', autoplay: false, loop: false, entries: [] }] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('create_tween()');
  });

  it('looping timeline emits set_loops()', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        timelines: [{ name: 'anim', autoplay: false, loop: true, entries: [] }] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('tween.set_loops()');
  });

  // ─── Transitions ──────────────────────────────────────────────────────────

  it('compiles transition to change_scene_to_file', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        transitions: [
          {
            name: 'go_hub',
            properties: [{ key: 'target', value: 'hub_world' }],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('func go_hub():');
    expect(gd).toContain('get_tree().change_scene_to_file("res://scenes/hub_world.tscn")');
  });

  // ─── UI ───────────────────────────────────────────────────────────────────

  it('compiles UI to CanvasLayer with Label', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        ui: {
          elements: [
            {
              name: 'score_text',
              properties: [
                { key: 'type', value: 'text' },
                { key: 'text', value: 'Score' },
              ],
            },
          ],
        } as any,
      }),
      'test-token'
    );
    expect(gd).toContain('CanvasLayer.new()');
    expect(gd).toContain('Label.new()');
    expect(gd).toContain('.text = "Score"');
  });

  it('compiles progress UI element to ProgressBar', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        ui: {
          elements: [{ name: 'hp_bar', properties: [{ key: 'type', value: 'progress' }] }],
        } as any,
      }),
      'test-token'
    );
    expect(gd).toContain('ProgressBar.new()');
  });

  it('compiles panel UI element to Panel', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        ui: {
          elements: [{ name: 'overlay', properties: [{ key: 'type', value: 'panel' }] }],
        } as any,
      }),
      'test-token'
    );
    expect(gd).toContain('Panel.new()');
  });

  // ─── Environment ──────────────────────────────────────────────────────────

  it('compiles skybox environment to WorldEnvironment', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        environment: { properties: [{ key: 'skybox', value: 'sunset' }] } as any,
      }),
      'test-token'
    );
    expect(gd).toContain('WorldEnvironment.new()');
    expect(gd).toContain('BG_SKY');
  });

  // ─── Spatial Groups ───────────────────────────────────────────────────────

  it('compiles spatial group to Node3D', () => {
    const gd = new GodotCompiler().compile(
      makeComp({
        spatialGroups: [
          {
            name: 'village',
            objects: [],
            properties: [{ key: 'position', value: [10, 0, 10] }],
          },
        ] as any,
      }),
      'test-token'
    );
    expect(gd).toContain('# Spatial Group: village');
    expect(gd).toContain('Node3D.new()');
    expect(gd).toContain('position = Vector3(10, 0, 10)');
    expect(gd).toContain('self.add_child(village)');
  });

  // ─── Reset ────────────────────────────────────────────────────────────────

  it('resets between compile calls', () => {
    const compiler = new GodotCompiler();
    compiler.compile(makeComp({ name: 'Alpha' }), 'test-token');
    const gd = compiler.compile(makeComp({ name: 'Beta' }), 'test-token');
    expect(gd).toContain('"Beta"');
    expect(gd).not.toContain('"Alpha"');
  });
});
