import { describe, it, expect } from 'vitest';
import { parseHolo } from '../../parser/HoloCompositionParser';
import { compileToNextJS } from '../NextJSCompiler';

describe('NextJSCompiler', () => {
  it('compiles a minimal .holo page to valid TSX', () => {
    const result = parseHolo(`
      composition "TestPage" {
        object "Title" {
          @text
          content: "Hello World"
        }
      }
    `);

    expect(result.success).toBe(true);
    const compiled = compileToNextJS(result.ast!);

    expect(compiled.path).toBe('testpage/page.tsx');
    expect(compiled.code).toContain("'use client'");
    expect(compiled.code).toContain('TestPageComponent');
    expect(compiled.code).toContain("from 'react'");
  });

  it('generates state hooks from composition state', () => {
    const result = parseHolo(`
      composition "StatefulPage" {
        state {
          count: 0
          name: "test"
        }

        object "Counter" {
          @text { variant: "body", content: "Count" }
        }
      }
    `);

    expect(result.success).toBe(true);
    const compiled = compileToNextJS(result.ast!);

    expect(compiled.code).toContain('useState');
    expect(compiled.code).toContain('const [count, setCount] = useState(0)');
    expect(compiled.code).toContain('const [name, setName] = useState("test")');
  });

  it('handles @slot trait to mount external components', () => {
    // Note: HoloCompositionParser currently parses @slot without config.
    // The @slot trait config enrichment is a follow-up task.
    const result = parseHolo(`
      composition "EditorPage" {
        object "Editor" {
          @slot
        }
      }
    `);

    expect(result.success).toBe(true);
    const compiled = compileToNextJS(result.ast!);
    // @slot without config produces a plain div (config enrichment is Phase 0B follow-up)
    expect(compiled.code).toContain('EditorPageComponent');
  });

  it('generates layout with nested objects', () => {
    const result = parseHolo(`
      composition "Dashboard" {
        object "Shell" {
          @layout

          object "Sidebar" {
            @panel
            content: "Menu"
          }

          object "Main" {
            content: "Dashboard"
          }
        }
      }
    `);

    expect(result.success).toBe(true);
    const compiled = compileToNextJS(result.ast!);
    expect(compiled.code).toContain('DashboardComponent');
    // Nested objects should produce nested JSX
    expect(compiled.code).toContain('<div');
  });

  it('generates @generated header', () => {
    const result = parseHolo(`
      composition "Simple" {
        object "Box" {
          @theme { className: "p-4" }
        }
      }
    `);

    expect(result.success).toBe(true);
    const compiled = compileToNextJS(result.ast!);
    expect(compiled.code).toContain('@generated by HoloScript');
  });
});
