import { describe, it, expect, vi } from 'vitest';
import { parseHolo } from '../../parser/HoloCompositionParser';
import { NextJSCompiler } from '../NextJSCompiler';

vi.mock('../identity/AgentRBAC', async (importOriginal) => {
  const actual = await importOriginal<any>();
  return {
    ...actual,
    getRBAC: () => ({ checkAccess: () => ({ allowed: true }) }),
  };
});

describe('NextJSCompiler', () => {
  it('compiles a minimal .holo page to valid TSX', async () => {
    const result = parseHolo(`
      composition "TestPage" {
        object "Title" {
          @text
          content: "Hello World"
        }
      }
    `);

    expect(result.success).toBe(true);
    const compiler = new NextJSCompiler();
    const compiled = await compiler.compile(result.ast!, 'test-token');

    expect(compiled.path).toBe('testpage/page.tsx');
    expect(compiled.code).toContain("'use client'");
    expect(compiled.code).toContain('TestPageComponent');
    expect(compiled.code).toContain("from 'react'");
  });

  it('generates state hooks from composition state', async () => {
    const result = parseHolo(`
      composition "StatefulPage" {
        state {
          count: 0
          name: "test"
        }

        object "Counter" {
          @text { variant: "body", content: "Count" }
        }
      }
    `);

    expect(result.success).toBe(true);
    const compiler = new NextJSCompiler();
    const compiled = await compiler.compile(result.ast!, 'test-token');

    expect(compiled.code).toContain('useState');
    expect(compiled.code).toContain('const [count, setCount] = useState(0)');
    expect(compiled.code).toContain('const [name, setName] = useState("test")');
  });

  it('handles @slot trait with build-time slot registry metadata', async () => {
    const result = parseHolo(`
      composition "EditorPage" {
        object "PipelineWorkbench" {
          @slot
        }
      }
    `);

    expect(result.success).toBe(true);
    const compiler = new NextJSCompiler({
      slots: {
        PipelineWorkbench: {
          component: 'PipelineWorkbench',
          importPath: '@/components/pipeline/PipelineWorkbench',
        },
      },
    });
    const compiled = await compiler.compile(result.ast!, 'test-token');

    expect(compiled.code).toContain(
      "import { PipelineWorkbench } from '@/components/pipeline/PipelineWorkbench';"
    );
    expect(compiled.code).toContain('<PipelineWorkbench />');
  });

  it('generates layout with nested objects', async () => {
    const result = parseHolo(`
      composition "Dashboard" {
        object "Shell" {
          @layout

          object "Sidebar" {
            @panel
            content: "Menu"
          }

          object "Main" {
            content: "Dashboard"
          }
        }
      }
    `);

    expect(result.success).toBe(true);
    const compiler = new NextJSCompiler();
    const compiled = await compiler.compile(result.ast!, 'test-token');
    expect(compiled.code).toContain('DashboardComponent');
    // Nested objects should produce nested JSX
    expect(compiled.code).toContain('<div');
  });

  it('generates @generated header', async () => {
    const result = parseHolo(`
      composition "Simple" {
        object "Box" {
          @theme { className: "p-4" }
        }
      }
    `);

    expect(result.success).toBe(true);
    const compiler = new NextJSCompiler();
    const compiled = await compiler.compile(result.ast!, 'test-token');
    expect(compiled.code).toContain('@generated by HoloScript');
  });

  it('omits metadata export for client pages', async () => {
    const result = parseHolo(`
      composition "ClientMetaPage" {
        @page { route: "/client-meta", client: true }
        @metadata { title: "Client Page", description: "Should not export metadata" }

        object "Body" {
          @text
          content: "Hello"
        }
      }
    `);

    expect(result.success).toBe(true);
    const compiler = new NextJSCompiler();
    const compiled = await compiler.compile(result.ast!, 'test-token');

    expect(compiled.code).toContain("'use client'");
    expect(compiled.code).not.toContain('export const metadata');
  });

  // x4dx (2026-10-08): the invite-only refusal page must stay out of search
  // results. Until robots was emitted, that page could not be generated at all.
  it('emits title, description and robots metadata for a server page', async () => {
    const result = parseHolo(`
      composition "ServerMetaPage" {
        @page { route: "/server-meta", client: false }
        @metadata {
          title: "Server Page"
          description: "Ships its metadata"
          robots: { index: false }
        }

        object "Body" {
          @text { content: "Hello" }
        }
      }
    `);

    expect(result.success).toBe(true);
    const compiled = await new NextJSCompiler().compile(result.ast!, 'test-token');

    expect(compiled.code).not.toContain("'use client'");
    expect(compiled.code).toContain('export const metadata = {');
    expect(compiled.code).toContain('  title: "Server Page",');
    expect(compiled.code).toContain('  description: "Ships its metadata",');
    expect(compiled.code).toContain('  robots: {"index":false},');
  });

  it('passes a string robots value through and leaves robots out when absent', async () => {
    const withString = parseHolo(`
      composition "NoIndexPage" {
        @page { route: "/no-index", client: false }
        @metadata { title: "No Index", robots: "noindex" }
        object "Body" { @text { content: "x" } }
      }
    `);
    const without = parseHolo(`
      composition "PlainPage" {
        @page { route: "/plain", client: false }
        @metadata { title: "Plain" }
        object "Body" { @text { content: "x" } }
      }
    `);

    expect(withString.success).toBe(true);
    expect(without.success).toBe(true);
    const compiler = new NextJSCompiler();
    const a = await compiler.compile(withString.ast!, 'test-token');
    const b = await compiler.compile(without.ast!, 'test-token');

    expect(a.code).toContain('  robots: "noindex",');
    expect(b.code).toContain('  title: "Plain",');
    expect(b.code).not.toContain('robots');
  });

  it('carries robots on a redirect page too', async () => {
    const result = parseHolo(`
      composition "MovedPage" {
        @page { route: "/moved", redirect: "/new-home" }
        @metadata { title: "Moved", robots: { index: false, follow: true } }
      }
    `);

    expect(result.success).toBe(true);
    const compiled = await new NextJSCompiler().compile(result.ast!, 'test-token');

    expect(compiled.code).toContain('redirect("/new-home")');
    expect(compiled.code).toContain('  robots: {"index":false,"follow":true},');
  });
});
