/**
 * quest-world-emit splat-branch test — proves the `compile_to_quest` world emitter routes a Gaussian
 * splat source to Meta's native `com.meta.spatial.splat.Splat` component, and that splat-free worlds
 * are completely unaffected (no splat import, no @OptIn, byte-identical to the mesh/primitive path).
 *
 * This is the production seam for the sovereign $0 Quest splat capability: a `.holo` object that
 * declares a `.spz`/`.ply` source compiles to `Splat(Uri.parse("apk:///splats/<file>"))` instead of
 * the GLB/primitive `Mesh(...)` path. The asset is generated by
 * apps/quest-universal-qr-scanner/scripts/gen-test-orb-spz.mts (our own SpzCodec), bundled into the
 * Quest app, and rendered on-device by SplatFeature.
 *
 * The emitter is parsed through the REAL HoloCompositionParser (the same path generate-native.mts
 * uses), so the test exercises the actual production grammar → emit pipeline, not a hand-built AST.
 */
import { describe, it, expect } from 'vitest';
import { HoloCompositionParser } from '../../parser/HoloCompositionParser';
import { emitWorldSceneKt } from '../quest-world-emit';
import type { HoloComposition } from '../../parser/HoloCompositionTypes';

function parse(src: string): HoloComposition {
  const r = new HoloCompositionParser().parse(src);
  if (!r.success || !r.ast) {
    throw new Error('parse failed: ' + JSON.stringify(r.errors));
  }
  return r.ast;
}

describe('quest-world-emit — Gaussian splat branch', () => {
  it('emits Splat(Uri.parse("apk:///splats/...")) for a .spz source via the `splat:` key', () => {
    const comp = parse(`composition "SplatTest" {
      environment { backgroundColor: "#101018" }
      object "Orb" {
        splat: "test-orb.spz"
        position: [0, 1.4, -2]
      }
    }`);
    const kt = emitWorldSceneKt(comp, 'splat-test');

    // The native Splat component, pointing at the bundled apk asset.
    expect(kt).toContain('Splat(Uri.parse("apk:///splats/test-orb.spz"))');
    // Experimental API import + opt-in are injected because the world uses a splat.
    expect(kt).toContain('import com.meta.spatial.splat.Splat');
    expect(kt).toContain('import com.meta.spatial.splat.SpatialSDKExperimentalSplatAPI');
    expect(kt).toContain('@OptIn(SpatialSDKExperimentalSplatAPI::class)');
    // It must NOT fall back to a mesh/primitive for the splat object.
    expect(kt).not.toContain('Mesh(Uri.parse("apk:///models/test-orb.spz"))');
    // Transform still emitted alongside the splat.
    expect(kt).toContain('Transform(Pose(Vector3(0.0f, 1.4f, -2.0f)))');
  });

  it('routes a `.ply` source given via `source:` to the splat path (not the glb mesh path)', () => {
    const comp = parse(`composition "PlyTest" {
      object "Cloud" { source: "capture.ply" }
    }`);
    const kt = emitWorldSceneKt(comp, 'ply-test');
    expect(kt).toContain('Splat(Uri.parse("apk:///splats/capture.ply"))');
    expect(kt).not.toContain('apk:///models/capture.ply');
  });

  it('strips a leading directory from the splat source basename', () => {
    const comp = parse(`composition "DirTest" {
      object "Orb" { splat: "assets/clouds/test-orb.spz" }
    }`);
    const kt = emitWorldSceneKt(comp, 'dir-test');
    expect(kt).toContain('Splat(Uri.parse("apk:///splats/test-orb.spz"))');
  });

  it('still emits a glb Mesh for a .glb model source (splat branch does not hijack meshes)', () => {
    const comp = parse(`composition "GlbTest" {
      object "Statue" { model: "statue.glb" }
    }`);
    const kt = emitWorldSceneKt(comp, 'glb-test');
    expect(kt).toContain('Mesh(Uri.parse("apk:///models/statue.glb"))');
    expect(kt).not.toContain('com.meta.spatial.splat');
  });

  it('a splat-FREE world emits NO splat import and NO @OptIn (marketing worlds unaffected)', () => {
    const comp = parse(`composition "PlainTest" {
      environment { backgroundColor: "#160a2e" }
      object "Ground" { geometry: "plane" scale: [10, 10, 1] color: "#241046" }
      object "Orb" { geometry: "sphere" color: "#22d3ee" glow: true }
    }`);
    const kt = emitWorldSceneKt(comp, 'plain-test');
    expect(kt).not.toContain('com.meta.spatial.splat');
    expect(kt).not.toContain('@OptIn');
    expect(kt).not.toContain('Splat(');
    // Sanity: the normal mesh path is intact.
    expect(kt).toContain('Mesh(Uri.parse("mesh://sphere"))');
    expect(kt).toContain('Mesh(Uri.parse("mesh://box"))');
  });
});
