import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it, vi } from 'vitest';
import { SDKCompiler } from '../SDKCompiler';
import { parseHolo } from '../../parser/HoloCompositionParser';
import type { HoloComposition } from '../../parser/HoloCompositionTypes';
import { DialectRegistry } from '../DialectRegistry';

const fixturesDir = dirname(fileURLToPath(import.meta.url));

vi.mock('../identity/AgentRBAC', async (importOriginal) => {
  const actual = (await importOriginal()) as Record<string, unknown>;
  return {
    ...actual,
    getRBAC: () => ({ checkAccess: () => ({ allowed: true }) }),
  };
});

function parseRegistryContract(): HoloComposition {
  const source = readFileSync(
    resolve(fixturesDir, '../../../../partner-sdk/src/api/registry-client.contract.holo'),
    'utf8'
  );
  const result = parseHolo(source);
  expect(result.errors).toEqual([]);
  return result.ast as HoloComposition;
}

describe('SDKCompiler', () => {
  it('emits a typed TypeScript SDK from the RegistryClient service contract', () => {
    const compiler = new SDKCompiler({
      clientClassName: 'RegistryClient',
      packageName: '@holoscript/generated-registry-client',
    });
    const files = compiler.compile(parseRegistryContract(), 'test-token');

    expect(files['src/RegistryClient.ts']).toBeDefined();
    expect(files['src/sdk-runtime.ts']).toBeDefined();
    expect(files['sdk-compiler-receipt.json']).toBeDefined();

    const packageJson = JSON.parse(files['package.json']) as {
      license?: string;
      repository?: string;
      files: string[];
      exports: Record<string, unknown>;
    };
    expect(packageJson.license).toBeUndefined();
    expect(packageJson.repository).toBeUndefined();
    expect(packageJson.files).toEqual(['dist', 'README.md', 'sdk-compiler-receipt.json']);
    expect(packageJson.exports).toEqual({
      '.': {
        types: './dist/RegistryClient.d.ts',
        import: './dist/RegistryClient.js',
      },
      './sdk-compiler-receipt.json': './sdk-compiler-receipt.json',
    });

    const client = files['src/RegistryClient.ts'];
    expect(client).toContain('@generated by HoloScript SDKCompiler');
    expect(client).toContain("from './sdk-runtime.js'");
    expect(client).toContain('export interface PackageInfo');
    expect(client).toContain('details?: unknown;');
    expect(client).toContain('export interface DeprecateVersionRequest');
    expect(client).toContain('export interface SearchParams');
    expect(client).toContain('async getPackage(params: GetPackageParams');
    expect(client).toContain("SDKRuntime.interpolatePath('/packages/{name}', params)");
    expect(client).toContain('async deprecateVersion(');
    expect(client).toContain('body: DeprecateVersionRequest');
    expect(client).toContain('async getMyPackages(params?: GetMyPackagesParams');
    expect(client).toContain('SDKRuntime.pickQuery(params ?? {}, ["page","pageSize"])');
    expect(client).toContain("this.runtime.request<PackageInfo>('GET', path");
    expect(client).toContain("const DEFAULT_BASE_URL = 'https://mcp.holoscript.net/api/v1';");
    expect(client).toContain(
      'export { SDKRuntime, SDKAuthenticationError, SDKError, SDKRateLimitError }'
    );

    const runtime = files['src/sdk-runtime.ts'];
    expect(runtime).toContain('const SDK_AUTH_HEADERS');
    expect(runtime).toContain('holoKey?: string;');
    expect(runtime).toContain('SDK_SIGNATURE_PAYLOAD_TEMPLATE');
    expect(runtime).toContain('export class SDKRateLimitError extends SDKError');
    expect(runtime).toContain('export class SDKAuthenticationError extends SDKError');
    expect(runtime).toContain('SDKRuntime HMAC signing requires Web Crypto');
    expect(runtime).toContain('static interpolatePath(path: string, params: object)');
    expect(runtime).toContain('static pickQuery(params: object');

    const receipt = JSON.parse(files['sdk-compiler-receipt.json']) as {
      type: string;
      endpointCount: number;
      schemaCount: number;
      target: string;
      serviceBaseUrl: string;
      publication: {
        packageName: string;
        version: string;
        license?: string;
      };
      integrationSurfaces: {
        credential: string;
        routing: string;
        provenance: string;
        holoGate: string;
      };
      fanOut: { targets: string[] };
    };
    expect(receipt.type).toBe('SDKCompilerReceipt');
    expect(receipt.target).toBe('sdk:typescript');
    expect(receipt.serviceBaseUrl).toBe('https://mcp.holoscript.net/api/v1');
    expect(receipt.publication.packageName).toBe('@holoscript/generated-registry-client');
    expect(receipt.publication.version).toBeDefined();
    expect(receipt.publication.license).toBeUndefined();
    expect(receipt.endpointCount).toBe(11);
    expect(receipt.schemaCount).toBeGreaterThanOrEqual(10);
    expect(receipt.integrationSurfaces.credential).toContain('HoloKey-compatible');
    expect(receipt.integrationSurfaces.routing).toContain('UmbrellaRoute-compatible');
    expect(receipt.integrationSurfaces.provenance).toContain('triad-ready');
    expect(receipt.integrationSurfaces.holoGate).toContain('documentation umbrella only');
    expect(receipt.fanOut.targets).toContain('sdk:python');
  });

  it('fans the same contract AST out to python, react hooks, and connectors', () => {
    const contract = parseRegistryContract();

    const pythonFiles = new SDKCompiler({
      target: 'sdk:python',
      clientClassName: 'RegistryClient',
      packageName: 'holoscript-registry-client',
    }).compile(contract, 'test-token');
    expect(pythonFiles['holoscript_sdk/registry_client.py']).toContain('class RegistryClient:');
    expect(pythonFiles['holoscript_sdk/registry_client.py']).toContain('def get_package');
    expect(pythonFiles['holoscript_sdk/sdk_runtime.py']).toContain('holo_key');
    const pythonReceipt = JSON.parse(pythonFiles['sdk-compiler-receipt.json']) as {
      target: string;
      generatedFiles: string[];
      fanOut: { source: string };
    };
    expect(pythonReceipt.target).toBe('sdk:python');
    expect(pythonReceipt.generatedFiles).toContain('holoscript_sdk/registry_client.py');
    expect(pythonReceipt.fanOut.source).toContain('ServiceContractIR');

    const reactFiles = new SDKCompiler({
      target: 'sdk:react',
      clientClassName: 'RegistryClient',
      packageName: '@holoscript/generated-registry-react',
    }).compile(contract, 'test-token');
    expect(reactFiles['src/RegistryClient.ts']).toContain('@generated by HoloScript SDKCompiler');
    expect(reactFiles['src/useRegistryClient.tsx']).toContain("'use client';");
    expect(reactFiles['src/useRegistryClient.tsx']).toContain(
      "Parameters<RegistryClient['getPackage']>"
    );
    const reactReceipt = JSON.parse(reactFiles['sdk-compiler-receipt.json']) as {
      target: string;
    };
    expect(reactReceipt.target).toBe('sdk:react');

    const connectorFiles = new SDKCompiler({
      target: 'sdk:connectors',
      clientClassName: 'RegistryClient',
      packageName: '@holoscript/generated-registry-connector',
    }).compile(contract, 'test-token');
    expect(connectorFiles['src/RegistryConnector.ts']).toContain('extends ServiceConnector');
    expect(connectorFiles['src/RegistryConnector.ts']).toContain('registry_get_package');
    expect(connectorFiles['src/tools.ts']).toContain('createConnectorTools');
    const connectorReceipt = JSON.parse(connectorFiles['sdk-compiler-receipt.json']) as {
      target: string;
    };
    expect(connectorReceipt.target).toBe('sdk:connectors');
  });

  it('emits public package identity from the HoloScript service contract', () => {
    const parsed = parseHolo(`
composition "PublicImageService" {
  schema "ImageContract" {
    composition: string
  }

  endpoint "imageContract" {
    method: "GET"
    path: "/api/v1/images/contract"
    response_200: ImageContract
  }

  service "PublicImageAPI" {
    version: "1.0.0"
    base_url: "https://images.example.com"
    description: "HoloScript-authored public image API client"
    license: "MIT"
    repository: "https://github.com/example/public-image-service"
    homepage: "https://images.example.com/docs"
  }
}
`);
    expect(parsed.errors).toEqual([]);

    const files = new SDKCompiler({
      clientClassName: 'PublicImageClient',
      packageName: '@holoscript/image-client',
    }).compile(parsed.ast as HoloComposition, 'test-token');
    const packageJson = JSON.parse(files['package.json']) as {
      name: string;
      version: string;
      description: string;
      license: string;
      repository: string;
      homepage: string;
      files: string[];
      exports: Record<string, unknown>;
    };
    expect(packageJson).toMatchObject({
      name: '@holoscript/image-client',
      version: '1.0.0',
      description: 'HoloScript-authored public image API client',
      license: 'MIT',
      repository: 'https://github.com/example/public-image-service',
      homepage: 'https://images.example.com/docs',
    });
    expect(packageJson.files).toContain('sdk-compiler-receipt.json');
    expect(packageJson.exports).toHaveProperty('./sdk-compiler-receipt.json');

    const receipt = JSON.parse(files['sdk-compiler-receipt.json']) as {
      sourceComposition: string;
      publication: {
        packageName: string;
        version: string;
        description: string;
        license: string;
        repository: string;
        homepage: string;
        manifest: string;
      };
    };
    expect(receipt.sourceComposition).toBe('PublicImageService');
    expect(receipt.publication).toEqual({
      packageName: '@holoscript/image-client',
      version: '1.0.0',
      description: 'HoloScript-authored public image API client',
      license: 'MIT',
      repository: 'https://github.com/example/public-image-service',
      homepage: 'https://images.example.com/docs',
      manifest: 'package.json',
    });

    const reactFiles = new SDKCompiler({
      target: 'sdk:react',
      clientClassName: 'PublicImageClient',
      packageName: '@holoscript/image-react',
    }).compile(parsed.ast as HoloComposition, 'test-token');
    expect(JSON.parse(reactFiles['package.json'])).toMatchObject({
      description: 'HoloScript-authored public image API client',
      license: 'MIT',
      repository: 'https://github.com/example/public-image-service',
      homepage: 'https://images.example.com/docs',
      files: ['dist', 'README.md', 'sdk-compiler-receipt.json'],
    });

    const connectorFiles = new SDKCompiler({
      target: 'sdk:connectors',
      clientClassName: 'PublicImageClient',
      packageName: '@holoscript/image-connector',
    }).compile(parsed.ast as HoloComposition, 'test-token');
    expect(JSON.parse(connectorFiles['package.json'])).toMatchObject({
      description: 'HoloScript-authored public image API client',
      license: 'MIT',
      repository: 'https://github.com/example/public-image-service',
      homepage: 'https://images.example.com/docs',
      files: ['dist', 'README.md', 'sdk-compiler-receipt.json'],
    });

    const pythonFiles = new SDKCompiler({
      target: 'sdk:python',
      clientClassName: 'PublicImageClient',
      packageName: 'holoscript-image-client',
    }).compile(parsed.ast as HoloComposition, 'test-token');
    expect(pythonFiles['pyproject.toml']).toContain(
      'description = "HoloScript-authored public image API client"'
    );
    expect(pythonFiles['pyproject.toml']).toContain('license = { text = "MIT" }');
    expect(pythonFiles['pyproject.toml']).toContain(
      'Repository = "https://github.com/example/public-image-service"'
    );
    expect(pythonFiles['pyproject.toml']).toContain(
      'Homepage = "https://images.example.com/docs"'
    );
  });

  it('registers the sdk dialect for native compiler discovery', () => {
    expect(DialectRegistry.has('sdk')).toBe(true);
    const info = DialectRegistry.get('sdk');
    expect(info?.ansPath).toBe('/compile/runtime/sdk');
    expect(info?.supportedTraits).toContain('endpoint');
  });
});
