import { describe, it, expect, beforeEach, vi } from 'vitest';
import { UnityCompiler } from '../UnityCompiler';
import type { HoloComposition } from '../../parser/HoloCompositionTypes';

vi.mock('../identity/AgentRBAC', async (importOriginal) => {
  const actual = await importOriginal();
  return {
    ...actual,
    getRBAC: () => ({ checkAccess: () => ({ allowed: true }) }),
  };
});

function makeComposition(overrides: Partial<HoloComposition> = {}): HoloComposition {
  return { name: 'TestScene', objects: [], ...overrides } as HoloComposition;
}

describe('UnityCompiler', () => {
  let compiler: UnityCompiler;

  beforeEach(() => {
    compiler = new UnityCompiler();
  });

  // =========== Minimal output ===========

  it('compiles minimal composition to C#', () => {
    const cs = compiler.compile(makeComposition(), 'test-token');
    expect(cs).toContain('using UnityEngine');
    expect(cs).toContain('MonoBehaviour');
    expect(cs).toContain('Awake');
  });

  it('includes auto-generated header', () => {
    const cs = compiler.compile(makeComposition(), 'test-token');
    expect(cs).toContain('Auto-generated by HoloScript');
    expect(cs).toContain('TestScene');
  });

  // =========== Options ===========

  it('respects custom namespace', () => {
    const c = new UnityCompiler({ namespace: 'MyGame' });
    const cs = c.compile(makeComposition(), 'test-token');
    expect(cs).toContain('namespace MyGame');
  });

  it('respects custom className', () => {
    const c = new UnityCompiler({ className: 'MyScene' });
    const cs = c.compile(makeComposition(), 'test-token');
    expect(cs).toContain('class MyScene');
  });

  // =========== State → fields ===========

  it('compiles state to C# fields', () => {
    const comp = makeComposition({
      state: {
        properties: [
          { key: 'score', value: 0 },
          { key: 'active', value: true },
        ],
      },
    });
    const cs = compiler.compile(comp, 'test-token');
    expect(cs).toContain('score');
    expect(cs).toContain('active');
  });

  // =========== Objects ===========

  it('compiles objects into Awake body', () => {
    const comp = makeComposition({
      objects: [
        { name: 'cube', properties: [{ key: 'geometry', value: 'box' }], traits: [] },
      ] as any,
    });
    const cs = compiler.compile(comp, 'test-token');
    expect(cs).toContain('cube');
    expect(cs).toContain('GameObject');
  });

  it('handles sphere geometry', () => {
    const comp = makeComposition({
      objects: [
        { name: 'ball', properties: [{ key: 'geometry', value: 'sphere' }], traits: [] },
      ] as any,
    });
    const cs = compiler.compile(comp, 'test-token');
    expect(cs).toContain('ball');
  });

  // =========== Lights ===========

  it('compiles lights', () => {
    const comp = makeComposition({
      lights: [
        { name: 'sun', lightType: 'directional', properties: [{ key: 'intensity', value: 1.5 }] },
      ] as any,
    });
    const cs = compiler.compile(comp, 'test-token');
    expect(cs).toContain('Light');
  });

  // =========== Environment ===========

  it('compiles environment settings', () => {
    const comp = makeComposition({
      environment: { properties: [{ key: 'skybox', value: 'sunset' }] } as any,
    });
    const cs = compiler.compile(comp, 'test-token');
    expect(cs).toContain('RenderSettings');
  });

  // =========== Spatial groups ===========

  it('compiles spatial groups', () => {
    const comp = makeComposition({
      spatialGroups: [
        {
          name: 'group1',
          objects: [{ name: 'child', properties: [{ key: 'geometry', value: 'box' }], traits: [] }],
          properties: [],
        },
      ] as any,
    });
    const cs = compiler.compile(comp, 'test-token');
    expect(cs).toContain('group1');
  });

  // =========== Audio ===========

  it('compiles audio sources', () => {
    const comp = makeComposition({
      audio: [{ name: 'bgm', properties: [{ key: 'src', value: 'music.wav' }] }] as any,
    });
    const cs = compiler.compile(comp, 'test-token');
    expect(cs).toContain('AudioSource');
  });

  // =========== Multiple objects ===========

  it('compiles multiple objects', () => {
    const comp = makeComposition({
      objects: [
        { name: 'obj_a', properties: [{ key: 'geometry', value: 'box' }], traits: [] },
        { name: 'obj_b', properties: [{ key: 'geometry', value: 'sphere' }], traits: [] },
      ] as any,
    });
    const cs = compiler.compile(comp, 'test-token');
    expect(cs).toContain('obj_a');
    expect(cs).toContain('obj_b');
  });

  // =========== Reset between compilations ===========

  it('resets between compilations', () => {
    compiler.compile(makeComposition({ name: 'first' }), 'test-token');
    const cs = compiler.compile(makeComposition({ name: 'second' }), 'test-token');
    expect(cs).toContain('second');
  });
});
