import { describe, it, expect } from 'vitest';
import { parseHolo } from '../../parser/HoloCompositionParser';
import { Vector2DCompiler } from '../Vector2DCompiler';
import type { HoloComposition } from '../../parser/HoloCompositionTypes';

/**
 * Golden / regression test for Vector2DCompiler.
 *
 * Added 2026-06-14 as the missing byte-stability baseline (paper "Compile the Surface",
 * research/2026-06-14_paper-native-frontend-aaa-compile.md). The compiler had ZERO tests, so the
 * shared-emit refactor (factoring the primitive/radar emitters into vector2d/emit.ts) had nothing
 * to verify byte-identical against. This fixture exercises every emit path that was moved: radar
 * (rings/spokes/labels/facet/series) plus the line/circle/text primitives plus esc()/f1(). The
 * snapshot is the byte-identical guard.
 */

const FIXTURE = `@page({ route: "/test-vec" })
composition "TestVec" {
  object "radar" { kind: "radar" cx: 200 cy: 200 r: 140 max: 10 }
  object "axis_a" { kind: "axis" label: "Alpha" }
  object "axis_b" { kind: "axis" label: "Beta" facet: "X" }
  object "axis_c" { kind: "axis" label: "Gamma" }
  object "series_one" { kind: "series" name: "One" color: "#378ADD" values: "5,9,7" }
  object "ln" { kind: "line" x1: 0 y1: 0 x2: 10 y2: 10 stroke: "#000000" }
  object "cir" { kind: "circle" cx: 5 cy: 5 r: 3 fill: "#ffffff" }
  object "txt" { kind: "text" x: 1 y: 2 content: "Hi <there> & you" }
}
`;

function compileFixture(): string {
  const parsed = parseHolo(FIXTURE);
  if (!parsed.success || !parsed.ast) {
    throw new Error('fixture parse failed: ' + JSON.stringify(parsed.errors ?? []));
  }
  return new Vector2DCompiler().compile(parsed.ast as unknown as HoloComposition, {
    componentName: 'TestVec',
  }).code;
}

describe('Vector2DCompiler', () => {
  it('emits a byte-stable @generated React SVG component (golden)', () => {
    expect(compileFixture()).toMatchSnapshot();
  });

  it('is deterministic across repeated compiles', () => {
    expect(compileFixture()).toBe(compileFixture());
  });

  it('emits the generated header, a default export, and escapes text/markup', () => {
    const code = compileFixture();
    expect(code.startsWith('// @generated by HoloScript Vector2DCompiler')).toBe(true);
    expect(code).toContain('export default function TestVec()');
    // esc(): < > & are entity-encoded in emitted text content
    expect(code).toContain('Hi &lt;there&gt; &amp; you');
    // radar expands to <polygon> rings + series; facet axis emits the ⊥ marker
    expect(code).toContain('<polygon');
    expect(code).toContain('&#8869;');
    // primitives present
    expect(code).toContain('<line');
    expect(code).toContain('<circle');
  });
});
