import { TraitPlatformSupport, TraitMatrixEntry } from './types';

export const PLATFORM_KEYS: (keyof TraitPlatformSupport)[] = [
  'r3f',
  'gltf',
  'unity',
  'unreal',
  'babylon',
  'webxr',
  'arcore',
  'arkit',
];

export const PLATFORM_LABELS: Record<string, string> = {
  r3f: 'R3F',
  gltf: 'glTF',
  unity: 'Unity',
  unreal: 'Unreal',
  babylon: 'Babylon',
  webxr: 'WebXR',
  arcore: 'ARCore',
  arkit: 'ARKit',
};

export const CATEGORY_COLORS: Record<string, string> = {
  interaction: 'bg-blue-900/40 text-blue-300',
  visual: 'bg-purple-900/40 text-purple-300',
  physics: 'bg-orange-900/40 text-orange-300',
  audio: 'bg-pink-900/40 text-pink-300',
  networking: 'bg-cyan-900/40 text-cyan-300',
  intelligence: 'bg-emerald-900/40 text-emerald-300',
  xr: 'bg-indigo-900/40 text-indigo-300',
  animation: 'bg-amber-900/40 text-amber-300',
  accessibility: 'bg-teal-900/40 text-teal-300',
  other: 'bg-studio-panel text-studio-muted',
};

export const SAMPLE_TRAITS: TraitMatrixEntry[] = [
  {
    name: 'grabbable',
    category: 'interaction',
    platforms: {
      r3f: true,
      gltf: false,
      unity: true,
      unreal: true,
      babylon: true,
      webxr: true,
      arcore: false,
      arkit: false,
    },
    features: ['snap_to_hand', 'two_handed', 'haptic_feedback'],
    properties: [
      { name: 'snap_to_hand', type: 'boolean', required: false, default: true },
      { name: 'grab_distance', type: 'number', required: false, default: 0.5 },
      { name: 'throw_velocity', type: 'number', required: false, default: 1.0 },
    ],
    requires: [],
    conflicts: ['static'],
    coverage: { hasExample: true, hasTest: true, hasDoc: true },
  },
  {
    name: 'glowing',
    category: 'visual',
    platforms: {
      r3f: true,
      gltf: true,
      unity: true,
      unreal: true,
      babylon: true,
      webxr: true,
      arcore: true,
      arkit: true,
    },
    features: ['emissive_color', 'pulse_animation', 'intensity'],
    properties: [
      { name: 'color', type: 'string', required: false, default: '#ffffff' },
      { name: 'intensity', type: 'number', required: false, default: 1.0 },
      { name: 'pulse', type: 'boolean', required: false, default: false },
    ],
    requires: [],
    conflicts: [],
    coverage: { hasExample: true, hasTest: true, hasDoc: true },
  },
  {
    name: 'animated',
    category: 'animation',
    platforms: {
      r3f: true,
      gltf: true,
      unity: true,
      unreal: true,
      babylon: true,
      webxr: true,
      arcore: false,
      arkit: false,
    },
    features: ['keyframe', 'loop', 'blend'],
    properties: [
      { name: 'clip', type: 'string', required: true },
      { name: 'loop', type: 'boolean', required: false, default: true },
      { name: 'speed', type: 'number', required: false, default: 1.0 },
    ],
    requires: [],
    conflicts: [],
    coverage: { hasExample: true, hasTest: false, hasDoc: true },
  },
  {
    name: 'physics_body',
    category: 'physics',
    platforms: {
      r3f: true,
      gltf: false,
      unity: true,
      unreal: true,
      babylon: true,
      webxr: false,
      arcore: false,
      arkit: false,
    },
    features: ['rigidbody', 'collider', 'mass', 'friction'],
    properties: [
      { name: 'mass', type: 'number', required: false, default: 1.0 },
      { name: 'type', type: 'string', required: false, default: 'dynamic' },
      { name: 'friction', type: 'number', required: false, default: 0.5 },
      { name: 'restitution', type: 'number', required: false, default: 0.3 },
    ],
    requires: [],
    conflicts: [],
    coverage: { hasExample: true, hasTest: true, hasDoc: true },
  },
  {
    name: 'networked',
    category: 'networking',
    platforms: {
      r3f: true,
      gltf: false,
      unity: true,
      unreal: true,
      babylon: false,
      webxr: true,
      arcore: false,
      arkit: false,
    },
    features: ['sync_transform', 'ownership', 'interpolation'],
    properties: [
      { name: 'sync_rate', type: 'number', required: false, default: 20 },
      { name: 'interpolate', type: 'boolean', required: false, default: true },
      { name: 'ownership', type: 'string', required: false, default: 'server' },
    ],
    requires: [],
    conflicts: [],
    coverage: { hasExample: true, hasTest: false, hasDoc: false },
  },
  {
    name: 'interactive',
    category: 'interaction',
    platforms: {
      r3f: true,
      gltf: false,
      unity: true,
      unreal: true,
      babylon: true,
      webxr: true,
      arcore: true,
      arkit: true,
    },
    features: ['click', 'hover', 'focus', 'pointer_events'],
    properties: [
      { name: 'cursor', type: 'string', required: false, default: 'pointer' },
      { name: 'highlight_on_hover', type: 'boolean', required: false, default: true },
    ],
    requires: [],
    conflicts: [],
    coverage: { hasExample: true, hasTest: true, hasDoc: true },
  },
  {
    name: 'spatial_audio',
    category: 'audio',
    platforms: {
      r3f: true,
      gltf: false,
      unity: true,
      unreal: true,
      babylon: true,
      webxr: true,
      arcore: false,
      arkit: false,
    },
    features: ['3d_positioning', 'occlusion', 'reverb'],
    properties: [
      { name: 'src', type: 'string', required: true },
      { name: 'volume', type: 'number', required: false, default: 1.0 },
      { name: 'rolloff', type: 'number', required: false, default: 1.0 },
      { name: 'max_distance', type: 'number', required: false, default: 50 },
    ],
    requires: [],
    conflicts: [],
    coverage: { hasExample: false, hasTest: false, hasDoc: true },
  },
  {
    name: 'npc_behavior',
    category: 'intelligence',
    platforms: {
      r3f: true,
      gltf: false,
      unity: true,
      unreal: true,
      babylon: false,
      webxr: false,
      arcore: false,
      arkit: false,
    },
    features: ['patrol', 'dialogue', 'state_machine'],
    properties: [
      { name: 'behavior_tree', type: 'string', required: true },
      { name: 'personality', type: 'string', required: false },
      { name: 'aggression', type: 'number', required: false, default: 0.5 },
    ],
    requires: ['animated'],
    conflicts: [],
    coverage: { hasExample: true, hasTest: false, hasDoc: false },
  },
  {
    name: 'ar_anchor',
    category: 'xr',
    platforms: {
      r3f: false,
      gltf: false,
      unity: true,
      unreal: false,
      babylon: false,
      webxr: true,
      arcore: true,
      arkit: true,
    },
    features: ['surface_detection', 'persistence', 'cloud_anchor'],
    properties: [
      { name: 'anchor_type', type: 'string', required: false, default: 'plane' },
      { name: 'persistent', type: 'boolean', required: false, default: false },
    ],
    requires: [],
    conflicts: [],
    coverage: { hasExample: false, hasTest: false, hasDoc: true },
  },
  {
    name: 'material',
    category: 'visual',
    platforms: {
      r3f: true,
      gltf: true,
      unity: true,
      unreal: true,
      babylon: true,
      webxr: true,
      arcore: true,
      arkit: true,
    },
    features: ['pbr', 'textures', 'clearcoat', 'sheen', 'transmission'],
    properties: [
      { name: 'color', type: 'string', required: false, default: '#ffffff' },
      { name: 'roughness', type: 'number', required: false, default: 0.5 },
      { name: 'metalness', type: 'number', required: false, default: 0.0 },
      { name: 'emissive', type: 'string', required: false, default: '#000000' },
    ],
    requires: [],
    conflicts: [],
    coverage: { hasExample: true, hasTest: true, hasDoc: true },
  },
  {
    name: 'particles',
    category: 'visual',
    platforms: {
      r3f: true,
      gltf: false,
      unity: true,
      unreal: true,
      babylon: true,
      webxr: true,
      arcore: false,
      arkit: false,
    },
    features: ['emission_rate', 'lifetime', 'forces', 'color_over_life'],
    properties: [
      { name: 'count', type: 'number', required: false, default: 100 },
      { name: 'lifetime', type: 'number', required: false, default: 2.0 },
      { name: 'speed', type: 'number', required: false, default: 1.0 },
      { name: 'color', type: 'string', required: false, default: '#ffffff' },
    ],
    requires: [],
    conflicts: [],
    coverage: { hasExample: true, hasTest: false, hasDoc: true },
  },
  {
    name: 'a11y_narrate',
    category: 'accessibility',
    platforms: {
      r3f: true,
      gltf: false,
      unity: true,
      unreal: false,
      babylon: false,
      webxr: true,
      arcore: false,
      arkit: true,
    },
    features: ['screen_reader', 'spatial_description', 'alt_text'],
    properties: [
      { name: 'label', type: 'string', required: true },
      { name: 'description', type: 'string', required: false },
      { name: 'role', type: 'string', required: false, default: 'object' },
    ],
    requires: [],
    conflicts: [],
    coverage: { hasExample: false, hasTest: false, hasDoc: false },
  },
];
