// Auto-generated by HoloScript AndroidCompiler
// Source: composition "AndroidReference"
// Do not edit manually — regenerate from .holo source

package net.holoscript.android

import android.os.Bundle
import android.view.MotionEvent
import android.view.View
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.ViewModelProvider
import com.google.ar.core.*
import com.google.ar.core.exceptions.*
import com.google.ar.sceneform.*
import com.google.ar.sceneform.math.Vector3
import com.google.ar.sceneform.rendering.*
import com.google.ar.sceneform.ux.*
import java.util.concurrent.CompletableFuture

class GeneratedARSceneActivity : AppCompatActivity() {
    private lateinit var arFragment: ArFragment
    private lateinit var sceneState: SceneState
    private val placedNodes = mutableMapOf<String, TransformableNode>()
    
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_ar_scene)
        
        sceneState = ViewModelProvider(this)[SceneState::class.java]
        arFragment = supportFragmentManager.findFragmentById(R.id.ar_fragment) as ArFragment
        
        setupARSession()
        setupTapListener()
        setupUI()
    }
    
    private fun setupARSession() {
        arFragment.arSceneView.scene.addOnUpdateListener { frameTime ->
            val frame = arFragment.arSceneView.arFrame ?: return@addOnUpdateListener
            
            // Track planes
            for (plane in frame.getUpdatedTrackables(Plane::class.java)) {
                if (plane.trackingState == TrackingState.TRACKING) {
                    sceneState.onPlaneDetected(plane)
                }
            }
        }
    }
    
    private fun setupTapListener() {
        arFragment.setOnTapArPlaneListener { hitResult, plane, motionEvent ->
            if (plane.type != Plane.Type.HORIZONTAL_UPWARD_FACING) return@setOnTapArPlaneListener
            
            placeObject(hitResult)
        }
    }
    
    private fun placeObject(hitResult: HitResult) {
        val anchor = hitResult.createAnchor()
        val anchorNode = AnchorNode(anchor)
        anchorNode.setParent(arFragment.arSceneView.scene)
        
        // Create one renderable node per HoloScript object
        NodeFactory.createAnchor_cube(this) { renderable ->
            attachRenderableToAnchor(anchorNode, "anchor_cube", renderable, Vector3(0f, 0f, -1f), Vector3(0.2f, 0.2f, 0.2f))
        }
        NodeFactory.createTarget_sphere(this) { renderable ->
            attachRenderableToAnchor(anchorNode, "target_sphere", renderable, Vector3(0.3f, 0f, -1f), Vector3(0.1f, 0.1f, 0.1f))
        }
    }
    
    private fun attachRenderableToAnchor(
        anchorNode: AnchorNode,
        objectName: String,
        renderable: Renderable,
        localPosition: Vector3,
        localScale: Vector3
    ) {
        val transformableNode = TransformableNode(arFragment.transformationSystem)
        transformableNode.setParent(anchorNode)
        transformableNode.renderable = renderable
        transformableNode.localPosition = localPosition
        transformableNode.localScale = localScale
        transformableNode.select()
        
        val id = "$objectName-${java.util.UUID.randomUUID()}"
        placedNodes[id] = transformableNode
        
        // Setup interaction
        transformableNode.setOnTapListener { _, _ ->
            sceneState.onNodeTapped(id)
            animateNodeTap(transformableNode)
        }
        
        android.util.Log.d("HoloScript", "Placed object: $objectName as $id")
    }
    
    private fun animateNodeTap(node: TransformableNode) {
        val originalScale = node.localScale
        val scaledUp = Vector3(originalScale[0] * 1.2f, originalScale[1] * 1.2f, originalScale[2] * 1.2f)
        
        android.animation.ObjectAnimator.ofObject(
            node, "localScale",
            com.google.ar.sceneform.math.Vector3Evaluator(),
            originalScale, scaledUp, originalScale
        ).apply {
            duration = 200
            start()
        }
    }
    
    private fun setupUI() {
        findViewById<View>(R.id.reset_button)?.setOnClickListener {
            resetScene()
        }
    }
    
    private fun resetScene() {
        for (node in placedNodes.values) {
            node.anchor?.detach()
            node.setParent(null)
        }
        placedNodes.clear()
        
        sceneState.reset()
        Toast.makeText(this, "Scene reset", Toast.LENGTH_SHORT).show()
    }
    
    override fun onResume() {
        super.onResume()
        checkARCoreAvailability()
    }
    
    private fun checkARCoreAvailability() {
        val availability = ArCoreApk.getInstance().checkAvailability(this)
        if (availability.isTransient) {
            android.os.Handler(mainLooper).postDelayed({ checkARCoreAvailability() }, 200)
            return
        }
        if (!availability.isSupported) {
            Toast.makeText(this, "ARCore is not supported on this device", Toast.LENGTH_LONG).show()
            finish()
        }
    }
}