/**
 * generator.ts — Produces agent config files from ProjectDNA.
 *
 * Self-contained generators that mirror the Studio scaffolder templates
 * but are bundled into this CLI package with zero external dependencies.
 *
 * Generated file map:
 *   AGENTS.md                         → project root (universal)
 *   .cursorrules                      → project root (Cursor)
 *   .github/copilot-instructions.md   → project root (Copilot)
 *   GEMINI.md                         → project root (Gemini)
 *   .claude/CLAUDE.md                 → Claude Code
 *   .claude/NORTH_STAR.md             → Decision oracle
 *   .claude/MEMORY.md                 → Persistent memory
 *   team-connect.mjs                  → Multi-IDE coordination
 */

import type { ProjectDNA } from './scanner.js';

export interface GeneratedFile {
  /** Relative path from project root */
  path: string;
  /** File content */
  content: string;
  /** Human-readable description */
  description: string;
}

// ─── Shared helpers ────────────────────────────────────────────────────────

function testCmd(dna: ProjectDNA): string {
  if (dna.techStack.includes('vitest')) return dna.techStack.includes('pnpm') ? 'pnpm vitest' : 'npx vitest';
  if (dna.techStack.includes('jest')) return dna.techStack.includes('pnpm') ? 'pnpm jest' : 'npx jest';
  if (dna.languages.includes('py')) return 'pytest';
  if (dna.languages.includes('go')) return 'go test ./...';
  if (dna.languages.includes('rs')) return 'cargo test';
  return dna.techStack.includes('pnpm') ? 'pnpm test' : 'npm test';
}

function buildCmd(dna: ProjectDNA): string {
  if (dna.techStack.includes('pnpm')) return 'pnpm build';
  if (dna.techStack.includes('yarn')) return 'yarn build';
  if (dna.languages.includes('go')) return 'go build ./...';
  if (dna.languages.includes('rs')) return 'cargo build';
  if (dna.languages.includes('py')) return 'python -m build';
  return 'npm run build';
}

function lintCmd(dna: ProjectDNA): string {
  if (dna.techStack.includes('eslint')) return dna.techStack.includes('pnpm') ? 'pnpm lint' : 'npx eslint .';
  if (dna.languages.includes('py')) return 'ruff check .';
  if (dna.languages.includes('go')) return 'golangci-lint run';
  if (dna.languages.includes('rs')) return 'cargo clippy';
  return dna.techStack.includes('pnpm') ? 'pnpm lint' : 'npm run lint';
}

function stackConventions(dna: ProjectDNA): string {
  const rules: string[] = [];
  if (dna.techStack.includes('typescript')) {
    rules.push('- TypeScript strict mode. No `any` — use `unknown`.');
    rules.push('- Explicit return types on exported functions.');
    rules.push('- `.tsx` for JSX files.');
  }
  if (dna.languages.includes('py')) {
    rules.push('- Type hints on all public functions.');
    rules.push('- Format: black. Lint: ruff.');
  }
  if (dna.languages.includes('go')) {
    rules.push('- Always check errors. No `_` discards.');
    rules.push('- `context.Context` as first I/O parameter.');
  }
  if (dna.languages.includes('rs')) {
    rules.push('- No `unwrap()` in production — use `?` or explicit error handling.');
  }
  if (dna.frameworks.includes('next.js')) {
    rules.push('- Server Components by default. `\'use client\'` only when needed.');
  }
  if (dna.frameworks.includes('react') && !dna.frameworks.includes('next.js')) {
    rules.push('- Functional components only. Co-locate tests.');
  }
  rules.push('- Never commit secrets. Use `.env`.');
  rules.push('- `git add <file>` only. Never `git add -A`.');
  return rules.join('\n');
}

// ─── AGENTS.md ─────────────────────────────────────────────────────────────

function generateAgentsMd(dna: ProjectDNA): string {
  const isMonorepo = dna.packageCount > 1;
  return `# AGENTS.md — ${dna.name}

> Universal agent instructions. Read by Codex, Copilot, Cursor, Windsurf, Amp, Devin, Continue.
> Generated by [HoloScript](https://holoscript.net) — upgrade at [studio.holoscript.net](https://studio.holoscript.net)

## Project

- **Languages**: ${dna.languages.join(', ') || 'not detected'}
- **Frameworks**: ${dna.frameworks.join(', ') || 'none'}
- **Structure**: ${isMonorepo ? `Monorepo (${dna.packageCount} packages)` : 'Single package'}

## Commands

| Action | Command |
|--------|---------|
| Build | \`${buildCmd(dna)}\` |
| Test | \`${testCmd(dna)}\` |
| Lint | \`${lintCmd(dna)}\` |

## Conventions

${stackConventions(dna)}

## Workflow

1. **Read** before editing — never modify blind
2. **Test** after changes — \`${testCmd(dna)}\`
3. **Commit** with explicit staging — \`git add <file>\`
4. **Lint** before committing — \`${lintCmd(dna)}\`

## Decision Defaults

- New file or existing? **Existing** first
- Ask user or decide? **Decide**, then explain
- Test failing? **Fix** if yours, **note** if pre-existing
- New dependency? **Use existing first**, ask before adding runtime deps

## Skills Reference (Read Before Working)

Skills are concentrated knowledge files for each domain. **Read the relevant skill before working.**

| Domain | Skill File | What It Knows |
|--------|-----------|---------------|
| Project work | \`.claude/skills/dev/SKILL.md\` | Build, test, ship workflow |
| Code scanning | \`.claude/skills/scan/SKILL.md\` | Markers, health, coverage |
| Documentation | \`.claude/skills/documenter/SKILL.md\` | Voice, staleness, versions |
| Code review | \`.claude/skills/review/SKILL.md\` | Conventions, security, perf |

**Claude Code**: Invoke via Skill tool (\`/dev\`, \`/scan\`). Skills fork context — saves your main window.
**All other agents**: Read directly — \`cat .claude/skills/<name>/SKILL.md\`.

## Additional Features

- Decision Oracle: \`.claude/NORTH_STAR.md\`
- Persistent Memory: \`.claude/MEMORY.md\`
- Team Coordination: \`team-connect.mjs\`
- Upgrade: \`npx @holoscript/agent-setup --upgrade\` or [studio.holoscript.net](https://studio.holoscript.net)
`;
}

// ─── .cursorrules ──────────────────────────────────────────────────────────

function generateCursorRules(dna: ProjectDNA): string {
  const isMonorepo = dna.packageCount > 1;
  return `# ${dna.name} — Cursor Rules

You are working on ${dna.name}${isMonorepo ? `, a monorepo with ${dna.packageCount} packages` : ''}.
Languages: ${dna.languages.join(', ') || 'not detected'}.
Frameworks: ${dna.frameworks.join(', ') || 'none'}.

## Conventions

${stackConventions(dna)}

## Workflow

- Read files before editing.
- Test: \`${testCmd(dna)}\`
- Lint: \`${lintCmd(dna)}\`
- Git: explicit \`git add <file>\`, never \`git add -A\`

## Decisions

- New file or existing? Existing first.
- Ask user or decide? Decide, then explain.
- New dependency? Use existing first.
- Test failing? Fix if yours, note if pre-existing.
`;
}

// ─── copilot-instructions.md ───────────────────────────────────────────────

function generateCopilotInstructions(dna: ProjectDNA): string {
  const isMonorepo = dna.packageCount > 1;
  return `# Copilot Instructions — ${dna.name}

## Project

${dna.name}${isMonorepo ? ` (monorepo, ${dna.packageCount} packages)` : ''}.
Languages: ${dna.languages.join(', ') || 'not detected'}.
Frameworks: ${dna.frameworks.join(', ') || 'none'}.

## Commands

- Build: \`${buildCmd(dna)}\`
- Test: \`${testCmd(dna)}\`
- Lint: \`${lintCmd(dna)}\`

## Conventions

${stackConventions(dna)}

## Workflow

1. Read relevant files before changes
2. Test after changes: \`${testCmd(dna)}\`
3. Lint before commit: \`${lintCmd(dna)}\`
4. Commit with descriptive messages, explicit \`git add <file>\`
`;
}

// ─── GEMINI.md ─────────────────────────────────────────────────────────────

function generateGeminiMd(dna: ProjectDNA): string {
  const isMonorepo = dna.packageCount > 1;
  return `# GEMINI.md — ${dna.name}

## Project

${dna.name} — ${isMonorepo ? `monorepo (${dna.packageCount} packages)` : 'single package'}.
Languages: ${dna.languages.join(', ') || 'not detected'}.
Frameworks: ${dna.frameworks.join(', ') || 'none'}.

## Commands

- Build: \`${buildCmd(dna)}\`
- Test: \`${testCmd(dna)}\`
- Lint: \`${lintCmd(dna)}\`

## Conventions

${stackConventions(dna)}

## Rules

1. Read files before editing.
2. Prefer editing existing files.
3. Never commit secrets.
4. Git: \`git add <file>\` only.
5. Test after changes.

## Oracle

Check \`.claude/NORTH_STAR.md\` and \`.claude/MEMORY.md\` before asking the user.
`;
}

// ─── CLAUDE.md ─────────────────────────────────────────────────────────────

function generateClaudeMd(dna: ProjectDNA): string {
  return `# ${dna.name} — Agent Instructions

## Project Overview
- **Repository**: ${dna.repoUrl}
- **Languages**: ${dna.languages.join(', ') || 'not detected'}
- **Frameworks**: ${dna.frameworks.join(', ') || 'none'}
- **Stack**: ${dna.techStack.join(', ') || 'minimal'}

## Oracle & Memory

Before asking the user architectural questions, consult:
1. \`NORTH_STAR.md\` — Decision trees for common choices
2. \`MEMORY.md\` — Persistent project knowledge

Only ask the user for: novel features with no precedent, budget decisions, destructive operations.

## Build & Test Commands

- **Build**: \`${buildCmd(dna)}\`
- **Test**: \`${testCmd(dna)}\`
- **Lint**: \`${lintCmd(dna)}\`

## Conventions

${stackConventions(dna)}
- Prefer editing existing files over creating new ones.
- Read files before editing. Concurrent reads, serial mutations.

## Agent Workflow

1. **Understand** — Read relevant files before making changes
2. **Plan** — Identify files to touch and blast radius
3. **Build** — Write code, prefer existing files over new ones
4. **Test** — Run tests. Fix failures before committing.
5. **Commit** — Sectioned commits by logical group. Explicit \`git add\`.

## Session Hygiene

- End sessions with a summary and next steps.
- Update MEMORY.md with new persistent facts.
- Keep context lean.
`;
}

// ─── NORTH_STAR.md ─────────────────────────────────────────────────────────

function generateNorthStar(dna: ProjectDNA): string {
  const isMonorepo = dna.packageCount > 1;
  return `# North Star Oracle — ${dna.name}

**Purpose**: Answer questions that would otherwise cause an IDE agent to stall.

## Quick Decision Defaults

- New file or existing? **Existing** (add to closest relevant file)
- Commit now? **Yes** if you completed a coherent unit and tests pass
- Test failing? **Fix** if yours, **skip** if pre-existing
- Git staging? **ALWAYS explicit paths**, never \`git add -A\`
- Ask user or decide? **Decide**, then tell user what you decided
${isMonorepo ? `- Which package? **The one closest to the feature**\n` : ''}
## Decision Trees

### DT-1: New file or existing?

\`\`\`
Is it a new utility function?
  YES → Add to closest existing utility file
Is it a new API endpoint?
  YES → Add to existing router or create in routes/
Everything else → Prefer existing files.
\`\`\`

### DT-2: When to commit?

\`\`\`
Completed a coherent unit? → Commit
Tests pass? → Safe to commit
Tests fail? → Fix first
\`\`\`

### DT-3: Test failing?

\`\`\`
Test runner: ${testCmd(dna)}

In code I changed? → Fix it
Pre-existing failure? → Skip, note in commit
Flaky? → Note it, move on
\`\`\`

### DT-4: Error recovery

\`\`\`
Build fails? → Read error, check types/imports/config
Test fails? → Read assertion, fix code or update test
Git conflict? → Read both sides, keep both intents, re-test
Unknown? → Search codebase for error, then ask user
\`\`\`
`;
}

// ─── MEMORY.md ─────────────────────────────────────────────────────────────

function generateMemory(dna: ProjectDNA): string {
  const isMonorepo = dna.packageCount > 1;
  return `# ${dna.name} — Agent Memory

## Architecture
- **Type**: ${isMonorepo ? `Monorepo (${dna.packageCount} packages)` : 'Single package'}
- **Languages**: ${dna.languages.join(', ') || 'not detected'}
- **Frameworks**: ${dna.frameworks.join(', ') || 'none'}
- **Build**: \`${buildCmd(dna)}\`
- **Test**: \`${testCmd(dna)}\`

## Key Patterns

_Agents will populate this section as they learn about the codebase._

## Known Issues

_Agents will track recurring issues here._

## Session Log

| Date | Agent | Summary |
|------|-------|---------|
| _setup_ | agent-setup | Initial scaffold via \`npx @holoscript/agent-setup\` |
`;
}

// ─── team-connect.mjs ──────────────────────────────────────────────────────

function generateTeamConnect(): string {
  return `#!/usr/bin/env node
/**
 * team-connect.mjs — Multi-IDE agent coordination bridge.
 *
 * Connects any AI agent (Claude, Copilot, Gemini, Cursor, Codex, Devin)
 * to a shared team board for coordination across IDEs.
 *
 * Usage:
 *   node team-connect.mjs --once --name=copilot --ide=vscode
 *   node team-connect.mjs --daemon --name=gemini --ide=antigravity
 *   node team-connect.mjs --report --name=agent --ide=ide-type
 *   node team-connect.mjs --board
 *
 * Requires HOLOMESH_API_KEY and HOLOMESH_TEAM_ID in .env
 *
 * For full team features, upgrade at: https://studio.holoscript.net
 */

import fs from 'node:fs';
import path from 'node:path';

// ─── Config ────────────────────────────────────────────────────────────────

const ENV_PATHS = [
  path.join(process.cwd(), '.env'),
  path.join(process.env.HOME || process.env.USERPROFILE || '', '.ai-ecosystem', '.env'),
];

function loadEnv() {
  for (const envPath of ENV_PATHS) {
    if (fs.existsSync(envPath)) {
      const content = fs.readFileSync(envPath, 'utf-8');
      for (const line of content.split('\\n')) {
        const match = line.match(/^([A-Z_]+)=(.*)$/);
        if (match && !process.env[match[1]]) {
          process.env[match[1]] = match[2].replace(/^["']|["']$/g, '');
        }
      }
      break;
    }
  }
}

loadEnv();

const API_BASE = process.env.HOLOMESH_API_URL || 'https://mcp.holoscript.net/api/holomesh';
const API_KEY = process.env.HOLOMESH_API_KEY || '';
const TEAM_ID = process.env.HOLOMESH_TEAM_ID || '';

// ─── Args ──────────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const flags = Object.fromEntries(
  args.filter(a => a.startsWith('--')).map(a => {
    const [k, v] = a.slice(2).split('=');
    return [k, v || true];
  })
);

const agentName = flags.name || 'agent';
const ideType = flags.ide || 'unknown';
const mode = flags.once ? 'once' : flags.daemon ? 'daemon' : flags.report ? 'report' : flags.board ? 'board' : 'once';

// ─── API helpers ───────────────────────────────────────────────────────────

async function api(method, endpoint, body) {
  if (!API_KEY || !TEAM_ID) {
    console.log('[team-connect] Missing HOLOMESH_API_KEY or HOLOMESH_TEAM_ID in .env');
    console.log('[team-connect] Get credentials at: https://studio.holoscript.net/start');
    return null;
  }
  try {
    const res = await fetch(\`\${API_BASE}/team/\${TEAM_ID}\${endpoint}\`, {
      method,
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': API_KEY,
      },
      body: body ? JSON.stringify(body) : undefined,
    });
    if (!res.ok) return null;
    return res.json();
  } catch {
    return null;
  }
}

// ─── Commands ──────────────────────────────────────────────────────────────

async function heartbeat() {
  return api('POST', '/presence', { agent: agentName, ide: ideType, status: 'active' });
}

async function readBoard() {
  const board = await api('GET', '/board');
  if (!board) return null;
  console.log('\\n=== TEAM BOARD ===');
  const tasks = board.tasks || board.items || [];
  const open = tasks.filter(t => t.status === 'open');
  const claimed = tasks.filter(t => t.status === 'claimed' || t.status === 'in-progress');
  const done = tasks.filter(t => t.status === 'done');
  console.log(\`Open: \${open.length} | Claimed: \${claimed.length} | Done: \${done.length}\`);
  for (const t of open.slice(0, 5)) {
    console.log(\`  [\${t.priority || '-'}] \${t.title}\`);
  }
  return board;
}

async function readMessages() {
  const msgs = await api('GET', '/messages');
  if (!msgs || !msgs.length) return;
  console.log('\\n=== INBOX ===');
  for (const m of msgs.slice(0, 5)) {
    console.log(\`  [\${m.from}] \${m.text || m.content || ''}\`);
  }
}

async function run() {
  if (mode === 'board') {
    await readBoard();
    return;
  }

  // Heartbeat
  await heartbeat();
  console.log(\`[team-connect] \${agentName}@\${ideType} connected\`);

  // Read board + messages
  await readBoard();
  await readMessages();

  if (mode === 'daemon') {
    // Heartbeat loop
    setInterval(() => heartbeat(), 60_000);
    setInterval(async () => {
      await readBoard();
      await readMessages();
    }, 300_000);
    console.log('[team-connect] Daemon mode — heartbeat every 60s, refresh every 5m');
  }

  if (mode === 'report') {
    // Post session summary
    await api('POST', '/messages', {
      from: agentName,
      type: 'handoff',
      text: \`Session end from \${agentName}@\${ideType}. Check git log for details.\`,
    });
    console.log('[team-connect] Session report posted');
  }
}

run().catch(err => {
  console.error('[team-connect] Error:', err.message);
  process.exit(1);
});
`;
}

// ─── Public API ────────────────────────────────────────────────────────────

export function generateAllFiles(dna: ProjectDNA): GeneratedFile[] {
  return [
    {
      path: 'AGENTS.md',
      content: generateAgentsMd(dna),
      description: 'Universal agent instructions (Codex, Copilot, Cursor, Windsurf, Amp, Devin)',
    },
    {
      path: '.cursorrules',
      content: generateCursorRules(dna),
      description: 'Cursor IDE agent instructions',
    },
    {
      path: '.github/copilot-instructions.md',
      content: generateCopilotInstructions(dna),
      description: 'GitHub Copilot instructions',
    },
    {
      path: 'GEMINI.md',
      content: generateGeminiMd(dna),
      description: 'Gemini CLI / Code Assist instructions',
    },
    {
      path: '.claude/CLAUDE.md',
      content: generateClaudeMd(dna),
      description: 'Claude Code project instructions',
    },
    {
      path: '.claude/NORTH_STAR.md',
      content: generateNorthStar(dna),
      description: 'Decision oracle — prevents agent stalls',
    },
    {
      path: '.claude/MEMORY.md',
      content: generateMemory(dna),
      description: 'Persistent cross-session memory',
    },
    {
      path: 'team-connect.mjs',
      content: generateTeamConnect(),
      description: 'Multi-IDE agent coordination bridge',
    },
  ];
}
