/**
 * @holoscript/alphafold-plugin v1.1.0
 * AlphaFold protein structure prediction for HoloScript
 *
 * Traits:
 *   @protein_structure  — Define a protein from amino acid sequence
 *   @binding_site       — Mark a ligand binding pocket on a structure
 *   @confidence_map     — Visualise per-residue pLDDT confidence as a heatmap
 *
 * @packageDocumentation
 */

// ---------------------------------------------------------------------------
// Config & result interfaces
// ---------------------------------------------------------------------------

export interface AlphaFoldPredictionConfig {
  sequence: string;
  job_name?: string;
  mode?: 'api' | 'local';
  num_models?: number;
  use_templates?: boolean;
}

export interface AlphaFoldMultimerConfig {
  sequences: string[];
  stoichiometry?: number[];
  job_name?: string;
}

export interface AlphaFoldResult {
  status: 'success' | 'failed';
  pdb_data?: string;
  confidence_scores?: number[];
  mean_plddt?: number;
  pae_data?: number[][];
  job_id?: string;
  error?: string;
}

// ---------------------------------------------------------------------------
// Domain trait interfaces
// ---------------------------------------------------------------------------

/** @protein_structure trait — a protein defined by its amino acid sequence */
export interface ProteinStructureTrait {
  trait: 'protein_structure';
  sequence: string;
  name?: string;
  pdb_data?: string;
  confidence?: number;
}

/** @binding_site trait — marks a ligand binding pocket */
export interface BindingSiteTrait {
  trait: 'binding_site';
  residues: number[];
  ligand?: string;
  affinity_nm?: number;
}

/** @confidence_map trait — per-residue pLDDT heatmap overlay */
export interface ConfidenceMapTrait {
  trait: 'confidence_map';
  scores: number[];
  colorScheme?: 'rainbow' | 'blue_red' | 'viridis';
  threshold?: number;
}

export type AlphaFoldTrait = ProteinStructureTrait | BindingSiteTrait | ConfidenceMapTrait;

// ---------------------------------------------------------------------------
// Compile target
// ---------------------------------------------------------------------------

export interface AlphaFoldCompileOptions {
  format?: 'pdb' | 'molstar_script' | 'holo';
}

/**
 * Compile a set of AlphaFold traits into a target representation.
 *
 * - `pdb`            — minimal PDB with REMARK lines (default)
 * - `molstar_script` — Mol* viewer JavaScript snippet
 * - `holo`           — HoloScript .holo composition
 */
export function compile(traits: AlphaFoldTrait[], opts: AlphaFoldCompileOptions = {}): string {
  const format = opts.format ?? 'pdb';

  switch (format) {
    case 'pdb':
      return compileToPdb(traits);
    case 'molstar_script':
      return compileToMolstar(traits);
    case 'holo':
      return compileToHolo(traits);
    default:
      throw new Error(`Unsupported format: ${format as string}`);
  }
}

function compileToPdb(traits: AlphaFoldTrait[]): string {
  const lines: string[] = ['HEADER    HOLOSCRIPT ALPHAFOLD PLUGIN'];

  for (const t of traits) {
    if (t.trait === 'protein_structure') {
      lines.push(`REMARK 100 PROTEIN ${t.name ?? 'unnamed'}`);
      lines.push(`REMARK 100 SEQUENCE ${t.sequence}`);
      if (t.pdb_data) {
        lines.push(t.pdb_data.trim());
      } else {
        // Generate placeholder ATOM records (Ca-only backbone)
        for (let i = 0; i < t.sequence.length; i++) {
          const x = (i * 3.8).toFixed(3).padStart(8);
          const y = '0.000'.padStart(8);
          const z = '0.000'.padStart(8);
          const res = t.sequence[i];
          lines.push(
            `ATOM  ${String(i + 1).padStart(5)}  CA  ${res}   A${String(i + 1).padStart(4)}    ${x}${y}${z}  1.00  0.00           C`
          );
        }
      }
    } else if (t.trait === 'binding_site') {
      lines.push(`REMARK 200 BINDING_SITE residues=${t.residues.join(',')}`);
      if (t.ligand) lines.push(`REMARK 200 LIGAND ${t.ligand}`);
    } else if (t.trait === 'confidence_map') {
      lines.push(`REMARK 300 CONFIDENCE_MAP len=${t.scores.length}`);
    }
  }

  lines.push('END');
  return lines.join('\n');
}

function compileToMolstar(traits: AlphaFoldTrait[]): string {
  const lines: string[] = [
    '// Mol* viewer script — generated by @holoscript/alphafold-plugin',
    'import { PluginContext } from "molstar/lib/mol-plugin/context";',
    '',
  ];

  for (const t of traits) {
    if (t.trait === 'protein_structure') {
      lines.push(`// Load protein: ${t.name ?? 'unnamed'}`);
      lines.push(`await plugin.loadStructureFromData(pdbData, "pdb");`);
    } else if (t.trait === 'confidence_map') {
      const scheme = t.colorScheme ?? 'rainbow';
      lines.push(`// Apply confidence coloring (${scheme})`);
      lines.push(`await plugin.applyColorTheme("plddt-confidence", { scheme: "${scheme}" });`);
    } else if (t.trait === 'binding_site') {
      lines.push(`// Highlight binding site residues`);
      lines.push(`await plugin.selectResidues([${t.residues.join(', ')}]);`);
    }
  }

  return lines.join('\n');
}

function compileToHolo(traits: AlphaFoldTrait[]): string {
  const lines: string[] = ['composition "AlphaFoldScene" {'];

  for (const t of traits) {
    if (t.trait === 'protein_structure') {
      const name = t.name ?? 'Protein';
      lines.push(`  object "${name}" @protein_structure {`);
      lines.push(`    sequence: "${t.sequence}"`);
      if (t.confidence !== undefined) {
        lines.push(`    confidence: ${t.confidence}`);
      }
      lines.push('  }');
    } else if (t.trait === 'binding_site') {
      lines.push(`  object "BindingSite" @binding_site {`);
      lines.push(`    residues: [${t.residues.join(', ')}]`);
      if (t.ligand) lines.push(`    ligand: "${t.ligand}"`);
      lines.push('  }');
    } else if (t.trait === 'confidence_map') {
      lines.push(`  object "ConfidenceOverlay" @confidence_map {`);
      lines.push(`    colorScheme: "${t.colorScheme ?? 'rainbow'}"`);
      lines.push('  }');
    }
  }

  lines.push('}');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

export const VERSION = '1.1.0';

export type {
  AlphaFoldPredictionConfig as PredictionConfig,
  AlphaFoldMultimerConfig as MultimerConfig,
  AlphaFoldResult as Result,
};

export default {
  VERSION,
  compile,
};
