import { CdpEvmWalletProvider } from './CdpEvmWalletProvider.js';

type WalletProvider = {
  getAddress(): string;
  signMessage(message: string): Promise<string>;
  getName(): string;
  getNetwork(): { networkId: string };
};

function createMockWalletProvider(networkId: string): WalletProvider {
  return {
    getAddress: () =>
      '0x' +
      Array.from({ length: 40 }, () => Math.floor(Math.random() * 16).toString(16)).join(''),
    signMessage: async (_msg: string) => '0xabcsignature123',
    getName: () => 'MockCdpWalletProvider',
    getNetwork: () => ({ networkId }),
  };
}

/**
 * AgentWalletService
 *
 * Provides financial sovereignty to HoloScript AI Instances by granting them
 * a native Base L2 wallet leveraging Coinbase's AgentKit SDK.
 *
 * Agents can use this service to:
 * - Hold and receive funds (ETH, USDC)
 * - Pay HTTP 402 "Payment Required" M2M Marketplace endpoints
 * - Automatically route gasless transactions via Coinbase CDP
 */
export class AgentWalletService {
  private walletProvider: WalletProvider | null = null;
  public walletAddress: string | null = null;

  constructor(private networkId: string = 'base-sepolia') {}

  /**
   * Initializes the autonomous wallet.
   * Uses existing generic variables or provisions a new wallet via CDP.
   */
  async initialize(): Promise<string> {
    try {
      const apiKeyId = process.env.CDP_API_KEY_NAME ?? process.env.CDP_API_KEY_ID;
      const apiKeySecret = process.env.CDP_API_KEY_SECRET;
      const walletSecret = process.env.CDP_WALLET_SECRET;

      if (apiKeyId && apiKeySecret && walletSecret) {
        this.walletProvider = await CdpEvmWalletProvider.configureWithWallet({
          apiKeyId,
          apiKeySecret,
          walletSecret,
          networkId: this.networkId,
        });
      } else {
        // Keep local tests and offline development free of external custody.
        this.walletProvider = createMockWalletProvider(this.networkId);
      }

      this.walletAddress = this.walletProvider.getAddress();

      console.info(`[AgentWalletService] Wallet initialized: ${this.walletAddress}`);
      return this.walletAddress as string;
    } catch (e) {
      console.error('[AgentWalletService] Initialization failed!', {
        error: e instanceof Error ? e.message : String(e),
      });
      throw e;
    }
  }

  /**
   * Processes an HTTP 402 Payment Challenge generated by the marketplace
   */
  async processPaymentChallenge(challengeObj: any): Promise<any> {
    if (!this.walletProvider) {
      throw new Error('Wallet not initialized');
    }

    // 1. Sign the authorization intent (EIP-712 equivalent)
    const authMessage = `Authorized payment of ${challengeObj.cost} wei for ${challengeObj.memo}`;
    const signature = await this.walletProvider.signMessage(authMessage);

    // 2. Package the X-Payment-Receipt
    const receipt = {
      txHash: '0xsimulatedtransactionhash0000abc123', // Real version executes a transfer here
      signature: signature,
      agentWallet: this.walletAddress,
    };

    return receipt;
  }
}
