import React from 'react';
import { useSecurityPresence } from '@/components/coordinator-panels/TraitRuntimeContext';

// @generated by HoloScript Native2DCompiler — DO NOT EDIT
export function AdminDashboardComponent() {
  const { stats, auditLog } = useSecurityPresence();


  const recent = auditLog.slice(-20).reverse();

  return (
    <div className="holoscript-2d-root w-full h-full">
      <div style={{"display":"flex","flexDirection":"column","gap":"12px"}} className="p-3 h-full overflow-y-auto text-xs text-studio-text">
      
      <h3 className="text-xl font-semibold text-sm font-semibold text-studio-text">
      {`Security & compliance`}
      
    </h3>
<div className="grid grid-cols-2 gap-2">
      
      <div style={{"display":"flex","flexDirection":"column","gap":"2px"}} className="rounded-md p-2 bg-studio-panel/40 border-l-2 border-studio-accent">
      
      <span className="text-sm text-[10px] uppercase tracking-wide text-studio-muted">
      {`Sessions`}
      
    </span>
<h2 className="text-3xl font-bold text-lg font-semibold text-studio-text">
      {stats?.sessions?.authenticated ?? "0"}
      
    </h2>
<span className="text-sm text-[10px] text-studio-muted">
      {`${(stats?.sessions?.revoked ?? 0)} revoked`}
      
    </span>
    </div>
<div style={{"display":"flex","flexDirection":"column","gap":"2px"}} className="rounded-md p-2 bg-studio-panel/40 border-l-2 border-studio-accent">
      
      <span className="text-sm text-[10px] uppercase tracking-wide text-studio-muted">
      {`Agents tracked`}
      
    </span>
<h2 className="text-3xl font-bold text-lg font-semibold text-studio-text">
      {stats?.agents?.tracked ?? "0"}
      
    </h2>
<span className="text-sm text-[10px] text-studio-muted">
      {`RBAC scope`}
      
    </span>
    </div>
<div style={{"display":"flex","flexDirection":"column","gap":"2px"}} className="rounded-md p-2 bg-studio-panel/40 border-l-2 border-studio-accent">
      
      <span className="text-sm text-[10px] uppercase tracking-wide text-studio-muted">
      {`Tenants active`}
      
    </span>
<h2 className="text-3xl font-bold text-lg font-semibold text-studio-text">
      {stats?.tenants?.active ?? "0"}
      
    </h2>
<span className="text-sm text-[10px] text-studio-muted">
      {`${(stats?.tenants?.suspended ?? 0)} suspended`}
      
    </span>
    </div>
<div style={{"display":"flex","flexDirection":"column","gap":"2px"}} className="rounded-md p-2 bg-studio-panel/40 border-l-2 border-studio-border">
      
      <span className="text-sm text-[10px] uppercase tracking-wide text-studio-muted">
      {`Quotas exceeded`}
      
    </span>
<h2 className={`text-3xl font-bold text-lg font-semibold ${(stats?.quotas?.exceeded ?? 0) >= 1 ? "text-studio-error" : "text-studio-text"}`}>
      {stats?.quotas?.exceeded ?? "0"}
      
    </h2>
<span className="text-sm text-[10px] text-studio-muted">
      {`${(stats?.quotas?.tracked ?? 0)} tracked`}
      
    </span>
    </div>
    </div>
<h3 className="text-xl font-semibold text-xs font-semibold text-studio-text-secondary">
      {`Recent audit`}
      
    </h3>
{(auditLog?.length) === 0 && (
      <span className="text-sm text-[10px] italic text-studio-muted">
        {`No audit events observed yet.`}
        
      </span>
    )}
{(auditLog?.length ?? 0) > 0 && (
      <div style={{"display":"flex","flexDirection":"column","gap":"2px"}} className="max-h-60 overflow-y-auto">
        
        {(recent ?? []).map((entry, i) => (
        <div style={{"display":"flex","flexDirection":"row","justifyContent":"space-between","alignItems":"center","gap":"6px"}} className="border-b border-studio-border py-1 text-[11px]" key={i}>
          
          <span className="text-sm text-studio-text-secondary">
          {entry?.event ?? "—"}
          
        </span>
    <span className="text-sm text-studio-muted">
          {entry?.actor ?? "—"}
          
        </span>
    <span className={`text-sm font-semibold ${(entry?.outcome ?? '') === "denied" ? "text-studio-error" : (entry?.outcome ?? '') === "error" ? "text-studio-error" : (entry?.outcome ?? '') === "success" ? "text-studio-success" : "text-studio-muted"}`}>
          {entry?.outcome ?? ""}
          
        </span>
        </div>
      ))}
      </div>
    )}
    </div>
    </div>
  );
}

export default AdminDashboardComponent;
