import React, { useState, useEffect } from 'react';

// @generated by HoloScript Native2DCompiler — DO NOT EDIT
export function AgentMonitorComponent() {
  const [agents, setAgents] = useState<Record<string, string | number | null | undefined> | null>(null);
  useEffect(() => {
    fetch(`/api/holomesh/agents/summary`)
      .then(r => r.json())
      .then(setAgents)
      .catch(console.error);
  }, []);

  return (
    <div className="holoscript-2d-root w-full h-full">
      <div style={{"display":"flex","flexDirection":"column","gap":"12px"}} className="p-3 h-full overflow-y-auto text-xs">
      
      <h3 className="text-xl font-semibold text-sm font-semibold text-studio-text">
      {`Agent Monitor`}
      
    </h3>
<div style={{"display":"flex","flexDirection":"column","gap":"4px"}} className="rounded-lg p-2 bg-emerald-500/10">
      
      <span className="text-sm text-gray-500 text-[10px] text-studio-muted">
      {`Active`}
      
    </span>
<h2 className="text-3xl font-bold text-lg font-bold text-emerald-400">
      {agents?.active ?? "0"}
      
    </h2>
    </div>
<div style={{"display":"flex","flexDirection":"column","gap":"4px"}} className="rounded-lg p-2 bg-studio-panel/30">
      
      <span className="text-sm text-gray-500 text-[10px] text-studio-muted">
      {`Idle`}
      
    </span>
<h2 className="text-3xl font-bold text-lg font-bold text-slate-400">
      {agents?.idle ?? "0"}
      
    </h2>
    </div>
<div style={{"display":"flex","flexDirection":"column","gap":"4px"}} className="rounded-lg p-2 bg-amber-500/10">
      
      <span className="text-sm text-gray-500 text-[10px] text-studio-muted">
      {`Busy`}
      
    </span>
<h2 className="text-3xl font-bold text-lg font-bold text-amber-400">
      {agents?.busy ?? "0"}
      
    </h2>
    </div>
    </div>
    </div>
  );
}

export default AgentMonitorComponent;
