import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import {
  formatMarkdownTable,
  isMetadataShellHoloContent,
  replaceCensusBlock,
  studioSubtree,
  summarizeStudioFiles,
} from '../studio-authoring-debt-census.mjs';

describe('studio-authoring-debt-census', () => {
  it('classifies pending @slot panel files as metadata shells only when no real object is mounted', () => {
    const pendingShell = [
      '@view({ id: "chat", title: "Brittney Chat" })',
      'composition "chat" {',
      '  // @slot widget mount pending - registry metadata migrated',
      '}',
      '',
    ].join('\n');
    const wiredSlot = [
      '@view({ id: "assetLib", title: "Asset Library" })',
      'composition "assetLib" {',
      '  object "AssetLibraryPanel" @slot(component: "AssetLibraryPanel", import: "@/components/assets/AssetLibraryPanel") {}',
      '}',
      '',
    ].join('\n');

    assert.equal(isMetadataShellHoloContent(pendingShell), true);
    assert.equal(isMetadataShellHoloContent(wiredSlot), false);
  });

  it('summarizes tracked Studio files by subtree and separates generated TSX', () => {
    const files = [
      'packages/studio/src/components/Widget.tsx',
      'packages/studio/src/lib/studio/native/generated.native.tsx',
      'packages/studio/src/lib/studio/panels/pending.holo',
      'packages/studio/holo-pages/start/page.holo',
      'packages/studio/README.md',
    ];
    const contents = new Map([
      ['packages/studio/src/components/Widget.tsx', 'export function Widget() { return null }'],
      [
        'packages/studio/src/lib/studio/native/generated.native.tsx',
        '// @generated by script\nexport {}',
      ],
      [
        'packages/studio/src/lib/studio/panels/pending.holo',
        '@view({ id: "pending" })\ncomposition "pending" {\n  // @slot widget mount pending\n}\n',
      ],
      [
        'packages/studio/holo-pages/start/page.holo',
        'composition "start" {\n  object "Body" {}\n}\n',
      ],
    ]);

    const summary = summarizeStudioFiles(files, (file) => contents.get(file) ?? '');

    assert.deepEqual(summary.totals, {
      label: 'Total',
      authoredTsx: 1,
      generatedTsx: 1,
      holo: 2,
      metadataShellHolo: 1,
    });
    assert.equal(summary.rows.find((row) => row.label === 'src/components')?.authoredTsx, 1);
    assert.equal(summary.rows.find((row) => row.label === 'src/lib')?.generatedTsx, 1);
    assert.equal(summary.rows.find((row) => row.label === 'holo-pages')?.holo, 1);
  });

  it('groups top-level Studio files under the package root label', () => {
    assert.equal(studioSubtree('packages/studio/holoscript-editor.holo'), '.');
  });

  it('replaces or creates the marked paper table block', () => {
    const markdown = formatMarkdownTable({
      rows: [
        {
          label: 'src/components',
          authoredTsx: 2,
          generatedTsx: 0,
          holo: 1,
          metadataShellHolo: 1,
        },
      ],
      totals: {
        label: 'Total',
        authoredTsx: 2,
        generatedTsx: 0,
        holo: 1,
        metadataShellHolo: 1,
      },
    });

    const created = replaceCensusBlock('', markdown);
    assert.match(created, /## 1\. Authoring-Debt Baseline/);
    assert.match(created, /\| `src\/components` \|\s+2 \|\s+0 \|\s+1 \|\s+1 \|\s+100\.0% \|/);

    const replaced = replaceCensusBlock(
      `# Paper\n\n<!-- authoring-debt-census:start -->\nstale\n<!-- authoring-debt-census:end -->\n\nTail`,
      markdown
    );
    assert.doesNotMatch(replaced, /stale/);
    assert.match(replaced, /Tail/);
  });
});
