/**
 * @holoscript/cli
 *
 * Command-line interface for HoloScript.
 * Parse, execute, and debug HoloScript files.
 */
export { HoloScriptCLI } from './HoloScriptCLI';
export { parseArgs, type CLIOptions } from './args';
export { formatAST, formatError } from './formatters';
export { HoloScriptREPL, startREPL } from './repl';
export { TRAITS, formatTrait, formatAllTraits, suggestTraits, getTraitsByCategory, getCategories, type TraitInfo, } from './traits';
export { generateObject, generateScene, listTemplates, getTemplate, type GeneratorOptions, type GeneratedObject, } from './generator';
export { PublishValidator, createPublishValidator, validateForPublish, PackagePackager, createPackager, packPackage, getPackageManifest, publishPackage, type ValidationResult, type ValidationError, type ValidationWarning, type ValidatorOptions, type PackageResult, type PackagerOptions, type PackageManifest, type FileEntry, type PublishOptions, type PublishResult, } from './publish';
export { importUnity, importGodot, importGltf, importGltfToFile, type UnityImportResult, type UnityImportOptions, type GodotImportResult, type GodotImportOptions, } from './importers';
export { hologramCommand, type HologramCommandOptions } from './commands/hologram';
export { runPhysicsSmoke, printSmokeReceipt, type SmokeOptions, type PhysicsSmokeReceipt, type DemoReceipt, } from './smoke';
export { DETERMINISTIC_HOLO_WORLD_PROJECTION, HEADLESS_OBSERVER_PROJECTION_SCHEMA, HEADLESS_OBSERVER_PROOF_SCHEMA, HEADLESS_SOURCE_RUN_RECEIPT_SCHEMA, HEADLESS_SOURCE_RUN_RECEIPT_SCHEMA_V3, HEADLESS_SOURCE_RUN_RECEIPT_SCHEMA_V4, HEADLESS_SOURCE_RUN_VERIFICATION_BOUNDARY, HEADLESS_SOURCE_RUN_VERIFICATION_BOUNDARY_V3, HEADLESS_SOURCE_RUN_VERIFICATION_BOUNDARY_V4, HOLO_WORLD_PROJECTION_COVERAGE, HOLO_WORLD_PROJECTION_PROVENANCE_SCHEMA, POST_SEAL_OBSERVER_PROCESS, PURE_HOLO_WORLD_PROJECTION, SINGLE_EXECUTION_POST_SEAL_OBSERVER, executeHoloWorldProjection, observeHeadlessExperimentReceipt, runHeadlessExperimentSources, verifyHoloWorldProjectionProvenance, verifyHeadlessExperimentSourceRunReceipt, type AnyHeadlessExperimentSourceRunReceipt, type HeadlessExperimentSourceRun, type HeadlessExperimentSourceRunReceipt, type HeadlessExperimentSourceRunReceiptV3, type HeadlessExperimentSourceRunReceiptV4, type HeadlessExperimentSourceRunSources, type HeadlessObserverEquivalenceProof, type HeadlessObserverProjection, type HoloWorldProjectionExecution, type HoloWorldProjectionProvenance, type HoloWorldProjectionVerificationOptions, } from './headless-experiment';
export { HOLOLAND_PHYSICS_OBSERVER_SCHEMA, HOLO_CPU_PHYSICS_ENGINE, HOLO_CPU_PHYSICS_EVIDENCE_SCHEMA, HOLO_CPU_PHYSICS_LIMITS, HOLO_CPU_PHYSICS_RECEIPT_SCHEMA, executeHoloCpuPhysicsReceipt, verifyHoloCpuPhysicsReceipt, type HoloCpuPhysicsBodyRegistration, type HoloCpuPhysicsEngineDefaultsSnapshot, type HoloCpuPhysicsExecutionOptions, type HoloCpuPhysicsExecutionReceipt, type HoloCpuPhysicsObservedBody, type HoloCpuPhysicsObservedContact, type HoloCpuPhysicsObservedContactPoint, type HoloCpuPhysicsObserverFrame, type HoloCpuPhysicsShape, type HoloCpuPhysicsVerificationOptions, type HoloCpuPhysicsVerificationResult, type HoloLandPhysicsObserverProjection, } from './holo-cpu-physics-receipt';
export { HS_PLAN_KERNEL_EXECUTION_PROVENANCE_SCHEMA, HS_PLAN_KERNEL_TRACE_SCHEMA, HS_PLAN_KERNEL_PARSER, HS_PLAN_KERNEL_COMPILER, HS_PLAN_KERNEL_VM, HS_PLAN_KERNEL_UAAL_LIMITS, HS_PLAN_KERNEL_TRACE_PROGRAM_COUNTERS, HS_PLAN_KERNEL_TRACE_OPCODES, RUST_WASM_UAAL_HS_PLAN_KERNEL, executeHsPlanKernel, verifyHsPlanKernelExecutionProvenance, type HsPlanKernelCompactTrace, type HsPlanKernelExecutionProvenance, type HsPlanKernelExecutionResult, type HsPlanKernelProvenanceVerificationOptions, type HsPlanKernelProvenanceVerificationResult, type HsPlanKernelVmExecutionProfile, } from './native-hs-plan-runner';
