/**
 * Age, Wear & Condition Traits
 */
export const AGE_CONDITION_TRAITS = [
  'pristine',
  'worn',
  'rusted',
  'weathered',
  'decayed',
  'fossilized',
  'tarnished',
  'polished',
  'crumbling',
  'corroded',
  'faded',
  'stained',
  'scratched',
  'dented',
  'chipped',
  'cracked',
  'shattered',
  'patched',
  'restored',
  'antique',
  'brand_new',
  'battle_scarred',
  'moss_covered',
  'vine_covered',
  'dust_covered',
  'blood_stained',
  'sun_bleached',
  'charred',
  'petrified',
  'calcified',
] as const;
