/**
 * Environmental & Biome Traits
 */
export const ENVIRONMENTAL_BIOME_TRAITS = [
  'weather_source',
  'day_night',
  'seasonal',
  'underwater',
  'zero_gravity',
  'low_gravity',
  'high_gravity',
  'foggy',
  'icy',
  'volcanic',
  'overgrown',
  'enchanted',
  'corrupted',
  'sacred',
  'haunted',
  'toxic',
  'subterranean',
  'celestial',
  'abyssal',
  'crystalline_biome',
  'desert',
  'tundra',
  'swamp',
  'forest',
  'urban',
  'ruins',
  'futuristic',
  'steampunk',
  'cyberpunk',
  'medieval',
  'alien',
  'dream',
  'void',
] as const;
