/**
 * Game Mechanics Traits
 */
export const GAME_MECHANICS_TRAITS = [
  'collectible',
  'spawnable',
  'destructible',
  'healable',
  'damageable',
  'explosive',
  'flammable',
  'freezable',
  'electrifiable',
  'magnetic',
  'poisonous',
  'radioactive',
  'fragile',
  'repairable',
  'upgradeable',
  'lootable',
  'quest_item',
  'currency',
  'ammunition',
  'fuel',
  'key_item',
  'power_up',
  'debuff',
  'shield',
  'weapon',
  'armor',
  'tool',
  'vehicle',
  'projectile',
  'trap',
  'puzzle_piece',
] as const;
