/**
 * Gems, Minerals & Precious Material Traits
 */
export const GEMS_MINERALS_TRAITS = [
  'diamond_gem',
  'ruby_gem',
  'emerald_gem',
  'sapphire_gem',
  'amethyst',
  'topaz',
  'opal',
  'pearl',
  'obsidian',
  'jade',
  'amber',
  'quartz',
  'crystal_gem',
  'gold_material',
  'silver_material',
  'bronze_material',
  'copper_material',
  'iron_material',
  'steel_material',
  'titanium_material',
  'mithril',
  'adamantine',
  'orichalcum',
  'moonstone',
  'sunstone',
  'bloodstone',
  'lapis_lazuli',
  'turquoise_gem',
  'onyx',
  'garnet',
] as const;
