/**
 * Healthcare & Medical Traits
 */
export const HEALTHCARE_MEDICAL_TRAITS = [
  'patient',
  'vital_signs',
  'x_ray_scan',
  'mri_scan',
  'ct_scan',
  'ultrasound',
  'ecg',
  'surgical_tool',
  'scalpel',
  'forceps',
  'syringe',
  'iv_drip',
  'defibrillator',
  'stethoscope',
  'bandage',
  'splint',
  'wheelchair',
  'prosthetic',
  'therapeutic',
  'meditation',
  'breathing_exercise',
  'biofeedback',
  'exposure_therapy',
  'pain_management',
  'rehabilitation',
  'cognitive_therapy',
  'phobia_treatment',
  'ptsd_therapy',
  'mindfulness',
  'body_scan',
  'guided_relaxation',
] as const;
