/**
 * Intelligence & Behavior Traits
 */
export const INTELLIGENCE_BEHAVIOR_TRAITS = [
  'autonomous',
  'scripted',
  'adaptive',
  'pathfinding',
  'flocking',
  'swarming',
  'conversational',
  'teachable',
  'tameable',
  'friendly',
  'hostile',
  'neutral',
  'territorial',
  'nocturnal',
  'migratory',
  'predator',
  'prey',
  'pack_animal',
  'solitary',
  'curious',
  'fearful',
  'aggressive',
  'passive',
  'protective',
  'playful',
  'mischievous',
  'wise',
  'ancient',
  'baby',
  'elder',
  'legendary',
  'mythical',
  'mechanical',
  'organic',
  'hybrid',
  'shapeshifter',
  'invisible_agent',
  'omniscient',
  // V43 Tier 1: Planning & Behavior
  'behavior_tree',
  'goal_oriented',
] as const;
