/**
 * Material Property Traits
 */
export const MATERIAL_PROPERTIES_TRAITS = [
  'wooden',
  'stone_material',
  'brick',
  'concrete',
  'marble_material',
  'granite',
  'sandstone',
  'slate',
  'clay',
  'terracotta',
  'glass_material',
  'stained_glass',
  'crystal_material',
  'ice_material',
  'bone',
  'ivory',
  'shell',
  'coral',
  'bamboo',
  'paper',
  'cardboard',
  'plastic',
  'resin',
  'wax',
  'foam',
  'composite',
  'carbon_fiber',
  'kevlar',
  'fiberglass',
  'plaster',
  'concrete_reinforced',
  'thatch',
  'adobe',
] as const;
