/**
 * Nature & Life Traits
 */
export const NATURE_LIFE_TRAITS = [
  'growable',
  'witherable',
  'bloomable',
  'bloom_reactive',
  'botanical_lotus',
  'pollinating',
  'photosynthetic',
  'lotus_root',
  'lotus_stalk',
  'lotus_petal',
  'lotus_center',
  'lotus_gardener',
  'bioluminescent',
  'venomous',
  'symbiotic',
  'parasitic',
  'carnivorous_plant',
  'aquatic',
  'amphibious',
  'aerial',
  'burrowing',
  'nesting',
  'egg',
  'larva',
  'cocoon',
  'metamorphic',
] as const;
