/**
 * Shape & Form Modifier Traits
 */
export const SHAPE_FORM_TRAITS = [
  'round',
  'square',
  'triangular',
  'hexagonal',
  'octagonal',
  'spiral',
  'twisted',
  'hollow',
  'solid',
  'perforated',
  'lattice',
  'branching',
  'tapered',
  'flared',
  'curved',
  'angular',
  'symmetrical',
  'asymmetrical',
  'organic_form',
  'geometric',
  'fractal_shape',
  'amorphous',
  'segmented',
  'layered_form',
  'nested',
  'interlocking',
  'modular_shape',
  'tessellated',
  'ribbed',
  'corrugated',
  'faceted',
  'smooth_form',
] as const;
