/**
 * v6 Universal Service & Backend Trait Constants
 *
 * 215+ trait name constants for the universal semantic platform extension.
 * These traits enable HoloScript to describe backend services, data layers,
 * networking, pipelines, observability, and deployment infrastructure.
 *
 * Organized into 8 categories matching the v6/ trait handler files.
 */

// ── Service & API Traits (28) ────────────────────────────────────────────────
export const UNIVERSAL_SERVICE_TRAITS = [
  'service',
  'endpoint',
  'route',
  'handler',
  'middleware',
  'api_gateway',
  'reverse_proxy',
  'load_balancer',
  'service_discovery',
  'service_mesh',
  'sidecar',
  'ingress',
  'egress',
  'cors_policy',
  'rate_limiter',
  'request_validator',
  'response_transformer',
  'api_version',
  'webhook_sender',
  'webhook_receiver',
  'sse_endpoint',
  'batch_endpoint',
  'file_upload',
  'multipart_handler',
  'graphql_resolver',
  'rest_resource',
  'rpc_method',
  'health_endpoint',
] as const;

// ── Contract & Schema Traits (26) ────────────────────────────────────────────
export const UNIVERSAL_CONTRACT_TRAITS = [
  'contract',
  'schema',
  'validator',
  'serializer',
  'json_schema',
  'avro_schema',
  'protobuf_message',
  'graphql_type',
  'graphql_input',
  'graphql_enum',
  'graphql_union',
  'graphql_directive',
  'openapi_path',
  'openapi_response',
  'openapi_security',
  'asyncapi_channel',
  'asyncapi_message',
  'contract_test',
  'consumer_contract',
  'schema_evolution',
  'backward_compatible',
  'forward_compatible',
  'input_sanitizer',
  'output_filter',
  'data_transformer',
  'dto',
] as const;

// ── Data Access Traits (38) ──────────────────────────────────────────────────
export const UNIVERSAL_DATA_TRAITS = [
  'db',
  'model',
  'query',
  'migration',
  'cache',
  'relational_db',
  'document_db',
  'key_value_store',
  'graph_db',
  'time_series_db',
  'vector_db',
  'search_index',
  'full_text_search',
  'data_warehouse',
  'data_lake',
  'materialized_view',
  'read_replica',
  'connection_pool',
  'transaction',
  'saga',
  'cqrs_command',
  'cqrs_query',
  'event_store',
  'projection',
  'aggregate_root',
  'repository',
  'unit_of_work',
  'data_mapper',
  'identity_map',
  'lazy_load',
  'eager_load',
  'cursor_pagination',
  'offset_pagination',
  'soft_delete',
  'audit_column',
  'version_column',
  'tenant_column',
  'sharding_key',
] as const;

// ── Network Protocol Traits (30) ─────────────────────────────────────────────
export const UNIVERSAL_NETWORK_TRAITS = [
  'http',
  'websocket',
  'grpc',
  'graphql',
  'tcp_server',
  'tcp_client',
  'udp_server',
  'udp_client',
  'http2_server',
  'http3_server',
  'quic_transport',
  'tls_config',
  'mtls_config',
  'dns_resolver',
  'cdn_config',
  'cors_config',
  'csp_config',
  'hsts_config',
  'session_config',
  'oauth2_config',
  'oidc_provider',
  'api_key_auth',
  'bearer_auth',
  'jwt_config',
  'jwt_issuer',
  'jwt_verifier',
  'rate_limit_config',
  'throttle_config',
  'backpressure',
  'connection_drain',
] as const;

// ── Pipeline & Messaging Traits (32) ─────────────────────────────────────────
export const UNIVERSAL_PIPELINE_TRAITS = [
  'pipeline',
  'stream',
  'queue',
  'worker',
  'scheduler',
  'etl_pipeline',
  'data_flow',
  'dag',
  'batch_job',
  'micro_batch',
  'real_time_stream',
  'change_data_capture',
  'event_sourcing',
  'message_broker',
  'topic',
  'subscription',
  'dlq_handler',
  'priority_queue',
  'delay_queue',
  'fanout',
  'content_router',
  'message_filter',
  'message_aggregator',
  'message_splitter',
  'message_enricher',
  'idempotent_consumer',
  'competing_consumer',
  'workflow_engine',
  'state_machine',
  'saga_orchestrator',
  'choreography',
  'compensating_transaction',
] as const;

// ── Observability & Metric Traits (30) ───────────────────────────────────────
export const UNIVERSAL_METRIC_TRAITS = [
  'metric',
  'trace',
  'log',
  'health_check',
  'prometheus_exporter',
  'grafana_dashboard',
  'alert_rule',
  'alert_channel',
  'slo',
  'sli',
  'error_budget',
  'latency_percentile',
  'throughput_counter',
  'request_rate',
  'error_rate',
  'availability_monitor',
  'uptime_monitor',
  'synthetic_monitor',
  'real_user_monitoring',
  'apm_agent',
  'profiler',
  'memory_profiler',
  'cpu_profiler',
  'span',
  'trace_context',
  'sampling_strategy',
  'structured_log',
  'log_aggregator',
  'audit_log',
  'access_log',
] as const;

// ── Container & Deployment Traits (30) ───────────────────────────────────────
export const UNIVERSAL_CONTAINER_TRAITS = [
  'container',
  'deployment',
  'scaling',
  'secret',
  'dockerfile',
  'docker_compose',
  'kubernetes_pod',
  'kubernetes_service',
  'kubernetes_deployment',
  'kubernetes_statefulset',
  'kubernetes_job',
  'kubernetes_cronjob',
  'kubernetes_configmap',
  'kubernetes_ingress',
  'kubernetes_hpa',
  'kubernetes_pdb',
  'kubernetes_network_policy',
  'kubernetes_service_account',
  'helm_chart',
  'helm_values',
  'terraform_resource',
  'terraform_module',
  'pulumi_resource',
  'persistent_volume',
  'storage_class',
  'resource_quota',
  'node_affinity',
  'pod_affinity',
  'toleration',
  'init_container',
] as const;

// ── Resilience Pattern Traits (25) ───────────────────────────────────────────
export const UNIVERSAL_RESILIENCE_TRAITS = [
  'circuit_breaker',
  'retry',
  'timeout',
  'fallback',
  'bulkhead',
  'token_bucket',
  'leaky_bucket',
  'sliding_window',
  'adaptive_concurrency',
  'load_shedding',
  'graceful_degradation',
  'canary_release',
  'blue_green_deploy',
  'rolling_update',
  'chaos_experiment',
  'fault_injection',
  'latency_injection',
  'exponential_backoff',
  'jitter_backoff',
  'deadline_propagation',
  'request_hedging',
  'speculative_retry',
  'idempotency_key',
  'health_aggregator',
  'dependency_check',
] as const;

// ── Combined v6 Universal Traits ─────────────────────────────────────────────
export const UNIVERSAL_V6_TRAITS = [
  ...UNIVERSAL_SERVICE_TRAITS,
  ...UNIVERSAL_CONTRACT_TRAITS,
  ...UNIVERSAL_DATA_TRAITS,
  ...UNIVERSAL_NETWORK_TRAITS,
  ...UNIVERSAL_PIPELINE_TRAITS,
  ...UNIVERSAL_METRIC_TRAITS,
  ...UNIVERSAL_CONTAINER_TRAITS,
  ...UNIVERSAL_RESILIENCE_TRAITS,
] as const;

export type UniversalV6TraitName = (typeof UNIVERSAL_V6_TRAITS)[number];
