/**
 * Visual Effects Traits
 */
export const VISUAL_EFFECTS_TRAITS = [
  'transparent',
  'reflective',
  'emissive',
  'spinning',
  'floating',
  'pulsing',
  'blinking',
  'fading',
  'color_shifting',
  'holographic',
  'outlined',
  'x_ray',
  'neon_glow',
  'iridescent',
  'frosted',
  'luminous',
  'camouflaged',
  'mirrored',
  'pixelated',
  'dissolving',
  'crystalline',
  'ethereal',
  'smoky',
  'fiery',
  'electric_arc',
  'ghostly',
  'rainbow',
  'metallic_sheen',
  'ink_wash',
  'cel_shaded',
] as const;
