#!/usr/bin/env tsx
/**
 * gen-trait-schemas.ts — derive TraitSchema[] from the .holo trait tree so the
 * enum/type prop-schema enforcer ({@link ConfabulationValidator}) can see every trait
 * authors actually wrote, not just the ~63 hand-maintained schemas.
 *
 * Thin CLI wrapper: the derivation logic lives in
 * packages/core/src/compiler/identity/deriveTraitSchema.ts (unit-tested there). This
 * script globs packages/core/src/traits/**\/*.holo, derives each, DEDUPES by trait name,
 * DETECTS .holo-vs-.holo drift (same handler name, divergent schema — e.g. abtest.holo vs
 * devops/abtest.holo), and emits derived-trait-schemas.generated.ts.
 *
 * Regenerate: pnpm gen:trait-schemas
 *
 * Drift policy: a conflicting name keeps the FIRST occurrence in sorted-path order
 * (deterministic) and the conflict is reported to stderr AND recorded in the generated
 * file header so it is visible, never silently resolved.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { deriveTraitSchemaFromHolo } from '../packages/core/src/compiler/identity/deriveTraitSchema';
import type { TraitSchema } from '../packages/core/src/compiler/identity/ConfabulationValidator';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const TRAITS_DIR = path.join(ROOT, 'packages', 'core', 'src', 'traits');
const OUT = path.join(
  ROOT,
  'packages',
  'core',
  'src',
  'compiler',
  'identity',
  'derived-trait-schemas.generated.ts'
);

function holoFiles(dir: string): string[] {
  return readdirSync(dir, { recursive: true, encoding: 'utf8' })
    .filter((f) => typeof f === 'string' && f.endsWith('.holo'))
    .map((f) => path.join(dir, f))
    .sort();
}

function main(): void {
  const files = holoFiles(TRAITS_DIR);
  const byName = new Map<string, { schema: TraitSchema; rel: string }>();
  const conflicts: string[] = [];
  let derived = 0;
  let skipped = 0;

  for (const file of files) {
    const rel = path.relative(ROOT, file).replace(/\\/g, '/');
    let schema: TraitSchema | null = null;
    try {
      schema = deriveTraitSchemaFromHolo(readFileSync(file, 'utf8'));
    } catch {
      schema = null;
    }
    if (!schema) {
      skipped++;
      continue;
    }
    derived++;
    const existing = byName.get(schema.name);
    if (existing) {
      if (JSON.stringify(existing.schema) !== JSON.stringify(schema)) {
        conflicts.push(`  ${schema.name}: kept ${existing.rel}, ignored divergent ${rel}`);
      }
      continue; // deterministic winner = first in sorted-path order
    }
    byName.set(schema.name, { schema, rel });
  }

  const schemas = [...byName.values()]
    .map((v) => v.schema)
    .sort((a, b) => a.name.localeCompare(b.name));

  const conflictBlock = conflicts.length
    ? `//\n// ⚠ ${conflicts.length} .holo-vs-.holo name conflict(s) (first-in-sorted-path kept):\n${conflicts
        .map((c) => `//${c}`)
        .join('\n')}\n`
    : '//\n// No .holo-vs-.holo name conflicts detected.\n';

  const header =
    `// @generated by scripts/gen-trait-schemas.ts — DO NOT EDIT.\n` +
    `// Regenerate: pnpm gen:trait-schemas\n` +
    `// Source of truth: packages/core/src/traits/**/*.holo\n` +
    `// ${derived} trait(s) derived, ${schemas.length} unique after dedupe, ${skipped} file(s) skipped (no clean @trait).\n` +
    conflictBlock;

  const body =
    `import type { TraitSchema } from './ConfabulationValidator';\n\n` +
    `export const DERIVED_TRAIT_SCHEMAS: TraitSchema[] = ${JSON.stringify(schemas, null, 2)};\n`;

  writeFileSync(OUT, `${header}\n${body}`, 'utf8');

  process.stdout.write(
    `[gen-trait-schemas] ${schemas.length} unique schema(s) from ${derived} trait(s) ` +
      `(${skipped} skipped, ${conflicts.length} conflict(s)) -> ` +
      `${path.relative(ROOT, OUT).replace(/\\/g, '/')}\n`
  );
  if (conflicts.length) {
    process.stderr.write(`[gen-trait-schemas] .holo-vs-.holo conflicts:\n${conflicts.join('\n')}\n`);
  }
}

main();
