// @generated by HoloScript Vector2DCompiler — DO NOT EDIT
import React from 'react';

export default function AgentAbility() {
  return (
    <div style={{ maxWidth: 520, margin: '0 auto', padding: 24 }}>
      <svg
        viewBox="0 0 460 440"
        style={{ width: '100%', height: 'auto' }}
        role="img"
        aria-label="AgentAbility"
      >
        <polygon
          points="220,180 241.2,188.8 250,210 241.2,231.2 220,240 198.8,231.2 190,210 198.8,188.8"
          fill="none"
          stroke="rgba(0,0,0,0.12)"
          strokeWidth={0.6}
        />
        <polygon
          points="220,150 262.4,167.6 280,210 262.4,252.4 220,270 177.6,252.4 160,210 177.6,167.6"
          fill="none"
          stroke="rgba(0,0,0,0.12)"
          strokeWidth={0.6}
        />
        <polygon
          points="220,120 283.6,146.4 310,210 283.6,273.6 220,300 156.4,273.6 130,210 156.4,146.4"
          fill="none"
          stroke="rgba(0,0,0,0.12)"
          strokeWidth={0.6}
        />
        <polygon
          points="220,90 304.9,125.1 340,210 304.9,294.9 220,330 135.1,294.9 100,210 135.1,125.1"
          fill="none"
          stroke="rgba(0,0,0,0.12)"
          strokeWidth={0.6}
        />
        <polygon
          points="220,60 326.1,103.9 370,210 326.1,316.1 220,360 113.9,316.1 70,210 113.9,103.9"
          fill="none"
          stroke="rgba(0,0,0,0.12)"
          strokeWidth={1.1}
        />
        <line x1={220} y1={210} x2={220} y2={60} stroke="rgba(0,0,0,0.12)" strokeWidth={0.6} />
        <text
          x={220}
          y={38}
          textAnchor="middle"
          dominantBaseline="middle"
          fontSize={12.5}
          fontWeight={500}
          fill="#333"
        >
          Reasoning
        </text>
        <line x1={220} y1={210} x2={326.1} y2={103.9} stroke="rgba(0,0,0,0.12)" strokeWidth={0.6} />
        <text
          x={341.6}
          y={88.4}
          textAnchor="start"
          dominantBaseline="middle"
          fontSize={12.5}
          fontWeight={500}
          fill="#333"
        >
          Tool use
        </text>
        <line x1={220} y1={210} x2={370} y2={210} stroke="rgba(0,0,0,0.12)" strokeWidth={0.6} />
        <text
          x={392}
          y={210}
          textAnchor="start"
          dominantBaseline="middle"
          fontSize={12.5}
          fontWeight={500}
          fill="#333"
        >
          Write
        </text>
        <line x1={220} y1={210} x2={326.1} y2={316.1} stroke="rgba(0,0,0,0.12)" strokeWidth={0.6} />
        <text
          x={341.6}
          y={331.6}
          textAnchor="start"
          dominantBaseline="middle"
          fontSize={12.5}
          fontWeight={500}
          fill="#333"
        >
          Accuracy &#8869;
        </text>
        <text x={341.6} y={344.6} textAnchor="start" fontSize={10.5} fill="#BA7517">
          X facet
        </text>
        <line x1={220} y1={210} x2={220} y2={360} stroke="rgba(0,0,0,0.12)" strokeWidth={0.6} />
        <text
          x={220}
          y={382}
          textAnchor="middle"
          dominantBaseline="middle"
          fontSize={12.5}
          fontWeight={500}
          fill="#333"
        >
          Memory
        </text>
        <line x1={220} y1={210} x2={113.9} y2={316.1} stroke="rgba(0,0,0,0.12)" strokeWidth={0.6} />
        <text
          x={98.4}
          y={331.6}
          textAnchor="end"
          dominantBaseline="middle"
          fontSize={12.5}
          fontWeight={500}
          fill="#333"
        >
          Truth &#8869;
        </text>
        <text x={98.4} y={344.6} textAnchor="end" fontSize={10.5} fill="#BA7517">
          Z facet
        </text>
        <line x1={220} y1={210} x2={70} y2={210} stroke="rgba(0,0,0,0.12)" strokeWidth={0.6} />
        <text
          x={48}
          y={210}
          textAnchor="end"
          dominantBaseline="middle"
          fontSize={12.5}
          fontWeight={500}
          fill="#333"
        >
          Coordination
        </text>
        <line x1={220} y1={210} x2={113.9} y2={103.9} stroke="rgba(0,0,0,0.12)" strokeWidth={0.6} />
        <text
          x={98.4}
          y={88.4}
          textAnchor="end"
          dominantBaseline="middle"
          fontSize={12.5}
          fontWeight={500}
          fill="#333"
        >
          Mobility
        </text>
        <polygon
          points="220,135 315.5,114.5 325,210 304.9,294.9 220,255 156.4,273.6 130,210 188.2,178.2"
          fill="#378ADD"
          fillOpacity={0.12}
          stroke="#378ADD"
          strokeWidth={2.2}
          strokeLinejoin="round"
        />
        <circle cx={220} cy={135} r={3.5} fill="#378ADD" stroke="#fff" strokeWidth={1.2} />
        <circle cx={315.5} cy={114.5} r={3.5} fill="#378ADD" stroke="#fff" strokeWidth={1.2} />
        <circle cx={325} cy={210} r={3.5} fill="#378ADD" stroke="#fff" strokeWidth={1.2} />
        <circle cx={304.9} cy={294.9} r={4.5} fill="#378ADD" stroke="#fff" strokeWidth={1.2} />
        <circle cx={220} cy={255} r={3.5} fill="#378ADD" stroke="#fff" strokeWidth={1.2} />
        <circle cx={156.4} cy={273.6} r={4.5} fill="#378ADD" stroke="#fff" strokeWidth={1.2} />
        <circle cx={130} cy={210} r={3.5} fill="#378ADD" stroke="#fff" strokeWidth={1.2} />
        <circle cx={188.2} cy={178.2} r={3.5} fill="#378ADD" stroke="#fff" strokeWidth={1.2} />
        <polygon
          points="220,90 294.2,135.8 310,210 283.6,273.6 220,315 145.8,284.2 100,210 156.4,146.4"
          fill="#1D9E75"
          fillOpacity={0.12}
          stroke="#1D9E75"
          strokeWidth={2.2}
          strokeLinejoin="round"
        />
        <circle cx={220} cy={90} r={3.5} fill="#1D9E75" stroke="#fff" strokeWidth={1.2} />
        <circle cx={294.2} cy={135.8} r={3.5} fill="#1D9E75" stroke="#fff" strokeWidth={1.2} />
        <circle cx={310} cy={210} r={3.5} fill="#1D9E75" stroke="#fff" strokeWidth={1.2} />
        <circle cx={283.6} cy={273.6} r={4.5} fill="#1D9E75" stroke="#fff" strokeWidth={1.2} />
        <circle cx={220} cy={315} r={3.5} fill="#1D9E75" stroke="#fff" strokeWidth={1.2} />
        <circle cx={145.8} cy={284.2} r={4.5} fill="#1D9E75" stroke="#fff" strokeWidth={1.2} />
        <circle cx={100} cy={210} r={3.5} fill="#1D9E75" stroke="#fff" strokeWidth={1.2} />
        <circle cx={156.4} cy={146.4} r={3.5} fill="#1D9E75" stroke="#fff" strokeWidth={1.2} />
        <polygon
          points="220,75 283.6,146.4 325,210 283.6,273.6 220,360 124.5,305.5 85,210 124.5,114.5"
          fill="#7F77DD"
          fillOpacity={0.12}
          stroke="#7F77DD"
          strokeWidth={2.2}
          strokeLinejoin="round"
        />
        <circle cx={220} cy={75} r={3.5} fill="#7F77DD" stroke="#fff" strokeWidth={1.2} />
        <circle cx={283.6} cy={146.4} r={3.5} fill="#7F77DD" stroke="#fff" strokeWidth={1.2} />
        <circle cx={325} cy={210} r={3.5} fill="#7F77DD" stroke="#fff" strokeWidth={1.2} />
        <circle cx={283.6} cy={273.6} r={4.5} fill="#7F77DD" stroke="#fff" strokeWidth={1.2} />
        <circle cx={220} cy={360} r={3.5} fill="#7F77DD" stroke="#fff" strokeWidth={1.2} />
        <circle cx={124.5} cy={305.5} r={4.5} fill="#7F77DD" stroke="#fff" strokeWidth={1.2} />
        <circle cx={85} cy={210} r={3.5} fill="#7F77DD" stroke="#fff" strokeWidth={1.2} />
        <circle cx={124.5} cy={114.5} r={3.5} fill="#7F77DD" stroke="#fff" strokeWidth={1.2} />
      </svg>
    </div>
  );
}
