#!/usr/bin/env tsx
/**
 * compile-vector-pages.mts — compile HoloScript 2D-vector .holo pages to @generated
 * Next.js page.tsx via the Vector2DCompiler (the native 2D-vector / data-viz target).
 *
 * Sibling to compile-holo-pages.ts (which uses NextJSCompiler for shell pages); this one
 * handles pages whose composition is a 2D-vector scene (radar / chart). The output carries
 * the `@generated by HoloScript Vector2DCompiler` header so it passes the render-surface
 * native freeze natively. Wire into prebuild once the set of vector pages grows.
 *
 *   pnpm vector:build   |   pnpm vector:check
 *
 * WHY THIS GENERATOR FORMATS ITS OWN OUTPUT, AND WHY --check EXISTS
 *
 * Measured 2026-09-21 on a clean checkout of main: running this generator with NO
 * source change rewrote src/app/agent-ability/page.tsx by 19 insertions and 154
 * deletions -- every line of it pure whitespace. The committed copy is prettier
 * wrapped at printWidth 100; the generator emitted raw 200-column lines. The cause
 * is 8b0f3a850 (2026-07-28), a repo-wide "clear prettier format drift" pass that
 * reformatted a file whose first line reads "@generated ... DO NOT EDIT".
 *
 * While that is true this surface cannot be reviewed: a real change to the radar
 * drowns in 154 lines of whitespace restoration, and nobody can tell the two apart.
 * That is the same fault the view registry carried, found the same day.
 *
 * So: one path produces the bytes for both modes. emit() buffers, finish() formats
 * in memory through the prettier API (not the CLI -- .prettierignore excludes some
 * generated paths whose committed form IS formatted), and then either writes or
 * compares. A check that regenerated differently from the build would be worth
 * nothing, so there is no second code path for it to differ from.
 *
 * The formatting half was recovered from the uncommitted WIP snapshot e99aac259 on
 * fix/framework-6.1.7-workspace-leak, where it had been written and left unlanded.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { formatGenerated } from './lib/format-generated';
import { parseHolo } from '../../core/src/parser/HoloCompositionParser';
import { Vector2DCompiler } from '../../core/src/compiler/Vector2DCompiler';
import type { HoloComposition } from '../../core/src/parser/HoloCompositionTypes';
import {
  applyPillarDomainRadarTelemetry,
  normalizePillarTelemetryInput,
} from '../src/lib/agentAbility/pillarDomainRadar';

const STUDIO_ROOT = join(import.meta.dirname || __dirname, '..');

/** --check: regenerate into memory and COMPARE. Writes nothing. */
const CHECK = process.argv.includes('--check');

const PENDING: Array<{ file: string; code: string }> = [];
const drift: string[] = [];

/** Buffer one generated artifact. finish() decides whether it is written or compared. */
function emit(file: string, code: string): void {
  PENDING.push({ file, code });
}

/**
 * Format every buffered artifact in memory, then write it (build) or compare it
 * against the committed copy (--check). Both modes consume the identical bytes.
 */
async function finish(): Promise<void> {
  for (const { file, code } of PENDING.splice(0, PENDING.length)) {
    // Same rule as the other two generators: prettier failing on generated output
    // names the file and stops the build or check (task_1790066851748_j9di).
    const pretty = await formatGenerated(file, code);

    if (CHECK) {
      let current: string | null = null;
      try {
        current = readFileSync(file, 'utf-8');
      } catch {
        current = null;
      }
      if (current !== pretty) drift.push(file);
      continue;
    }

    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, pretty, 'utf-8');
  }
}

const PAGES: Array<{ src: string; out: string; component: string }> = [
  {
    src: join(STUDIO_ROOT, 'holo-pages', 'agent-ability', 'page.holo'),
    out: join(STUDIO_ROOT, 'src', 'app', 'agent-ability', 'page.tsx'),
    component: 'AgentAbility',
  },
];

function telemetryPaths(): string[] {
  const fromEnv =
    process.env.AGENT_ABILITY_PILLAR_TELEMETRY ||
    process.env.HOLOSCRIPT_AGENT_ABILITY_PILLAR_TELEMETRY ||
    '';

  return fromEnv
    .split(/[;,]/)
    .map((entry) => entry.trim())
    .filter(Boolean)
    .map((entry) => resolve(STUDIO_ROOT, entry));
}

function parseTelemetryFile(path: string): unknown[] {
  const text = readFileSync(path, 'utf-8').trim();
  if (!text) return [];

  try {
    return normalizePillarTelemetryInput(JSON.parse(text));
  } catch {
    // Fall through to JSONL: one pillar event/envelope per line.
  }

  return text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .flatMap((line) => normalizePillarTelemetryInput(JSON.parse(line)));
}

function loadAgentAbilityTelemetry(): unknown[] {
  const records: unknown[] = [];
  for (const path of telemetryPaths()) {
    if (!existsSync(path)) {
      console.warn(
        `agent-ability telemetry missing: ${path}; using fallback_values for absent slices`
      );
      continue;
    }
    records.push(...parseTelemetryFile(path));
  }
  return records;
}

function prepareComposition(
  page: { component: string },
  composition: HoloComposition
): HoloComposition {
  if (page.component !== 'AgentAbility') return composition;
  return applyPillarDomainRadarTelemetry(
    composition,
    loadAgentAbilityTelemetry()
  ) as HoloComposition;
}

let failed = 0;
for (const page of PAGES) {
  const source = readFileSync(page.src, 'utf-8');
  const parsed = parseHolo(source);
  if (!parsed.success || !parsed.ast) {
    console.error(
      `✗ parse error in ${page.src}:`,
      JSON.stringify(parsed.errors ?? []).slice(0, 400)
    );
    failed++;
    continue;
  }
  const composition = prepareComposition(page, parsed.ast as unknown as HoloComposition);
  const { code, componentName } = new Vector2DCompiler().compile(composition, {
    componentName: page.component,
  });
  emit(page.out, code);
  if (!CHECK) console.log(`✓ ${componentName} → ${page.out} (${code.length} bytes)`);
}

finish()
  .then(() => {
    if (!CHECK) {
      process.exit(failed > 0 ? 1 : 0);
    }

    // A check whose inputs are not all in the repo must say so before it reports a
    // colour. This generator folds pillar telemetry from a path named in the
    // environment; where that is set, the committed artifact is a function of data
    // this repo does not carry, and a red here may be a difference in that data
    // rather than drift in the tree.
    const external = telemetryPaths();
    if (external.length > 0) {
      console.log(
        `vector:check NOTE -- ${external.length} external telemetry input(s) were folded in: ` +
          `${external.join(', ')}. A machine without them regenerates different bytes.`
      );
    }

    if (failed > 0) {
      console.error('vector:check FAILED -- a source page did not compile (see above).');
      process.exit(1);
    }

    if (drift.length > 0) {
      console.error('');
      console.error(
        `vector:check FAILED -- ${drift.length} generated file(s) differ from what this generator emits:`
      );
      for (const f of drift) console.error(`    ${f}`);
      console.error('');
      console.error('  The committed output is stale or was hand-edited.');
      console.error('  Fix: pnpm run vector:build, then commit the result.');
      console.error('  Never edit a @generated file directly -- change the .holo source.');
      process.exit(1);
    }

    console.log(
      `vector:check OK -- ${PAGES.length} vector page(s): committed output matches the generator.`
    );
    process.exit(0);
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
