#!/usr/bin/env tsx
/**
 * HoloScript Studio — View Registry Compiler (dogfood proof slice, 2026-05-31)
 *
 * Derives the Studio view registry from per-panel `.holo` composition files in
 * src/lib/studio/panels/ instead of hand-maintaining 7 parallel `Record<>` maps
 * in viewRegistry.ts. Each panel is a `.holo` that declares its view metadata via
 * an `@view({...})` decorator and mounts its React widget via `@slot(...)` — so the
 * panel IS a HoloScript composition (core's parseHolo, F.014: no regex), and the
 * registry becomes a GENERATED artifact.
 *
 * This emits viewRegistry.generated.ts ADDITIVELY — the hand-TS STUDIO_VIEW_REGISTRY
 * stays the source of truth; viewRegistry.generated.test.ts pins generated ≡ hand-TS
 * for the migrated panels. Reversible. Once the full set is proven equal, the hand-TS
 * maps are deleted and this becomes the source.
 *
 * Usage: pnpm viewreg:build   |   pnpm viewreg:build --strict  (CI: fail on bad .holo)
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'fs';
import { join, extname, basename } from 'path';
import { parseHolo } from '../../core/src/parser/HoloCompositionParser';

const STUDIO_ROOT = join(import.meta.dirname || __dirname, '..');
const PANELS_DIR = join(STUDIO_ROOT, 'src', 'lib', 'studio', 'panels');
const OUT_PATH = join(STUDIO_ROOT, 'src', 'lib', 'studio', 'viewRegistry.generated.ts');
const STRICT = process.argv.includes('--strict') || process.env.HOLO_STRICT === '1';

interface ViewMeta {
  id: string;
  title: string;
  icon: string;
  category: string;
  placement: string;
  scope: string;
  gate: string;
  surfaceClass: string;
  defaultOpen: boolean;
  exclusiveWith: string[];
}
interface SlotMeta {
  component: string;
  import: string;
}

function extractView(ast: any, file: string): ViewMeta {
  const viewTrait = (ast.traits ?? []).find((t: any) => t.name === 'view');
  if (!viewTrait?.config?._arg0) {
    throw new Error(`${file}: missing @view({...}) decorator on composition`);
  }
  const v = viewTrait.config._arg0 as Partial<ViewMeta>;
  const required = ['id', 'title', 'icon', 'category', 'placement', 'scope', 'gate', 'surfaceClass'];
  for (const k of required) {
    if (v[k as keyof ViewMeta] === undefined) throw new Error(`${file}: @view missing '${k}'`);
  }
  return {
    id: v.id!,
    title: v.title!,
    icon: v.icon!,
    category: v.category!,
    placement: v.placement!,
    scope: v.scope!,
    gate: v.gate!,
    surfaceClass: v.surfaceClass!,
    defaultOpen: v.defaultOpen ?? false,
    exclusiveWith: v.exclusiveWith ?? [],
  };
}

function extractSlot(ast: any): SlotMeta | null {
  const obj = (ast.objects ?? [])[0];
  const slot = obj?.traits?.find((t: any) => t.name === 'slot');
  if (!slot?.config?.component || !slot?.config?.import) return null;
  return { component: slot.config.component, import: slot.config.import };
}

/** Map the .holo @view source fields onto the StudioViewDefinition shape. */
function toDefinition(v: ViewMeta) {
  // Fixed key order → deterministic output (stable diffs across reruns).
  return {
    id: v.id,
    title: v.title,
    icon: v.icon,
    category: v.category,
    defaultPlacement: v.placement,
    activationCommand: `studio.view.${v.id}.toggle`,
    workspaceScope: v.scope,
    availabilityGate: v.gate,
    surfaceClass: v.surfaceClass,
    defaultOpen: v.defaultOpen,
    exclusiveWith: v.exclusiveWith,
  };
}

function build(): void {
  if (!existsSync(PANELS_DIR)) {
    console.log(`No panels dir at ${PANELS_DIR}; nothing to compile.`);
    return;
  }
  const files = readdirSync(PANELS_DIR)
    .filter((f) => extname(f) === '.holo')
    .sort();

  const defs: ReturnType<typeof toDefinition>[] = [];
  const slots: Record<string, SlotMeta> = {};
  let errorCount = 0;

  for (const f of files) {
    const full = join(PANELS_DIR, f);
    try {
      const parsed = parseHolo(readFileSync(full, 'utf-8'));
      if (!parsed.success || !parsed.ast) {
        throw new Error(`${f}: parse failed — ${JSON.stringify(parsed.errors?.[0] ?? 'unknown')}`);
      }
      const view = extractView(parsed.ast, f);
      if (view.id !== basename(f, '.holo')) {
        throw new Error(`${f}: @view id '${view.id}' must match filename`);
      }
      defs.push(toDefinition(view));
      const slot = extractSlot(parsed.ast);
      if (slot) slots[view.id] = slot;
      console.log(`  ✓ ${f} → ${view.id} (${view.surfaceClass})`);
    } catch (err) {
      errorCount++;
      console.error(`  ✗ ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  defs.sort((a, b) => a.id.localeCompare(b.id));

  const out =
    '// @generated by scripts/compile-view-registry.ts from src/lib/studio/panels/*.holo — DO NOT EDIT\n' +
    "'use client';\n\n" +
    "import type { StudioViewDefinition } from './viewRegistry';\n\n" +
    '/** View definitions derived from panel .holo compositions (dogfood). */\n' +
    `export const GENERATED_VIEW_REGISTRY: StudioViewDefinition[] = ${JSON.stringify(defs, null, 2)};\n\n` +
    '/** Per-view React widget mounts declared via @slot in each panel .holo. */\n' +
    `export const GENERATED_VIEW_SLOTS: Record<string, { component: string; import: string }> = ${JSON.stringify(
      slots,
      null,
      2
    )};\n`;

  writeFileSync(OUT_PATH, out);
  console.log(`\nWrote ${defs.length} view(s) → ${OUT_PATH} (${errorCount} error(s))`);

  if (errorCount > 0) {
    const msg = `viewreg:build: ${errorCount} panel .holo file(s) did not compile`;
    if (STRICT) throw new Error(`${msg} (strict mode — failing the gate)`);
    console.warn(`\n⚠ ${msg} — keeping last-good generated registry; deploy NOT blocked. Run --strict in CI.`);
  }
}

build();
