/**
 * @deprecated AI module has moved to `@holoscript/framework/ai`.
 * Import from `@holoscript/framework` or `@holoscript/framework/ai` instead.
 * This stub is retained for backward compatibility during migration.
 */
export {
	type AIAdapter,
	type GenerateResult,
	type ExplainResult,
	type OptimizeResult,
	type FixResult,
	type GenerateOptions,
	registerAIAdapter,
	getAIAdapter,
	getDefaultAIAdapter,
	setDefaultAIAdapter,
	listAIAdapters,
	unregisterAIAdapter,
	generateHoloScript,
	explainHoloScript,
	optimizeHoloScript,
	fixHoloScript,
	OpenAIAdapter,
	AnthropicAdapter,
	OllamaAdapter,
	LMStudioAdapter,
	GeminiAdapter,
	XAIAdapter,
	TogetherAdapter,
	FireworksAdapter,
	NVIDIAAdapter,
	type OpenAIAdapterConfig,
	type AnthropicAdapterConfig,
	type OllamaAdapterConfig,
	type LMStudioAdapterConfig,
	type GeminiAdapterConfig,
	type XAIAdapterConfig,
	type TogetherAdapterConfig,
	type FireworksAdapterConfig,
	type NVIDIAAdapterConfig,
	useOpenAI,
	useAnthropic,
	useOllama,
	useLMStudio,
	useGemini,
	useXAI,
	useGrok,
	useTogether,
	useFireworks,
	useNVIDIA,
	SemanticSearchService,
	type SearchResult,
	BehaviorTree,
	type BTTreeContext,
	type BTTreeDef,
	BTNode,
	SequenceNode,
	SelectorNode,
	ParallelNode,
	InverterNode,
	RepeaterNode,
	GuardNode,
	ActionNode,
	ConditionNode,
	WaitNode,
	type BTStatus,
	Blackboard,
	StateMachine,
	type StateConfig,
	type TransitionConfig,
	type StateAction,
	type GuardFn,
	SteeringBehavior,
	SteeringBehaviors,
	NavMesh,
	PerceptionSystem,
	InfluenceMap,
	UtilityAI,
	BehaviorSelector,
	GoalPlanner,
	HoloScriptGenerator,
	generateHoloScript as generateHoloScriptWithAdapter,
	generateBatch,
	validateBatch,
	GenerationCache,
	cachedGenerate,
	GenerationAnalytics,
	createAnalytics,
	TrainingDataGenerator,
	createTrainingDataGenerator,
	ALL_CATEGORIES,
	PromptTemplateSystem,
	QuickPrompts,
	type PromptTemplate,
	type TemplateContext,
	AICopilot,
	validateAIOutput,
	isAISafe,
} from '@holoscript/framework/ai';
