// @generated by HoloScript NextJSCompiler — DO NOT EDIT
'use client';

import React from 'react';
import { PipelineWorkbench } from '@/components/pipeline/PipelineWorkbench';

// @generated by HoloScript Native2DCompiler — DO NOT EDIT
function PipelineEditorComponent() {
  return (
    <div className="holoscript-2d-root w-full h-full">
      <div className="min-h-screen bg-gray-950 text-white flex flex-col">
        <div className="flex-1 flex flex-col">
          <div data-holo-slot="PipelineWorkbench">
            <PipelineWorkbench />
          </div>
        </div>
      </div>
    </div>
  );
}

export default PipelineEditorComponent;
