import type { CompilerWalkthroughData } from '../../components/CompilerWalkthroughTemplate';

export const androidData: CompilerWalkthroughData = {
  compilerTarget: 'Android XML',
  subtitle: 'From .holo scene to Android Activity + SceneView layout',
  outputLanguage: 'XML',
  tag: 'Android',
  holoSteps: [
    {
      title: 'Write the .holo scene',
      description:
        'Android target outputs an Activity + XML layout with Google SceneView integration.',
      lines: [
        { content: 'scene AndroidDemo {', highlight: true },
        { content: '  object FloatingCard {' },
        { content: '    mesh: Plane { width: 0.3, height: 0.2 }' },
        { content: '    material: StandardMaterial { color: #1a73e8 }' },
        { content: '    position: [0, 0, -0.5]' },
        { content: '    traits: [ARPlaceable, Tappable]', annotation: 'AR traits' },
        { content: '  }' },
        { content: '  camera: ARCamera { }' },
        { content: '}' },
      ],
    },
    {
      title: 'Invoke the Android compiler',
      description:
        'Returns { activityFile, layoutFile } — two files for your Android Studio project.',
      lines: [
        {
          content: 'import { AndroidCompiler } from "@holoscript/core/compilers"',
          highlight: true,
        },
        { content: '' },
        { content: 'const compiler = new AndroidCompiler({', highlight: true },
        { content: "  activityName: 'AndroidDemoActivity'," },
        { content: "  packageName: 'com.example.holodemo'," },
        { content: '  useARCore: true,' },
        { content: '})' },
        {
          content: 'const { activityFile, layoutFile } = compiler.compile(composition)',
          highlight: true,
        },
      ],
    },
  ],
  outputSteps: [
    {
      title: 'Generated XML — Activity layout',
      description: "A layout XML with ArSceneView from Google's SceneView SDK.",
      lines: [
        { content: '<!-- Auto-generated by HoloScript v3.4.0 -->', dim: true },
        { content: '<!-- res/layout/activity_android_demo.xml -->', dim: true },
        { content: '<?xml version="1.0" encoding="utf-8"?>', highlight: true },
        { content: '<androidx.coordinatorlayout.widget.CoordinatorLayout' },
        { content: '    xmlns:android="http://schemas.android.com/apk/res/android"', dim: true },
        { content: '    android:layout_width="match_parent"' },
        { content: '    android:layout_height="match_parent">', type: 'added' },
        { content: '' },
        {
          content: '  <com.google.ar.sceneform.ArSceneView',
          highlight: true,
          annotation: '← AR surface',
        },
        { content: '      android:id="@+id/ar_scene_view"', type: 'added' },
        { content: '      android:layout_width="match_parent"', type: 'added' },
        { content: '      android:layout_height="match_parent" />', type: 'added' },
        { content: '' },
        { content: '</androidx.coordinatorlayout.widget.CoordinatorLayout>' },
      ],
    },
  ],
};
