import type { CompilerWalkthroughData } from "../../components/CompilerWalkthroughTemplate";

export const godotData: CompilerWalkthroughData = {
  compilerTarget: "Godot GDScript",
  outputLanguage: "GDScript",
  holoSteps: [
    {
      title: "Write the .holo scene",
      description: "The same SpinningDemo scene — a blue cube with directional light and camera.",
      lines: [
        { content: "scene SpinningDemo {", highlight: true },
        { content: "  object Cube {" },
        { content: "    mesh: Cube { size: 1 }" },
        { content: "    material: StandardMaterial { color: #4488ff }" },
        { content: "    position: [0, 0, 0]" },
        { content: "    traits: [CastShadow, ReceiveShadow]" },
        { content: "  }" },
        { content: "  light: DirectionalLight { intensity: 1.2, castShadows: true }" },
        { content: "  camera: PerspectiveCamera { fov: 60, position: [3, 3, 5] }" },
        { content: "}" },
      ],
    },
    {
      title: "Invoke the Godot compiler",
      description: "GodotCompiler returns a GDScript string — drop it into a .gd file.",
      lines: [
        { content: 'import { parse } from "@holoscript/core"', highlight: true },
        { content: 'import { GodotCompiler } from "@holoscript/core/compilers"', highlight: true },
        { content: "" },
        { content: "const { composition } = parse(source)" },
        { content: "" },
        { content: "const compiler = new GodotCompiler({", highlight: true },
        { content: "  className: 'SpinningDemo'," },
        { content: "  extends: 'Node3D'," },
        { content: "})" },
        { content: "const gdScript = compiler.compile(composition)", annotation: "→ string", highlight: true },
      ],
    },
  ],
  outputSteps: [
    {
      title: "Generated GDScript — class & state",
      description: "A Node3D script with typed variable declarations for each scene element.",
      lines: [
        { content: "# Auto-generated by HoloScript v3.4.0", dim: true },
        { content: "extends Node3D", highlight: true, annotation: "← scene root type" },
        { content: "" },
        { content: "var _cube: MeshInstance3D", type: "added" },
        { content: "var _directional_light: DirectionalLight3D", type: "added" },
        { content: "var _camera: Camera3D", type: "added" },
      ],
    },
    {
      title: "Generated GDScript — _ready()",
      description: "Scene construction in _ready() — called before the first frame.",
      lines: [
        { content: "func _ready() -> void:" },
        { content: "    _cube = MeshInstance3D.new()", highlight: true },
        { content: "    var mesh := BoxMesh.new()", type: "added" },
        { content: "    mesh.size = Vector3(1, 1, 1)", type: "added" },
        { content: "    _cube.mesh = mesh", type: "added" },
        { content: "    var mat := StandardMaterial3D.new()", type: "added" },
        { content: "    mat.albedo_color = Color(0.27, 0.53, 1.0)", type: "added", annotation: "#4488ff" },
        { content: "    _cube.material_override = mat", type: "added" },
        { content: "    add_child(_cube)", type: "added" },
        { content: "" },
        { content: "    _directional_light = DirectionalLight3D.new()", highlight: true },
        { content: "    _directional_light.light_energy = 1.2", type: "added" },
        { content: "    add_child(_directional_light)", type: "added" },
      ],
    },
  ],
};
