import type { CompilerWalkthroughData } from '../../components/CompilerWalkthroughTemplate';

export const visionosData: CompilerWalkthroughData = {
  compilerTarget: 'Vision Pro Swift',
  outputLanguage: 'Swift',
  tag: 'visionOS',
  holoSteps: [
    {
      title: 'Write the .holo scene',
      description:
        'HoloScript targets visionOS natively — spatial computing in one scene declaration.',
      lines: [
        { content: 'scene SpatialShowroom {', highlight: true },
        { content: '  object Product {' },
        { content: '    mesh: Sphere { radius: 0.15 }' },
        {
          content: '    material: PBRMaterial { albedo: #c8a876, metalness: 0.8, roughness: 0.2 }',
        },
        { content: '    position: [0, 1.2, -0.5]' },
        { content: '    traits: [Hoverable, Grabbable, Spatial]' },
        { content: '  }' },
        { content: '  environment: SpatialBlend { immersionStyle: mixed }' },
        { content: '}' },
      ],
    },
    {
      title: 'Invoke the VisionOS compiler',
      description: 'Outputs a SwiftUI view with RealityView — paste into an Xcode project.',
      lines: [
        {
          content: 'import { VisionOSCompiler } from "@holoscript/core/compilers"',
          highlight: true,
        },
        { content: '' },
        { content: 'const compiler = new VisionOSCompiler({', highlight: true },
        { content: "  structName: 'SpatialShowroomView'," },
        { content: "  immersionStyle: 'mixed'," },
        { content: '})' },
        {
          content: 'const swiftCode = compiler.compile(composition)',
          annotation: '→ string',
          highlight: true,
        },
      ],
    },
  ],
  outputSteps: [
    {
      title: 'Generated Swift — SwiftUI View',
      description: 'A RealityView struct that compiles directly in Xcode for Apple Vision Pro.',
      lines: [
        { content: '// Auto-generated by HoloScript v3.4.0', dim: true },
        { content: 'import RealityKit', highlight: true },
        { content: 'import SwiftUI', highlight: true },
        { content: '' },
        { content: 'struct SpatialShowroomView: View {', highlight: true },
        { content: '    var body: some View {' },
        { content: '        RealityView { content in', type: 'added' },
        { content: '            let product = Entity()', type: 'added' },
        {
          content: '            let mesh = MeshResource.generateSphere(radius: 0.15)',
          type: 'added',
        },
        { content: '            let material = SimpleMaterial(', type: 'added' },
        {
          content: '                color: .init(red: 0.78, green: 0.66, blue: 0.46, alpha: 1),',
          type: 'added',
        },
        { content: '                isMetallic: true', type: 'added' },
        { content: '            )', type: 'added' },
        {
          content: '            product.components[ModelComponent.self] =',
          type: 'added',
          annotation: 'attach mesh',
        },
        {
          content: '                ModelComponent(mesh: mesh, materials: [material])',
          type: 'added',
        },
        { content: '            product.position = SIMD3(0, 1.2, -0.5)', type: 'added' },
        { content: '            content.add(product)', type: 'added' },
        { content: '        }' },
        { content: '    }' },
        { content: '}' },
      ],
    },
  ],
};
