import type { CompilerWalkthroughData } from '../../components/CompilerWalkthroughTemplate';

export const vrchatData: CompilerWalkthroughData = {
  compilerTarget: 'VRChat UdonSharp',
  subtitle: 'From .holo scene to VRChat world-ready UdonSharp behaviour',
  outputLanguage: 'C#',
  tag: 'VRChat',
  holoSteps: [
    {
      title: 'Write the .holo scene',
      description: 'VRChat targets support VRC-specific traits for interactions and networking.',
      lines: [
        { content: 'scene VRChatLobby {', highlight: true },
        { content: '  object WelcomeOrb {' },
        { content: '    mesh: Sphere { radius: 0.3 }' },
        { content: '    material: EmissiveMaterial { color: #7c3aed, emissionStrength: 2.0 }' },
        { content: '    position: [0, 1.5, 0]' },
        { content: '    traits: [VRCInteract, VRCNetworked, Hoverable]', annotation: 'VRC traits' },
        { content: '  }' },
        { content: '  light: DirectionalLight { intensity: 1.0 }' },
        { content: '}' },
      ],
    },
    {
      title: 'Invoke the VRChat compiler',
      description: 'Outputs UdonSharpBehaviour — import into your VRChat SDK project.',
      lines: [
        { content: 'import { VRChatCompiler } from "@holoscript/core/compilers"', highlight: true },
        { content: '' },
        { content: 'const compiler = new VRChatCompiler({', highlight: true },
        { content: "  behaviourName: 'VRChatLobby'," },
        { content: "  syncMode: 'Manual'," },
        { content: '})' },
        {
          content: 'const { mainScript } = compiler.compile(composition)',
          annotation: 'object',
          highlight: true,
        },
      ],
    },
  ],
  outputSteps: [
    {
      title: 'Generated UdonSharp — class & Start()',
      description: 'An UdonSharpBehaviour class with VRC SDK hooks and interaction callbacks.',
      lines: [
        { content: '// Auto-generated by HoloScript v3.4.0', dim: true },
        { content: 'using UdonSharp;', highlight: true },
        { content: 'using UnityEngine;' },
        { content: 'using VRC.SDKBase;' },
        { content: '' },
        {
          content: '[UdonBehaviourSyncMode(BehaviourSyncMode.Manual)]',
          highlight: true,
          annotation: '← sync mode',
        },
        { content: 'public class VRChatLobby : UdonSharpBehaviour', highlight: true },
        { content: '{' },
        { content: '    private GameObject _welcomeOrb;', type: 'added' },
        { content: '    private Light _directionalLight;', type: 'added' },
        { content: '' },
        { content: '    void Start()', highlight: true },
        { content: '    {' },
        { content: "        _welcomeOrb = new GameObject('WelcomeOrb');", type: 'added' },
        { content: '        var mr = _welcomeOrb.AddComponent<MeshRenderer>();', type: 'added' },
        {
          content: '        mr.material.color = new Color(0.49f, 0.23f, 0.93f);',
          type: 'added',
          annotation: '#7c3aed',
        },
        { content: '    }' },
        { content: '' },
        {
          content: '    public override void Interact()',
          highlight: true,
          annotation: '← VRC callback',
        },
        { content: '    { /* triggered by VRCInteract trait */ }' },
        { content: '}' },
      ],
    },
  ],
};
