/**
 * Board module — canonical home for team board types, logic, and utilities.
 */
export {
  // Types
  type TaskStatus,
  type SlotRole,
  type TaskAction,
  ARTIFACT_RECEIPT_TYPES,
  type ArtifactReceiptType,
  type ArtifactHashAlgorithm,
  type ArtifactVerificationStatus,
  type ArtifactVerificationCommand,
  type ArtifactOutputReceipt,
  type ArtifactProvenanceLink,
  type ArtifactReceipt,
  TASK_ENVIRONMENT_PROFILE_KINDS,
  TASK_ENVIRONMENT_NETWORK_ACCESS,
  TASK_ENVIRONMENT_PACKAGE_MANAGERS,
  TASK_ORCHESTRATION_EVENT_TYPES,
  TASK_ORCHESTRATION_AGENT_SURFACES,
  type TaskEnvironmentProfileKind,
  type TaskEnvironmentNetworkAccess,
  type TaskEnvironmentPackageManager,
  type TaskEnvironmentGpuBackend,
  type TaskEnvironmentStep,
  type TaskEnvironmentNetworkPolicy,
  type TaskEnvironmentGpuRequirement,
  type TaskEnvironmentWasmRequirement,
  type TaskEnvironmentProfile,
  type TaskEnvironmentFingerprint,
  type CodexHardwareAuditReceipt,
  type TaskEnvironmentReceipt,
  TASK_POLICY_ACTION_KINDS,
  TASK_POLICY_DECISIONS,
  type TaskPolicyActionKind,
  type TaskPolicyDecisionType,
  type TaskPolicyEnforcementMode,
  type TaskFilesystemAccessMode,
  type TaskEscalationTrigger,
  type TaskEscalationTarget,
  type TaskFilesystemPolicy,
  type TaskSecretPolicy,
  type TaskSpendCap,
  type TaskEscalationRule,
  type TaskPolicyProfile,
  type TaskPolicyAction,
  type TaskPolicyEvent,
  type TaskPolicyEvaluationContext,
  type TaskPolicyDecision,
  type TaskOrchestrationEventType,
  type TaskOrchestrationAgentSurface,
  type TaskDecompositionStrategy,
  type TaskSubagentStatus,
  type TaskOrchestrationAgentRef,
  type TaskDecompositionChild,
  type TaskDecompositionWave,
  type TaskDecompositionPlan,
  type SubagentEvent,
  type TaskCoordinationTimeline,
  type TeamTask,
  type DoneLogEntry,
  type SuggestionCategory,
  type SuggestionVote,
  type TeamSuggestion,
  type RoomPreset,
  type AgentRole,
  type AIProvider,
  type ClaimFilter,
  type TeamAgentProfile,

  // Constants
  ROOM_PRESETS,
  TEAM_MODES,
  type TeamModeId,
  PRIMARY_ASSISTANT_AGENT,
  BRITTNEY_AGENT,
  DAEMON_AGENT,
  ABSORB_AGENT,
  ORACLE_AGENT,
  TEAM_AGENT_PROFILES,

  // Functions
  getAllProfiles,
  getProfileById,
  getProfilesByClaimRole,
  getProfilesByDomain,
  isSupportedArtifactReceiptType,
  validateArtifactReceipt,
  cloneArtifactReceipt,
  isSupportedTaskEnvironmentProfileKind,
  validateTaskEnvironmentProfile,
  validateTaskEnvironmentReceipt,
  cloneTaskEnvironmentProfile,
  cloneTaskEnvironmentReceipt,
  validateTaskPolicyProfile,
  cloneTaskPolicyProfile,
  cloneTaskPolicyEvent,
  evaluateTaskPolicyAction,
  isSupportedTaskOrchestrationEventType,
  isSupportedTaskOrchestrationAgentSurface,
  validateTaskDecompositionPlan,
  validateSubagentEvent,
  cloneTaskOrchestrationAgentRef,
  cloneTaskDecompositionPlan,
  cloneSubagentEvent,
  replayTaskCoordination,
  normalizeTitle,
  generateTaskId,
  generateSuggestionId,
  inferFixPriority,
  parseDeriveContent,
} from './board-types';

export {
  type AuditResult,
  type AuditViolation,
  type AgentStats,
  type SourceStats,
  type CompletionBucket,
  type DoneLogStats,
  type FullAuditResult,
  isLikelyReportEntry,
  isCommitProof,
  auditDoneLog,
  DoneLogAuditor,
} from './audit';

export {
  type ClaimResult,
  type DoneResult,
  type TaskActionResult,
  type SuggestionActionResult,
  type SkippedTaskReason,
  type SkippedTaskEntry,
  hasDefinitionOfDone,
  normalizeTaskDescription,
  claimTask,
  completeTask,
  blockTask,
  reopenTask,
  attachTaskArtifacts,
  attachTaskEnvironmentReceipt,
  recordTaskPolicyEvent,
  attachTaskDecomposition,
  recordSubagentEvent,
  delegateTask,
  deleteTask,
  addTasksToBoard,
  createSuggestion,
  voteSuggestion,
  promoteSuggestion,
  dismissSuggestion,
  appendFollowUpCommit,
} from './board-ops';

export {
  // HoloWeb Network Reality Schema Pack (HWEB-B3)
  HOLOWEB_NETWORK_REALITY_SCHEMA_VERSION,
  HOLOWEB_NODE_ROLES,
  HOLOWEB_PRIVACY_SCOPES,
  HOLOWEB_RESOURCE_KINDS,
  HOLOWEB_LOCATION_PROOF_SCOPES,
  HOLOWEB_LOCATION_PROOF_METHODS,
  HOLOWEB_LOCATION_PRECISIONS,
  HOLOWEB_UNDERLAY_CLASSIFICATIONS,
  HOLOWEB_CONFIDENCE_LEVELS,
  HOLOWEB_OWNER_DECLARED_KINDS,
  HOLOWEB_OWNER_DECLARED_SOURCES,
  HOLOWEB_INTERFACE_KINDS,
  HOLOWEB_VPN_STATES,
  HOLOWEB_HEALTH_STATES,
  HOLOWEB_PROCESS_KINDS,
  HOLOWEB_BANDWIDTH_POSTURES,
  HOLOWEB_HEAVY_WORK_POLICIES,
  HOLOWEB_AGENT_ACTIONS,
  HOLOWEB_BRITTNEY_STANCES,
  HOLOWEB_RECEIPT_TYPES,
  HOLOWEB_RECEIPT_ACTIONS,
  type HoloWebNetworkRealitySchemaVersion,
  type HoloWebJsonValue,
  type HoloWebNodeRole,
  type HoloWebPrivacyScope,
  type HoloWebResourceKind,
  type HoloWebLocationProofScope,
  type HoloWebLocationProofMethod,
  type HoloWebLocationPrecision,
  type HoloWebUnderlayClassification,
  type HoloWebConfidenceLevel,
  type HoloWebOwnerDeclaredKind,
  type HoloWebOwnerDeclaredSource,
  type HoloWebInterfaceKind,
  type HoloWebVpnState,
  type HoloWebHealthState,
  type HoloWebProcessKind,
  type HoloWebBandwidthPosture,
  type HoloWebHeavyWorkPolicy,
  type HoloWebAgentAction,
  type HoloWebBrittneyStance,
  type HoloWebReceiptType,
  type HoloWebReceiptAction,
  type HoloWebSourceAnchors,
  type HoloWebLocationProof,
  type HoloWebNode,
  type HoloWebWifiEvidence,
  type HoloWebCostEvidence,
  type HoloWebAdapterEvidence,
  type HoloWebUnderlay,
  type HoloWebHealth,
  type HoloWebNetworkConsumer,
  type HoloWebAgentLane,
  type HoloWebPolicy,
  type HoloWebBrittneyPolicy,
  type HoloWebRedactionPolicy,
  type HoloWebReceipt,
  type HoloWebNetworkRealitySnapshot,
  isSupportedHoloWebNodeRole,
  isSupportedHoloWebUnderlayClassification,
  isSupportedHoloWebPrivacyScope,
  isSupportedHoloWebLocationPrecision,
  isSupportedHoloWebReceiptType,
  validateHoloWebLocationProof,
  validateHoloWebNetworkRealitySnapshot,
  cloneHoloWebNetworkRealitySnapshot,
} from './holoweb-network-reality';

export {
  // HoloShell Legacy App Reality Schema Pack
  HOLOSHELL_LEGACY_APP_REALITY_SCHEMA_VERSION,
  HOLOSHELL_LEGACY_PROCESS_ROLES,
  HOLOSHELL_LEGACY_NETWORK_POSTURES,
  HOLOSHELL_LEGACY_CUSTODY_STATUSES,
  HOLOSHELL_LEGACY_LANE_COLORS,
  HOLOSHELL_LEGACY_RECEIPT_ACTIONS,
  type HoloShellLegacyAppRealitySchemaVersion,
  type HoloShellLegacyJsonValue,
  type HoloShellLegacyProcessRole,
  type HoloShellLegacyNetworkPosture,
  type HoloShellLegacyCustodyStatus,
  type HoloShellLegacyLaneColor,
  type HoloShellLegacyReceiptAction,
  type HoloShellLegacySourceAnchors,
  type HoloShellLegacySummary,
  type HoloShellLegacyLane,
  type HoloShellLegacyProcess,
  type HoloShellLegacyWindow,
  type HoloShellLegacyNetworkConsumer,
  type HoloShellLegacyRedactionPolicy,
  type HoloShellLegacyReceipt,
  type HoloShellLegacyAppRealitySnapshot,
  isSupportedHoloShellLegacyProcessRole,
  isSupportedHoloShellLegacyLaneColor,
  validateHoloShellLegacyAppRealitySnapshot,
  cloneHoloShellLegacyAppRealitySnapshot,
} from './holoshell-legacy-app-reality';

export {
  // HoloLand receipt types (task_1778186605462_4z0o)
  HARDWARE_RECEIPT_KINDS,
  AGENT_ACTION_KINDS,
  QUALCOMM_NIR_RUNTIME_TARGETS,
  type HardwareReceiptKind,
  type HardwareReceipt,
  type ReplayInput,
  type ReplayOutcome,
  type AgentActionKind,
  type AgentActionReceipt,
  type ValidationReceipt,
  type QualcommNIRRuntimeTarget,
  type QualcommNIRModelExportReceipt,
  type HardwareCompilationTargetKind,
  type CrossHardwareCompilationReceipt,
  validateHardwareReceipt,
  validateReplayInput,
  validateReplayOutcome,
  validateAgentActionReceipt,
  validateQualcommNIRModelExportReceipt,
  validateCrossHardwareCompilationReceipt,
  validateValidationReceipt,
  isSupportedHardwareReceiptKind,
  isSupportedAgentActionKind,
  isSupportedReplayOutcomeStatus,
  isSupportedQualcommNIRRuntimeTarget,
  isSupportedValidationStatus,
  isSupportedHardwareCompilationTarget,
  cloneHardwareReceipt,
  cloneReplayInput,
  cloneReplayOutcome,
  cloneAgentActionReceipt,
  cloneQualcommNIRModelExportReceipt,
  cloneCrossHardwareCompilationReceipt,
  cloneValidationReceipt,
  // Package Provenance Receipt (task_1778618757735_1mih)
  type PackageProvenanceReceipt,
  validatePackageProvenanceReceipt,
  isSupportedTrustTier,
  isSupportedAdmissionDecision,
  clonePackageProvenanceReceipt,
} from './hololand-receipts';

export {
  // HoloShell Browser Absorption Receipts (task_1778625587950_34rn)
  BROWSER_ACTION_KINDS,
  type BrowserActionKind,
  type BrowserAction,
  type BrowserAbsorptionPolicy,
  type BrowserAbsorptionReceipt,
  validateBrowserAbsorptionReceipt,
  isSupportedBrowserActionKind,
  isSupportedBrowserAbsorptionOutcome,
  cloneBrowserAbsorptionReceipt,
} from './holoshell-browser-receipts';

export {
  // HoloShell Account Export Receipts (task_1779135531091_h53w)
  ACCOUNT_EXPORT_PROVIDERS,
  ACCOUNT_EXPORT_DELIVERY_METHODS,
  ACCOUNT_EXPORT_ARCHIVE_FORMATS,
  ACCOUNT_EXPORT_STATUSES,
  PROVIDER_EXPORT_WAIT_STATES,
  ACCOUNT_EXPORT_PERMISSION_ENVELOPES,
  ACCOUNT_EXPORT_WARNING_KINDS,
  type AccountExportProvider,
  type AccountExportDeliveryMethod,
  type AccountExportArchiveFormat,
  type AccountExportStatus,
  type ProviderExportWaitState,
  type AccountExportPermissionEnvelope,
  type AccountExportWarningKind,
  type AccountExportWarning,
  type ProviderExportProductSelection,
  type ProviderExportPlanReceipt,
  type ProviderExportRequestReceipt,
  type ProviderExportReadyReceipt,
  type AccountExportArchivePart,
  type LocalArchiveDownloadReceipt,
  type BrowserAccountBoundaryReceipt,
  type AccountExportApprovalReceipt,
  type ProviderExportWaitReceipt,
  type LocalDownloadQuarantineReceipt,
  type ProviderExportRollbackLimitReceipt,
  type AccountExportArchiveReceipt,
  type AccountExportReplayReceipt,
  type HoloShellAccountExportReceiptPack,
  isSupportedAccountExportProvider,
  isSupportedAccountExportDeliveryMethod,
  isSupportedAccountExportArchiveFormat,
  isSupportedAccountExportStatus,
  isSupportedProviderExportWaitState,
  validateBrowserAccountBoundaryReceipt,
  validateAccountExportApprovalReceipt,
  validateProviderExportWaitReceipt,
  validateLocalDownloadQuarantineReceipt,
  validateProviderExportRollbackLimitReceipt,
  validateProviderExportPlanReceipt,
  validateProviderExportRequestReceipt,
  validateProviderExportReadyReceipt,
  validateLocalArchiveDownloadReceipt,
  validateAccountExportArchiveReceipt,
  validateAccountExportReplayReceipt,
  validateHoloShellAccountExportReceiptPack,
  cloneProviderExportPlanReceipt,
  cloneHoloShellAccountExportReceiptPack,
} from './holoshell-account-export-receipts';

export {
  // HoloShell CLI Absorption Receipts (task_1778625587950_uiv5)
  CLI_ACTION_KINDS,
  type CliActionKind,
  type CliAction,
  type LocalCliPolicy,
  type LocalCliAbsorptionReceipt,
  validateLocalCliAbsorptionReceipt,
  isSupportedCliActionKind,
  isSupportedCliAbsorptionOutcome,
  cloneLocalCliAbsorptionReceipt,
} from './holoshell-cli-receipts';

export {
  // HoloShell Source-Native Readiness Receipt (task_1778739828973_uirq)
  READINESS_OUTCOMES,
  type ReadinessOutcome,
  type ReadinessGitStatus,
  type ReadinessValidationCheck,
  type ReadinessSourceValidation,
  type ReadinessDeviceLabCheck,
  type ReadinessDeviceLabStatus,
  type ReadinessGraphStatus,
  type ReadinessTaskFiling,
  type HoloShellReadinessReceipt,
  validateHoloShellReadinessReceipt,
  isSupportedReadinessOutcome,
  isSupportedReadinessStatus,
  cloneHoloShellReadinessReceipt,
} from './holoshell-readiness-receipt';

export {
  // HoloShell Work-File Custody Receipt (task_1778868513735_mv51)
  WORKFILE_KINDS,
  WORKFILE_PRIVACY_CLASSES,
  WORKFILE_ADAPTER_KINDS,
  WORKFILE_PARSE_STATUSES,
  WORKFILE_WARNING_KINDS,
  WORKFILE_WARNING_SEVERITIES,
  WORKFILE_PREVIEW_KINDS,
  WORKFILE_OUTPUT_KINDS,
  WORKFILE_CUSTODY_OUTCOMES,
  type WorkFileKind,
  type WorkFilePrivacyClass,
  type WorkFileAdapterKind,
  type WorkFileParseStatus,
  type WorkFileWarningKind,
  type WorkFileWarningSeverity,
  type WorkFilePreviewKind,
  type WorkFileOutputKind,
  type WorkFileCustodyOutcome,
  type WorkFileHashAlgorithm,
  type WorkFileWarning,
  type WorkFileSnapshot,
  type WorkFileParserEvidence,
  type WorkFilePreviewReceipt,
  type WorkFileExportReceipt,
  type WorkFileReceiptMetadataValue,
  type HoloShellWorkFileCustodyReceipt,
  isSupportedWorkFileKind,
  isSupportedWorkFileAdapterKind,
  isSupportedWorkFileCustodyOutcome,
  validateHoloShellWorkFileCustodyReceipt,
  cloneHoloShellWorkFileCustodyReceipt,
} from './holoshell-workfile-custody-receipt';

export {
  // HoloShell Asset Shard Receipts (task_1779092479438_6pk4)
  ASSET_SHARD_KINDS,
  ASSET_SHARD_STATUSES,
  ASSET_SHARD_PERMISSION_ENVELOPES,
  type AssetShardKind,
  type AssetShardStatus,
  type AssetShardPermissionEnvelope,
  type AssetShardFileProxy,
  type AssetShardWorkflowReceipt,
  type AssetShardImportApprovalReceipt,
  type AssetShardImportReceipt,
  type PlayableShardWitnessReceipt,
  isSupportedAssetShardKind,
  isSupportedAssetShardStatus,
  validateAssetShardWorkflowReceipt,
  validateAssetShardImportApprovalReceipt,
  validateAssetShardImportReceipt,
  validatePlayableShardWitnessReceipt,
  validateAssetShardReceiptBundle,
  cloneAssetShardWorkflowReceipt,
} from './holoshell-asset-shard-receipts';


export {
  // Device Lab Warning Tokens (task_1778739828973_47f5)
  WARNING_SEVERITY,
  WARNING_ACTION_TYPE,
  type WarningSeverity,
  type WarningActionType,
  type DeviceLabWarningToken,
  type DeviceLabWarningAction,
  deriveWarningTokens,
  getWarningColorClass,
  getWarningIcon,
  formatWarningForHoloShell,
  summarizeWarningTokens,
} from './device-lab-warning-tokens';

export {
  // Twin Earth Substrate Contract (task_1778618552503_3zqx)
  type ParticipationMode,
  type TwinEarthRole,
  type TwinEarthKind,
  type TwinEarthIdentity,
  type TwinEarthAction,
  type PermissionGrant,
  type SafetyEnvelope,
  type TwinEarthReceiptKind,
  type TwinEarthReceiptStatus,
  type TwinEarthReceipt,
  type ParticipationModeConfig,
  type ModeTransitionReceipt,
  type TwinEarthSubstrateStatus,
  type ActuationResult,
  validateTwinEarthIdentity,
  validatePermissionGrant,
  validateSafetyEnvelope,
  validateTwinEarthReceipt,
  validateModeTransitionReceipt,
  evaluateActuation,
  isSupportedTwinEarthRole,
  isSupportedParticipationMode,
  isSupportedTwinEarthKind,
  isSupportedTwinEarthReceiptKind,
  isSupportedTwinEarthReceiptStatus,
  cloneTwinEarthIdentity,
  clonePermissionGrant,
  cloneSafetyEnvelope,
  cloneTwinEarthReceipt,
  cloneModeTransitionReceipt,
} from './twin-earth-substrate';

export {
  // Frontier Shard 0 primitives (task_1778186605462_2mlp)
  SKILL_RARITIES,
  ITEM_CATEGORIES,
  ENCOUNTER_TRIGGER_KINDS,
  ZONE_BIOMES,
  type SkillRarity,
  type Skill,
  type ItemCategory,
  type Item,
  type LootTableEntry,
  type LootTable,
  type EncounterTriggerKind,
  type Encounter,
  type QuestStep,
  type Quest,
  type ZoneBiome,
  type Zone,
  type Shard,
  type ShardReceipt,
  isSupportedSkillRarity,
  isSupportedItemCategory,
  isSupportedEncounterTrigger,
  isSupportedZoneBiome,
  isSupportedShardReceiptStatus,
  validateSkill,
  validateItem,
  validateLootTableEntry,
  validateLootTable,
  validateEncounter,
  validateQuestStep,
  validateQuest,
  validateZone,
  validateShard,
  validateShardReceipt,
  cloneSkill,
  cloneItem,
  cloneLootTableEntry,
  cloneLootTable,
  cloneEncounter,
  cloneQuestStep,
  cloneQuest,
  cloneZone,
  cloneShard,
  cloneShardReceipt,
} from './frontier-shard';

export {
  // Spatial Logic Framework (task_1778462298192_qczd)
  PREDICATE_KINDS,
  ACTION_KINDS,
  type PredicateKind,
  type ActionKind,
  type PredicateMode,
  type SpatialPredicate,
  type SpatialAction,
  type SpatialRule,
  isSupportedPredicateKind,
  isSupportedActionKind,
  validateSpatialPredicate,
  validateSpatialAction,
  validateSpatialRule,
  cloneSpatialPredicate,
  cloneSpatialAction,
  cloneSpatialRule,
} from './spatial-logic';

export {
  // Creator Playable-Template Pipeline (task_1778186605462_muzd)
  TEMPLATE_PARAMETER_KINDS,
  DEFAULT_PLAYABILITY_REQUIREMENTS,
  type TemplateParameterKind,
  type TemplateParameter,
  type PlayabilityRequirements,
  type CreatorTemplate,
  type PlayableChallenge,
  type PublishReview,
  isSupportedTemplateParameterKind,
  validateTemplateParameter,
  validatePlayabilityRequirements,
  validateCreatorTemplate,
  validatePlayableChallenge,
  validatePublishReview,
  checkPlayability,
  cloneTemplateParameter,
  clonePlayabilityRequirements,
  cloneCreatorTemplate,
  clonePlayableChallenge,
  clonePublishReview,
} from './creator-template';

export {
  // Agent steward protocol (task_1778186605462_rp05)
  STEWARD_ROLES,
  STEWARD_CAPABILITY_KINDS,
  WORLD_ISSUE_SEVERITIES,
  WORLD_ISSUE_CATEGORIES,
  WORLD_ISSUE_STATUSES,
  ROLLBACK_STEP_KINDS,
  STEWARD_PROPOSAL_STATUSES,
  PROPOSAL_IMPACT_KINDS,
  type StewardRole,
  type StewardCapabilityKind,
  type StewardCapability,
  type StewardScope,
  type AgentSteward,
  type WorldIssueSeverity,
  type WorldIssueCategory,
  type WorldIssueStatus,
  type WorldIssue,
  type RollbackStepKind,
  type RollbackStep,
  type RollbackPlan,
  type StewardProposalStatus,
  type ProposalImpactKind,
  type ProposalImpact,
  type StewardProposal,
  type StewardActionReceipt,
  isSupportedStewardRole,
  isSupportedStewardCapabilityKind,
  isSupportedWorldIssueSeverity,
  isSupportedWorldIssueCategory,
  isSupportedWorldIssueStatus,
  isSupportedRollbackStepKind,
  isSupportedStewardProposalStatus,
  isSupportedProposalImpactKind,
  isSupportedStewardActionReceiptStatus,
  validateStewardCapability,
  validateAgentSteward,
  validateWorldIssue,
  validateRollbackStep,
  validateRollbackPlan,
  validateProposalImpact,
  validateStewardProposal,
  validateStewardActionReceipt,
  cloneStewardCapability,
  cloneStewardScope,
  cloneAgentSteward,
  cloneWorldIssue,
  cloneRollbackStep,
  cloneRollbackPlan,
  cloneProposalImpact,
  cloneStewardProposal,
  cloneStewardActionReceipt,
} from './agent-steward';

export {
  BOARD_WEBHOOK_EVENT_TYPES,
  BOARD_WEBHOOK_ORDERING_GUARANTEE,
  BOARD_WEBHOOK_FETCH_BY_ID_BEHAVIOR,
  type BoardWebhookEventType,
  type BoardWebhookDeliveryStatus,
  type BoardWebhookOrderingScope,
  type BoardWebhookRetryPolicy,
  type BoardWebhookSigningConfig,
  type BoardWebhookSubscription,
  type BoardWebhookFetchById,
  type BoardWebhookEnvelope,
  type CreateBoardWebhookEnvelopeOptions,
  type BoardWebhookRequest,
  type BoardWebhookDelivery,
  validateBoardWebhookSubscription,
  createBoardWebhookEnvelope,
  canonicalBoardWebhookBody,
  shouldDeliverBoardWebhook,
  signBoardWebhookEnvelope,
  verifyBoardWebhookSignature,
  buildBoardWebhookRequest,
  nextBoardWebhookRetry,
  recordBoardWebhookDeliveryFailure,
} from './webhooks';

