/**
 * Board module — canonical home for team board types, logic, and utilities.
 */
export {
  // Types
  type TaskStatus,
  type SlotRole,
  type TaskAction,
  ARTIFACT_RECEIPT_TYPES,
  type ArtifactReceiptType,
  type ArtifactHashAlgorithm,
  type ArtifactVerificationStatus,
  type ArtifactVerificationCommand,
  type ArtifactOutputReceipt,
  type ArtifactProvenanceLink,
  type ArtifactReceipt,
  TASK_ENVIRONMENT_PROFILE_KINDS,
  TASK_ENVIRONMENT_NETWORK_ACCESS,
  TASK_ENVIRONMENT_PACKAGE_MANAGERS,
  TASK_ORCHESTRATION_EVENT_TYPES,
  TASK_ORCHESTRATION_AGENT_SURFACES,
  type TaskEnvironmentProfileKind,
  type TaskEnvironmentNetworkAccess,
  type TaskEnvironmentPackageManager,
  type TaskEnvironmentGpuBackend,
  type TaskEnvironmentStep,
  type TaskEnvironmentNetworkPolicy,
  type TaskEnvironmentGpuRequirement,
  type TaskEnvironmentWasmRequirement,
  type TaskEnvironmentProfile,
  type TaskEnvironmentFingerprint,
  type CodexHardwareAuditReceipt,
  type TaskEnvironmentReceipt,
  TASK_POLICY_ACTION_KINDS,
  TASK_POLICY_DECISIONS,
  type TaskPolicyActionKind,
  type TaskPolicyDecisionType,
  type TaskPolicyEnforcementMode,
  type TaskFilesystemAccessMode,
  type TaskEscalationTrigger,
  type TaskEscalationTarget,
  type TaskFilesystemPolicy,
  type TaskSecretPolicy,
  type TaskSpendCap,
  type TaskEscalationRule,
  type TaskPolicyProfile,
  type TaskPolicyAction,
  type TaskPolicyEvent,
  type TaskPolicyEvaluationContext,
  type TaskPolicyDecision,
  type TaskOrchestrationEventType,
  type TaskOrchestrationAgentSurface,
  type TaskDecompositionStrategy,
  type TaskSubagentStatus,
  type TaskOrchestrationAgentRef,
  type TaskDecompositionChild,
  type TaskDecompositionWave,
  type TaskDecompositionPlan,
  type SubagentEvent,
  type TaskCoordinationTimeline,
  type TeamTask,
  type DoneLogEntry,
  type SuggestionCategory,
  type SuggestionVote,
  type TeamSuggestion,
  type RoomPreset,
  type AgentRole,
  type AIProvider,
  type ClaimFilter,
  type TeamAgentProfile,

  // Constants
  ROOM_PRESETS,
  TEAM_MODES,
  type TeamModeId,
  PRIMARY_ASSISTANT_AGENT,
  BRITTNEY_AGENT,
  DAEMON_AGENT,
  ABSORB_AGENT,
  ORACLE_AGENT,
  TEAM_AGENT_PROFILES,

  // Functions
  getAllProfiles,
  getProfileById,
  getProfilesByClaimRole,
  getProfilesByDomain,
  isSupportedArtifactReceiptType,
  validateArtifactReceipt,
  cloneArtifactReceipt,
  isSupportedTaskEnvironmentProfileKind,
  validateTaskEnvironmentProfile,
  validateTaskEnvironmentReceipt,
  cloneTaskEnvironmentProfile,
  cloneTaskEnvironmentReceipt,
  validateTaskPolicyProfile,
  cloneTaskPolicyProfile,
  cloneTaskPolicyEvent,
  evaluateTaskPolicyAction,
  isSupportedTaskOrchestrationEventType,
  isSupportedTaskOrchestrationAgentSurface,
  validateTaskDecompositionPlan,
  validateSubagentEvent,
  cloneTaskOrchestrationAgentRef,
  cloneTaskDecompositionPlan,
  cloneSubagentEvent,
  replayTaskCoordination,
  normalizeTitle,
  generateTaskId,
  generateSuggestionId,
  inferFixPriority,
  parseDeriveContent,
} from './board-types';

export {
  type AuditResult,
  type AuditViolation,
  type AgentStats,
  type SourceStats,
  type CompletionBucket,
  type DoneLogStats,
  type FullAuditResult,
  isLikelyReportEntry,
  isCommitProof,
  auditDoneLog,
  DoneLogAuditor,
} from './audit';

export {
  type ClaimResult,
  type DoneResult,
  type TaskActionResult,
  type SuggestionActionResult,
  type SkippedTaskReason,
  type SkippedTaskEntry,
  claimTask,
  completeTask,
  blockTask,
  reopenTask,
  attachTaskArtifacts,
  attachTaskEnvironmentReceipt,
  recordTaskPolicyEvent,
  attachTaskDecomposition,
  recordSubagentEvent,
  delegateTask,
  deleteTask,
  addTasksToBoard,
  createSuggestion,
  voteSuggestion,
  promoteSuggestion,
  dismissSuggestion,
} from './board-ops';

export {
  // HoloLand receipt types (task_1778186605462_4z0o)
  HARDWARE_RECEIPT_KINDS,
  AGENT_ACTION_KINDS,
  type HardwareReceiptKind,
  type HardwareReceipt,
  type ReplayInput,
  type ReplayOutcome,
  type AgentActionKind,
  type AgentActionReceipt,
  type ValidationReceipt,
  validateHardwareReceipt,
  validateReplayInput,
  validateReplayOutcome,
  validateAgentActionReceipt,
  validateValidationReceipt,
  isSupportedHardwareReceiptKind,
  isSupportedAgentActionKind,
  isSupportedReplayOutcomeStatus,
  isSupportedValidationStatus,
  cloneHardwareReceipt,
  cloneReplayInput,
  cloneReplayOutcome,
  cloneAgentActionReceipt,
  cloneValidationReceipt,
} from './hololand-receipts';

export {
  BOARD_WEBHOOK_EVENT_TYPES,
  BOARD_WEBHOOK_ORDERING_GUARANTEE,
  BOARD_WEBHOOK_FETCH_BY_ID_BEHAVIOR,
  type BoardWebhookEventType,
  type BoardWebhookDeliveryStatus,
  type BoardWebhookOrderingScope,
  type BoardWebhookRetryPolicy,
  type BoardWebhookSigningConfig,
  type BoardWebhookSubscription,
  type BoardWebhookFetchById,
  type BoardWebhookEnvelope,
  type CreateBoardWebhookEnvelopeOptions,
  type BoardWebhookRequest,
  type BoardWebhookDelivery,
  validateBoardWebhookSubscription,
  createBoardWebhookEnvelope,
  canonicalBoardWebhookBody,
  shouldDeliverBoardWebhook,
  signBoardWebhookEnvelope,
  verifyBoardWebhookSignature,
  buildBoardWebhookRequest,
  nextBoardWebhookRetry,
  recordBoardWebhookDeliveryFailure,
} from './webhooks';
